### ISSUE TITLE
Add Handlebars helper for resolving system and environment variables

### ISSUE THREAD

**Issue by asarkar** [tomakehurst/wiremock#1000]
I'm looking to stand up a standalone version for load testing. One of the needs is to be able to replace values in the response template from system or environment variables. Based on https://github.com/tomakehurst/wiremock/issues/789, looks like it's not currently possible without repackaging the code, although I'm not sure even in that case how'd I register the custom helper class.

I can imagine such a helper to be pretty useful, and will be happy to make a PR. I'm not super familiar with Handlebars, but I think the following should get the job done:
```
{{var key='something' scope='[sys|env]'}}
```
If `scope` isn't specified, the code will lookup in the system variables first, followed by environment variables. Any `.` or `-` in the key will be converted to a `_` if `scope=env`, as well as uppercased. For example, `key=wire-mock.rocks` will be converted to `WIRE_MOCK_ROCKS`. No such translation will be performed for `scope=sys`.

**Comment by asarkar** [comment]
Knock knock @tomakehurst

**Comment by tomakehurst** [comment]
That kind of comment pretty much guarantees I won't be looking at this any time soon

**Comment by asarkar** [comment]
![screen shot 2018-10-09 at 1 54 55 am](https://user-images.githubusercontent.com/1302775/46657960-5ea87080-cb66-11e8-9531-056749fde140.jpg)

Oops, looks like someone forgot that GitHub sends out email notifications! Here's the thing though: I tried to raise you a week after creating the ticket. In case you didn't notice, I stated a problem, proposed a solution, and offered a PR; that's more than most people do on a OSS project. If you're expecting an award or something for maintaining the project, sorry, it won't come from me.
Now, feel free to do whatever you wish with the ticket; I can anytime fork the project, or just use the mock server I wrote myself.

**Comment by tomakehurst** [comment]
I don't expect an award, but neither do I expect people to presume my voluntary, unpaid time is theirs to demand. There are PRs far older than this one that I've not had time to properly review and merge yet.

I appreciate contributions to WireMock, but hassling me and attempting to jump the queue when I've got no bandwidth isn't at all helpful.

BTW, I'm fully aware of how GitHub notifications work.

**Comment by asarkar** [comment]
>  hassling me and attempting to jump the queue when I've got no bandwidth isn't at all helpful.
Feel free to relinquish project ownership and put up the project for adoption. Retaining control, and then complaining about it is just pretentious.

**Comment by zkendall** [comment]
I have a usecase for this too. I want to proxy requires in maven integration tests. But the port of the service to proxy to is generated by another maven plugin. So I was hoping I could have a mapping like `"proxyBaseUrl" : "http://localhost:${generatedPort}/other-service"`

**Comment by tomakehurst** [comment]
@zkendall I agree this would be useful, and I'm happy for it to be added. If you're up for a creating a PR that would make things happen much more quickly.

**Comment by philippe-granet** [comment]
See PR #1085

**Comment by asarkar** [comment]
@philippe-granet The PR seems to be missing the following:
1. Scope doesn't seem to be optional. One of the goals of this ticket is to keep it transparent where the value is coming from. This is especially important when used with Spring Boot because of [relaxed property binding](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding).
2. You don't seem to be normalizing the key names, or falling back to env var if not found in system var.

**Comment by philippe-granet** [comment]
@asarkar OK, I will do a second PR.
What do you think of this more concise syntax ?
```
{{var 'sys:user.home'}}
{{var 'env:JAVA_HOME'}}
{{var 'java.home'}}
```

**Comment by tomakehurst** [comment]
How about having a top-level config object in the template model, which performs the sleight of hand required to do relaxed binding e.g.

`{{config.[java.home]}}` when you want the value to come from any config source
`{{config.env.JAVA_HOME}}` when you want to target just the environment
`{{config.sys.[java.home}}` when you want to target just the system props

**Comment by philippe-granet** [comment]
What do you think of my new implementation in PR #1085 ?

**Comment by tomakehurst** [comment]
Added in d06f3aa60b9a2a887d6d0b7a89c45b3193dcc5f3
