### ISSUE TITLE
Issue with stub not being matched – toString helped?

### ISSUE THREAD

**Issue by bweefting** [tomakehurst/wiremock#1001]
We have a test that fails on a stub not being matched.

The before-all starts the wireMock-server, the after-all stops the server.
The before-each adds two instructions (a GET and a POST) using stubFor, like:
myStubServerMapping = stubServer.stubFor(WireMock.post(urlMatching("/my-url")).
      willReturn(
        WireMock.aResponse().
          withHeader("Content-length", okResponse.length.toString).
          withBody(okResponse).
          withStatus(HttpStatus.OK.value)))

//FIX:added this line to fix stubMapping not responding
myStubServerMapping.toString() 

On our build-server the tests fails on a http-call that uses the stub.
Locally I could hardly reproduce this, a colleague could make it fail consistently.

We tried some ‘fixes’: 
- Thread.sleep (helped sometimes, but not always)
- validating the server was running after being started
- validating the number of stubMappings was 0 after reset
- validating the number of stubMappings was increased after adding one
- validating myStubServerMapping.getItem was not null
- calling some other method (we tried myStubServerMapping.isPersistent)

All of the above did not fix the tests.

In the end, when calling the toString-method on ‘myStubServerMapping’ is what made the test work again. 
(we found that out because printing it for debugging purposes seemed to fix it, then narrowed it down to even just performing the toString)
Removing/ adding the call toString made the test both fail again and succeed again.
Also confirmed that on the buildserver this leads to working tests again.

Our best guess is that there is some sort of ‘evaluation’ of the StubMapping that is triggered by the toString, but have not found an actual root-cause.

We use:
                <groupId>com.github.tomakehurst</groupId>
                <artifactId>wiremock-standalone</artifactId>
                <version>2.18.0</version>

**Comment by tomakehurst** [comment]
This is more of a question than a bug report, so I suggest posting it on the mailing list.
