### ISSUE TITLE
"$schema" refused in stubs definition

### ISSUE THREAD

**Issue by lmazuel** [tomakehurst/wiremock#1006]
To improve auto-completion in IDE, I added a "$schema" to my stub definition:

```json
{
    "$schema": "https://raw.githubusercontent.com/tomakehurst/wiremock/master/src/main/resources/raml/schemas/stub-mapping.schema.json",
    "scenarioName": "To do list",
    "requiredScenarioState": "Started",
    "request": {
        "method": "GET",
        "url": "/todo/items"
    },
    "response": {
        "status": 200,
        "body" : "<items><item>Buy milk</item></items>"
    }
}
```

It works like a charm and help a lot to write stub files. However, wiremock won't load the stub with that node (standalone jar)
```shell
Exception in thread "main" com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file C:\Users\lmazuel\Wiremock\.\mappings\scenario1.json:
Unrecognized field "$schema" (class com.github.tomakehurst.wiremock.stubbing.StubMapping), not marked as ignorable
        at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:89)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:159)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:155)
        at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:89)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:71)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:125)
```

Am I missing something? I'm a bit new in JSON schema definition, but it seems to me "$schema" is a common practice.

Thank you!

**Comment by tomakehurst** [comment]
WireMock won't let you add new top-level attributes to its JSON, but you can add a `metadata` key with anything you like underneath e.g.

```json
{
    "scenarioName": "To do list",
    "requiredScenarioState": "Started",
    "request": {
        "method": "GET",
        "url": "/todo/items"
    },
    "response": {
        "status": 200,
        "body" : "<items><item>Buy milk</item></items>"
    },
    "metadata": {
         "$schema": "https://raw.githubusercontent.com/tomakehurst/wiremock/master/src/main/resources/raml/schemas/stub-mapping.schema.json"
    }
}
```

**Comment by tomakehurst** [comment]
Hmmm....having re-read this, I'm guessing the IDE needs the attribute at the top level.

**Comment by lmazuel** [comment]
Yes, it has to be at the root. But I realize it's VSCode specific
https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json

> Please note that this syntax is VS Code-specific and not part of the JSON Schema specification. Adding the $schema key changes the JSON itself, which systems consuming the JSON might not expect, for example, schema validation might fail. If this is the case, you can use one of the other mapping methods.

But that's really helpful:
![image](https://user-images.githubusercontent.com/1050156/46499237-5ce05500-c7d4-11e8-8967-ff47c989d5a7.png)

So, if "$schema" is not reserved keyword for you, maybe accepting to parse it but ignore it? Would be awesome :)

**Comment by tomakehurst** [comment]
Let me give it some thought. I can't think of a reason at the moment not to make the parsing tolerant of unknown fields, other than it discourages misspellings of `request`, `response` etc.

But then I might have had a good reason when I configured it that way...
