### ISSUE TITLE
Have withRequestBody take a Predicate for custom matching

### ISSUE THREAD

**Issue by anrask** [tomakehurst/wiremock#101]
It would be good if there was a more flexible way of matching the incoming request body, for example by supplying a Predicate that would take the body as a String and return a boolean whether it matched or not.

**Comment by tomakehurst** [comment]
Closing, as this can be done via the custom matcher extension point.

**Comment by AkhilVashisht** [comment]
Hi.
Anyone has any idea how to check the length of one of the parameters coming in Request body using wiremock(Java Usage)?
