### ISSUE TITLE
Record of two POST requests to same endpoint, mapping file creation fail for the second one

### ISSUE THREAD

**Issue by remcalmels** [tomakehurst/wiremock#1011]
Hi.
I've seen that Wiremock has a bad comportment when :

- I start Wiremock standalone 2.19.0 and proxy-all requests on my API server, with --record-mappings option
- I start record
- I run a first POST request req1 to a endpoint with the JSON body { "attr1":"value1", "attr2":"value2" }
   --> Wiremock server creates the corresponding mapping file
- I run a second POST request req2 to the SAME ENDPOINT with the body { "attr1":"value1" }
   --> Wiremock server doesn't create a mapping file for this one !

So when I stop server and reset mappings to playback and then execute req2, Wiremock try to use the mapping file corresponding to req1, and reject with a natural "Request was not matched".

But after restart server with killed files and recording mode again, if I start to run req2 first and then req1, no problem, mapping files are created for both.

Have you ever encountered this problem ?

Regards

**Comment by tomakehurst** [comment]
You're using the legacy record feature. I suggest trying the new one and seeing if that fixes the problem.
