### ISSUE TITLE
Test does not match after recording if JSON array empty

### ISSUE THREAD

**Issue by lmazuel** [tomakehurst/wiremock#1013]
I recorded one of my call thourgh Wiremock (standalone 2.19.0), this is what I got:

```json
{
  "id" : "1e6a0dcc-4edb-4274-a18a-9940c6250d3d",
  "name" : "array_empty",
  "request" : {
    "url" : "/array/empty",
    "method" : "PUT",
    "bodyPatterns" : [ {
      "equalToJson" : "[]",
      "ignoreArrayOrder" : true,
      "ignoreExtraElements" : true
    } ]
  },
  "response" : {
    "status" : 200,
    "headers" : {
      "X-Powered-By" : "Express",
      "Vary" : "Origin",
      "Access-Control-Allow-Credentials" : "true",
      "Date" : "Thu, 18 Oct 2018 17:39:20 GMT",
      "Connection" : "keep-alive"
    }
  },
  "uuid" : "1e6a0dcc-4edb-4274-a18a-9940c6250d3d",
  "persistent" : true,
  "insertionIndex" : 52
}
```

However, when run the test after based on this recording, it doen't find a match. When I asked mear-misses, I see this request:
```json
{
    "nearMisses": [
        {
            "request": {
                "url": "/array/empty",
                "absoluteUrl": "http://localhost:3000/array/empty",
                "method": "PUT",
                "clientIp": "0:0:0:0:0:0:0:1",
                "headers": {
                    "Accept": "application/json",
                    "User-Agent": "python/3.6.4 (Windows-10-10.0.17763-SP0)",
                    "Connection": "keep-alive",
                    "Host": "localhost:3000",
                    "Accept-Encoding": "gzip, deflate",
                    "Content-Length": "2",
                    "Content-Type": "application/json; charset=UTF-8"
                },
                "cookies": {},
                "browserProxyRequest": false,
                "loggedDate": 1539893931354,
                "bodyAsBase64": "W10=",
                "body": "[]",
                "scheme": "http",
                "host": "localhost",
                "port": 3000,
                "loggedDateString": "2018-10-18T20:18:51Z",
                "queryParams": {}
            },
            "requestPattern": {
                "url": "/array/empty",
                "method": "PUT"
            },
            "matchResult": {
                "distance": 0
            }
        }
   ]
}
```

Which I feel like this should match right?

I discovered that if I remove both "ignoreArrayOrder" and "ignoreExtraElements", then the recording matches perfectly and everything works.

I feel like based on the name of these options, and being that the array is empty, this should not impact the matching. Could it be possible that there is a bug somewhere that if the array is empty, these options fails the matching?

Note that I was able to reproduce too with an empty object '{}'

I'm not blocked, since removing these options make it work, but I feel like the recording should work out of the box.

Thanks!

**Comment by tomakehurst** [comment]
Please post questions on the mailing list as per the README. Suggest you include a bit more detail about your setup and in particular the exact requests you made a) to record the stub, b) during your test.

**Comment by lmazuel** [comment]
@tomakehurst That's not a question, I humbly think you read too fast. When the JSON array is empty and the ignoreArrayOrder option is set, there is no matching, but it matches if I remove the option. Which doesn't make sense being than the array is empty....

Also, you ask the exact request: I copy/pasted it. The request to record will be exactly the same, that's an automatic system that trigger the same request part of a testsuite.

**Comment by tomakehurst** [comment]
Actually, this might be a duplicate of https://github.com/tomakehurst/wiremock/issues/632.

**Comment by lmazuel** [comment]
@tomakehurst Sounds like a duplicate indeed, sorry I didn't find it since I used JSON syntax only...
