### ISSUE TITLE
Scenario name conflict generates invalid scenario while recording

### ISSUE THREAD

**Issue by lmazuel** [tomakehurst/wiremock#1014]
Using recording with 2.19.0 standalone.

I have really close URLs for two different tests:
- `"url" : "/paging/multiple/retrysecond/page/3",`
- `"url" : "/paging/multiple/page/3",`

Wiremock recording decides to to use the name scenarioName "scenario-page-3" for all calls to both these URIs.

However, the doc states:
> However, when set to true (which is the default if omitted), multiple identical requests will be added to a Scenario,

For me, these urls are not identical at all, they share the some fragments of the path, but not identical. Shouldn't they been added in two scenarios? (assuming each of them is called several times).

It's painful right now for me, since I have to untangle a lot of recording that just happen to have some fragments in common.

Thank you!

**Comment by tomakehurst** [comment]
Fixed in https://github.com/tomakehurst/wiremock/pull/1024
