### ISSUE TITLE
Scenario name is the same for the same url with different parameters while recording

### ISSUE THREAD

**Issue by nancyhu1229** [tomakehurst/wiremock#1015]
Using recording with 2.19.0 standalone.

#1014 Very similar to #1014
But I have the same URL with diff paramters, each requests 2 times

"url" : "/ly?p=2",  
"url" : "/ly?p=1", 

Wiremock recording decides to to use the name scenarioName "scenario-ly" for all calls to both different parameter

when I replay them , the  response will not be correct  when I request /ly?p=2 & /ly?p=1 each 2 times

Thank you!

**Comment by nancyhu1229** [comment]
Attachemnt is the record mappings
[mappings.zip](https://github.com/tomakehurst/wiremock/files/2504439/mappings.zip)

**Comment by tomakehurst** [comment]
I believe this is resolved by the fix for #1014
