### ISSUE TITLE
Fail-safe behavior if json mapping file is not valid

### ISSUE THREAD

**Issue by Max-Hab** [tomakehurst/wiremock#1025]
We are using wiremock standalone 2.18.0 as a common mock server across several teams, so many people are constantly adding new mappings in form of json files. 
If somebody makes a simple typo in json file, ex. omits the only one curly brace, the wiremock doesn't start fully (it doesn't respond to http calls) and log doesn't contain any explicit error, so:

1. It takes time to understand what happened.
2. It takes even more time to identify a broken file.

Suggestions:

1. Add validation for json files with mappings.
2. If file doesn't pass validation, print explicit error into log with file name.
3. Reject broken file and let wiremock run with not corrupted files.

**Comment by tomakehurst** [comment]
There is already a error that gets reported to stdout when a mapping file isn't valid, but I take your point about it not reporting the filename, so I'll mark this as a feature request.

I'm not sure I'm keen on your idea of starting WireMock when there are broken mapping files. Failing early was a deliberate design choice - not starting the server at all is a very visible sign that something isn't right, whereas starting with missing mappings, unless you're watching the log closely could lead to subtle failures that take a long time to unravel.

**Comment by Max-Hab** [comment]
Ok, for some reason I didn't see any error in the logs, but I guess it may be related to the devops scripts trying to restart the server and clearing logs.
