### ISSUE TITLE
Dynamic response values for Stubs deployed on Nomad

### ISSUE THREAD

**Issue by amitsharmayogesh** [tomakehurst/wiremock#1033]
Hi team,

We have our WireMock Stubs deployed on Nomad architecture - CI/CD pipeline. Field values in Stubs are populated. We have validations on response such as some field should have the same values as Request (e.g : message id) . Does WireMock supports the functionality of building Dynamic response  based on requests ?

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README
