### ISSUE TITLE
How to limit Customer Request Matcher only apply to single request ?

### ISSUE THREAD

**Issue by Mikuu** [tomakehurst/wiremock#1050]
Wiremock Version: 2.19.0

I'm going to create a customer request matcher, take the document example for the case:

```java
@Override
    public MatchResult match(Request request, Parameters parameters) {
        int maxLength = parameters.getInt("maxLength");
        return MatchResult.of(request.getBody().length > maxLength);
    }
```
this matcher is to check a request body length > maxLength, but given I have 2 requests, 
e.g. :
a. /get/endpoint/one
b. /get endpoint/two

currently, both of these 2 requests will be checked with the same matcher, how can I limit this customer matcher is only applied to request a, and leave request b only be checked with its own JSON rules (recorded)?

Hope I described the issue clearly.

thanks.

Mikuu

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README
