### ISSUE TITLE
unable to use different ports on the same machine when running wiremock as standalone

### ISSUE THREAD

**Issue by pradeepanchan** [tomakehurst/wiremock#1052]
I am using standalone wiremock server. When i am running wiremock over TLS, it boots up fine for one port. When i start another server (with the first one still running) , with a different port, it cribs that the Bind address is already in use. I checked that this port is not in-use by stopping the first wiremock and starting the second one. And this works.

Our requirement is that our micro-service is fetching details from two other services and we are mocking both of them for our Unit-tests via wire-mock. So we need both wiremock servers to be up and running. Note that this issue does not crop up when using non-secure channels.

Wiremock version: 2.20

Test case: 
`> java -jar wiremock-standalone-2.20.0.jar --https-port 8089 --https-keystore file1.jks  --keystore-password changeit --print-all-network-traffic --verbose`
`> java -jar wiremock-standalone-2.20.0.jar --https-port 8090 --https-keystore file2.jks  --keystore-password changeit --print-all-network-traffic --verbose`

Stack trace:
`2018-12-28 17:56:57.768 Verbose logging enabled
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-12-28 17:56:58.447 Verbose logging enabled
2018-12-28 17:56:58.462 Verbose logging enabled
java.lang.RuntimeException: java.net.BindException: Address already in use`

**Comment by tomakehurst** [comment]
You're only setting the HTTPS port, so the http port is defaulted to 8080 in both cases. Try explicitly setting the --port parameter.

Also, please post future questions to the mailing list.
