### ISSUE TITLE
No way to add duplicate headers using json config (e.g. two Set-Cookie lines)

### ISSUE THREAD

**Issue by cyberw** [tomakehurst/wiremock#1054]
I think there is no way to set multiple cookies in one response using json config. The below config will only give foo2 in the response (because json doesnt support duplicate keys). Is there a workaround? If there is, I dont think it is mentioned in the documentation.

```
...
    "response": {
        "headers": {
            "Set-Cookie": "foo=bar; path=/",
            "Set-Cookie": "foo2=bar2; path=/",
...
```

- Which version of WireMock you're using
2.19
- How you're starting and configuring WireMock, including configuration or CLI the command line
java -jar wiremock-standalone-2.19.0.jar --global-response-templating

**Comment by tomakehurst** [comment]
You can set multiple values for a given response header by using an array value like this:

```json
"response": {
        "headers": {
            "Set-Cookie": ["foo=bar; path=/", "foo2=bar2; path=/"]
        }
}
```

Marking this as a feature request as a reminder to document this properly.

**Comment by cyberw** [comment]
That works perfectly, thanks!

**Comment by tomakehurst** [comment]
Added a doc note in fea7cde3c3a6f05b323579ee950ff435069c242f
