### ISSUE TITLE
Order of headers seems to matter when using etags (and kubernetes ingress)

### ISSUE THREAD

**Issue by davidh87** [tomakehurst/wiremock#1058]
Version: Wiremock 2.14+
Configuration: Running standalone, proxying requests (app -> wiremock proxy -> service)

Note, this isn't directly a bug in wiremock but rather a combination of wiremock/jetty and potentially kubernetes ingress.

When wiremock returns proxied responses, it builds up a HttpServletResponse by adding each header from the proxied response. In our situation, the service is including an etag header and a gzipped response body.

When copying headers over to the HttpServletResponse in [WireMockHandlerDispatchingServlet](
https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHandlerDispatchingServlet.java#L198), all headers are looped through (in the order they were provided in the downstream response) and for compressed response bodies this will call out to jetty's CompressedResponseWrapper.setHeader(String, String). In this setHeader method, setting an etag header will not populate an actual header but instead a _etag variable. Later on, when setting a content-encoding header, jetty will build an ETag header and add that to the response. This seems to work in our usual case where a Jersey response contains headers, and wiremock encounters an etag header before a content-encoding header. In most situations this seems to work.

When accessing the server through a kubernetes ingress (app -> wiremock proxy -> ingress -> service), it appears that the headers returned by ingress are in a different order, potentially being sorted. What this crucially means is that when wiremock copies headers from the downstream response to the proxied response, it will process the content-encoding header *before* the etag header. When this happens, the constructed HttpServletResponse tries to set the Etag header before it has been given the value, and the wiremock proxied response does not contain the header.

To demonstrate this, make wiremock proxy a response that contains an etag and content-encoding header, and the etag will / won't be included in the proxied response based on the order of these headers in the downstream response. Added [etag-downstream-mocks.zip](https://github.com/tomakehurst/wiremock/files/2733194/etag-downstream-mocks.zip) showing the downstream mocks that were being proxied.

While the order of headers shouldn't matter, it appears it does when Jetty uses them to construct etags. A fix in wiremock could be to treat etag's as a special case and copy this over to the HttpServletResponse before processing the other headers.

**Comment by tomakehurst** [comment]
I'm closing this due to age and inactivity, but appreciate that it may still be an issue. If so, I'm happy to accept a PR giving special treatment to etag headers.
