### ISSUE TITLE
Allow for extra elements during XML matching or add placeholder to ignore elements

### ISSUE THREAD

**Issue by D0rmouse** [tomakehurst/wiremock#1061]
It would be very nice if we would be able to ignore extra elements in XML expectations or would be able to ignore values by adding a placeholder as value.

json-unit, for example, has an ignore placeholder `${json-unit.ignore}`. And you're able to add a configuration specifying which paths to ignore.

Maybe this feature is already implemented, but I couldn't find it in the documentation.

**Comment by D0rmouse** [comment]
Exactly like in that PR 👍

**Comment by D0rmouse** [comment]
To make it even more flexible maybe a custom XMLUnit `DifferenceEvaluator` and/or node filter could be supported.

**Comment by tomakehurst** [comment]
Closing, since the associated PR is merged now.

Will happily consider a further PR for a custom `DifferenceEvaluator`.
