### ISSUE TITLE
getting 405 error message for verificationException when trying to connect a env 

### ISSUE THREAD

**Issue by wiremockzeus** [tomakehurst/wiremock#1070]
com.github.tomakehurst.wiremock.client.VerificationException: Expected status 201 for http://"remotehost":8080/__admin/mappings/new but was 405
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAssertOkAndReturnBody(HttpAdminClient.java:147)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:65)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:122)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:118)

@Rule
  public static WireMock wireMock = new WireMock(remotehost, 8080);

        wireMock.register(get(urlMatching("/account"))
                     .withHeader("Content-Type", containing("application/json"))
                 .willReturn(aResponse()
                        .withHeader("Content-Type", "application/json")
                        .withHeader("Accept", "application/json")
                        .withStatus(200)
                        .withBody("get200.json")));

Containing below jars in pom.xml

com.github.tomakehurst:wiremock:standalone:1.53
com.github.tomakehurst:wiremock:1.18
org.apache.httpcomponents:httpclient:4.3.2
com.github.tomakehurst:wiremock:pom:2.20.0
com.github.tomakehurst:wiremock-standalone:2.20.0

# Issue guidelines

If you're asking a question, rather than reporting a bug or requesting a feature, **please post your question on the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user), and do not open an issue**.

Please do not log bugs regarding classpath issues (typically manifesting as 'NoClassDefFoundException' or 'ClassNotFoundException').
These are not WireMock bugs, and need to be diagnosed for your project using your build tool. Plenty has already been written in WireMock's issues and mailing list about how to resolve these issues
so please search these sources before asking for help.

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [ ] Which version of WireMock you're using
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
- [ ] A failing test case that demonstrates the problem
- [ ] Profiler data if the issue is performance related   

## Feature requests

Please include details of the use case and motivation for a feature when suggesting it.

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the above message.
