### ISSUE TITLE
feat(stub): allow to provide function to `willReturn`

### ISSUE THREAD

**Issue by davinkevin** [tomakehurst/wiremock#1073]
Hi, 

In my use case, I need to be able to generate the response served by the `server` dynamically. Especially, I would like to include a date relative to when the call is done.

I've seen the `Response Templating` which could be useful but is verbose and rely on handlebar templating.

It could be good to have some method like `okJson(Function<XXX, String> f)` or at least `okJson(Supplier<String> f)` which can be called when the endpoint is reached.

The following code is an example based on the renew of a token
```kotlin

        server.apply {
            stubFor(post("/foo/bar/token")
                    .inScenario("renew token after midlife")
                    .whenScenarioStateIs(STARTED)
                    .willReturn(okJson("""{ "access_token": "$firstToken" }"""))
                    .willSetStateTo("After first fetch")
            )
            stubFor(post("/foo/bar/token")
                    .inScenario("renew token after midlife")
                    .whenScenarioStateIs("After first fetch")
                    .willReturn(okJson("""{ "access_token": "$secondToken" }"""))
                    .willSetStateTo("After second fetch")
            )
            stubFor(post("/foo/bar/token")
                    .inScenario("renew token after midlife")
                    .whenScenarioStateIs("After second fetch")
                    .willReturn(okJson("""{ "access_token": "$thirdToken" }"""))
            )
        }

        /* When */
        StepVerifier.withVirtualTime { TokenProvider(p, WebClient.create(p.brokerUri)).tokenFlux.take(3) }
                /* Then */
                .expectSubscription()
                .assertNext { assertThat(it.access_token).isEqualTo(firstToken) }
                .thenAwait(ofSeconds(5))
                .assertNext { assertThat(it.access_token).isEqualTo(secondToken) }
                .thenAwait(ofSeconds(15))
                .assertNext { assertThat(it.access_token).isEqualTo(thirdToken) }
                .verifyComplete()
```

I've searched for a similar issue about this kind of feature without success. If I miss it, you can close this one.

Thanks

**Comment by davinkevin** [comment]
Sorry, I totally forgot to write an example of what I think should be simpler/better to use.

In Java, I think something like this could be useful: 

```java
server. stubFor(
  post("/foo/bar/token")
    .willReturn(() -> ok(Intant.now().toString()))
)
```

With this supplier as parameter of the `willReturn` method, the result will be the date (as string in this case) when the endpoint is called. 
With the current behavior, this is the date when the endpoint is configured, which is, in my case, hard to handle because I have some retry logic with backoff so I have to calculate first what should happen...

**Comment by kennedyoliveira** [comment]
I have an interest in this feature too, is anything like that available?
Did you found an alternative solution @davinkevin ?

**Comment by davinkevin** [comment]
I didn't find any solution for this sadly...

**Comment by tomakehurst** [comment]
@davinkevin @kennedyoliveira Do you know you can achieve the same effect with response templating?

e.g. the current date example, you can just return a body like `{{now}}`.

**Comment by tomakehurst** [comment]
Closing due to age and inactivity

**Comment by davinkevin** [comment]
Sorry. I totally miss the first notification in 2019 ! 🤦‍♂️

I didn't use the response templating solution, which seems to be very complete, with a lot of helper. 

But, I still think a solution based on a lambda would be simpler to use, because you don't need to provide custom helpers or anything else… because the whole JDK is the helper in this case. Furthermore, all the code is checked at compile time and so, simpler to write than templating mainly based on string.

Thank for the answer and let me know if this kind of feature could be proposed as a PR, I would be glad to help if possible!
