### ISSUE TITLE
Start wiremock with certain delay

### ISSUE THREAD

**Issue by MkJha** [tomakehurst/wiremock#1074]
In certain test cases, i need to intentionally start the wiremock after some delay. So that initially when the request comes, it should be down. When request is retried after sometime, it should be up and running. Is there anyway to specify the time delay before the wiremock starts.

**Comment by tomakehurst** [comment]
Is there any reason you can't wait the required time, then call `wireMockServer.start()`?

**Comment by MkJha** [comment]
Firstly, even delay option would not work very accurately to serve my purpose.  And yes, waiting for the required time is the ideal way, but in my case it is difficult to do so as the code which sends the request can't be intervened/penetrated  to start/stop the wiremock in-between the requests.  You can junk this query. Thanks!!
