### ISSUE TITLE
[Feature request] New template helpers(e.g. hostname) supported for using in container env

### ISSUE THREAD

**Issue by yuanpli** [tomakehurst/wiremock#1075]
## Feature requests

Can wiremock add 'hostname' helper to get the hostname that wiremock is running? To make the same mapping configuration can be used in multiple different instances, 'hostname' helper can be used in response template to render different responses.

**Comment by tomakehurst** [comment]
I'm curious what the use case would be for this.

Usually it's `localhost`, but if you've changed the bind address via the config, then surely you already know what hostname to use?

**Comment by yuanpli** [comment]
Sorry I didn't describe the clear use case. What my purpose is to run wiremock in docker env. When multiple containers are setup, it is better to have some keyword to distinguish them.

**Comment by tomakehurst** [comment]
How would this keyword manifest? Do you mean you'd like log messages to be distinguished by it?

**Comment by yuanpli** [comment]
Not like log messages.  It would be better to support new helpers(e.g. hostname, systemenv ...) that can be used in response template.
Take an example to explain my points.
Response Templating configured in docker image
```
{
    "request": {
        "urlPath": "/hostname",
        "method": "GET"
    },
    "response": {
        "body": "{{hostname}}",
        "transformers": ["response-template"]
    }
}
```
Container1 started with this image by
```docker run --hostname wiremock1 -d wiremock```
Container2 started with the same image by
```docker run --hostname wiremock2 -d wiremock```

When client requests http get /hostname on Container1 , it can get the response 'wiremock1', and likewise, when requests on Container2, it can get the response 'wiremock2'.

**Comment by yuanpli** [comment]
@tomakehurst could you kindly share your comments? Thanks!
