### ISSUE TITLE
Performance issue with templating

### ISSUE THREAD

**Issue by max3163** [tomakehurst/wiremock#1077]
# Performance issue with templating 

I am encountering a problem of performance when I active the reponse templating on wiremock, especially when the response content is important. ( with or without handlebar function in the content )
By example, for a full text response of 500Kb, I got a response time of 21 second ! ( with the last version of wiremock 2.21 it's better 14sec but still inconceivable )
I've check where we lost so much time, and it's on the handlebars lib. I've ask help on the github of this lib, the answer is to activate a cache. I've check on the code of Wiremock, no cache is implemented. 
But I can't figure out how the process can take so much time to just parse a string of 500Kb.

- [ ] WireMock V2.20 and V2.21
- [ ] Wiremock Standalone with theses options --no-request-journal --container-threads=200 --jetty-acceptor-threads=100 --async-response-enabled --async-response-threads=100 --local-response-templating  --root-dir data
- [ ] Active templating with a response size about 500Kb
- [ ] ![l_3892 tmp](https://user-images.githubusercontent.com/13835366/52265841-3c1c3d80-2935-11e9-9fec-a1093af49e61.PNG)

**Comment by tomakehurst** [comment]
Wow, that is especially bad. I've never seen it take anything like that long.

Any chance you can post the template (or something similar) that caused the problem?

**Comment by tomakehurst** [comment]
Thanks, I'll try and take a look at that next time I'm in the code.

I suspect caching compiled templates might be a good idea, but I need to think a bit about memory usage and ensuring invalidation at the right moments.

**Comment by max3163** [comment]
Hi, 

I implemented the cache in Handlerbars. Result are totaly predicatble and better on second call ( about 60ms ). This solution is not entirely satisfactory because lost 15 sec on the first call in a benchmark test is still not acceptable.

I've implement in wiremock an other lib of templating called pebble which is close to the handlebars one, results are really great !

Response time :

|Size|Handlebars|Pebble|
|----|-------------|---------|
|500kb| 15 sec | 70 ms |
|1Mb| 35 sec | 70 ms |

**Comment by max3163** [comment]
See PR #1082 to implement cache

**Comment by philippe-granet** [comment]
See also PR #1088 to only template datas between first '{{' and last '}}'

**Comment by tomakehurst** [comment]
Closing since the associated PR has been merged
