### ISSUE TITLE
POM of 2.21.0 JRE 8 looks odd

### ISSUE THREAD

**Issue by GFriedrich** [tomakehurst/wiremock#1089]
I found the Maven POM of version 2.21.0 JRE8 looks rather odd.
It contains two Guava version, two Jetty versions and some other duplicates.
Even though Maven might choose the newer one, I think it should only contain one version of each dependency.
I guess this is the result of a failed merging of the Java 8 project dependencies and the global ones.

**Comment by tomakehurst** [comment]
Thanks for reporting. I think I know why this is.
