### ISSUE TITLE
FAILED SslConnectionFactory@3c0be339{SSL->http/1.1}: java.lang.NoSuchMethodError: org.eclipse.jetty.util.ssl.SslContextFactory.selectCipherSuites([Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String; java.lang.NoSuchMethodError: org.eclipse.jetty.util.ssl.SslContextFactory.selectCipherSuites([Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String; 	at com.github.tomakehurst.wiremock.jetty92.CustomizedSslContextFactory.customize(CustomizedSslContextFactory.java:39) 	at org.eclipse.jetty.util.ssl.SslContextFactory.newSSLEngine(SslContextFactory.java:1592)

### ISSUE THREAD

**Issue by Priyanghaa** [tomakehurst/wiremock#1090]
Getting these exceptions while trying to connect https with wiremock
Wiremock Configuration 
WireMockServer wireMockServer = new WireMockServer(WireMockConfiguration.wireMockConfig().extensions(new BodyTransformer()).httpsPort(8443).needClientAuth(true).trustStorePath("mocker.jks").trustStorePassword("password"));
Maven dependancy
 <dependency>
      <groupId>com.github.tomakehurst</groupId>
      <artifactId>wiremock</artifactId>
      <version>2.21.0</version>
      <scope>test</scope>
    </dependency>

Have tried Maven standalone also but still the same issue
 
      
      
      
      
    

Can someone please suggest for this issue ? Which version of wiremock should be used ?

**Comment by Priyanghaa** [comment]
Have excluded wiremock jar from body transformer and hence the issue got solved.Closing this issue
In pom.xml

<dependency>
      <groupId>com.github.tomakehurst</groupId>
      <artifactId>wiremock-standalone</artifactId>
      <version>RELEASE</version>
      
    </dependency>
    <dependency>
      <groupId>com.opentable</groupId>
      <artifactId>wiremock-body-transformer</artifactId>
      <version>1.1.6</version>
      <exclusions>
        <exclusion>
          <groupId>com.github.tomakehurst</groupId>
          <artifactId>wiremock</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

**Comment by gotw** [comment]
> Have excluded wiremock jar from body transformer and used wiremock standalone jar then the issue got solved.Closing this issue
> In pom.xml
> 
> com.github.tomakehurst wiremock-standalone RELEASE com.opentable wiremock-body-transformer 1.1.6 com.github.tomakehurst wiremock

This is not working for me. What is the exclusion incantation in your POM? Thanks!

**Comment by Priyanghaa** [comment]
<dependency>
      <groupId>com.opentable</groupId>
      <artifactId>wiremock-body-transformer</artifactId>
      <version>1.1.6</version>
      <exclusions>
        <exclusion>
          <groupId>com.github.tomakehurst</groupId>
          <artifactId>wiremock</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
