### ISSUE TITLE
Why JDK8 build+ was renamed to wiremock-jre8?

### ISSUE THREAD

**Issue by modax** [tomakehurst/wiremock#1091]
Hello,

Didn't it make more sense to have wiremock-jre7 (or 6 whatever is the lowest supported) for legacy applications? Now I bet most users will use just `wiremock` without knowing there is a better build out there.

I guess uou are not going to support legacy forever and eventually legacy users will have to stick to prior versions

**Comment by tomakehurst** [comment]
I did it this way to avoid it being a breaking change. Suddenly dropping a JDK version in a minor release of the existing artifact would, I believe, cause more trouble than requiring people to opt into the JRE8 version.

**Comment by modax** [comment]
I see. My concern is that old users will never read installation documentation again and would never find out a better build with updated dependencies. Personally I wouldn't have if I was not subscribed to a bug where this was mentioned. But your point is also valid, just I would not give higher priority to legacy JDK users :) It would be easier for them to find out that something is wrong when they immediately see class version errors.

**Comment by tomakehurst** [comment]
I'm hoping a point will come in the not-too-distant future where I can just drop JDK7 support, bump the major version to 3 and go back to publishing `wiremock` and `wiremock-standalone` artifacts only.

**Comment by lackovic** [comment]
Hey, just landed on this page while trying to figure out which version was the latest. We are using Java 17 in our projects and I was mislead to think `wiremock-jre8` was the version compatible with Java 8 and below while `wiremock` was the latest version. Took some time to figure out it's the other way around.

**Comment by tomakehurst** [comment]
@kdefives for 3.x and onward we're back to using the `wiremock` and `wiremock-standalone` artifact IDs. The `jre8` qualifier was put in there so that we run the Java 7 and 8+ builds in parallel. 3.x is Java 11+ and we're not supporting any older versions, so we're back to a single pair of IDs.

**Comment by kdefives** [comment]
Cool! Thx @tomakehurst to be back using standards :D

**Comment by yellow-straw-hat** [comment]
Hello @tomakehurst , what is the difference between wiremock and wiremock-standalone jars ?

I have run `mvn dependency:tree` to see the difference:
Having `wiremock-standalone` in pom.xml
`[INFO] +- org.wiremock:wiremock-standalone:jar:3.3.1:test`

Having `wiremock `in pom.xml :

```
[INFO] +- org.wiremock:wiremock:jar:3.3.1:test
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:11.0.18:test
[INFO] |  |  +- org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api:jar:5.0.2:test
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:11.0.18:test
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:11.0.18:test
[INFO] |  |  \- org.eclipse.jetty:jetty-security:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:11.0.18:test
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:11.0.18:test
[INFO] |  |  \- org.eclipse.jetty:jetty-xml:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-proxy:jar:11.0.18:test
[INFO] |  |  \- org.eclipse.jetty:jetty-client:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty.http2:http2-server:jar:11.0.18:test
[INFO] |  |  \- org.eclipse.jetty.http2:http2-common:jar:11.0.18:test
[INFO] |  |     \- org.eclipse.jetty.http2:http2-hpack:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-alpn-server:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-alpn-java-server:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-alpn-java-client:jar:11.0.18:test
[INFO] |  +- org.eclipse.jetty:jetty-alpn-client:jar:11.0.18:test
[INFO] |  +- com.google.guava:guava:jar:32.1.3-jre:test
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.37.0:test
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.21.1:test
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:2.8:test
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:test
[INFO] |  |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2:test
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:test
[INFO] |  +- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] |  |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.xmlunit:xmlunit-legacy:jar:2.9.1:test
[INFO] |  +- org.xmlunit:xmlunit-placeholders:jar:2.9.1:test
[INFO] |  +- net.javacrumbs.json-unit:json-unit-core:jar:2.38.0:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |  |     \- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.8.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.10:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.9:test
[INFO] |  +- org.ow2.asm:asm:jar:9.6:test
[INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:5.0.4:test
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.13.0:test
[INFO] |  +- com.github.jknack:handlebars:jar:4.3.1:test
[INFO] |  +- com.github.jknack:handlebars-helpers:jar:4.3.1:test
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.5:test
[INFO] |  +- commons-io:commons-io:jar:2.15.0:test
[INFO] |  \- com.networknt:json-schema-validator:jar:1.0.87:test
[INFO] |     +- com.ethlo.time:itu:jar:1.7.0:test
[INFO] |     \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.16.0:test
[INFO] |        \- org.yaml:snakeyaml:jar:2.2:test
```

When running my unit tests with `wiremock-standalone`, I don't get verbose logs, but when running them with with `wiremock `I get the following logs:

```
[INFO] --- surefire:3.0.0-M3:test (default-test) @ *** ---
[INFO] Running ***
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.18; built: 2023-10-27T02:14:36.036Z; git: 5a9a771a9fbcb9d36993630850f612581b78c13f; jvm 11.0.21+9-LTS
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6d7d0946{/__admin,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler.ROOT - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@3054cdd3{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started NetworkTrafficServerConnector@2fd409c1{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:39051}
[main] INFO org.eclipse.jetty.server.Server - Started Server@9fd5dd0{STARTING}[11.0.18,sto=1000] @10755ms
[main] INFO org.eclipse.jetty.server.Server - Stopped Server@9fd5dd0{STOPPING}[11.0.18,sto=1000]
[main] INFO org.eclipse.jetty.server.Server - Shutdown Server@9fd5dd0{STOPPING}[11.0.18,sto=1000]
[main] INFO org.eclipse.jetty.server.AbstractConnector - Stopped NetworkTrafficServerConnector@2fd409c1{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@3054cdd3{/,null,STOPPED}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@6d7d0946{/__admin,null,STOPPED}
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.178 s - in ***
```

And when adding Spring Boot BOM (just an example) I get errors when running my UT with `wiremock`, but no errors with `wiremock-standalone`

Sample of errors with Spring boot BOM (2.7.18)

```
java.lang.NoClassDefFoundError: jakarta/servlet/DispatcherType
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.DispatcherType
```

**Comment by simonwu1024** [comment]
Hi @tomakehurst , I'm a software engineer and working on a Play project with java 8. 
Now I'm trying to use WireMock to add some tests for http calls.

What I've done is I added this into build.sbt file:
`"org.wiremock" % "wiremock-standalone" % "3.0.1" % Test`
`After reloading dependencies and IDEA didn't give some complaints in my tests, but found this error when running the test:class file has wrong version 55.0, should be 52.0`
As you mentioned above in this issue earlier, 3.X is for java 11, I guess this makes sense.

Then, I guess the version 2.X with "jre8" must be compatible with java 8, so I added this line in build.sbt:
`"com.github.tomakehurst" % "wiremock-jre8" % "2.35.2" % Test`
and it shows this error when reloading dependencies:
`sbt.ResolveException: unresolved dependency: com.github.tomakehurst#wiremock-jre8;2.35.2: not found`
In Maven repo, I saw this
<img width="811" alt="image" src="https://github.com/wiremock/wiremock/assets/127800463/18c2e091-2335-4725-a889-785ebf050fc1">
so I guess the dependencies can't be found is because it's moved to another name org.wiremock >> wiremock, the name with jre8 doesn't exist anymore. 

May I ask which one is the name/version that is compatible with java 8?
Thank you so much if you could give me some ideas!
