### ISSUE TITLE
Request mapping is not differentiating between create/update 

### ISSUE THREAD

**Issue by udayanichava** [tomakehurst/wiremock#1100]
# Issue guidelines

If you're asking a question, rather than reporting a bug or requesting a feature, **please post your question on the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user), and do not open an issue**.

Please do not log bugs regarding classpath issues (typically manifesting as 'NoClassDefFoundException' or 'ClassNotFoundException').
These are not WireMock bugs, and need to be diagnosed for your project using your build tool. Plenty has already been written in WireMock's issues and mailing list about how to resolve these issues
so please search these sources before asking for help.

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [ ] Which version of WireMock you're using
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
- [ ] A failing test case that demonstrates the problem
- [ ] Profiler data if the issue is performance related   

## Feature requests

Please include details of the use case and motivation for a feature when suggesting it.

**Comment by tomakehurst** [comment]
Closing, as this is just a copy of the issue posting guidelines.

Please post questions to the mailing list.

**Comment by udayanichava** [comment]
sorry for the earlier post, please find my issue here. 

I am trying to record Request n Response of my application's api calls from UI to the backend using Record and Playback(New). I am able to replicate my scenarios like

Create a new product,
go back to list of products and see the new product in the list
try to edit the new product -> data is fetched for the new product from stubs
When trying to update the product => it says Request was not matched . while it is trying to match the request of UPDATE to equal to CREATE. 

I read the entire documentation but unable to figure out a solution to this. 

Please help find a solution or provide me with one if I am not looking at the right place for this.
