### ISSUE TITLE
wiremock return wrong content-length in response for 200 status code

### ISSUE THREAD

**Issue by zhoujia1974** [tomakehurst/wiremock#1101]
We are using wiremock-jre8-standalone 2.21.0. We start wiremock as a standalone server.

We have a mapping file like below.
`{
  "request": {
    "method": "POST",
    "url": "/api/work/123/start"
  },
  "response": {
    "status": 200
  }
}`

When the client sends a request to this mapping, it gets the below response.

`Matched-Stub-Id →1868d9cc-3201-411d-aa8f-e31711123551
Vary →Accept-Encoding, User-Agent
Content-Encoding →gzip
Content-Length →20
Server →Jetty(9.4.z-SNAPSHOT)`

The Content-Length = 20 is obvious wrong since this response has no body. It causes the jersey log in the client code throws exception since the log code tries to read more bytes from the response stream but there are no more content.

In this case, 204 should be more appropriate status code since it means no content. If we switch to 204 code, it will return with out Content-Length and client code will work fine. We made this change to fix the issue. But this still looks like a bug with 200 status code if there is no body.

**Comment by tomakehurst** [comment]
Thanks for reporting. Seems to be specific to gzipped responses that would normally be chunk encoded.

You can work around the problem by upgrading to WireMock 2.22.0 and disabling chunked encoding in the options.

**Comment by zhoujia1974** [comment]
Thanks. Actually we didn't use gzip compression in our client code. The response I posted is when I test this in POSTMAN which uses gzip by default. I checked my client log. The transfer-Encoding is Chunked.

**Comment by zhoujia1974** [comment]
One more thing I want to mention is that this issue only occurs on some platform. I run the same client and wiremock server on windows 10 without any issue. But it fails on macos and linux container. So it may be related to *nix os family only.

**Comment by tomakehurst** [comment]
OK, so in some cases you've seen this happen without a gzip response being sent?

**Comment by zhoujia1974** [comment]
yes, in all the real cases we we don't use gzip compression. The only time using gzip compression is when I tested the mapping directly using POSTMAN tool today. Below is the log when I run our bdd test in a windows machine. I can't get the response log from the failed deployment since it throws exception when try to log.

`36 > POST http://localhost:9091/api/work/123/start
36 > Accept: application/json
36 > Content-Type: application/json
{}
36 < 200
36 < Matched-Stub-Id: 7c981af3-757a-43f3-8ce8-cfc2b9a8dfa5
36 < Server: Jetty(9.4.z-SNAPSHOT)
36 < Transfer-Encoding: chunked
36 < Vary: Accept-Encoding, User-Agent`

**Comment by tomakehurst** [comment]
I'm going to close this because, as far as I can tell, this is working OK in `2.23.2-jre8`.

If you find you're still having this problem with the latest version, please post the info required to replicate (or the full test source ideally) and I'll take another look.
