### ISSUE TITLE
[Feature] Add ability to disable auto compress response of Wiremock bundled in Jetty GzipHandler

### ISSUE THREAD

**Issue by oz4899** [tomakehurst/wiremock#1104]
**Feature request:**  Add ability to disable auto compress response of Wiremock bundled in Jetty GzipHandler

**Current situation**
We're using Wiremock as a proxy forwarding instance for testing purpose, We found that the behavior of response when connecting directly to real service and while connected to the real service via Wiremock are different. After did an investigation for a while, we found that our client sends the request with header "Accept-Encoding: gzip" but our service did not handle it properly and didn't do any compression before return the response to the client but when we test this via Wiremock, the response seems to be encoded in gzip format properly, this can lead to the gap that we cannot capture the bug in our end.

**Request**
Provide the option for WiremockServer instance to be able to disable the "auto compress" feature bundled in the Jetty GZIP handler class. Would be nice if we can have it also as an option in standalone version

**Comment by jfriedly** [comment]
+1 for this feature!

**Comment by chenka88** [comment]
+1 it took us sometime to find out wiremock response is flipped and we can't disable it.

**Comment by alexfanshawebabylon** [comment]
+1 so the: ConsoleNotifyingWiremockNetworkTrafficListener can log the response, currently output:
`2019-07-12 13:51:30.856 Outgoing bytes: HTTP/1.1 200 OK
Content-Type: application/json
Matched-Stub-Id: 76b5ceda-1d8d-4fd0-9268-e3aef0ebf977
Vary: Accept-Encoding, User-Agent
Content-Encoding: gzip
Content-Length: 104
Server: Jetty(9.4.14.v20181114)


2019-07-12 13:51:30.856 Problem decoding network traffic
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:813)
	at com.github.tomakehurst.wiremock.http.trafficlistener.ConsoleNotifyingWiremockNetworkTrafficListener.outgoing(ConsoleNotifyingWiremockNetworkTrafficListener.java:49)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer$NetworkTrafficListenerAdapter.outgoing(JettyHttpServer.java:441)`
