### ISSUE TITLE
Allow the WireMock standalone to specify notifier. 

### ISSUE THREAD

**Issue by pvanassen** [tomakehurst/wiremock#1108]
Allow the WireMock standalone to specify notifier. 

Currently WireMock standalone server always uses 'ConsoleNotifier' as its notifier. A nice improvement would be to make this configurable. This would allow request mismatch logging to slf4j. 

Our specific use-case is, we run WireMock standalone in Mesos and we don't have easy access to those logs but we can forward slf4j to an ELK stack making the logs available for all our devs.

**Comment by MEZk** [comment]
Hello!
I faced the same problem trying to configure WireMock to log in a specific format. For example: if I want to use SL4J to deliver logs to Splunk, or GrayLog. Currently WireMock logs requests journal as a multiline pretty json. These logs cannot be parsed easily by Splunk. It would be nice to have the ability to set custom notifier to transform logs.

**Comment by pvanassen** [comment]
Ready for review

**Comment by pvanassen** [comment]
PR needed merging again after 2 months of nothing. Not interested in only resolving merge conflicts without result.
