### ISSUE TITLE
Epoch format from `now` helper does not give a UNIX Timestamp

### ISSUE THREAD

**Issue by asgrim** [tomakehurst/wiremock#1110]
Using `{{now format='epoch'}}` in a templated response gives a timestamp with too much precision. A Unix timestamp should be represented in _seconds_ since 1/1/1970 etc, the representation returned needs to be divided by 1000 it seems.

Right now using `{{now format='epoch'}}` gives `1554989345111` which is 25th August 51245 at 8:45pm... in reality, to be a truly portable timestamp, it the result should be divided by 1000 (and rounded I guess), to give `1554989345` 11th April 2019 @ 1:29pm (the correct value).

Depending on opinions, this could either be a bug (Unix timestamp is output with too much precision), or a feature request (please add support for portable Unix timestamps) :grin: thanks!

**Comment by tomakehurst** [comment]
I'd be happy to accept a PR to add `{{now format='unix'}}` if you feel like contributing one.

**Comment by asgrim** [comment]
Seeing what I can do :+1:

**Comment by asgrim** [comment]
Added PR in #1111
