### ISSUE TITLE
com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java NullPointerException on newer than 2.20

### ISSUE THREAD

**Issue by halkeye** [tomakehurst/wiremock#1112]
I havn't gotten it down to a simple test case yet, but I dug into it,

StubMappingJsonRecorder#buildRequestPatternFrom has a call to request.getParts(), which returns null. This seems to be because WireMockHttpServletRequestAdapter#cachedMultiparts is defined, but size of 0. I'm not sure how it gets populated because I don't see it ever being null.

When i downgraded to 2.20 the same code ran again.

Nothing stands out to me looking at https://github.com/tomakehurst/wiremock/compare/2.20.0...2.22.0

Code is configured using the WireMockRule
```
@Rule
    public WireMockRule bitbucketApi = new WireMockRule(wireMockConfig().
            dynamicPort().dynamicHttpsPort()
            .usingFilesUnderClasspath("api/cloud")
    );
```
https://github.com/jenkinsci/blueocean-plugin/blob/340402489d16646128b5d75f205e0a241ca88761/blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BbCloudWireMock.java#L15-L18

I didn't set this up so I'm not entirely sure how everything works or what other info is useful.

**Comment by halkeye** [comment]
Oh, I added the logger
```
.notifier(new ConsoleNotifier(true))
```

not sure if that matters

**Comment by tomakehurst** [comment]
If you're still having this problem, please could you post a failing test case + your dependencies?
