### ISSUE TITLE
feature: make standalone mappings loader configurable

### ISSUE THREAD

**Issue by aklemp** [tomakehurst/wiremock#1120]
We are using wiremock for integration tests in standalone mode inside OpenShift. This works great in most cases. Unfortunately, we use OpenShift mechanisms to mount the contents of `mappings` and `__files` folders from so-called ConfigMaps which results in the following structure.

```
/home/wiremock/
├── mappings/
│   ├── mapping1.json -> ..data/mapping1.json
│   ├── mapping2.json -> ..data/mapping2.json
│   ├── ..data -> ..2019_04_16_09_33_26.819580497
│   └── ..2019_04_16_09_33_26.819580497/
│       ├── mapping1.json
│       └── mapping2.json
└── __files/
    ├── response1.json -> ..data/response1.json
    ├── ..data -> ..2019_04_16_09_33_26.676892730
    └── ..2019_04_16_09_33_26.676892730/
        └── response1.json
```

Wiremock is showing the mappings three times in the `__admin` endpoint, because it finds for example:

```
mapping1.json
..data/mapping1.json
..2019_04_16_09_33_26.819580497/mapping1.json
```
[JsonFileMappingsSource](https://github.com/tomakehurst/wiremock/blob/2.22.0/src/main/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSource.java#L110) is simply loading all files recursively.

Detecting duplicates would be more complex I suppose but I can think of several ways using configuration (to not break existing behavior).

1. Configure to skip files and folders with leading dot (as these are hidden in Linux/Unix).
2. Generic case of the above: configure to skip (or include) files and folders matching a specific regex.
3. Configure to load files non-recursive.
4. Instead of configuring `ROOT_DIR` one could specify `MAPPINGS_ROOT` and `FILES_ROOT` independently to use the respective `..data` subfolder link (might have some side effects I'm not aware of).
5. Configure to skip symbolic links (although they might link to somewhere completely different in the directory tree).

My preference is given in the above order and I could provide a pull request if you name the solution that would suit your tool the most.

**Comment by tomakehurst** [comment]
Closing due to age and inactivity
