### ISSUE TITLE
Using jsonPath helper in standalone and the type of the target it is an Array of Map. All double quote are replace with &quot;

### ISSUE THREAD

**Issue by wingzhao8132** [tomakehurst/wiremock#1122]
Reproduce steps:
Given a request body like :
{
    "foo": "bar",
    "target": [
                       { 
                              "aaa": "1",
                              "bbb": "2"
                       }
                  ]
}

When I enable --global-response-templating in wiremock standalone, and I try to show the value in the response body defination with 
"response" : {
    "status" : 200,
    "body" : " Blablabla {{jsonPath request.body '$.target'}} blablabla",
.......
.......

Expected:
I could get the result body like  Blablabla [{"aaa":"1","bbb":"2"}] blablabla

Actually:
I will get the result body like Blablabla [{&quot;aaa&quot;:&quot;1&quot;,&quot;bbb&quot;:&quot;2&quot;}] blablabla

BTW, when I try to debugging, result instanceof List below is True,
Object result = JsonPath.read(inputJson, jsonPath);

**Comment by tomakehurst** [comment]
I'm not sure what the problem is here. Your expected and actual are the same, so surely that's working OK?

**Comment by wingzhao8132** [comment]
Sorry... wrong paste...
Here is actually:
I will get the result body like 
Blablabla [{&quot;aaa&quot;:&quot;1&quot;,&quot;bbb&quot;:&quot;2&quot;}] blablabla

**Comment by wingzhao8132** [comment]
Sorry, the browser will change "& quot;" (a space inside) to " automatically. 
So the response will shows like:
Blablabla [{& quot;aaa& quot;:& quot;1& quot;,& quot;bbb& quot;:& quot;2& quot;}] blablabla

**Comment by mayankj1995** [comment]
Does we have any update on this issue? I am facing the same problem where my json string has its double quotes replaced by &quot; only when using the response template transformer.

**Comment by mayankj1995** [comment]
@tomakehurst Found the answer. We need to use the triple { to escape the html values. 
So the solution in the above case would be  `"body" : " Blablabla {{{jsonPath request.body '$.target'}}} blablabla",`
Check out http://handlebarsjs.com/

**Comment by tomakehurst** [comment]
Yep, that's the one
