### ISSUE TITLE
DEBUG level logs for verbose mode, log request details before calling reponse renderer

### ISSUE THREAD

**Issue by erichhsun** [tomakehurst/wiremock#1126]
Version: 2.23.2

In AbstractRequestHandler.handle() is there a reason why logRequests isn't done before the responseRenderer.render() is called?

If the renderer throws an exception (like a ProxyResponseRenderer), then its not possible to see the incoming request details, since notifier().info() is called after responseRenderer.render().

It would be nice to expose certain logs at DEBUG level so we can set the logback level to choose how verbose the verbose logs should actually be, or select the amount of detail to log based on other configuration options.

Thanks!

**Comment by tomakehurst** [comment]
Closing individual logging issues in favour of (referenced) logging redesign issue.
