### ISSUE TITLE
How to switch automatically when server is down

### ISSUE THREAD

**Issue by swapnilshetes** [tomakehurst/wiremock#1130]
Hi team, 
How wiremock automatically switch from main server to proxy when main server down? 

I have created test case on Rest APi.  Created Rest api on my local server.  Normally run the test case And ran the test senarioies. Now I am using service virtulazation using wiremock. It's good experience but i have some concerns
1. I have created test case for rest api. 
2.then use stand alone server 
3.then start stand alone server using  -- proxy with default server
4.it created mapping files in __file and mapping folder
5.then I stop my main server and then use that proxy and then run properly
But my concerns are below please check
1.how can i create mapping files automatically using wirmock open source library with java (note : find solution to create mapping automatically using wiremock server and config port and then record and save in mapping and file folder ) 
2.i want cotinus recording and switch automatically when main server is down how can i use point #1 to compare old recording with new,  if new recording is dmiss match with old one then I want to update mapping file automatically. 

Please assist me and I am very thank full if giving me proper direction.  If possible if any one have small demo on this automatic switch please share 

Thank in advance

Swapnil

**Comment by tomakehurst** [comment]
Please post questions to the mailing list

**Comment by swapnilshetes** [comment]
Thanks, 
but I am not getting any answer from mailing list,That why I have created.I will do that. Thanks for your suggestion.

**Comment by tomakehurst** [comment]
Reposting on here won't get you an answer any faster. It just clogs up my inbox.
