### ISSUE TITLE
Publish NPM package with Wiremock Standalone

### ISSUE THREAD

**Issue by tomasbjerre** [tomakehurst/wiremock#1131]
# Background
Perhaps you are familiar with this already but **NPM** now includes an [`npx` command](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b).

This means you can publish a package named `any-package` in **NPM** and users can run it by simple running `npx any-package`. That command will download and run the tool.

This feature can be combined with [jdeploy](https://github.com/shannah/jdeploy) to publish command line `java` tools in **NPM** and ease usage.

This is what I've done here: https://www.npmjs.com/package/git-changelog-command-line

# Feature request

Make Wiremock Standalone available through **NPM** with something like `npx wiremock-standalone`.

**Comment by tomakehurst** [comment]
I think this sounds like a very reasonable idea, but as with https://hub.docker.com/r/rodolpheche/wiremock/ may work best as an independent project.

**Comment by tomasbjerre** [comment]
I published: https://www.npmjs.com/package/wiremock

It can now be run with:
```bash
npx wiremock
```

**Comment by tomakehurst** [comment]
Awesome stuff, thanks!
