### ISSUE TITLE
Providing catch-all stubs with absent query parameters doesn't work

### ISSUE THREAD

**Issue by Davio** [tomakehurst/wiremock#1133]
Found on version 2.23.2

Given 2 mocks:
```
MappingBuilder mappingBuilder1 = get(urlPathEqualTo("/api")
                .withQueryParam("param1", equalTo("foo"))
                .withQueryParam("param2", equalTo("bar"))
                .willReturn(okForContentType(MediaType.APPLICATION_JSON_UTF8_VALUE, body));
```
And
```
MappingBuilder mappingBuilder1 = get(urlPathEqualTo("/api")
                .withQueryParam("param1", equalTo("foo"))
                .withQueryParam("param2", StringValuePattern.ABSENT)
                .willReturn(okForContentType(MediaType.APPLICATION_JSON_UTF8_VALUE, body));
```
If we query this mock with `/api?param1=foo&param2=bar` it will not match.
It looks like it tries to match this request to the first (or latest, not sure) stub that was configured.

I.e. it looks only at the URL path for matching the stub and only then for the actual query parameters for verification of the stub. I think there should be a way to make the query parameters part of the matching process.

**Comment by tomakehurst** [comment]
This works fine for me. Can you post a full failing test case?
