### ISSUE TITLE
incomplete documentation for "Pushing JSON files to a remote WireMock instance"

### ISSUE THREAD

**Issue by ogarling** [tomakehurst/wiremock#1138]
At https://github.com/tomakehurst/wiremock/blob/master/docs-v2/_docs/running-standalone.md#pushing-json-files-to-a-remote-wiremock-instance it is mentioned it is possible to push JSON files to a remote WireMock instance.

The content of the paragraph starts with "You can push a collection of mappings to a remote" and then it stops in the middle of the sentence.

**Comment by tomakehurst** [comment]
LOL, I obviously got distracted! Will try and put something useful in there next time I publish the docs.

**Comment by ogarling** [comment]
Could you please share the solution without being elaborate because the documentation will follow?
I am hoping it is possible to HTTP POST the mappings to a remote instance via the admin API.
This one gets close: http://wiremock.org/docs/api/#tag/Stub-Mappings/paths/~1__admin~1mappings/post
But I would like to upload an entire set at once.

**Comment by tomakehurst** [comment]
Basically, you need to set up a WireMock instance in Java, then call a specific method:

```java
WireMock wm = new WireMock("my.host", 8080);
wm.loadMappingsFrom("/my/root/directory"); // Root dir contains mappings and __files
```

**Comment by RAZAW** [comment]
I was searching for the same and came across this post. Seeing this issue is still open, @ogarling were you able to successfully post the mappings using the above method? Also, could you please share how you have connected to the remote instance? Many thanks.
