### ISSUE TITLE
Implement Rolling Request Log (delete oldest request logs)

### ISSUE THREAD

**Issue by JesseKPhillips** [tomakehurst/wiremock#1139]
Our test automation makes heavy use of the log entries to verify requests being sent to the service. Since tests are run in parallel and don't know if other testing is happening it is not possible to clear the complete request log without affecting the validation of other tests.

These logs also get large enough that Java is unable to return all requests do to running out of memory.

Finally I believe extremely large logs slow the mocks responsiveness to requests.

Thus I'm requesting some form of internal purging of older logs 1024 log entries should be enough for everyone :)

**Comment by tomakehurst** [comment]
Have you tried limiting the request journal size as described here? http://wiremock.org/docs/configuration/#request-journal

**Comment by JesseKPhillips** [comment]
That is probably what I need (Using the stand allow options: http://wiremock.org/docs/running-standalone/)

Thanks,
