### ISSUE TITLE
XML placeholder support doesn't work

### ISSUE THREAD

**Issue by D0rmouse** [tomakehurst/wiremock#1145]
I've tested the XML placeholder support #1061 (#1059) (@zheng-wang) and it seems it doesn't work. 

Please refer to this [demo project](https://github.com/D0rmouse/wiremock-placeholder-bug) showing the bug.

**Comment by D0rmouse** [comment]
@zheng-wang

**Comment by zheng-wang** [comment]
If you change the dependency (in pom.xml) from wiremock-standalone to wiremock, it'll work. I have no experience of using wiremock-standalone, so can't tell whether the placeholder feature should be provided by it as well.

By the way, dependency xmlunit-placeholders seems unnecessary, as it is a transitive dependency of wiremock.

**Comment by D0rmouse** [comment]
Yes, it works with the normal wiremock artifact. Think I've read somewhere in the Spring docs that the standalone version is recommended. Anyway, it would be nice if it'd work in standalone.

Yes, the xmlunit-placeholders was me trying to fix things.

**Comment by tomakehurst** [comment]
Closing due to age and inactivity
