### ISSUE TITLE
Multipart request verification fails

### ISSUE THREAD

**Issue by aurelien-baudet** [tomakehurst/wiremock#1146]
The server is started and configured to stub a response on a particular URL only.
An HTTP client performs the request and receives the stubbed response correctly.
Then to ensure that the request is sent as expected, the `verify` is used. `verify` works well when request body is JSON but not when it is multipart.

Here is a sample that demonstrates the issue with wiremock-jre8 version 2.23.2:

```java
@Test
public void issue() {
  WireMockServer server = new WireMockServer(options().dynamicPort());
  server.start();
  server.stubFor(post("/api/mail.send.json")
    .willReturn(okForJson("{\"message\": \"success\"}")));

  HttpPost httpRequest = new HttpPost(server.baseUrl() + "/api/mail.send.json");
  httpRequest.setEntity(MultipartEntityBuilder.create().addTextBody("test", "hello").build());

  HttpResponse httpResponse = HttpClients.createDefault().execute(httpRequest);

  server.verify(postRequestedFor(urlEqualTo("/api/mail.send.json"))
    .withRequestBodyPart(new MultipartValuePatternBuilder()
      .withName("test")
      .withBody(equalTo("hello"))
      .build()));
}
```

The stacktrace:
```
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
POST
/api/mail.send.json

> but was:<
POST
/api/mail.send.json

>
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:39)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:548)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:539)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:517)
	at com.github.tomakehurst.wiremock.WireMockServer.verify(WireMockServer.java:265)
...
```

It seems that calling `request.getParts()` returns an empty content for parts because the InputStream has already been read before. While debugging, the exception `throw new IOException("Missing content for multipart request")` is thrown but it is caught later and silently ignored.
Then verification process considers the request as not multipart so matchers don't call multipart matcher at all.

I also used the standalone jar to record requests and responses and request body is missing when it is multipart and works well when it is JSON.

**Comment by aurelien-baudet** [comment]
After investigating more, changing **stub** like this:

```java
@Test
public void issue() {
  WireMockServer server = new WireMockServer(options().dynamicPort());
  server.start();
  server.stubFor(post("/api/mail.send.json")
    .withMultipartRequestBody(aMultipart("test"))
    .willReturn(okForJson("{\"message\": \"success\"}")));

...
}
```

Make **verification** works.

The issue comes from initialization of `LoggedRequest`. The `multiparts` attribute of `LoggedRequest` is not set (`null`) if stub doesn't contain at least one declared multipart.
There should have no link between stub and verification. Stub is used to define a response whereas verification is used to ensure that the client has correctly sent a particular request. Therefore, the request matching used for stubbing should be independent of the request matching for verification.

**Comment by tomakehurst** [comment]
Closing, as the initial test case now passes
