### ISSUE TITLE
Feature Request: Alter original HTTP Request

### ISSUE THREAD

**Issue by bademux** [tomakehurst/wiremock#1147]
Hello ,
I have weird problem with SOAP body, server requires to have its url in request body (SOAP AdressingFeature on), I have to rewrite request body by replacing wiremock's url (localhost in my case) to targetServerUrl. More info [here](https://groups.google.com/forum/#!topic/wiremock-user/rU8ZG8MyBJI).

With a bit of pain I found a way to hook the request [here the example](https://gist.github.com/bademux/b2eb7e930207a521aa210d1ebcff21e0), but it will be nice to have a wiremock Extension and ability to alter current request (RequestBuilder#like() method for Request url)

Thanks!

**Comment by tomakehurst** [comment]
Already built :-) Just waiting for a release, which I'll try and do this weekend.

Here's an example: https://github.com/tomakehurst/wiremock/blob/master/src/test/java/com/github/tomakehurst/wiremock/RequestFilterAcceptanceTest.java#L194

**Comment by bademux** [comment]
It's fantastic! Thanks!
Waiting for the release.

**Comment by bademux** [comment]
Works like a charm in [2.24.0](https://github.com/tomakehurst/wiremock/releases)
