### ISSUE TITLE
Request was not matched: how to print bodies without modifications?

### ISSUE THREAD

**Issue by fedotxxl** [tomakehurst/wiremock#1148]
Hello,

It's impossible to compare expected body / real body with current "Request was not matched" implementation. It tries to fit a smal screen and cuts rows. This leads that I can't diff expected and real body and view difference. 

Is it possible just to print the expected / real body without any modifications to be able to copy them and diff with any diff program?

**Comment by tomakehurst** [comment]
There are a couple of things you can do to help with this:
1) Reduce the column width used to render the ASCII table by sending e.g. `X-WireMock-Console-Width: 59` in your request headers.
2) Use the "near misses" API to get at the underlying data used to render the diff, then print it however best suits you.
