### ISSUE TITLE
FeatureRequest: tune equalToXml to mach different xml ns prefixes

### ISSUE THREAD

**Issue by bademux** [tomakehurst/wiremock#1150]
Hello,
I have the problem with SOAP client generated with "wsgen" tool.

It generates different prefixes on request on unpredictable conditions, so I'm not able to create stub.
I need A way to tune XMLUnit as per question: https://stackoverflow.com/questions/13358305/how-to-compare-two-xml-with-the-same-namespace-but-different-prefixes-using-java

```
-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
                                                           |
                                                           |
POST                                                       | POST
/                                                          | /
                                                           |
......
    <ns2:GetValue                                          |     <ns3:GetValue
xmlns="http://CIS/BIR/PUBL/2014/07/DataContract"           | xmlns="http://CIS/BIR/PUBL/2014/07"
xmlns:ns2="http://CIS/BIR/2014/07"                         | xmlns:ns2="http://CIS/BIR/PUBL/2014/07/DataContract"
xmlns:ns3="http://CIS/BIR/PUBL/2014/07"                    | xmlns:ns3="http://CIS/BIR/2014/07"
xmlns:ns4="http://schemas.microsoft.com/2003/10/Serializa  | xmlns:ns4="http://schemas.microsoft.com/2003/10/Serializa
tion/">                                                    | tion/">
......
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

Proposition: ability to tune "equalToXml"

Thanks!

**Comment by tomakehurst** [comment]
So you'd want to be able to toggle `equalToXml` to be able to use "similar" in addition to "identical"?

**Comment by bademux** [comment]
Yes I want to access XMLUnit rule creation\be able to override com.github.tomakehurst.wiremock.matching.EqualToXmlPattern#match\hook EqualToXmlPattern creation

I'm using record\replay strategy implemented with [Junit Rule](https://gist.github.com/bademux/88365665332630450858bb81f2a6bc9c). 
I can imagine that there is a way to define custom matcher while recording stubs and then use it on replay.
If there no ready to use solution, can you please recommend me a fix. I be grateful for any solution including reflection-based :) .

**Comment by bademux** [comment]
I tried to add custom ```EqualToXmlPatternIgnoringNsPrefix``` using ```StubMappingTransformer```,
but can't see how my custom json stub file can be used:
```com.github.tomakehurst.wiremock.matching.StringValuePatternJsonDeserializer#findPatternClass``` throws JsonMappingException if it is custom matcher.

**Comment by svpace** [comment]
Any news on this. I am having the same issue.

**Comment by tomakehurst** [comment]
No progress, but I'm rewriting sections of the XML handling code at the moment, so I'll look at whether it's feasible.

**Comment by svpace** [comment]
Thanks!! Let me known if I can be of assistance.

**Comment by tomakehurst** [comment]
I think I've figured out the right way to do it. Thanks anyway!

**Comment by saunaksinha** [comment]
> I think I've figured out the right way to do it. Thanks anyway!

Was this change also incorporated in wiremock-jre8-standalone ? We are using spring-cloud-contract-wiremock which has wiremock-jre8-standalone as transitive dependency and its failing due to that.

**Comment by tomakehurst** [comment]
@saunaksinha yes, this is in all versions of WireMock.

If you think there's a WireMock bug preventing this from working, please could you open a new issue with the details of how to replicate the issue i.e. your stub definition and test request?
