### ISSUE TITLE
[Feature request] Add ability to modify Request sent to WireMock before proxying it to real server

### ISSUE THREAD

**Issue by AndriiFrolov** [tomakehurst/wiremock#1154]
Please add possibility to modify request before sending it to proxied real server

Use case:
I have an application that configured to WireMock server. WireMock server configured to proxy requests to real server. 

 wireMock.register(stubFor(any(anyUrl())
                    .willReturn(aResponse().proxiedFrom("http://myrealserver.com")
UI application -> WireMock -> Real server. This scheme is used to stub only several requests.

Would be useful to have possibility to modify requests that sends real application. For instance, it can be used to avoid login procedure via UI. With such feature I would be able to get token via Rest api request and add this token to all requests

**Comment by bademux** [comment]
Duplicate? https://github.com/tomakehurst/wiremock/issues/1147
