### ISSUE TITLE
[Feature Request] Add --extract-body-size-threshold option for standalone process

### ISSUE THREAD

**Issue by s-shirayama** [tomakehurst/wiremock#1155]
## Feature requests

I want `--extract-body-size-threshold` option for standalone process.
The option is the same feature as `extractBodyCriteria` option (`textSizeThreshold` and `binarySizeThreshold`) on [Start Recording API](http://wiremock.org/docs/api/#tag/Recordings/paths/~1__admin~1recordings~1start/post).

## Motivation
I'd like to see the mappings on UI after recording with standalone process. Currently the response body is written to another file in `__files/` directory when `--record-mapping` option is used on standalone process.
Some wiremock UI (unofficial tools) are not supporting to show response in `__files/` directory so I cannot see the mappings on UI now.
So I'd like wiremock to have `--extract-body-size-threshold` option to avoid writing response on another file in `__files/` directory.

**Comment by tomakehurst** [comment]
The `--record-mappings` option is the old recorder and won't be around after v2, so this won't be possible.

When you're running standalone you can select this option when you start recording via an API call. Also, the intention in the long run is to add this to the recording UI.

**Comment by s-shirayama** [comment]
Hi @tomakehurst ,

Thank you for commenting. I understood that `--record-mappings` is old recorder and we should record with API call. I'll see the API meet our requirement.
Let me close this issue.
