### ISSUE TITLE
attempting to use urlPathEqualTo with a path containing a query param does not give descriptive error 

### ISSUE THREAD

**Issue by Adriani277** [tomakehurst/wiremock#1165]
When using `urlPathEqualsTo` with a path containing a query parameter, the error returned does not represent the underlying problem. Instead of returning an error saying "urlPathEqualsTo does not support query parameters, please use `withQueryParam`" it just says "URL does not match"

![image](https://user-images.githubusercontent.com/36544115/62376805-698b2200-b539-11e9-9e5a-d4f6aae0170b.png)

**Comment by tomakehurst** [comment]
Stub part is now annotated with the match operator to provide some clarity in this case.
