### ISSUE TITLE
[Feature Request] Add "scheme" to request matching rule

### ISSUE THREAD

**Issue by s-shirayama** [tomakehurst/wiremock#1166]
## Feature requests

I'd like wiremock to route the requests according to `scheme` of the request (http or https).
The image of mapping is below,

```
{
  "request": {
    "scheme": "http"
  },
  "response" : {
    "proxyBaseUrl" : "http://http-forward-proxy"
  }
}
---
{
  "request": {
    "scheme": "https"
  },
  "response" : {
    "proxyBaseUrl" : "http://https-forward-proxy"
  }
}
```

## Motivation

I'm using wiremock to catch all requests from the application and proxying to forward proxy in order to record all requests and responses.
Wiremock listens from http and https port (`--port 8080 --https-port 8081`).
And I'd like to route http request to http-forward-proxy and https request to https-forward-proxy.
Currently I'm running 2 wiremock server to realize this use case, but if we have "scheme" on request matching rule, we can realize this use case with 1 wiremock server.

**Comment by tomakehurst** [comment]
Ability to match on scheme added in  eb4a6950a410fc67e97297d7614cfdbad5f0eec1
