### ISSUE TITLE
Content-Length response header is lost for HEAD method proxied stubs

### ISSUE THREAD

**Issue by echemezov-issart** [tomakehurst/wiremock#1169]
### Environment:
- [ ] Version of WireMock: 2.24.0
- [ ] Started as embedded server for JUnit tests with default configuration.

### How to reproduce:

- Run Wiremock server with default configuration.
- Configure stubbing like
stubFor(any(urlPathMatching("/images/.*")).willReturn(aResponse().proxiedFrom("http://www.google.com").build())
- Request for URL like 'http://localhost:8080/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
- persist stubs to snapshot using snapshotRecord()
- check saved stub file

#### Expected result
There is Content-Length header in response definition

#### Actual Result
There is no Content-Length header in response definition

### Cause
Header is removed from response definition by LoggedResponseDefinitionTransformer. It makes sense for other requests when body is saved too but not for HEAD method.

### Found workaround
Use custom ResponseTransformer to save Content-Length for requests with HEAD method into custom header (like X-Saved-Content-Length) and also use custom StubMappingTransformer to add Content-Length header to response definition if header X-Saved-Content-Length presents

**Comment by echemezov-issart** [comment]
BTW, there is another bug which can be reproduced only with workaround for this one: For HEAD request Content-Length header is always "0" if options Options.ChunkedEncodingPolicy.NEVER and Options.ChunkedEncodingPolicy.BODY_FILE because hasInlineBody for HEAD is true but body is empty byte[].

**Comment by tomakehurst** [comment]
This is intentional, as `Content-Length` is calculated on the fly when the response is served, or chunked encoding is used.

**Comment by echemezov-issart** [comment]
@tomakehurst 
But how can you calculate it on the fly for HEAD requests when response does not include body but only headers?

**Comment by tomakehurst** [comment]
OK, I see your point I think. At the moment Jetty will just default `Content-Length` to 0 (although only if you've turned off chunked encoding in WireMock's options) on a HEAD request, but I can see that you'd might want to set it to the value you would receive for the corresponding GET.

**Comment by maoso** [comment]
Hi, this has been fixed? so I think that still cannot get content-length when I do a HEAD request. Into a real HEAD request the content-length of the file is into the response. 

Also do you know how to turn on/off chunked enconding on wiremock .Net? 

Thank you very much
