### ISSUE TITLE
Incorrect scheme in baseUrl

### ISSUE THREAD

**Issue by Jpunt** [tomakehurst/wiremock#1176]
We're using WireMock (2.23.2) standalone and deploy it to Google App Engine. The only option we're giving it at the moment is `--global-response-templating`. 

On GAE we're getting https "for free", but in the responses where we're using `request.requestLine.baseUrl`, this results in a base-url with `http` instead of `https`. 

I must say that I'm not sure if this is a bug or missing config 🤔

**Comment by tomakehurst** [comment]
GAE uses reverse proxying and makes http backend requests, so what you're seeing makes sense in that regard.

You might find it sets the x-forwarded-for header with the origin URL, so reading this might make more sense.
