### ISSUE TITLE
MatchesJsonPathPattern .equals method ignores pattern expression

### ISSUE THREAD

**Issue by symposion** [tomakehurst/wiremock#1178]
Version 2.24.0

The .equals/hashcode methods for MatchesJsonPathPattern are inherited from StringValuePattern, which simply checks that 'expectedValue' is the same. This ignores the value of 'valuePattern' in PathPattern, which can result in a Pattern that matches in a completely different Json body. 

I don't know if this has internal consequences for how Wiremock stores mappings, but it causes me problems because I'm storing the StubMappings in order to verify them later, and I'm expecting to be able to put them in datastructures that distinguish them based on .equals and this isn't working :-(

**Comment by tomakehurst** [comment]
Hmmm...yeah, that sounds like it could be improved.

Please could you supply a specific example of where this is causing you an issue i.e. a pair of stub mappings that ought to be distinct but aren't?

**Comment by symposion** [comment]
Sure. I'd hope this would pass:

`
RequestPattern request1 = post("/myendpoint")
      .withRequestBody(matchingJsonPath("$.LinkageDetails.AccountId", equalTo("1000")))
      .build().getRequest();

RequestPattern request2 = post("/myendpoint")
     .withRequestBody(matchingJsonPath("$.LinkageDetails.AccountId", equalTo("1001")))
     .build().getRequest();

assertFalse(request1.equals(request2));
`

**Comment by symposion** [comment]
To be clearer: I'm storing the RequestPatterns of the mappings I add in order to be able to verify them later. I don't know if it breaks internally because obviously Wiremock has a unique id on each mapping, but it would certainly be useful for me if these objects had a content-faithful .equals method!

**Comment by symposion** [comment]
Hey, thanks for fixing - I only just saw this!
