### ISSUE TITLE
EOF in inputstream, when when bodyPatterns and multipartPatterns are used

### ISSUE THREAD

**Issue by pschwager** [tomakehurst/wiremock#1179]
with commit https://github.com/tomakehurst/wiremock/commit/64012fccc130aa7d4912997a2fad6d9cbb25c0f6#diff-59cd8a8de7281c77e950bd5ac9398d38L276-R273

the call to `getBody()` function was removed, thus the body isn't cached in `cachedBody` and more important a first call to `getBody()` will read the inputstream up to EOF, so that a call to `getParts()` afterwards, can't parse anything.

I faced this problem first with wiremock 2.21 (last working 2.20, which matches the commit above, which was released in 2.21).

How to reproduce:
Take one test case which has a mapping with `multipartPatterns` and add another one which checks `bodyPatterns`. In this case wirmock will call the getBody() first, reads the stream up to EOF, then cannot read the multipart and reports `[Multipart request body] is not present`. If `multipartPatterns` alone is tested, everything is fine.

**Comment by tomakehurst** [comment]
Thanks for reporting this. Please could you post a test case that reproduces it?

**Comment by pschwager** [comment]
Sure, here were go: https://github.com/pschwager/wiremock-1179
if you remove the `bodyPatterns` in `conflicting.json`, then the test is green.

**Comment by pschwager** [comment]
Wiremock Log:
```                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/upload                                                    | /upload
                                                           |
Content-Type [contains] : multipart/form-data              | Content-Type:
                                                           | multipart/form-data;boundary=Boundary_1_639769517_1567107
                                                           | 752214
                                                           |
[Multipart request body]                                   |                                                     <<<<< [Multipart request body] is not present
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

**Comment by tomakehurst** [comment]
Thanks - working test cases very much appreciated!
