### ISSUE TITLE
Apply a delay behaviour during a period and another behaviour in another period

### ISSUE THREAD

**Issue by jabrena** [tomakehurst/wiremock#1180]
Hi,

I am using Wiremock to review some resilience patterns.
http://wiremock.org/docs/simulating-faults/

Using the object, I would like that for a period of time, the wiremock could have a behaviour and after a period of time, it could be have another behaviour.

Currently for all request in the same test, has the same behaviour:

``` java
        //Given
        wireMockServer.stubFor(get(urlEqualTo("/roman-instance1"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withStatus(200)
                        .withBodyFile("latency-problem7/roman.json")
                        .withLogNormalRandomDelay(1500, 0.25)));

```

But I would like that for example the first 5 seconds, wiremock has delay and after that period, wiremock could have another behaviour:

``` java
        wireMockServer.stubFor(get(urlEqualTo("/roman-instance1"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                .withStatus(200)
                .withBodyFile("latency-problem7/roman.json")));
```

How to do it?

Many thanks in advance.

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README
