### ISSUE TITLE
JavaDocs and docs explaining what server and client do? (How to interact with several WireMock servers?)

### ISSUE THREAD

**Issue by christianbalzer** [tomakehurst/wiremock#119]
Are there any JavaDocs available for WireMock (i.e. to tell you what exactly WireMockServer.stop() does, without having to look at the source code)?

Or documentation that explains how the server and client work together (i.e. what each one's tasks are)? Or docs containing hints to nuggets such as https://github.com/tomakehurst/wiremock/issues/18#issuecomment-14923087

I'm particularly interested if you can interact with several WireMockServers in the same unit test, e.g. a localhost and two remote ones...

**Comment by simranj** [comment]
Hi tomakehurst

I found that wiremock standalone app always take request body in json format but my server reads the request body in Hashmap. Is there any work around in that ?

**Comment by tomakehurst** [comment]
Can I suggest you post the details of your setup on the mailing list with a description of the problem you're seeing?

**Comment by jchester** [comment]
> There aren't any JavaDocs. I don't find they're a particularly good way to document DSLs.

They help a lot in IDEs.

**Comment by eostermueller** [comment]
The client code that @tomakehurst added above:
> WireMock wireMock = new WireMock("my.remote.host", "8888");
> wireMock.register(get(urlEqualTo("/thing"))....

...was real helpful.  Would love to see that in the doc.

**Comment by tomakehurst** [comment]
I'm about to give the docs a fairly major overhaul. Agree this needs to be in there, so I'll include it.

**Comment by tomakehurst** [comment]
In new docs.
