### ISSUE TITLE
Wiremock has 'handshake_failure' error when trying to use HTTPS with keystore, and password

### ISSUE THREAD

**Issue by mongoDynamo** [tomakehurst/wiremock#1195]
Wiremock works fine using its own keystore/credential, but when I provide the one I create it no longer works. The Java Spring application returns : "message": "I/O error on POST request for \"https://localhost:8443/profiles/456\": Received fatal alert: handshake_failure; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure"

And when I look at the local url in my browser I see : `localhost uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

The code I'm using to configure wiremock is this : `  @Rule
  public WireMockRule   wireMockRule = new WireMockRule(wireMockConfig()
      .httpsPort(8443)
      .keystorePath("src/main/resources/keystore.p12")
      .keystorePassword("cahngeme"));`

This code worked with HTTP, but fails with HTTPs as for some reason wiremock cannot use my keystore properly (NOTE : This is a valid ketstore and has been tested)

**Comment by sasha943** [comment]
any updates?

**Comment by domholmes** [comment]
I spent several days trying to get Wiremock to work with my own cert as described here and could not get it to work at all. I tried everything including multiple certs, standalone or server started in code, adding certs to the Java trust store etc.

https://stackoverflow.com/questions/60261503/sslhandshakeexception-when-connecting-to-wiremock-with-my-own-self-signed-cert

**Comment by stewartfrancis** [comment]
I had this problem but I was able to work around it by using a JKS type for my keystore rather than PKCS12.

**Comment by cyan-haru-25** [comment]
When I tried, I encountered same symptom. 
but I tried again from beginning, then I mended.

It was not due to keystore type.
I used PKCS12.

**Comment by MolochSim** [comment]
Has anyone found a solution to this issue?
I'm using a BKS keystore, since I work on Android and can't use JKS.

**Comment by tomakehurst** [comment]
Closing as this seems to have become an SSL support thread.

If you need help with this kind of error please post full details needed to replicate on the mailing list, ideally including the actual keystore you're using.
