### ISSUE TITLE
Response templating not working with jsonBody in version 2.25.0 standalone

### ISSUE THREAD

**Issue by jakobnordztrom** [tomakehurst/wiremock#1197]
Version:  2.25.0 standalone
CLI:  java -jar wiremock-standalone-2.25.0.jar --no-request-journal --local-response-templating

Stub mapping exhibiting issue:
<code>{
  "request": {
    "method": "GET",
    "urlPath": "/some/json"
  },
  "response": {
    "jsonBody": {"Key": "Hello world {{request.query.qp}}!"},
    "status": 200,
    "transformers": ["response-template"]
  }  
}</code>

Request: http://localhost:8080/some/json?qp=2

Response: {"Key":"Hello world {{request.query.qp}}!"}

Stub mapping **not** exhibiting issue:
<code>{ "request": { "method": "GET", "urlPath": "/some/body" }, "response": { "body": "{\\"Key\\": \\"Hello world {{request.query.qp}}!\\"}", "status": 200, "transformers": ["response-template"] } }</code>
Request: http://localhost:8080/some/body?qp=2

Response: {"Key": "Hello world 2!"}

**Comment by softdevadamlach** [comment]
is fix released in 2.25.1 standalone?

**Comment by tomakehurst** [comment]
Yarp
