### ISSUE TITLE
Question: Stubs: Matching Requests: Why accepted multiple matching stubs

### ISSUE THREAD

**Issue by DrMattFaulkner** [tomakehurst/wiremock#1201]
If two stubs are created which have matching request parameters these are added to the mappingSet, but with the most recent used to service any requests. 

Instead of allowing multiple stubs why not simply reject the new one with a 409 (Conflict) and / or override the existing?

I'm sure there is a use case here, I just don't see it.

The test case that covers this scenario is:
  `returnsMostRecentlyInsertedResponseIfTwoOrMoreMatch`

**Comment by tomakehurst** [comment]
In principle we could do this, but it seems a bit of a stretch for the meaning (or common use at least) of a 409 status. It would also be a significant backwards-compatibility break at this point, so I'm going to pass on this idea.
