### ISSUE TITLE
Create a separate File Manipulation API

### ISSUE THREAD

**Issue by JesseKPhillips** [tomakehurst/wiremock#1205]
The Mappings API provides operations such as "save" and "delete."

When calling delete it is unknown if it will manipulate the underlining files. If you remove a single mapping the files are not touched. If the general Delete is utilize, all mapping files are removed from the server.

I recommend keeping the Mappings API as a in memory manipulation only. Reset will load the files from disk only because that is the easiest way to get the service "back" to a starting state.

**Comment by tomakehurst** [comment]
If you're not seeing mapping files be deleted when you delete stubs individually via the API, then that's a bug. Can you share a test case that replicates this problem?

**Comment by JesseKPhillips** [comment]
That came to me from someone else, it wouldn't surprise me if there was just confusion.

I think in memory and file operations are still important to separate.

**Comment by tomakehurst** [comment]
Currently there aren't any memory-only operations - all CRUD ops will result in the underlying file being updated if it's marked `persistent`.

**Comment by JesseKPhillips** [comment]
Hmm, well I must be using it differently because I post mapping then use reset to return to the state defined on disk. So from my perspective it is all in memory and writing to dink is a risk.
