### ISSUE TITLE
2.25.1 not published to maven central

### ISSUE THREAD

**Issue by mikebell90** [tomakehurst/wiremock#1208]
Title says it all :;

**Comment by tomakehurst** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/wiremock-user/cMImWh7I7QE

**Comment by mikebell90** [comment]
I had trouble with nexus on wed, thurs, fri last week, but it's been fine pushing stuff as of monday for me fwiw

https://status.maven.org/incidents/t40ylgmsmbl2

**Comment by tomakehurst** [comment]
It's there now
