### ISSUE TITLE
test failure - AdminApiTest::listStubFiles

### ISSUE THREAD

**Issue by nhomble** [tomakehurst/wiremock#1219]
I was building wiremock on my windows 10 and ran the tests. I found a handful of failures. The travis builds are against linux machines.
This assertion:
```java
assertThat(new String(response.binaryContent()), matches("\\[ \".*/bar.txt\", \".*zoo.*txt\" ]"));
```
couldn't match
```text
[ "E:\\wiremock\\build\\resources\\test\\empty\\__files\\bar.txt", "E:\\wiremock\\build\\resources\\test\\empty\\__files\\zoo.txt" ]
```
because of the forward slashes. If we want to support the tests in windows, I was planning to submit a change.

I think updating the matcher to ```"\\[ \".*bar.txt\", \".*zoo.*txt\" ]"``` should do the trick and avoid asserting on the backslash.

**Comment by tomakehurst** [comment]
Fixed by cf282c16241abb61b5f70c450733b6cddb4f3ed0
