### ISSUE TITLE
Response delay times impact global wiremock performance even when running async

### ISSUE THREAD

**Issue by cyberw** [tomakehurst/wiremock#1221]
- Which version of WireMock you're using
Latest master

- How you're starting and configuring WireMock, including configuration or CLI the command line
```
{
    "request": {
        "method": "GET",
        "urlPattern": "/slow"
    },
    "response": {
        "delayDistribution": {
            "type": "uniform",
            "lower": 50,
            "upper": 50
        },
        "body": "whatever"
    }
}
```

`java -jar wiremock-jre8-standalone-2.25.1.jar --bind-address 127.0.0.1 --no-request-journal --async-response-enabled --async-response-threads 500`

- A failing test case that demonstrates the problem

I ran a load test (using locust, and 100 clients/concurrent requests) and was unable to reach more than ~170req/s until response times started growing rapidly (>500ms on average).

There is no issue if I remove the response delay times (it can handle >5000req/s then).

- Profiler data if the issue is performance related   

I havent done any profiling, but I can see wiremock's cpu usage is not very high, about 10-20% of one core on my macbook pro.

**Comment by tomakehurst** [comment]
Have you tried increasing the number of container threads (via `--container-threads`)?

This defaults to 10, which is probably too low for your needs. Also, 500 async response threads is probably too high - 50 might be a better number to start with.

**Comment by cyberw** [comment]
I had kind of misread the documentation I guess. I thought you should either change to async *or* increase container threads.

Increasing the number of container threads had a big impact! Increasing them to 50 gets me to ~840 rps, increasing them to 400 gets me to 1800rps (which is good enough for my use case!)

Decreasing the number of async response threads didnt seem to make a difference, but you are probably right about that as well. It seems using async or not has no impact on the issue at all.

**Comment by rafan** [comment]
FWIW, `--async-response-enabled` takes argument. One needs to use `--async-response-enabled true`.
