### ISSUE TITLE
confusing error messaging around query parameter expectations (for a new user)

### ISSUE THREAD

**Issue by pauldambra** [tomakehurst/wiremock#1222]
I was recently working on a fix in an application I didn't develop and am not familiar with wiremock

The fix to our issue was to add a query parameter to a URL that previously didn't have one.

It turned out we had wiremock tests that asserted on the URL and began to fail. The error message provided didn't help me understand the issue and was very confusing (to me).

## Versions of things
testCompile "com.github.tomakehurst:wiremock:2.6.0"
testCompile "org.mockito:mockito-core:1.+"
assertJ 3.9.1
junit 4.12

## What did I see
On running a test I was given the following output

```
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
GET
/dashboard?registrationFlow=linkAccountSuccess
> but was:<
GET
/dashboard?registrationFlow=linkAccountSuccess
>
```

It isn't clear from this what has failed. And as I haven't used wiremock or written these tests didn't give me any onward journey.

I can't share our exact code because it's overly complicated. But will try and make time to make a replication of the issue.

In short we had 

```
        stubFor(get(urlPathEqualTo("/dashboard"))
                .willReturn(aResponse()
                        .withStatus(303)
                        .withHeader("Location", redirectUrl)));
```

and then after the body of the test

```
WireMock.verify(1, WireMock.getRequestedFor(
          WireMock.urlPathEqualTo("/dashboard")));
```

When if failed I changed it to

```
WireMock.verify(1, WireMock.getRequestedFor(
          WireMock.urlPathEqualTo("/dashboard?registrationFlow=linkAccountSuccess")));
```

But I needed to change it to:

```
WireMock.verify(1, WireMock.getRequestedFor(
          WireMock.urlPathEqualTo("/dashboard"))
          .withQueryParam("registrationFlow", equalTo("linkAccountSuccess")));
```

## What would have been better

It would have saved me 10 minutes of googling if the test output had been

```
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
GET
/dashboard?registrationFlow=linkAccountSuccess
> but was:<
GET
/dashboard?registrationFlow=linkAccountSuccess
>

It looks like this URL path includes a query parameter. You might want to use withQueryParam in your assertion. See: http://wiremock.org/docs/request-matching/

```

**Comment by tomakehurst** [comment]
I can see in this situation that it would be better to a) indicate which URL match operator was in use, and b) show the relevant part of the request URL, rather than always showing the whole thing.

Do you feel like creating a PR to fix?

BTW, 2.6.0 is a pretty ancient version. Although the latest (2.25.1) doesn't improve this particular issue, there are plenty of things it does better, so I'd recommend updating.
