### ISSUE TITLE
Feature request: remove hardcoded /__admin path from HttpAdminClient

### ISSUE THREAD

**Issue by theangrydev** [tomakehurst/wiremock#1231]
`HttpAdminClient#ADMIN_URL_PREFIX` has a hardcoded `/__admin` suffix. It would be useful to make that hardcoded suffix configurable/removable to cover the case that a client is connecting to a WireMock instance hosted behind a URL rewriting proxy, where the `/__admin` suffix is not present in the proxy path.

**Comment by tomakehurst** [comment]
Do you know you can already add a URL path prefix when newing up a `WireMock` instance?

If you tweak your proxy rule so that it keeps the `/__admin` bit but adds a path node before it, that should satisfy your requirement I think.

**Comment by theangrydev** [comment]
Yes, I think the path prefix is not the problem, the problem is like this:

I want to be able to host WireMock at `http://server/*` where internally I am mapping `/*` to `/__admin/*` and have admin requests like:
```
http://server/mappings
```

Instead of:
```
http://server/__admin/mappings
```

This works fine already when using a custom HTTP client to make the admin requests, but the WireMock `HttpAdminClient` has the limitation that it assumes you always want to make a request including `/__admin`

**Comment by tomakehurst** [comment]
Why would you want to strip the `/__admin` bit out?

**Comment by theangrydev** [comment]
I want the flexibility to strip the `/__admin` bit out so that I can have freedom to choose exactly what the API path look like. For example, I might have a naming convention that I usually use that conflicts with the `/__admin` naming.

**Comment by theangrydev** [comment]
I have a workaround in mind now that is enough for my use case and so this issue can be closed.

I can just support multiple paths, one path `http://server/__admin/*` to remain compatible with `HttpAdminClient` and the other path `http://server/*` where I have the naming convention flexibility I was looking for.
