### ISSUE TITLE
Getting null pointer while running from maven but from eclipse Junit individual test working fine.

### ISSUE THREAD

**Issue by madhusudansahu** [tomakehurst/wiremock#1233]
Hi, 

I am using following wiremock dependency : 
<dependency>
					<groupId>com.github.tomakehurst</groupId>
					<artifactId>wiremock-standalone</artifactId>
					<scope>test</scope>
					<version>2.6.0</version>
				</dependency>

and when running from eclipse by choosing run as JunitTest everything is working fine. but when I am running this program from maven I am getting following error. 

wiremock.com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.github.tomakehurst.wiremock.stubbing.StubMapping["request"]->com.github.tomakehurst.wiremock.matching.RequestPattern["bodyPatterns"]->java.util.ArrayList[0])
	at com.example.integration.controller.FileUploadControllerIntegrationTest.configureSystemUnderTest(FileUploadControllerIntegrationTest.java:47)
Caused by: java.lang.NullPointerException
	at com.example.integration.controller.FileUploadControllerIntegrationTest.configureSystemUnderTest(FileUploadControllerIntegrationTest.java:47)

I am having following code which is throwing error.

`package com.example.integration.controller;

import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.options;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.multipart;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.io.IOException;
import java.io.InputStream;

import org.json.JSONException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import static com.example.integration.controller.TestConstants.*;
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.common.ConsoleNotifier;
import com.example.Application;

@SpringBootTest(classes = Application.class)
@AutoConfigureMockMvc
@Import(TestConfig.class)
@TestInstance(Lifecycle.PER_CLASS)
public class FileUploadControllerIntegrationTest extends GenericIntegrationTest {
	@Autowired
	MockMvc mockMvc;

	private WireMockServer wireMockServer;

	@BeforeAll
	void configureSystemUnderTest() {
		this.wireMockServer = new WireMockServer(options().port(8090).notifier(new ConsoleNotifier(true)));
		this.wireMockServer.start();
	}

	@AfterAll
	void stopWireMockServer() {
		this.wireMockServer.stop();
	}

	@DisplayName("upload and validate with success")
	@Test
	public void testUploadFile() throws Exception {
		MvcResult result = mockMvc.perform(createRequest(BCM_DEPLOY_SCOPE, "integration-payload/order-type.json"))
				.andExpect(status().isCreated()).andReturn();
		assertNotNull(result.getResponse().getContentAsString());
	}

	@DisplayName("upload and validate with validation failed.")
	@Test
	public void uploadFileWithValidationFail() throws Exception {

		mockMvc.perform(createRequest(BCM_DEPLOY_SCOPE, "integration-payload/order-type-with-invalid.json"))
				.andExpect(status().isBadRequest())
				.andExpect(content().json(populateJsonToString("__files/json/validation-failure-response.json")));

	}

	/**
	 * @param endpoint
	 * @param multipartFile
	 * @param headers
	 * @return
	 * @throws IOException
	 * @throws JSONException
	 */
	private MockHttpServletRequestBuilder createRequest(String scope, String payloadFile)
			throws IOException, JSONException {
		String endpoint = "http://localhost:8080/files/upload";

		InputStream fis = new ClassPathResource(payloadFile).getInputStream();
		MockMultipartFile multipartFile = new MockMultipartFile("file", fis);
		HttpHeaders headers = getHeadersUsingScope(scope);
		return multipart(endpoint).file(multipartFile).contentType(MediaType.MULTIPART_FORM_DATA).headers(headers);
	}

}
`
Thanks
Madhusudan

**Comment by tomakehurst** [comment]
2.6.0 is very old. Suggest upgrading to 2.25.1.
