### ISSUE TITLE
new protocol supported

### ISSUE THREAD

**Issue by t3573393** [tomakehurst/wiremock#1236]
## Feature requests
When I use the wiremock in the enterprise applications，I found much other protocols in the network or the packing. So support the protocol layer and packing layer in the frameworks, it will more useful in the various situation. For example, the binding port TCP server, the private packing model. I think just add the feature in the jetty filter, it will work.

**Comment by tomakehurst** [comment]
I'm not really sure I understand what you're proposing here.

Could you provide an example of what you'd like to achieve?
