### ISSUE TITLE
Checking no cookie

### ISSUE THREAD

**Issue by arcuri82** [tomakehurst/wiremock#1238]
Hi,
  upgrading Wiremock from 2.2.1 to latest 2.25.1, and tests started to fail.
In one test I am explicitly checking that a SESSION cookie is not set:

```
.withCookie("SESSION", WireMock.notMatching(".+"))
```

this worked in 2.2.1, but not 2.25.1

Is there any easy way to check that a request must not have a specific cookie?
For example, it would be great to have something like:

```
.withoutCookie("SESSION")
```

**Comment by tomakehurst** [comment]
Questions on the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/wiremock-user) please
