### ISSUE TITLE
Wiremock: Not able to set a stub based on finding a required parameter from a json body

### ISSUE THREAD

**Issue by kawalbirsingh** [tomakehurst/wiremock#1239]
The title might look a little confusing. What I'm trying to do, in Mocklab, is create a stub, which would give me a certain response on the basis of a particular parameter or a set of parameter on the json body of that request.

Let's say the body of the request is like below:

{
 "A":{
     "B":{
         "key":"value",
          "key":"value" },
      "C":{
          "key":"value",
          "key":"value"
},
}

I want it to go through the entire body, and look for the key value pair in C, and give me a set response if it finds that pair. Rest of the body is optional.

**Comment by tomakehurst** [comment]
Please post questions to the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/wiremock-user)
