### ISSUE TITLE
Intercepting wire mock request 

### ISSUE THREAD

**Issue by murali474** [tomakehurst/wiremock#1249]
Hi,

i am calling get/post requests using resttemplate in main (String args [] )  method,
in another class  i need to write a for loop so i need to match with incoming request  method name and then call appropriate stubbing

i am using below code. But request size is empty. Can some help . i want to intercept request and iterate them and based on request method i need to call related stubbing.  
Early Responses are much appreciated.
###################################################

WireMock.configureFor(8089);
private static WireMockServer wireMockServer = new WireMockServer(wireMockConfig().port(8089)
wireMockServer.start();

   List<Request> requests = new ArrayList<Request>();

            wireMockServer.addMockServiceRequestListener(new RequestListener() {
                @Override
                public void requestReceived(Request request, Response response) {
                    requests.add(LoggedRequest.createFrom(request));
                }
            });
            for (Request request : requests) {
                LOGGER.info("Method Name from request**********{}", request.getMethod().getName());

            }

and even i tried to call admin endpoint like below , but  i am not getting requests received by wiremock

public void givenWireMockEndpoints() {
		
		LOGGER.info("*********Entered givenWireMockEndpoints*********");
		
		RestTemplate restTemplate = new RestTemplate();

		ResponseEntity<String> response = restTemplate.getForEntity("http://localhost:8089/__admin/requests",
				String.class);

		LOGGER.info("*********Wire Mock Configurations*********{}", response);

	}

**Comment by tomakehurst** [comment]
Please post questions to the mailing list, per the README.

**Comment by murali474** [comment]
I have done it . As I could not get response there so I have created an
issue
