### ISSUE TITLE
Feature Request: Debug info in WireMock response headers

### ISSUE THREAD

**Issue by yogurtearl** [tomakehurst/wiremock#125]
It would be great to put some details in the HTTP headers of the wiremock response.

X-WireMock-MappingId:
X-WireMock-Scenario:
X-WireMock-ScenarioState:

Where mapping id is a optional attribute on mappings ( maybe there is an auto-generated id if one is not explicitly provided )

``` json
{
   "id": "foo1234", 
   "scenarioName": "To do list",
    "requiredScenarioState": "Started",
    "request": {
        "method": "GET",
        "url": "/todo/items"
    },
    "response": {
        "status": 200,
        "body" : "<items><item>Buy milk</item></items>"
    }
}
```

( maybe this is a configurable feature, turned off by default )

**Comment by aumohanraj** [comment]
Looks like this feature request is completed. I can see below http headers in wiremock response.
Matched-Stub-Id
Matched-Stub-Name

**Comment by tomakehurst** [comment]
Good point, closed!
