### ISSUE TITLE
Wiremock giving 500 response if both fileSource and extensions are used.

### ISSUE THREAD

**Issue by mutyasaisrikar** [tomakehurst/wiremock#1252]
Wiremock is giving 500 Server error for all requests when we are configuring both `fileSource` and `extensions` are used.

Version of wiremock : 2.25.1
`        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>2.25.1</version>
        </dependency>`

How am I using wiremock:
`
        WireMockServer wireMockServer =
                new WireMockServer(
                        WireMockConfiguration.options()
                                .gzipDisabled(true)
                                .port(8080)
                                .fileSource(new ClasspathFileSource(configDirectory.getAbsolutePath()))
                                .extensions(
                                        new CustomTransformer()
                                )
                );
        wireMockServer.start();
`

**Comment by tomakehurst** [comment]
Please post questions to the mailing list, and if you're after help with an error, please post the full error message/stack trace.
