### ISSUE TITLE
StubRequestFilter  used to encode the URL is not working as expected.

### ISSUE THREAD

**Issue by gr423** [tomakehurst/wiremock#1259]
my Sample url  :

Get /uri?filter={"accountID":1}

I've the stub for the Get with the 
`wireMockRule.stubFor(get("uri?"+URLEncoder.encode(filter={"accountID":1}))`

I've written the custom StubRequestFilter to encode the query param  .

But request fails with IllegalArgumentException , because of UrisyntaxException.

```
public class EncodeRequestFilter extends StubRequestFilter {

	@Override
	public String getName() {
		return "encode-uri";
	}

	@Override
	public RequestFilterAction filter(Request request) {

		System.out.println("Coming to encode filter");
		//request.isBrowserProxyRequest();
		Request wrappedRequest = RequestWrapper.create().transformAbsoluteUrl(this::encodeAbsoluteUrl).wrap(request);
		wrappedRequest.isBrowserProxyRequest();
        //System.out.println(wrappedRequest.getAbsoluteUrl());
		return RequestFilterAction.continueWith(wrappedRequest);
	}

	private String encodeAbsoluteUrl(String absoluteUrl) {
		int idxOfQueryParam = absoluteUrl.indexOf("?");
		String queryParam = absoluteUrl.substring(idxOfQueryParam + 1);

		if (queryParam.contains("{"))// has json value as part of query encode it .
		{
			try {
				String encodedQuery = URLEncoder.encode(queryParam, StandardCharsets.UTF_8.name());
				return absoluteUrl.substring(0, idxOfQueryParam + 1).concat(encodedQuery);
			} catch (UnsupportedEncodingException e) {
				return absoluteUrl;// Ignoring the exception.Let the request fail
			}
		}
		return absoluteUrl;
	}

}
```

**Comment by tomakehurst** [comment]
If you think this is a bug, please can you post a failing test case.

If you're just asking for some help implementing a filter, please post on the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/wiremock-user)

**Comment by gr423** [comment]
The absoluteUrlTransformer set on the requestWrapper is never used .

<h3>Caused by:</h3><pre>java.net.URISyntaxException: Illegal character in query at index 23: 
/uri?filter={&quot;accountid&quot;:&quot;1&quot;}
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.&lt;init&gt;(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at com.github.tomakehurst.wiremock.jetty9.JettyUtils.getUri(JettyUtils.java:93)
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.isBrowserProxyRequest(WireMockHttpServletRequestAdapter.java:257)
	at com.github.tomakehurst.wiremock.extension.requestfilter.RequestWrapper.isBrowserProxyRequest(RequestWrapper.java:271)
	at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:69)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:82)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:204)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:53)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:60)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)

**Comment by tomakehurst** [comment]
`{`, `}` and `"` are considered unsafe characters accounting to https://www.ietf.org/rfc/rfc1738.txt. Java takes a fairly strict view of this, so this is why it's throwing an error.

If you URL encode your query parameters at the calling end, this should resolve the problem e.g. `/uri?filter=%7B%22accountid%22%3A%221%22%7D`.

**Comment by gr423** [comment]
You are right  .

But i don't have the code access to change the uri before the call comes to Wiremock . 

So was trying with the requestfilter  .

Can't we use the requestFilter to accomplish the same  ?

**Comment by tomakehurst** [comment]
No, it's already too late by that point unfortunately.

**Comment by gr423** [comment]
I see from the Wiremock Docs page ,RequestWrapper  could be used to  Transformation of the URL. 

What are the scenarios i could use it ?

**Comment by tomakehurst** [comment]
Sure, you can use it to transform URLs, but the URL will have been parsed by Java's `URI` class by the time it arrives at your filter.

**Comment by gr423** [comment]
Hmm Tom i see the issue comes when the R`equestWrapper.isBrowserProxyRequest()` method is called 
Which inturn calls `WireMockHttpServletRequestAdapter.isBrowserProxyRequest() `.

Since the RequestWrapper will have the transformers  , can we pass it to WireMockHttpServletRequestAdapter.isBrowserProxyRequest() and invoke the transfomers there  .So the call to URi.create() would succeed.

**Comment by gr423** [comment]
I get the exception in class JettyUtils  .

    ```
public static URI getUri(Request request) {
        HttpURI httpUri = getHttpUri(request);

        URI uri;
        try {
            Method getUriMethod = HttpURI.class.getDeclaredMethod("toURI");
            uri = (URI) getUriMethod.invoke(httpUri);
        } catch (NoSuchMethodException | SecurityException | IllegalAccessException | InvocationTargetException e) {
            uri = URI.create(httpUri.toString());
        }

        return uri;
    }

```

Always the exception block gets executed and UR.create() , is throwing me the excpetion.

**Comment by tomakehurst** [comment]
Yeah, actually that particular call doesn't really need to convert to a `URI`, since it's just used to check whether it's relative or absolute. Changing it to just do the absolute check directly against's Jetty's native class would probably solve this issue.

I'll mark this as a feature request and see about putting this in the next release.

**Comment by gr423** [comment]
@tomakehurst  Thank you .

**Comment by gr423** [comment]
Hi Tom ,
Any updates on this feature  , and may i know when can i expect this .

Thanks in advance

**Comment by tomakehurst** [comment]
No updates and no idea when I'll be doing it, sorry.

**Comment by gr423** [comment]
Please could you suggest me changes which i can do it resolve it  , may be i'll try doing it from my end  .

**Comment by gr423** [comment]
Instead of converting URI.create(httpUri.toString());  

Can we have a check if httpUri.toString().startsWith("http) or httpUri.toString().startsWith("httsp") ?

and continue .

And just for my information , method  isBrowserProxyRequest() why are we checking it ?
