### ISSUE TITLE
Bug: Unrecognized field "bodyAsBase64"

### ISSUE THREAD

**Issue by vishalksahu** [tomakehurst/wiremock#1260]
# bodyAsBase64 not recongnized

I observed that the recording gives a new attribute "bodyAsbase64" instead of "base64Body" which was delivered earlier. When the mock server is run against new recording it fails to start.

Caused by: com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file C:\AZ_DATEN\Workspace\appName\target\classes\mock-data\mappings\mock123\home\amount.json:
Unrecognized field "bodyAsBase64" (class com.github.tomakehurst.wiremock.http.ResponseDefinition), not marked as ignorable
Please do not log bugs regarding classpath issues (typically manifesting as 'NoClassDefFoundException' or 'ClassNotFoundException').

Version : 2.26.0

Config -->

> public WireMockConfiguration MockConfig() throws IOException {
        return WireMockConfiguration.wireMockConfig()
                .notifier(new ConsoleNotifier(true))
                .httpsPort(8443)
                .needClientAuth(true)
                .trustStorePath(keystorePath.getURI().getPath())
                .trustStorePassword("password")
                .usingFilesUnderClasspath("mock-data")
                .extensions(CorsHeaderTransformer.class)
                .keystorePath(keystorePath.getURI().getPath())
                .keystorePassword("password")
                ;

recorded data:

> {
  "request": {
    "method": "POST",
    "bodyPatterns": [
      {
        "contains": "cutomerNo>90704<"
      }
    ],
    "url": "/ws_tatmo_app/services/AService/v8"
  },
  "response": {
    "headers": {
      "Keep-Alive": "timeout=5, max=100",
      "Server": "Apache",
      "Access-Control-Allow-Origin": "*",
      "X-Content-Type-Options": "nosniff",
      "Connection": "Keep-Alive",
      "Date": "Tue, 04 Feb 2020 17:39:10 GMT",
      "Access-Control-Allow-Headers": "Content-Type",
      "X-Frame-Options": "SAMEORIGIN",
      "Referrer-Policy": "no-referrer",
      "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
      "Content-Encoding": "gzip",
      "Vary": "Accept-Encoding",
      "X-XSS-Protection": "1; mode=block",
      "Content-Length": "2504",
      "Content-Type": "multipart/related; type=\"application/xop+xml\"; boundary=\"uuid:7be7c714-09d7-4594-9d7a-313103bfcbb9\"; start=\"<root.message@cxf.apache.org>\"; start-info=\"text/xml\""
    },
    "bodyAsBase64": "<value removed>",
    "body": "<value removed>",
    "status": 200
  }
}

> have removed the contents of the field body and bodyAsBase64

**Comment by tomakehurst** [comment]
Please can you post the details of all the steps you took to arrive at this problem?

**Comment by vishalksahu** [comment]
- Ran the server to do the recording , made requests and retrieved the response from http://localhost:8080/__admin/requests
- copy the response ( as in the bug description) into a JSON file.
- placed the file where mock data are read (for my application src/main/resources/mock-data.mapping/)
-"clean install" and start the application thereafter

**Comment by tomakehurst** [comment]
Step 2 is the problem. The fields for a response don't match those for a response definition.

Wondering why you'd want to do that at all?

Also, are you using the legacy or new recording feature?

**Comment by vishalksahu** [comment]
The ResponseDefination class does not have "bodyAsBase64" as one of the body fields.

https://github.com/tomakehurst/wiremock/blob/ffb2c457036fd33b48f007b1545c163081cb421a/src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java#L94

I am using all manual way of recording , that legacy maybe

**Comment by tomakehurst** [comment]
No, you're right it doesn't, which is why you can't paste logged response JSON into a file that's expecting a response definition.

I suggest you try using the new recorder as per http://wiremock.org/docs/record-playback/. You shouldn't encounter this problem that way.

**Comment by vishalksahu** [comment]
Thanks.

I found out http://localhost:8080/__admin/requests gives "bodyAsBase64"

while http://localhost:8080/__admin/recordings/snapshot gives "base64Body"
