### ISSUE TITLE
handlebars using jsonPath error when evaluating request.headers and request.requestLine.query

### ISSUE THREAD

**Issue by MacTheFork** [tomakehurst/wiremock#1264]
## Bug report

handlebars evaluation using jsonPath error with with PathNotFoundException for request.headers and request.requestLine.query

I use the request.headers.Correlation-ID to control WireMock response

value returned is 
[ERROR: $.outer.inner is not a valid JSONPath expression]

wiremock.com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['outer'] in path $ but found 'com.github.tomakehurst.wiremock.common.ListOrSingle'. This is not a json object according to the JsonProvider: 'wiremock.com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.

- Which version of WireMock you're using
Bahaviour not apparent in 2.22.0
Behaviour appears in 2.23.0 and later - tested in 2.25.1

- How you're starting and configuring WireMock, including configuration or CLI the command line
java -jar wiremock-standalone-2.25.1.jar --local-response-templating

- A failing test case that demonstrates the problem

Mapping file
{
	"request": {
		"method": "POST",
		"urlPattern": "/handlebars/(.*)/test?(.*)"
	},
	"response": {
		"transformers": ["response-template"],
		"body": "{{jsonPath request.requestLine.pathSegments.[1] '$.outer.inner'}} {{jsonPath request.body '$.outer.inner'}} {{jsonPath request.headers.Correlation-ID '$.outer.inner'}} {{jsonPath request.requestLine.query.queryParameters '$.outer.inner'}}"
	}
}

Request is using JSON with a value indicating where the JSON appears in the request

POST /handlebars/{"outer": {"inner": "Path-Parameter"}}/test?queryParameters={%22outer%22:%20{%22inner%22:%20%22Query-Parameter%22}}

HTTP Header is
  Correlation-ID: {"outer": {"inner": "HTTP-Header"}}

Request body is
  {"outer": {"inner": "Request-Body"}}

Actual Response (version 2.23.0 and later)
HTTP/1.1 200 OK
Path-Parameter Request-Body [ERROR: $.outer.inner is not a valid JSONPath expression] [ERROR: $.outer.inner is not a valid JSONPath expression]

Expected Response (as with version 2.22.0)
Path-Parameter Request-Body HTTP-Header Query-Parameter

**Comment by MacTheFork** [comment]
note to self - by compiling each commit after tag 2.22.0 the first commit where it breaks is 
12 Apr 2019 commit ae350716 Made the handlebars JSONPath helper support objects in addition to strings

**Comment by MacTheFork** [comment]
reverting line 50 in WireMockHelpers.java from
  return this.helper.apply(context, options);
back to 
  return this.helper.apply(String.valueOf(context), options);
fixes it

**Comment by tomakehurst** [comment]
This seems to work OK:
`{{jsonPath request.requestLine.pathSegments.[1] '$.outer.inner'}} {{jsonPath request.body '$.outer.inner'}} {{jsonPath request.headers.Correlation-ID.0 '$.outer.inner'}} {{jsonPath request.requestLine.query.queryParameters.0 '$.outer.inner'}}`

Basically, you need to use the indexed form with helpers at the moment. I'm planning to tweak the helpers to detect and avoid this in a future release.

**Comment by tomakehurst** [comment]
I've written this up as a feature request here: https://github.com/tomakehurst/wiremock/issues/1270

**Comment by MacTheFork** [comment]
Many thanks for considering this issue and providing an explanation and a resolution. 

It's a lot clearer to me now what the behaviour is.  
We will review our existing mappings and decide if we should rework them or wait for the feature request to be implemented.

**Comment by tomakehurst** [comment]
I wouldn't recommend waiting. I can't make any guarantees about how soon I'll be able to work on it.

**Comment by MacTheFork** [comment]
No problem, I get your point.  Thanks.

**Comment by tomakehurst** [comment]
Closing, as we have #1270 covering this issue
