### ISSUE TITLE
Response templating offset days not working properly

### ISSUE THREAD

**Issue by 277roshan** [tomakehurst/wiremock#1265]
When using "{{ now timezone='Europe/Paris' offset='+89 days' format='yyyy-MM-dd' }}", it does not consider DST (Daylight Saving Time).

I am expecting 2020-05-06 but WireMock is returning 2020-05-07. The correct date is 2020-05-06. 

This happens when time is in between 2:00 PM PST to 3:00 PM PST. I am using ZonedDateTime for my calculation. 
https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html

Looks like this is a bug from the way WireMock is handling the plusDays scenario.

**Comment by 277roshan** [comment]
https://www.worldtimebuddy.com/?pl=1&lid=8,2988507,5128581,100&h=8&date=2/6/2020%7C0

Refer to this for time comparison

**Comment by tomakehurst** [comment]
I think the logic is correct:

2020-02-07T14:01:00-08:00 (PST) = 2020-02-07T22:01:00Z (UTC)

2020-02-07T22:01:00Z + 89 days = 2020-05-06T22:01:00Z

2020-05-06T22:01:00Z = 2020-05-07T00:01:00+02:00 (Europe/Paris in summer time)

Closing this for now, but please let me know if this working is wrong.
