### ISSUE TITLE
Support XMLUnit placeholders

### ISSUE THREAD

**Issue by HSB-tester** [tomakehurst/wiremock#1269]
I have to ignore some text by using specify custom delimiters (using regular expressions)
It will be deemed a match in most of simple case, excepted when I have a CDATA section in my document

JSON:
{
  "request": {
    "url": "/MyApplication",
    "method": "POST",
    "bodyPatterns": [
      {
        "equalToXml": "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><soapenv:Body><processOCIMessage soapenv:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'><arg0>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;BroadsoftDocument protocol=&quot;OCI&quot; xmlns=&quot;C&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;sessionId xmlns=&quot;&quot;&gt[[xmlunit.ignore]]&lt;/sessionId&gt;&lt;command xsi:type=&quot;TheRequest&quot; xmlns=&quot;&quot;&gt;&lt;userId&gt;None&lt;/userId&gt;&lt;/command&gt;&lt;/BroadsoftDocument&gt;</arg0></processOCIMessage></soapenv:Body></soapenv:Envelope>",
        "enablePlaceholders": true,
        "placeholderOpeningDelimiterRegex" : "\\[\\[",
        "placeholderClosingDelimiterRegex" : "]]"
      }
    ]
  }  ...

**Comment by tomakehurst** [comment]
Already supported: http://wiremock.org/docs/request-matching/#use-of-placeholders

**Comment by HSB-tester** [comment]
Unless I'm mistaken, I still have a problem.
Thanks so much for your help

In my case, wiremock works as a stand-alone process.
If I configure it with this JSON file as it's described in the doc, there is a match when the body of the request is
<message><id>123456</id><content>Hello</content></message>

JSON :
 {
  "request": {
    ...
    "bodyPatterns" : [ {
      "equalToXml" : "<message><id>[[xmlunit.ignore]]</id><content>Hello</content></message>",
      "enablePlaceholders" : true,
      "placeholderOpeningDelimiterRegex" : "\\[\\[",
      "placeholderClosingDelimiterRegex" : "]]"
    } ]
    ...
  },
  ...
}

But if I modify the JSON file to transform part of the XML into CDATA, there is no more correspondence when the body of the request is
<message><id>123456</id><content>Hello</content></message>
I think wiremock is really waiting for the string 
<message>&lt;id&gt;[[xmlunit.ignore]]&lt;/id&gt;&lt;content&gt;Hello&lt;/content&gt;</message>
and the substitution doesn't work.

new JSON :
{
  "request": {
    ...
    "bodyPatterns" : [ {
      "equalToXml" : "<message>&lt;id&gt;[[xmlunit.ignore]]&lt;/id&gt;&lt;content&gt;Hello&lt;/content&gt;</message>",
      "enablePlaceholders" : true,
      "placeholderOpeningDelimiterRegex" : "\\[\\[",
      "placeholderClosingDelimiterRegex" : "]]"
    } ]
    ...
  },
  ...
}
