### ISSUE TITLE
WiremockServer class expose verify with CountMatchingStrategy

### ISSUE THREAD

**Issue by lukasGemela** [tomakehurst/wiremock#1280]
WireMock class seems to have very useful method called 

`verifyThat(CountMatchingStrategy expectedCount, RequestPatternBuilder requestPatternBuilder)`

which is being used by wiremockServer class in this method:

` public void verify(int count, RequestPatternBuilder requestPatternBuilder)`

Unfortunately this method takes only exact number, not a CountMatchingStrategy.
can you please expose version with CountMatchingStrategy also?

**Comment by tomakehurst** [comment]
Do you feel like creating a pull request?

**Comment by lukasGemela** [comment]
sure, I can raise one next week if that's ok

**Comment by tomakehurst** [comment]
Fine by me
