### ISSUE TITLE
JSON stub loading should either allow loading more than one node {} or fail when sees second, not silently parse just first

### ISSUE THREAD

**Issue by antonalechnovic** [tomakehurst/wiremock#1281]
(Feature request)

Reported false positive because of this :-). As I put scenarios next to each other in single file as in tutorial expecting them to work. After debugging I realized that only one of two scenarios in one file is loaded. Then I remembered one of my team PR reviews asking to put all endless .json definitions into one file and then I recalled that wiremock has this mine that it will load just first node silently ignoring the rest. 

It would be nice to put multi-json node in one file so this confusion does not happen. Or at the worst throw parsing error if there are multiple root {} {} in single JSON file. :bowing_man: 

Version 2.26.2

~Wanted to test retry for a client on the same endpoint, the client retries but the switch in scenario state doesn't appear to happen so i only get 502 but not 200 on retry, attached sample stub (based on official [tutorial](http://wiremock.org/docs/stateful-behaviour/)):~

```
{
    "scenarioName": "To do list",
    "requiredScenarioState": "Started",
    "newScenarioState": "Bla",
    "request": {
        "method": "POST",
        "url": "/billing"
    },
    "response": {
        "status": 502,
        "body" : "<items><item>Buy milk</item><item>Cancel newspaper subscription</item></items>"
    }
}
{
    "scenarioName": "To do list",
    "requiredScenarioState": "Bla",
    "request": {
        "method": "POST",
        "url": "/billing"
    },
    "response": {
        "status": 200,
        "body" : "<items><item>Buy milk</item><item>Cancel newspaper subscription</item></items>"
    }
}
```

~Wiremock fails to match second request, so it appears the transition doesn't happen:~

```
-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/billing                                                   | /billing
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

~As a dummy hypothesis added 2 seconds delay to client just to see if wiremock is some sort of late in switching state but got same error.~

**Comment by tomakehurst** [comment]
It's already possible to put multiple stubs into one JSON file. Or am I misunderstanding what you're asking for?

**Comment by antonalechnovic** [comment]
With     `testCompile group: 'com.github.tomakehurst', name: 'wiremock', version: '2.26.3'`  if you put:

`{ .... } { ....} `only first one will load, second won't be and will be silently ignored.

**Comment by tomakehurst** [comment]
Did you put them under a root `mappings` key?

**Comment by antonalechnovic** [comment]
yes, that's correct

**Comment by tomakehurst** [comment]
Were you loading your JSON via the `/__admin/mappings/import` API, or by dropping it in the `mappings` directory?

**Comment by hokkaido** [comment]
@tomakehurst I think the problem is that the documentation for scenarios makes it look like you can just put a single json file into a `mappings` directory that looks like this (copied from http://wiremock.org/docs/stateful-behaviour/)

```
{
    "scenarioName": "To do list",
    "requiredScenarioState": "Started",
    "request": {
        "method": "GET",
        "url": "/todo/items"
    },
    "response": {
        "status": 200,
        "body" : "<items><item>Buy milk</item></items>"
    }
}

{
    "scenarioName": "To do list",
    "requiredScenarioState": "Started",
    "newScenarioState": "Cancel newspaper item added",
    "request": {
        "method": "POST",
        "url": "/todo/items",
        "bodyPatterns": [
            { "contains": "Cancel newspaper subscription" }
         ]
    },
    "response": {
        "status": 201
    }
}

{
    "scenarioName": "To do list",
    "requiredScenarioState": "Cancel newspaper item added",
    "request": {
        "method": "GET",
        "url": "/todo/items"
    },
    "response": {
        "status": 200,
        "body" : "<items><item>Buy milk</item><item>Cancel newspaper subscription</item></items>"
    }
}
```

Which doesn't work, it's not obvious that you need to do a enclose this with a `mappings` property to make it work:

```
{
  "mappings": [
     { ... },
     { ... },
     { ... }
  ]
}
```
