### ISSUE TITLE
Remotely accessing a WiremockServer from a over-the-wire Wiremock client instance

### ISSUE THREAD

**Issue by hiteshbhojwani** [tomakehurst/wiremock#1289]
Hi,

I am working on spring-boot application which would act as service-virtualization app, to be accessed remotely, containing a WireMock server within it. 

Essentially, this spring boot is deployed as a Jar containing standalone-wiremock-server jar in it as dependency. The whole bunch is deployed in Pivotal Cloud Foundry.

When the spring-boot app bootstraps, it also bootstraps the wiremock server with it. Below is the code which does that,

		public WireMockServer getWireMockServer() {

		return new WireMockServer(new WireMockConfiguration().httpsPort(8085).port(8081).extensions(new ResponseTransformer() {

			@Override
			public Response transform(Request request, Response response, FileSource files, Parameters parameters) {

-
-
- }
}

WiremockServer wiremockServer = getWireMockServer(); // above method
wiremockServer.start();

This way, the wiremock server is started and it is accessible from the same app by using Wiremock client instance,

WireMock.configureFor("https", "localhost", 8085);
stubFor(WireMock.post(...).willReturn(aResponse()));

The response is transformed at the runtime as part of ResponseTransformer().

--------------------------------------------------------------------------------------------------------------

This works fine when the Wiremock Client and Wiremock Server are present in the same application. 

The requirement is, to extract out client from the server, so that both can talk remotely on PCF(Pivotal Cloud Foundry) as two separate Spring boot apps.

Lets call the client which contains Wiremock Instance as 
1. springboot.client.app
and Server that contains standalone wiremock Server as 
2. springboot.server.app

The server app bootstraps first,
When the client app bootstraps and tries to connect the server app as

WireMock.configureFor("https", "springboot.server.app", 8085);
stubFor(WireMock.post(...).willReturn(aResponse()));
			
I receive the below error
Connect to springboot.server.app.abc.pcfdev00.mastercard.int:8085 [springboot.server.app/10.158.139.19] failed: Connection refused (Connection refused)

The question is, same code works fine when both client and server are on the same application via localhost, however it does not work when client is accessing the server remotely.

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.

**Comment by hiteshbhojwani** [comment]
Posted on mailing list.
Need it urgently :( 
Hence replying here to bring it to your notice.
https://groups.google.com/forum/#!topic/wiremock-user/PasKvtl6OTg
