### ISSUE TITLE
Wiremock Standalone contains Vulnerable Handlebars v4.0.4

### ISSUE THREAD

**Issue by Siebes** [tomakehurst/wiremock#1290]
# Issue guidelines

Wiremock Standalone contains Vulnerable Handlebars v4.0.4

This package contains a Prototype Pollution vulnerability according to the following npm advisory https://www.npmjs.com/advisories/1164 

https://github.com/tomakehurst/wiremock/blob/master/build.gradle has a version below 4.3.0 and might need to get bumped. 

## Bug reports

When wiremock-standalone-2.26.3.jar is extracted there is `handlebars-v4.0.4.js` that is packaged in the .jar

## Feature requests

Upgrade handlebars.js to version 4.3.0 or later according to advisory.

**Comment by Siebes** [comment]
Looks like its coming from jknack dependency which hasnt been released since October

see related issue
https://github.com/jknack/handlebars.java/issues/703

**Comment by tomakehurst** [comment]
I suspect the risk of prototype pollution is pretty much theoretical in a server-side Java only context.

**Comment by Siebes** [comment]
yeah theoretical - it got detected by a vulnerability scanner

**Comment by Siebes** [comment]
My PR has been merged in the dependency - just waiting on the 4.1.3 release.

**Comment by tomakehurst** [comment]
Fixed in cd85809195d3fba3283f9e6149a3c3587006d757
