### ISSUE TITLE
verify async methods

### ISSUE THREAD

**Issue by Raydow** [tomakehurst/wiremock#1295]
Hi,
Feature request: Test whether an asynchronous api has been called. If you only use 'verify' it may happen that the api has not yet been called.
Suggestion:

`public static void verifyWithAttempts(int exactly, String url, Method method, int attempt_limit,
            int attempt_delay) {
        verifyWithAttempts(exactly, url, method, 0, attempt_limit, attempt_delay);
    }

    public static void verifyWithAttempts(int exactly, String url, Method method, int attempt, int attempt_limit,
            int attempt_delay) {
        try {
            sleep(attempt_delay);
            switch (method) {
                case GET:
                    verify(exactly(exactly), getRequestedFor(urlEqualTo(url)));
                    break;
                case PUT:
                    verify(exactly(exactly), putRequestedFor(urlEqualTo(url)));
                    break;
                case POST:
                    verify(exactly(exactly), postRequestedFor(urlEqualTo(url)));
                    break;
                case DELETE:
                    verify(exactly(exactly), deleteRequestedFor(urlEqualTo(url)));
                    break;
                case HEAD:
                    verify(exactly(exactly), headRequestedFor(urlEqualTo(url)));
                    break;
                case TRACE:
                    verify(exactly(exactly), traceRequestedFor(urlEqualTo(url)));
                    break;
                case OPTIONS:
                    verify(exactly(exactly), optionsRequestedFor(urlEqualTo(url)));
                    break;
                case PATCH:
                    verify(exactly(exactly), patchRequestedFor(urlEqualTo(url)));
                    break;
            }
        } catch (VerificationException | InterruptedException e) {
            if (attempt < attempt_limit) {
                verifyWithAttempts(exactly, url, method, attempt + 1, attempt_limit, attempt_delay);
            } else {
                fail(e.getMessage());
            }
        }`

Wiremock used: 2.20.0
Is there any way to do this in this version or in more recent versions (without using sleep(1111))?

**Comment by tomakehurst** [comment]
There's nothing built into WireMock at the moment, but I usually use [Awaitility](https://github.com/awaitility/awaitility) when I need to do this.

**Comment by Raydow** [comment]
ok, i will close this issue so, thanks.
