### ISSUE TITLE
Resetting stubs doesn't reload files included by "bodyFileName"

### ISSUE THREAD

**Issue by palmlan** [tomakehurst/wiremock#1296]
I want to trigger a reload of the stubs on the file system without a restart by hitting `POST http://<host>:<port>/__admin/mappings/reset`.

But the file included by "bodyFileName" in the stub defintion has not been reloaded, still remains the old version in memory. I am using the dynamic response templating here, so I have to disable the template cache on mock server startup to enforce recompilation of the included body file template. Maybe a template cache refreshing when stubs are reset is needed.

Example stub configuration:
```
{
        "request": {
                "urlPath": "/myurl",
                "method": "POST"
        },
        "response": {
                "headers": {
                        "Content-Type": "text/xml"
                },
                "bodyFileName": "response.xml",
                "transformers": [
                        "response-template"
                ]
        }
}
```

**Comment by tomakehurst** [comment]
Are you running the latest version of WireMock?

There's already a cache flush after reset in the latest version: https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java#L278 so if you're not using this, then an upgrade should fix the issue.

If you're seeing this in the latest version, please could you post all steps and data for me to reproduce the problem?

**Comment by palmlan** [comment]
yes, version: wiremock-jre8-standalone-2.26.3.jar
Steps:
1. Configure a stub to use template response. eg. mystub.json
```
{
        "request": {
                "urlPath": "/myurl",
                "method": "POST"
        },
        "response": {
                "headers": {
                        "Content-Type": "text/xml"
                },
                "bodyFileName": "mytemplate.xml",
                "transformers": [
                        "response-template"
                ]
        }
}

```

2. Start wiremock server.
3. Post the mystub.json to mock server's admin url.
4. Make requests to the stub url.
5. Modify the template file: mytemplate.xml under wiremock/__files/ 
6. Triger mock serve reset, eg. trigger a reload of the stubs on the file system without a restart by hitting POST http://<host>:<port>/__admin/mappings/reset
7. Make requests to the stub url again. Check the  reponse, not changed to use the new modified template.

**Comment by scaytrase** [comment]
> so I have to disable the template cache on mock server startup to enforce recompilation of the included body file template

We've hit the same problem - POST to rest does not reload template files. Disabling the template cache helped. 

wiremock is 2.27.2 (latest at the moment)

**Comment by tomakehurst** [comment]
@scaytrase can you share the full details of the steps you're taking?

**Comment by scaytrase** [comment]
yeah, sorry for delay. Actually if you have any 
```
                "bodyFileName": "mytemplate.xml",
                "transformers": [
                        "response-template"
                ]
```
we change contents of `mytemplate.xml` and expect POST to reset apply these changes. but we keep getting cached contents.

**Comment by tomakehurst** [comment]
I think this might have actually been related to #1158 which is now fixed in the mainline.

If you wanted to check whether this fixes your issue you could cut a build from HEAD, which you can now do via:

```
./gradlew publishToMavenLocal
```

**Comment by tomakehurst** [comment]
Closing this as I believe it's fixed. I'll re-open if this is still an issue.
