### ISSUE TITLE
Unable to get received requests from standalone Wiremock deployed on a remote host.

### ISSUE THREAD

**Issue by akuiz** [tomakehurst/wiremock#1300]
Hi! I'm sorry if this rather a question than an issue, but I've already posted the same in the mailing list and StackOverflow, but unfortunately didn't get an answer.

- https://stackoverflow.com/questions/61237103/how-to-verify-requests-from-wiremock-deployed-to-a-remote-host-based-on-its-url
- https://groups.google.com/forum/#!topic/wiremock-user/b3HNn-P2vcM

I've implemented a custom Wiremock Server programmatically using Spring Boot and this service is deployed and running on a remote host. The only way to access this Wiremock Server is URL provided by DevOps. Let's say testWiremockHost.com All mappings are working fine and Wiremock responds properly.

But I do have couple of questions:

1) There's no response from the Server when I try GET request on testWiremockHost.com/__admin

2) My goal is to verify requests that were sent to this Wiremock after another service is triggered, so I also need to find a way to properly define instance of this remote Wiremock in my tests in order to track incoming requests. Previously, when I tried to verify the requests from 'localhost' Wiremock server everything was just fine, but unfortunately I can't do the same for the remote one.

The latest code I've tried is the following:

`wiremock = new WireMockBuilder().host("testWiremockHost.com").https().build();`

*send request*

`wiremock.verify(1, postRequestedFor(urlEqualTo("/testEnpoint")))`
Once I try to reset requests or scenarios for the wiremock I get the following error:

`wiremock.resetRequests();`

I receive the same if I try to call verify() method.

`com.github.tomakehurst.wiremock.common.JsonException: {
  "errors" : [ {
    "code" : 10,
    "source" : { },
    "title" : "Error parsing JSON",
    "detail" : "Unrecognized token 'Request': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"\n                                               Request was not matched\n                                               =======================\n\n-----------------------------------------------------------------------------------------------------------------------\n| Closest stub                                             | Request                                                  |\n--------------------------------------------------------------------------------------------------------------------\"[truncated 1076 chars]; line: 2, column: 55]"
  } ]
}
`

Wiremock server is built based on SpringBoot Framework and starts with the following command: java -jar wiremock-1.0-SNAPSHOT.jar. As per the configuration it's set up on 8080 port by default. But I also have a host URL which is working fine when it comes to responses for stub data. Main problem is accessing the remote Wiremock.

Wiremock Server is running on 2.25.1 version. The code that's trying to access the Wiremock Server is using the same version.

Thanks in advance and sorry for the confusion if this is incorrect place to ask questions, but I have no other way to go.

**Comment by akuiz** [comment]
Hi @tomakehurst,
May I expect some help with this?

**Comment by LeonorLunatech** [comment]
Hi @akuiz did you manage the understand where your issue was coming from? 
I'm having a similar error. I have a simple wiremock setup, that works fine, but when I call verify I also get a `com.github.tomakehurst.wiremock.common.JsonException`

**Comment by asifRaeesIqbal** [comment]
ANy update ?
