### ISSUE TITLE
Can't decode Location header in response

### ISSUE THREAD

**Issue by markgargan** [tomakehurst/wiremock#1301]
## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [2.25.1] Which version of WireMock you're using

- [ Using the npm wrapper 
"start:mockv" : "env-cmd -f .env.development.local yarn wiremock --global-response-templating --verbose --root-dir ./mocks --permitted-system-keys=WIREMOCK_.*"] How you're starting and configuring WireMock, including configuration or CLI the command line

- [ 
We're trying to mock out the website https://api.autoaddress.ie. We've a few mappings in place but need wiremock to redirect back to the browser in a catchall fashion in the case that no direct mapping matches. This is because the box where we run wiremock doesn't have access to the outside web so we can't use the proxyBaseUrl to pass the request through. 

{
  "priority": 9,
  "name" : "autoaddress_redirect_to_actual",
  "request" : {
    "urlPattern": "/autocomplete.*",
    "method" : "GET"
  },
  "response": {
    "status": 302,
    "headers" : {
      "Location": "https://api.autoaddress.ie/2.0{{urlEncode request.url decode=true}}"
    }
  }
}

Other attempts to return the decoded Location included
      "Location": "https://api.autoaddress.ie/2.0{{request.url }}"
      "Location": "https://api.autoaddress.ie/2.0{{#urlEncode decode=true}}{{request.url}}{{/urlEncode}}"

In the latter case, the java object name returned from {{ request.url }} appears in the response 

] A failing test case that demonstrates the problem

**Comment by tomakehurst** [comment]
Could you give this a try on the latest WireMock version (2.26.3)?

If it's still a problem, please could you provide a failing test case the demonstrates the issue?

I'm also slightly surprised to see you're attempting to **decode** a string that's intended to be appended onto a URL. Is that really what you're intending to do?

**Comment by markgargan** [comment]
Hey Tom, 

Sure I'll give that a go now. 
what it was was that when the Location was coming back in the response it was urlEncoded so when chrome went to redirect to it it didnt' automatically decode it so the majority of the url was truncated to 
/autocomplete?language&

**Comment by markgargan** [comment]
Hi Tom, 

          I tried the various combinations with 2.26.3 but alas I got the same encoded Locaiton in each case. 

Copying the url https://localhost:8080/autocomplete?language=en&callback=jQuery34109912770621333904_1587574877465&key=248D8C23-E290-F98F-EA24-4566DB0A8F00&limit=-1&address=15%20Swo&geographicAddress=false&vanityMode=true&addressElements=false&addressProfileName=Aviva%20Profile%205Line%202&country=ie&_=1587574877470

should hopefully highlight what I'm seeing

Thanks,
Mark.

**Comment by tomakehurst** [comment]
Can you provide a failing test case?

**Comment by markgargan** [comment]
Sure Tom here you go! This mapping will catch all requests coming into wiremock and redirect it back to the browser. 

{
"priority": 9,
"name" : "autoaddress_redirect_to_actual",
"request" : {
"urlPattern": "/autocomplete.*",
"method" : "GET"
},
"response": {
"status": 302,
"headers" : {
"Location": "https://api.autoaddress.ie/2.0{{urlEncode request.url decode=true}}"
}
}
}

With wiremock running on port 8080 over HTTPS and this mapping in your mappings folder if you put the url  

https://localhost:8080/autocomplete?language=en&callback=jQuery34109912770621333904_1587574877465&key=248D8C23-E290-F98F-EA24-4566DB0A8F00&limit=-1&address=15%20Swo&geographicAddress=false&vanityMode=true&addressElements=false&addressProfileName=Aviva%20Profile%205Line%202&country=ie&_=1587574877470

and in the chrome developer tools network you'll see the url gets a 307 response.
The location in the response headers starts with 
https://api.autoaddress.ie/2.0/autocomplete?language&#x3D;en&amp;c
and because there's a hash at the end of 'language&' due to the encoding, chrome appears to truncate the redirected request to 

https://api.autoaddress.ie/2.0/autocomplete?language&

Thanks,
Mark,

**Comment by markgargan** [comment]
Just incase, if I hard code a response to the actual service in the location in the mapping, it comes back and redirects fine.

**Comment by tomakehurst** [comment]
Ah, I see what the problem is: Handlebars escapes the URL when you use double braces `{{ }}`. If you use triple braces `{{{ }}}` that'll fix it.

**Comment by markgargan** [comment]
Ah Tom! Sure you're only a legend mate! It was that simple all along? Is that something that handlebars itself introduces that it encodes everything within two curly braces but not in three? 

Thanks very much for all your help!
Mark.

For reference for anyone else stuck behind a corporate proxy the redirect back to the browser for a GET only differs from that for the POST in the status returned i.e. 302 vs 307. Also if your running wiremock over http and redirecting back to an https url chrome will not proceed with the request because of the difference in protocols. 
"response": {
    "status": 302,
    "headers" : {
      "Location": "https://api.autoaddress.ie/2.0{{{ request.url }}}"
    }
  }
and for a POST is 
"response": {
    "status": 307,
    "headers" : {
      "Location": "https://samdev.iehibdom.com{{{ request.url }}}"
    }
  }
