### ISSUE TITLE
Taking snapshot of requests is not working

### ISSUE THREAD

**Issue by palmlan** [tomakehurst/wiremock#1302]
## Bug reports

- version of WireMock: wiremock-jre8-standalone-2.26.3.jar
- WireMock startup command line: `java -jar opt/wiremock-jre8-standalone-2.26.3.jar --root-dir=$HOME/etc/wiremock --port 13334 --local-response-templating  --verbose`
- A failing test case that demonstrates the problem: 
1. make some requests to the mock server.
```
$ curl -X POST localhost:13334/__admin/requests/count -d @-
{ "method": "POST"}
[hit Ctrl+D]
{
  "count" : 1,
  "requestJournalDisabled" : false
}
```
2. take snapshot
```
$ curl -X POST http://localhost:13334/__admin/recordings/snapshot -d @-
{}
[hit Ctrl+D]
output:
{
  "mappings" : [ ]
}
```

**Comment by tomakehurst** [comment]
Snapshot record by default will only capture stubs that originated from a proxy response. Is this the case for the request you made?

**Comment by palmlan** [comment]
> 
> 
> Snapshot record by default will only capture stubs that originated from a proxy response. Is this the case for the request you made?

No, but according to the [doc ](http://wiremock.org/docs/record-playback/), which says: 

> 

    note

    You can still take snapshots without a proxy stub configured. You might want to do this e.g. if you want to capture requests made by your application under test that you can then modify by hand to provide the appropriate responses.

**Comment by tomakehurst** [comment]
OK, seems like no problem then.
