### ISSUE TITLE
Restricting the number of incoming requests to wiremock server

### ISSUE THREAD

**Issue by NandiniAradhya** [tomakehurst/wiremock#1304]
Throttling issue

How can we restrict the number of concurrent incoming requests to wiremock server? I tried using .containerThreads() but this doesn't seem to work. Is there any other possible way to implement this so the server doesn't break when there are too many requests triggered at the same time. Is there any method provided by wiremock to solve this? Also what is the maximum number of concurrent requests wiremock can handle?

WireMockServer wireMockServer = new WireMockServer(options().port(8087));

I am trying to implement throttling in the above line of code.

**Comment by anujbhatia** [comment]
I think while .containerThreads() limits the size of the tread pool of the embedded Jetty server used by WireMock the server can still continue to accept HTTP connections but they are queued. You would probably want to limit the size of the queue. Apart form that there may be OS level settings related to TCP/IP that may need to be tweaked to prevent the OS form accepting TCP connections and queuing them.

If you don't want to mess around with TCP/IP settings of the OS and are looking to throttle the max requests per second that Jety should process then you might want to take a look at the DOS Servlet Filter - https://www.eclipse.org/jetty/javadoc/9.4.20.v20190813/org/eclipse/jetty/servlets/DoSFilter.html

However I am not sure how to configure a custom servlet filter on the embedded Jetty server when initializing WireMock.

**Comment by tomakehurst** [comment]
Closing this due to age and inactivity.
