### ISSUE TITLE
Very large static files yield very low performance

### ISSUE THREAD

**Issue by MalikKillian** [tomakehurst/wiremock#1306]
I am attempting to virtualize a service that normally returns very large payloads (in excess of 30 MB).  The original server can return this data in under 3 seconds on average (also a Java service) but WireMock will take over 25 seconds. I understand this may not be a typical use-case for the tool but considering some of the horrible alternatives out there I'd much rather stick to using this.

If I am following the code correctly this line here would cause the entire file to be read into memory before it would ultimately be sent over the wire in chunks: https://github.com/tomakehurst/wiremock/blob/cc49a1848e262cdbc328020715a0d815c37d4393/src/main/java/com/github/tomakehurst/wiremock/standalone/RemoteMappingsLoader.java#L67

**Comment by tomakehurst** [comment]
Can you provide a bit more detail about your setup? It would help to know:

* Are you using the latest WireMock version?
* How are you running it (CLI parameters + environment)?
* Have you disabled chunked encoding?
* Your stub mapping JSON

BTW, the code above is just for publishing to a remote WireMock instance so it shouldn't get executed in the normal run of serving responses. This is where body files actually get sent in the response: https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHandlerDispatchingServlet.java#L223
