### ISSUE TITLE
Parsing request body as json and accessing values

### ISSUE THREAD

**Issue by Dheeman1999** [tomakehurst/wiremock#1308]
I could not find a way of parsing request json in the documentation(I found a way to parse url parameters though). What I am looking for is a way to access a particular field in the request after parsing it as json and then passing it as response. For example, if request is something like this
`
{
name:"xyz",
place:"qrs"
}
`
The response will be something like this:
`{name:"xyz"}`

Is there a way to do this?

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README
