### ISSUE TITLE
Response Templating: request.headers.<key> is case sensitive

### ISSUE THREAD

**Issue by tkrieger** [tomakehurst/wiremock#1313]
## Problem Description
The Response Templating request model expressions `request.headers.<key>` and `request.headers.[<key>]` are not case insensitive for header keys. E.g.:
- `{{request.headers.X-CorrelationID}}` could not replaced if only a header with the key `x-correlationid` is present.

Request matching is working perfectly case insensitive instead.

## Impact
We have to use WireMock behind a Node.JS proxy in our automated test setup. The Node.JS proxy converts all HTTP headers keys to lowercase. 
(Which is completely okay due RFC 2616 https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2). 
Which means that or response templating based on header values is not working in this setup. 
We can not simply use lowercase in the mapping definition because this would break the local development setup.
Unfortunately this bug stops us from fully automate all our tests right now.

As work around I tried to add a request filter which corrects the case for required headers. However this is not working because here it seems that a case insensitive check is done and the replacement of the key itself is not executed for any reason.
## WireMock Setup
WireMock Version: `2.26.3`
WireMock Standalone Command: `java -jar wiremock-standalone-jre8.jar  --verbose --global-response-templating`

### Sample Mapping and Request
Sample mapping using X-CorrelationID and tries to access request.headers.<key> with different cases.
```
{
  "id": "733ee0bd-7cbb-4483-8179-213dabc6d4c5",
  "name": "case-sensitive-headers",
  "request": {
    "url": "/test",
    "method": "GET",
    "headers": {
      "x-correlationid": {
        "equalTo": "test-id"
      }
    }
  },
  "response": {
    "status": 200,
    "body": "{\"X-CorrelationID\": \"{{request.headers.X-CorrelationID}}\", \"x-correlationid\": \"{{request.headers.x-correlationid}}\"}"
  },
  "uuid": "733ee0bd-7cbb-4483-8179-213dabc6d4c5",
  "persistent": true,
  "insertionIndex": 15
}
```
Request used to test:
```
curl --location --request GET 'http://localhost:8080/test' --header 'X-CorrelationID: test-id'
```
Received response:
```
{"X-CorrelationID": "test-id", "x-correlationid": ""}
```
Expected behavior: both attributes should contain `test-id`.
### JUnit Test to reproduce the issue
I added following JUnit test to reproduce the issue into the _ResponseTemplateTransformerTest.java_:
```
@Test
 public void requestHeadersCaseInsensitive() {
        ResponseDefinition transformedResponseDef = transform(mockRequest()
                        .url("/things")
                        .header("X-Request-Id", "req-id-1234")
                        .header("Case-KEY-123", "foundit"),
                aResponse().withBody(
                        "Request ID: {{request.headers.X-Request-Id}}, Case key header: {{request.headers.[case-key-123]}}"
                )
        );

        assertThat(transformedResponseDef.getBody(), CoreMatchers.is(
                "Request ID: req-id-1234, Case key header: foundit"
        ));
}
```

### Potential Solution 
I tried to solve the problem. My first attempt was to use the `CaseSensitiveKey` object as key of the `adaptedHeaders` map constructed in _ResponseTemplateModel.java:45_. This broke the whole header functionality in response templating due to the fact that the used handelbars library seems to require strings as key.
Second attempt was to replace the `adaptedHeaders` map with a `TreeMap` with `String.CASE_INSENSITIVE_ORDER` strategy. 
**This worked out, the test above ran green.**

_Sample code:_
```
TreeMap<String, ListOrSingle<String>> adaptedHeaders = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
adaptedHeaders.putAll(Maps.toMap(request.getAllHeaderKeys(), new Function<String, ListOrSingle<String>>() {

      @Override
       public ListOrSingle<String> apply(String input) {
                return ListOrSingle.of(request.header(input)
                                              .values());
       }
}));
```
But to be honest I'm not sure about potential side effects. In addition the project seems to use the google collections heavily. I don't now whether there is some convenience functionality to do the same in there also.
However it this would be an acceptable solution I can also create a PR for that.

**Comment by tomakehurst** [comment]
Thanks for reporting this. I agree templates should be case-insensitive WRT headers.

I'd be happy to receive a PR for this. I think your solution looks good.

**Comment by tkrieger** [comment]
Thanks for your quick reply. 
Sure I created https://github.com/tomakehurst/wiremock/pull/1314
