### ISSUE TITLE
Array of objects is compared incorrectly by EqualToJsonPattern

### ISSUE THREAD

**Issue by naushniki** [tomakehurst/wiremock#1326]
Steps to reproduce:
Try to compare these two JSONs using EqualToJsonPattern, setting both ignoreArrayOrder and ignoreExtraElements to true.
Expected:
```
{
    "a": [
        {
            "b": 3
        }
    ]
}
```
Actual
```
{
    "a": [
        {
            "b": 0,
            "c": 1
        },
        {
            "b": 3,
            "c": 1
        }
    ]
}
```

**Result:** isExactMatch() returns **false**.
**Expected result:** isExactMatch() returns **true**.

This can be reproduced by adding the following method to the file [EqualToJsonTest.java](https://github.com/tomakehurst/wiremock/blob/master/src/test/java/com/github/tomakehurst/wiremock/matching/EqualToJsonTest.java)
```
    @Test
    public void similarObjetcsInAnArray() {
        assumeJava8OrHigher();

        String expected = "{\n" +
                "    \"a\": [\n" +
                "        {\n" +
                "            \"b\": 3\n" +
                "        }\n" +
                "    ]\n" +
                "}";

        String actual = "{\n" +
                "    \"a\": [\n" +
                "        {\n" +
                "            \"b\": 0,\n" +
                "            \"c\": 1\n" +
                "        },\n" +
                "        {\n" +
                "            \"b\": 3,\n" +
                "            \"c\": 1\n" +
                "        }\n" +
                "    ]\n" +
                "}";

        MatchResult match = new EqualToJsonPattern(expected, true, true).match(actual);
        assertThat(match.isExactMatch(), is(true));
    }
```

**Comment by naushniki** [comment]
This is the diff object that is produced by zjsonpatch. As you can see there is a replace op in it, which is causing the issue. The same difference must be described as 2 add operations. I'm not sure whether this must be fixed in zjsonpatch or wiremock.
```
[
    {
        "op": "replace",
        "path": "/a/0/b",
        "value": 0
    },
    {
        "op": "add",
        "path": "/a/0/c",
        "value": 1
    },
    {
        "op": "add",
        "path": "/a/1",
        "value": {
            "b": 3,
            "c": 1
        }
    }
]
```

**Comment by tomakehurst** [comment]
Are you using the jre8 JAR?

**Comment by naushniki** [comment]
@tomakehurst Yes.

**Comment by tomakehurst** [comment]
Are you sure? zjsonpatch isn't used in the jre8 JSON equality matcher.

**Comment by tomakehurst** [comment]
When I run your test case in the JRE8 suite it passes. I only see it fail in JRE7, which is expected as it's still (and will forever be) dependent on zjsonpatch.

**Comment by naushniki** [comment]
@tomakehurst I checked once again and you are right! The issue doesn't occur on the java8 version. Thanks for your quick response! I guess this issue can be closed now, unless you wish to fix it for java 7.

**Comment by tomakehurst** [comment]
The Java7 version is going EOL soon, and it wouldn't be a simple fix as the library used for JSON equality in the jre8 version is Java 8+.
