### ISSUE TITLE
Allow to read query arrays passed like /path/to/endpoint?ids[]=1&ids[]=2

### ISSUE THREAD

**Issue by bashmish** [tomakehurst/wiremock#1344]
By default in Angular the HttpClient sends arrays of parameters (e.g. `ids=[1, 2]`) in the following format:

`/path/to/endpoint?ids[]=1&ids[]=2`

I tried different approaches to read them all using the `"response-template"` transformer, but none of them worked.
I also saw this https://github.com/tomakehurst/wiremock/issues/760, but it does not solve my case.

## Actual

URL: `/path/to/endpoint?ids[]=1&ids[]=2`
`{{request.query.ids.0}} {{request.query.ids.1}}` breaks
`{{request.query.ids[].0}} {{request.query.ids[].1}}` breaks
`{{lookup request.query 'ids[]}}` works, but allows to read only the first value
`regexExtract` could be an alternative, but does not work because of https://github.com/tomakehurst/wiremock/issues/1343

## Expected

URL: `/path/to/endpoint?ids[]=1`
`{{request.query.ids}}` contains array [1]
`{{request.query.ids.0}}` contains 1

URL: `/path/to/endpoint?ids[]=1&ids[]=2`
`{{request.query.ids}}` contains array [1, 2]
`{{request.query.ids.0}}` contains 1
`{{request.query.ids.1}}` contains 2

Not sure about how `lookup` should work, because it's API does not seem to be the perfect match for arrays.

**Comment by RibsaS** [comment]
any news on this ?

**Comment by tomakehurst** [comment]
I'm going to update the docs to show how to do this, but in the meantime here's how you use `lookup` to get around Handlebars' limitation on square brackets in key names:

```
{{lookup request.query 'ids[].0'}}
```
