### ISSUE TITLE
parallel execution of tests problem, only run the last call stubs

### ISSUE THREAD

**Issue by Apolayo27** [tomakehurst/wiremock#1351]
My project execution perfect no parallel tests but when I try the Parallel test, Wiremock only run the last config stubs and should run separately.

My project config in FrontEnd in port static: serverUrl: 'http://127.0.0.1:5502/v5', for this wiremock point to port 5502, I can't enable dynamicport.

    public WireMockServer wireMockServer = new WireMockServer(wireMockConfig().port(5502).extensions(new ResponseTemplateTransformer(true)));

I need run parallel test with wiremock in the same port but in different instances, I try use ThreadLocal does not separate instances of Wiremock.

The problem is "withTransformerParameter"

        wireMockServer.wireMockServer.stubFor(post(urlEqualTo("/v1/x/apiname"))
                    .withHeader("Authorization", containing(client))
                    .willReturn(aResponse()
                            .withStatus(200)
                            .withHeader("Content-Type", "application/json")
                            .withHeader("Access-Control-Allow-Origin", "*")
                            .withBody("{\n" +
                                    "    \"accessToken\": \"tokenX\",\n" +
                                    "    \"clientNumber\": 12345,\n" +
                                    "    \"channel\": \"{{parameters.channel}}\"\n" +
                                    "}")
                            .withTransformerParameter("channel",  wireMockConfigs.stubsChannel())
                            .withTransformers("response-template")));

@tomakehurst could you help me

**Comment by tomakehurst** [comment]
Please repost on the mailing list if still an issue
