### ISSUE TITLE
Wiremock not responding for duplicates queryParameters

### ISSUE THREAD

**Issue by MOU-HA** [tomakehurst/wiremock#1357]
Wiremock not responding for duplicates queryParameters:
http://localhost:9090/rdm/variables/variables?ids=2210&ids=44&ids=2271&dateValidite=9999-12-31

**Comment by dplavcic** [comment]
Please check this issue: https://github.com/tomakehurst/wiremock/issues/398

And than 'request matching' docs: http://wiremock.org/docs/request-matching/, 'URL matching' section.

I think you can use exact URL matching to get this 'mocked/called' as expected:
```
{
    "request": {
        "method": "GET",
        "url": "/rdm/variables/variables?ids=2210&ids=44&ids=2271&dateValidite=9999-12-31"
    },
    "response": {
        "status": 200,
        "statusMessage": "Everything was just fine!"
    }
}
```

**Comment by zhouyang68** [comment]
Facing same issue, where the order of duplicate query parameter may be changing. So the exact url match is not working as expected.

**Comment by tomakehurst** [comment]
This is quite old now, and not really enough info to replicate. Please post a question with details on replicating to the mailing list if still a problem.
