### ISSUE TITLE
JRE 11 version

### ISSUE THREAD

**Issue by samdnz** [tomakehurst/wiremock#1360]
A JRE 11 targeting version would be great, JRE 8 is rather old now an upgrade path is becoming a requirement for use of older libraries

**Comment by joschi** [comment]
@samdnz WireMock currently works with Java 11 (and 14, for that matter) without problems.

What exactly would you change for a "JRE 11 version"?

**Comment by va1m** [comment]
I think, the artifactId should be changed from _wiremock-jre8_ to just _wiremock_ because the current name is confusing devs who want use wiremock and who use J11 in their projects.

**Comment by tomakehurst** [comment]
That will happen from v3.0 onwards. Keeping the jre8 designation for 2.x to avoid pushing breaking changes within a major version.
