### ISSUE TITLE
Issue in the maven build with Junit having WireMock setup

### ISSUE THREAD

**Issue by nehasonisap** [tomakehurst/wiremock#1362]
Hi,

I am using WireMock to stub a post call. This call is internally called from another post call for which I am writing the junit. 

```
@Test
    @WithMockUser( username = "download_user" )
    public void testDownloadActionSuccessWithoutThreadContextExecutor()
        throws Exception
    {
        mockMvc
            .perform(
                (post(CURRENCY_EXCHANGE_RATE_SERVICE_URL + MRM_DOWNLOAD_ACTION))
                    .contentType(MediaType.APPLICATION_JSON)
                    .content(
                        new JSONObject()
                            .put(FetchRatesFromMRMContext.FROM_DATE, "0000-00-00")
                            .put(FetchRatesFromMRMContext.FROM_TIME, "00:00:00")
                            .put(FetchRatesFromMRMContext.TO_DATE, "0000-00-00")
                            .put(FetchRatesFromMRMContext.TO_TIME, "00:00:00")
                            .toString()))
            .andExpect(status().isNoContent());
    }
```

The stubs for the oAuth token and second post call is added as :- 

```
final Map<String, String> oauth2Response =
            ImmutableMap
                .<String, String> builder()
                .put("access_token", TEST_OAUTH_TOKEN)
                .put("token_type", "Bearer")
                .put("expires_in", "1500")
                .build();

        stubFor(
            get("/oauth2/token")
                .withQueryParam("grant_type", equalTo("client_credentials"))
                .withBasicAuth(TEST_CLIENT_ID, TEST_CLIENT_SECRET)
                .willReturn(okForJson(oauth2Response)));

        stubFor(
            **_post(urlMatching("/downloadMarketData?logicalSystemName=SCP-CF"))_**
                .withHeader("Content-Type", equalTo("application/json"))
                .withHeader("Authorization", equalTo("Bearer " + TEST_OAUTH_TOKEN))
                .willReturn(
                    aResponse().withStatus(200).withHeader("content-type", "application/json")));
```

This is the mocking for the second post call in the form of a destination:-

```
Destination mrmDestinationHttp =
            mockUtil.mockDestination(
                DESTINATION_NAME,
                URI.create(wireMockServer.baseUrl()),
                AuthenticationType.OAUTH2_SAML_BEARER_ASSERTION,
                credentials,
                null, // proxy type
                null, // proxy configuration
                Collections.singletonList(new Header(HttpHeaders.AUTHORIZATION, "Bearer " + credentials.getToken())),
                null, // trust store
                null, // trust store password
                null, // is trusting all certificates
                null, // key store
                null, // key store password
                null // properties by name
            );
        destinationMocker.addNamedDestination(mrmDestinationHttp);
```

The above destination 'mrmDestinationHttp' is called when we call the post method 'CURRENCY_EXCHANGE_RATE_SERVICE_URL + MRM_DOWNLOAD_ACTION'.

The test itself passes with all the setup but there is an issue in running the mvn clean install with below error :- 

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/i077870/git/sdk-1/integration/integration-object-currency-conversion-simple/srv/src/test/java/com/sap/cloud/sdk/integration/currencyconversion/integrationmodel/extension/MRMExchangeRateActionExtensionTest.java:[105,13] no suitable method found for post(com.github.tomakehurst.wiremock.matching.UrlPattern)
    method org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(java.net.URI) is not applicable
      (argument mismatch; com.github.tomakehurst.wiremock.matching.UrlPattern cannot be converted to java.net.URI)
    method org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(java.lang.String,java.lang.Object...) is not applicable
      (argument mismatch; com.github.tomakehurst.wiremock.matching.UrlPattern cannot be converted to java.lang.String)

- [2.26.3] Which version of WireMock you're using
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
@Rule
    public final WireMockRule wireMockServer = new WireMockRule(wireMockConfig().dynamicPort());
- [NA] A failing test case that demonstrates the problem
- [NA] Profiler data if the issue is performance related   

It is showing the line number where I am adding the URL for the expected post call 'post(urlMatching("/downloadMarketData?logicalSystemName=SCP-CF"))'. I am not sure how to fix it. Also, it is strange that it passes as junit and then shows compilation error when build is triggered.

Thanks,
Neha

**Comment by nehasonisap** [comment]
It looks like something where there is conflict between the post imports. The post which I have to mock has to be from WireMock and the one which I have to call in junit is coming from MockMvcRequestBuilders. But I just want to mock one post call and leave the other post call as it is.

**Comment by nehasonisap** [comment]
This issue was fixed with specific imports and changing a setting for credential in pom, root pom had some additional settings.

**Comment by Vesimeu** [comment]
Bro, but it was impossible to say what changes needed to be made to the imports and settings in pom.xml ?
