### ISSUE TITLE
unable to use https with jre8-2.27.1  (ok with non-jre8 version)

### ISSUE THREAD

**Issue by javathought** [tomakehurst/wiremock#1366]
## Bug reports

- version jre8-2.27.1, but not with version non-jre8  2.27.1 ()
- commande line :
`java -jar wiremock-jre8-standalone-2.27.1.jar --https-keystore keystoreServer.jks --https-port 9999 --verbose` 

No problem with the exact same line with non jre8 : 
`java -jar wiremock-standalone-2.27.1.jar --https-keystore keystoreServer.jks --https-port 9999 --verbose` 

I have the following error on the client :
`javax.net.ssl|ERROR|01|main|2020-08-19 10:11:05.644 CEST|TransportContext.java:318|Fatal (HANDSHAKE_FAILURE): Couldn't kickstart handshaking (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake `

no trace on wiremock , even with options ` -Djavax.net.debug=all -Djavax.net.debug=ssl:handshake:verbose` 

So I can't use it in my unit tests (not standalone version), as I need jre8 version.

**Comment by tomakehurst** [comment]
I suspect this is an issue with your keystore.

Does it work OK if you use the default one (removing the `--https-keystore`) param?

**Comment by javathought** [comment]
Done after config of my client to trust your certificate and bypass hostname verifier :
it works with the embedded keyStore.

It's still strange : 
- my keystore works with wiremock-standalone-2.27.1.jar
- I made a keystore the same way for the client cert and works perfectly with my client

For the moment no clue why my keystore does not work only with wiremock-jre8-standalone

**Comment by tomakehurst** [comment]
Did you create the keystore with an older Java version?

**Comment by javathought** [comment]
It can be that and I thought of it, no time to test yesterday. I have to check it today.

**Comment by javathought** [comment]
Still not working. Something better : mappings on http are OK now, but same error for request on https.
Before, even mappings on http were KO if I remember correctly.

I'll have less time until end of month to test further.

**Comment by luhuangAccedo** [comment]
I can reproduce this issue 
```
java -jar wiremock-jre8-standalone-2.27.2.jar --https-port 8089 —-https-keystore <my path to>ca-cert.jks  --bind-address 0.0.0.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 /$$      /$$ /$$                     /$$      /$$                     /$$      
| $$  /$ | $$|__/                    | $$$    /$$$                    | $$      
| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/ 
| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$ 
| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/

port:                         8080
https-port:                   8089
https-keystore:               jar:file:~/Documents/Mock/wiremock-jre8-standalone-2.27.2.jar!/keystore
enable-browser-proxying:      false
disable-banner:               false
no-request-journal:           false
verbose:                      false
```

Though I specified the https-keystore, it's still pointing to the default one
