### ISSUE TITLE
Facing issue when verify the request with query parameters,  if the query parameter KEY is encoded. 

### ISSUE THREAD

**Issue by kothja** [tomakehurst/wiremock#1368]
**I am using wiremock version: 2.26.3**

I have the URL if following format

http://localhost:8080/test?filter[id]=1

The URL is encoded as: http://localhost:8080/test?filter%5Bid%5D=1

When I try to stub the request

givenThat(get(urlPathEqualTo(GET_URL))
            .withQueryParam(**"filter[id]"**, equalTo("1"))

It fails with   -> **Request was not matched**

But if stub as:
givenThat(get(urlPathEqualTo(GET_URL))
        .withQueryParam(**URLEncoder.encode(("filter[id]", "UTF-8")**, equalTo("1"))

It matches the request successfully.

**Comment by vsouz4** [comment]
FYI we had many tests using %5B and %5D (it was ugly ik but that's how it was working) so bumping minor version for a breaking change like that wasn't the best idea perhaps :( took me some hours to figure this out, like why the heck our pipelines started failing out of the blue :D
