### ISSUE TITLE
Test cases result in Connection reset during mvn verify

### ISSUE THREAD

**Issue by juancdelgado** [tomakehurst/wiremock#1369]
I got a suite of test cases utilizing wiremock for testing mocked endpoints. When I run the test classes individually they run just fine and all pass, however when I run them through a `mvn clean verify` and goes through the `maven-surefire-plugin` and `maven-failsafe-plugin`, out of my 150+ test cases 3-4 will fail with a connection timeout. I'll have a stub created in the test method and when it finally makes a call, I'll get a timeout, like it couldn't reach the wiremock server.

- Spring Boot 2.3.3 using Hoxton.SR7, which using spring-cloud-contract-wiremock-2.2.4.RELEASE
-  Autoconfigure a wiremock port in the test class
- Failing test case example:
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = Application.class)
@AutoConfigureWireMock(port = 0)
@ActiveProfiles("test")
public class ServiceIT {
  @Autowired
  private TestRestTemplate testRestTemplate;

  @BeforeEach
  public void resetAllRequests() {
    //used to clear out previous wiremock instances
    WireMock.resetAllRequests();
  }

  @Test
  public void testRestCall() {
    stubFor(post(urlEqualTo("/services/test")).willReturn(
        aResponse()
            .withBody(
                response())
            .withHeader("Content-Type", "text/xml")
    ));
<--Removed sensitive code -->
    HttpEntity<Object> request = new HttpEntity<>(request, headers);
    ResponseEntity<Void> responseEntity = testRestTemplate.postForEntity("/services/test", request, Void.class);
    assertEquals((HttpStatus.OK), responseEntity.getStatusCode());
    verify(1, postRequestedFor(urlEqualTo("/services/test"")));
  }
```
During a mvn clean verify:
```
[ERROR] Tests run: `, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.192 s <<< FAILURE! - in com.test.ServiceIT
[ERROR] testRestCall  Time elapsed: 0.788 s  <<< ERROR!
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:52582/services/test": Connection reset; nested exception is java.net.SocketException: Connection reset
        at in com.test.ServiceIT.testRestCall.java:98)
Caused by: java.net.SocketException: Connection reset at com.test.ServiceIT.testRestCall.java:98)
```

**Comment by juancdelgado** [comment]
After doing some more digging, it looks like I have a system process in the background that took up a bunch of the ports that wiremock uses. is there a way to "retry" or look for a new port if one is already in use?

**Comment by juancdelgado** [comment]
Although I found issues with the ports being used, there are also instance as well that whenever I see if the failed port is already in use, it's not used by any other process. so i'm back at square one. I think there is a bug in wiremock that the server might not start up on time before the test cases are ran

**Comment by tomakehurst** [comment]
I think it's quite unlikely that WireMock is not starting in time. If that were the case you'd be seeing connection refused errors rather than reset.

Are you using the default underlying HTTP client i.e. `HTTPURLConnection` in Spring? If so, this has been known to exhibit buggy connection pooling behaviour when running tests across randomised ports. I'd suggest switching to a better client ideally, or failing that, completely disabling connection reuse.
