### ISSUE TITLE
Upgrade to modern Jetty

### ISSUE THREAD

**Issue by slandelle** [tomakehurst/wiremock#137]
Hi there,

Any reason why Wiremock is stucked to Jetty 6?
Getting stucked on such an old version makes me concerned...

Regards,

Stéphane

**Comment by guspower** [comment]
Jetty mailing list question - http://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02250.html

**Comment by handstandsam** [comment]
**The [2.0-beta branch] (https://github.com/tomakehurst/wiremock/blob/2.0-beta) supports Jetty 9 now.** 
```
compile "com.github.tomakehurst:wiremock:2.0.8-beta"
```
This issue can be marked as resolved.
