### ISSUE TITLE
Bug: Library source does not match the bytecode for class WireMockRule

### ISSUE THREAD

**Issue by PetrYako** [tomakehurst/wiremock#1370]
Version: 2.25.0
Issue in first answer https://stackoverflow.com/questions/36753524/library-source-does-not-match-the-bytecode-for-class

**Comment by tomakehurst** [comment]
Is this also the case for 2.27.1 (the latest)?

**Comment by PetrYako** [comment]
![image](https://user-images.githubusercontent.com/44511145/91844125-8ffd1e80-ec5f-11ea-91a2-c01dd77917c4.png)
yep

**Comment by tomakehurst** [comment]
That's not what I'm seeing. Please can you share your setup details so I can attempt to replicate?

**Comment by PetrYako** [comment]
Lombok plugin for idea 0.30EAP
Lombok version in pom: 1.18.10 (<scope>provided</scope>)
Wiremock version in pom: 2.27.1 (<scope>compile</scope>)

**Comment by tomakehurst** [comment]
<img width="1221" alt="Screen Shot 2020-09-01 at 14 37 27" src="https://user-images.githubusercontent.com/707169/91858145-b3749900-ec60-11ea-8818-3da3de7ec1c4.png">

Works fine for me (with both the jre8 and jre7 JARs), so I'm closing as a non-bug.

I suggest you take a look at whether your Maven/Gradle caches have become corrupted and the effect of the Lombok plugin. I've had trouble with this in the past and have had to disable it.
