### ISSUE TITLE
Division by zero in com.github.tomakehurst.wiremock.matching.EqualToJsonPattern

### ISSUE THREAD

**Issue by javahelp** [tomakehurst/wiremock#1372]
Wiremock 2.19.0
Using wiremock in JUnit tests

```
  "request" : {
    "url" : "/url/under/test",
    "method" : "POST",
    "bodyPatterns" : [ {
      "equalToJson" : "{}",
      "ignoreArrayOrder" : true,
      "ignoreExtraElements" : true
    } ]
  },
```

The request body is an empty Json object.
This creates division by zero in this code:

```
                    double maxNodes = maxDeepSize(expected, actual);
                    return diffSize(diff) / maxNodes;
```

Both `maxNodes` and `diffSize(diff)` resolve to zero, creating `NaN` which bubbles up as "Unmatched Request".

Yes, the workaround is to set
```
      "ignoreArrayOrder" : false,
      "ignoreExtraElements" : false
```

But the error message was so far off, that it took an entire afternoon to trace through debugging what really happened.

**Comment by tomakehurst** [comment]
That's an ancient version you're using. Suggest you upgrade to the 2.27.1 (JRE8 build as this has better JSON matching).

**Comment by javahelp** [comment]
I think there is the same bug here, at line 118
https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/matching/EqualToJsonPattern.java

**Comment by tomakehurst** [comment]
That's the JRE7 impl, which is going away soon. I suggest you switch to the JRE8 version if you're able to.
