### ISSUE TITLE
Wiremock response templating is not working as expected

### ISSUE THREAD

**Issue by explorer-fullstack** [tomakehurst/wiremock#1373]
I'm inserting stubs into the already running remote wiremock server as below as explained under the `JSON` section in [this](http://wiremock.org/docs/response-templating/) document

POST request onto: https://mywiremock.mycompanydomain.com/__admin/mappings
Payload:
{
  "request": {
    "method": "GET",
    "url": "/some/thing"
  },
  "response": {
    "body": "{{request.host}}",
    "headers": {
      "Content-Type": "text/plain"
    },
    "status": 200,
    **"transformers": [
      "response-template"
    ]**
  }
}

Stub has been inserted successfully.

**ISSUE**
When I hit the wiremock **https://mywiremock.mycompanydomain.com/some/thing** , i received the following response:
**{{request.host}}**

I expect that it needs to return the host variable of the request url instead of **{{request.host}}**

Please let me know why the response templating is not working as expected and described in your documentation.

As per your docs:
```
**Otherwise the transformer will need to be specified on each stub mapping by its name response-template:**


JSON
{
    "request": {
        "urlPath": "/templated"
    },
    "response": {
        "body": "{{request.path.[0]}}",
        **"transformers": ["response-template"]**
    }
}

```

- Which version of WireMock you're using -- **2.25.1**
- How you're starting and configuring WireMock, including configuration or CLI the command line
  **Packaging stubs and wiremock 2.25.1 into a JAR file and pushing that JAR**
- A failing test case that demonstrates the problem  
**Explained at the top**
- Profiler data if the issue is performance related

**Comment by tomakehurst** [comment]
Looks like you haven't enabled response templating on startup.

Please post further questions to the mailing list.

**Comment by explorer-fullstack** [comment]
@tomakehurst Thank for looking into the issue. **My scenario is:** _Im trying to enable the response templating on a wiremock remote instance which was already running and which was not started up with response templating enabled_. **Is this something that is possible to achieve? if so, pls let me know what needs to be done.**

Note:
I tried doing this on the given remote wiremock server which is already running but it didn't work. I just got the response as {{request.host}} instead of the actual value for request.host


```
configureFor("https", "mywiremock.mycompanydomain.com", 0);

WireMockServer wm = new WireMockServer(WireMockConfiguration.options().extensions(new ResponseTemplateTransformer(true)));

stubFor(
        get(urlMatching(“/abcd”))
                .withHeader("Content-Type", matching("application/json; charset=UTF-8"))
                .willReturn(
                        aResponse()
                                .withBody("{{request.host}}")));
```
