### ISSUE TITLE
WireMock does not match request headers properly for URL paths with a file extension

### ISSUE THREAD

**Issue by npmeyer** [tomakehurst/wiremock#1377]
I wrote a test that should have failed, but passed instead:

```
    // This test passes, but it should fail because the If-Modified-Since header is not provided.
    @Test
    public void testMatchHeader_PathWithExtension() throws URISyntaxException, IOException, InterruptedException {
        wireMock.stubFor(
                get(urlPathEqualTo("/test.txt"))
                        .withHeader("If-Modified-Since", equalTo("Mon, 07 Sep 2020 20:55:12 GMT"))
                        .willReturn(aResponse()
                                .withBody("hello, world\n")));
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder(new URI(wireMock.url("test.txt"))).build();
        HttpResponse<String> response = client.send(request, BodyHandlers.ofString());
        assertThat(response.statusCode(), equalTo(200));
        assertThat(response.body(), Matchers.equalTo("hello, world\n"));
    }
```

This test should fail because the request does not populate the `If-Modified-Since` header. Instead, it passes. If I change the URL path to just "/test", the test fails properly, with a message that indicates the expected request header was missing.

I am using WireMock 2.27.1 on JUnit 5.6.2 and Java 11. I've uploaded a repository that demonstrates the problem at https://github.com/npmeyer/wiremock-bug.

**Comment by tomakehurst** [comment]
Looks like this isn't a bug: in the test project there's a file called `test.txt` under the `__files` dir. The stub for `test.txt` isn't being matched since the header isn't present, but since WireMock by default will try to serve a file from `__files` directly, this is what it's doing.

Changing the contents of `test.txt` causes the test to fail as expected.
