### ISSUE TITLE
Extra Elements in the request not able stubs, and Verification Request has been failed.

### ISSUE THREAD

**Issue by YogeshKumbhare** [tomakehurst/wiremock#1383]
Hi Sir,

I am using wire mock version is 2.27.0
In the code level, I am using wiremock server.

#########     Issui 
I need help, in my wiremock stubbing put request I am not passing some extra elements, but I am getting some extra element in response . and hence its shows Verification Exception.
can you please tell me is there any way to ignore those field ...

com.github.tomakehurst.wiremock.client.VerificationException: 3 requests were unmatched by any stub mapping. Requests are:
{
"url" : "v1",
"absoluteUrl" : "http://localhost:9999/v1",
"method" : "PUT",
"clientIp" : "127.0.0.1",
"headers" : {
"Authorization" : "Intuit_IAM_Authentication",
"docid" : "62a5b2ff-260d-489d-a8fb-9e5f3b251yo7",
"User-Agent" : "Vert.x-WebClient/3.9.0",
"Host" : "localhost:9999",
"tid" : "f5f3332e-9848-4783-829c-da8f9e4d141e"
},
"cookies" : { },
"browserProxyRequest" : false,
"loggedDate" : 1600954680338,
"bodyAsBase64" : "",
"body" : "",
"scheme" : "http",
"host" : "localhost",
"port" : 9999,
"loggedDateString" : "2020-09-24T13:38:00Z",
"queryParams" : { }
}

these are the extra fields want to ignore ...
"cookies" : { },
"browserProxyRequest" : false,
"loggedDate" : 1600954680338,
"bodyAsBase64" : "",
"body" : "",
"scheme" : "http",
"host" : "localhost",
"port" : 9999,
"loggedDateString" : "2020-09-24T13:38:00Z",
"queryParams" : { }

Could you please tell me is there any possibility to handle that issue .

this is the runtime date how to add in stubbing .

**Comment by tomakehurst** [comment]
Please post questions to the mailing list, per the README

**Comment by YogeshKumbhare** [comment]
Thanks Tomakehurst/Wiremock,
I had posted ...same question please if you get chance to see , please
reply on that mail .

Thanks again.
