### ISSUE TITLE
Calling /__admin/mappings/import doesn't reverse stub order

### ISSUE THREAD

**Issue by Saborion** [tomakehurst/wiremock#1384]
I don't know if this is a bug or if it's working as intended. When importing mappings to the standalone server by calling /__admin/mappings/import it doesn't reverse the order of the stubs. This is a different behavior from when adding stubs to a .json config file in the stubs/mappings folder and something that can cause an issue when switching from one way or working to the other.

**Comment by tomakehurst** [comment]
The import function is set up to ensure that if you export then import, the stub order remains the same. In practice this means that it does actually insert the stubs in reverse order since WireMock puts the most recent stub at the top of the list.
