### ISSUE TITLE
missing find stubs

### ISSUE THREAD

**Issue by Srsnik** [tomakehurst/wiremock#1385]
The idea is to find a mapping without any call to wiemock that will be returned for url, query params, reqtest attribute, ....

This can be seen as a test of whether the mapping in wiremock is set up correctly.

missing:
POST /__admin/mappings/find

or you can write me back how it can be done otherwise.

**Comment by tomakehurst** [comment]
I feel like it's quite straightforward to pull the whole list of mappings and search it yourself to satisfy this use case, so I'm going to close this off.
