### ISSUE TITLE
Stateful stubbing appears to automatically retry requests

### ISSUE THREAD

**Issue by jaredculp** [tomakehurst/wiremock#1386]
# Issue guidelines

If you're asking a question, rather than reporting a bug or requesting a feature, **please post your question on the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user), and do not open an issue**.

Please do not log bugs regarding classpath issues (typically manifesting as 'NoClassDefFoundException' or 'ClassNotFoundException').
These are not WireMock bugs, and need to be diagnosed for your project using your build tool. Plenty has already been written in WireMock's issues and mailing list about how to resolve these issues
so please search these sources before asking for help.

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [x] Which version of WireMock you're using: `com.github.tomakehurst:wiremock-jre8-standalone:2.27.2` (latest)
- [x] How you're starting and configuring WireMock, including configuration or CLI the command line

```java
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.http.Fault;
import com.github.tomakehurst.wiremock.stubbing.Scenario;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.anyUrl;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static java.nio.charset.StandardCharsets.UTF_8;

public class Main {

    public static void main(String[] args) throws Exception {
        final WireMockServer w = new WireMockServer();
        w.stubFor(get(anyUrl())
                .inScenario("scenario")
                .whenScenarioStateIs(Scenario.STARTED)
                .willSetStateTo("second")
                .willReturn(aResponse().withFault(Fault.CONNECTION_RESET_BY_PEER)));

        w.stubFor(get(anyUrl())
                .inScenario("scenario")
                .whenScenarioStateIs("second")
                .willReturn(aResponse().withBody("success!")));

        w.start();

        final HttpURLConnection con = (HttpURLConnection) new URL(w.baseUrl()).openConnection();
        final InputStream is = con.getInputStream();
        final ByteArrayOutputStream os = new ByteArrayOutputStream();
        int read;
        final byte[] buf = new byte[1024];
        while ((read = is.read(buf, 0, buf.length)) != -1) {
            os.write(buf, 0, read);
        }
        os.flush();

        System.err.println("response: " + new String(os.toByteArray(), UTF_8));
        System.err.println("requests to server: " + w.getAllServeEvents().size());

        w.stop();
    }
}
```

- [x] A failing test case that demonstrates the problem

See above. I'd expect only a single request to be made to the server. Actual output:
```
response: success!
requests to server: 2
```

- [ ] Profiler data if the issue is performance related   

## Feature requests

Please include details of the use case and motivation for a feature when suggesting it.

I am attempting to test an application that has retry logic for retrying on `IOException`. My application's tests pass even when I disable retry. My expectation is that making a single client request would only result in a single response from the server (the mapping that simulates a network fault). I've reproduced the issue using the minimal example included above. Am I misconfiguring something?

**Comment by tomakehurst** [comment]
From running this code with a tcpdump going, it seems it's `HttpURLConnection` that's doing the retrying, and that this behaviour is intentional and hard-coded: https://dzone.com/articles/pola-and-httpurlconnection

I'd suggest using a better HTTP client TBH, `HttpURLConnection` is crap in all sorts of ways.

**Comment by jaredculp** [comment]
I'd ask you to reopen this. I only used `HttpURLConnection` to simplify the example. Here's the same issue reproduced using OkHttp. If its an internal retry implementation by these HTTP clients, is there a way to have wiremock return a response that would throw some kind of IOException?

```
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.http.Fault;
import com.github.tomakehurst.wiremock.stubbing.Scenario;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.anyUrl;
import static com.github.tomakehurst.wiremock.client.WireMock.get;

public class Main {

    public static void main(String[] args) throws Exception {
        final WireMockServer w = new WireMockServer();
        w.stubFor(get(anyUrl())
                .inScenario("scenario")
                .whenScenarioStateIs(Scenario.STARTED)
                .willSetStateTo("second")
                .willReturn(aResponse().withFault(Fault.CONNECTION_RESET_BY_PEER)));

        w.stubFor(get(anyUrl())
                .inScenario("scenario")
                .whenScenarioStateIs("second")
                .willReturn(aResponse().withBody("success!")));

        w.start();

        final Response res = new OkHttpClient()
                .newCall(new Request.Builder().url(w.baseUrl()).build())
                .execute();

        System.err.println("response: " + res.body().string());
        System.err.println("requests to server: " + w.getAllServeEvents().size());

        w.stop();
    }
}
```

```
response: success!
requests to server: 2
```

**Comment by tomakehurst** [comment]
Web servers can't make clients perform a retry, that's entirely at the client's discretion.

You can prevent `OkHttpClient` from retrying like this:

```java
OkHttpClient client = new OkHttpClient.Builder()
                .retryOnConnectionFailure(false)
                .build();
```

**Comment by tomakehurst** [comment]
If you want a response that's more likely to make the client throw an exception regardless of retry config, I'd suggest trying `Fault.MALFORMED_RESPONSE_CHUNK`
