### ISSUE TITLE
Allow to check requests against a JSON schema

### ISSUE THREAD

**Issue by x80486** [tomakehurst/wiremock#1390]
It would be extremely useful if there is a way to check the body of requests against a given JSON schema in a straightforward way.

For instance, something like this:

```json
{
  "request": {
    "headers": { . . . },
    "method": "POST",
    "url": "/path/to/resources",
    "body": {
      "jsonSchema": "schemas/create-resource.json"
    }
  },
  "response": {
    "headers": {
      "location": "{{ request.path }}/{{ randomValue type='UUID' }}"
    },
    "status": 201,
    "transformers": ["response-template"]
  }
}
```

> This is something I've seen implemented by MockServer (in exactly that way), for instance.

**Comment by tomakehurst** [comment]
You could do this via a custom matcher extension, and TBH I think this would be a better approach than making part of the core.

Some folks at Atlassian have already done something similar, but for full Swagger support (which uses JSON Schema), so you might want to take a look and see if it meets your needs: https://bitbucket.org/atlassian/swagger-request-validator/src/master/

**Comment by x80486** [comment]
I don't know much about WireMock, but since you are sort of the main folk/owner, how would you envision people using those extensions (actually that one in particular) while running the standalone process? Currently, [I don't use](https://stackoverflow.com/questions/64197930/use-json-schema-check-on-post-request-with-wiremock) any Java configuration, just the (unofficial) Docker image — which is pretty much the same as running the JAR file.

So I rely solely on multiple JSON files for the stub mappings. Probably I don't get it, but it looks like the `swagger-request-validator` library relies on an `OpenApiValidationListener` that's triggered when attached to a (WireMock) JUnit rule.

**Comment by tomakehurst** [comment]
It's possible to add extensions as extra JAR files when running WireMock standalone, and there's an explanation here of how to do it with the Docker image: https://github.com/rodolpheche/wiremock-docker#use-wiremock-extensions

I haven't looked at `swagger-request-validator` for a little while, but I thought there was more than one way to deploy it (i.e. other than the JUnit rule).

If you were to write your own extension, I'd recommend implementing it as a `ResponseDefinitionTransformer`. That way you'd essentially trap the incoming request and validate its body against your schema, then just return the original response if it's OK, and return e.g. a `422` response with a JSON error document if not.
