### ISSUE TITLE
Incompatibility with PowerMockRunner

### ISSUE THREAD

**Issue by mkemmerz** [tomakehurst/wiremock#1392]
wiremock-jre8, version 2.27.2
powermockito, version 2.0.4
Java 14

The annotation `@RunWith(PowerMockRunner.class)` in a test case leads to the following exception:

        javax.xml.transform.TransformerFactoryConfigurationError: Provider 
        com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl could not be instantiated: 
        java.lang.reflect.InvocationTargetException

	at java.xml/javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:181)
	at java.xml/javax.xml.transform.FactoryFinder.find(FactoryFinder.java:257)
	at java.xml/javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:126)
	at com.github.tomakehurst.wiremock.common.xml.Xml.optimizeFactoriesLoading(Xml.java:52)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<clinit>(WireMockApp.java:75)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:73)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.<init>(WireMockRule.java:43)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.<init>(WireMockRule.java:39)

Removing PowerMock and switching to a different runner like `@RunWith(MockitoJUnitRunner.class)` fixes the issue. The cause of the exception was kinda hard to track down so maybe this could be improved.

The issue is probably related to https://github.com/tomakehurst/wiremock/issues/1072

**Comment by tomakehurst** [comment]
I'm going to ask the standard questions:
1) Have you tried the standalone JAR?
2) Have you looked at your project dependencies when Powermock is present to see what's different and whether it can be fixed by e.g. dependency exclusions?

**Comment by mkemmerz** [comment]
Yes, I tried `wiremock-jre8` and `wiremock-jre8-standalone`. I also tried to exclude specific dependencies but I wasn't able to fix it. 
Like I said above, switching the JUnit Runner fixed it.

**Comment by anandbibek** [comment]
Apparently this issue can be solved by adding below dependencies with test scope.

`<dependency>
      <groupId>xalan</groupId>
      <artifactId>xalan</artifactId>
      <version>2.7.2</version>
      <scope>test</scope>
    </dependency>`

**Comment by tomakehurst** [comment]
I've wrapped the optimise method in a try/catch in 882b7d044fb6f113025237c9e3ad6c27fb923b49. Curious to know if this fixes the issue if you're able to re-test?

**Comment by mkemmerz** [comment]
> I've wrapped the optimise method in a try/catch in [882b7d0](https://github.com/tomakehurst/wiremock/commit/882b7d044fb6f113025237c9e3ad6c27fb923b49). Curious to know if this fixes the issue if you're able to re-test?

Thanks for the effort you put into that! Sadly I am no longer able to re-test it due to a change in work. I really hope someone else can confirm that in the future!

**Comment by tomakehurst** [comment]
OK, I'm going to close this for now. Someone please shout if it's still an issue.
