### ISSUE TITLE
Java API: MatchesJsonPathPattern with nested EqualToJson silently ignores ignoreArrayOrder and ignoreExtraElements attributes

### ISSUE THREAD

**Issue by laszlovandenhoek** [tomakehurst/wiremock#1398]
In the Java API, if you use an `equalToJson` with the `ignoreArrayOrder` and `ignoreExtraElements` attributes set, nested inside a `matchingJsonPath`, like so:

```
final String nested = "{\"anArray\": [1, 2]}"

stubFor(post(API)
        .withRequestBody(
                matchingJsonPath("$.nested",
                        equalToJson(nested, true, true)))
        .willReturn(aResponse()
                .withStatus(200)
        ));
```

...then I would expect a request with this body to match:

```
{
  "nested": {
    "anArray": [2,1],
    "anExtraElement": "oughtToBeIgnored"
  }
}
```

However, this is not the case. The request does not match because the stub mapping only registered the `expectedValue`; the `ignoreArrayOrder` and `ignoreExtraElements` attributes are __silently ignored__ (which caused me a lot of grief) and both remain `null`.

The reason for this is simple: upon registration of mapping, the outer `matchingJsonPath` serializes to something like:

```
{
  "matchesJsonPath": {
  "expression": "$.nested",
  "equalToJson": "{\"anArray\": [1, 2]}"
}
```

This is because `PathPatternJsonSerializer.serialize()` just uses `value.getValuePattern().getExpected()`, ignoring everything else:

https://github.com/tomakehurst/wiremock/blob/d43540a4a4421c49a2b866db5a19dca5d428f85b/src/main/java/com/github/tomakehurst/wiremock/matching/PathPatternJsonSerializer.java#L35

`StringValuePatternJsonDeserializer` on the other end already seems perfectly capable of interpreting the extra attributes:

https://github.com/tomakehurst/wiremock/blob/d43540a4a4421c49a2b866db5a19dca5d428f85b/src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java#L120-L136

What would be the best place to customize serialization of nested `StringValuePattern`s like `EqualToJson`? Bluntly adding this to `PathPatternJsonSerializer` works:

```
if (value.getValuePattern() instanceof EqualToJsonPattern) {
    final EqualToJsonPattern equalToJsonPattern = (EqualToJsonPattern) value.getValuePattern();
    if (equalToJsonPattern.isIgnoreArrayOrder() != null && equalToJsonPattern.isIgnoreArrayOrder()) {
        gen.writeStringField("ignoreArrayOrder", equalToJsonPattern.isIgnoreArrayOrder().toString());
    }
    if (equalToJsonPattern.isIgnoreExtraElements() != null && equalToJsonPattern.isIgnoreExtraElements()) {
        gen.writeStringField("ignoreExtraElements", equalToJsonPattern.isIgnoreExtraElements().toString());
    }
}
```

...but that seems inappropriately specific inside `PathPatternJsonSerializer`. Also, this could probably be a one-liner (or none-liner) when leveraging the Jackson Databind annotations already present on `EqualToJsonPattern`.

Another option could be to delegate to `StringValuePatternJsonSerializer`. The bad news is that in its current state it doesn't work correctly. The good news is that it is apparently not used anywhere; if that's correct we can change it as required without impact (although that it is public, so it might still be used by library consumers).

How to proceed?

This issue is present in all versions of WireMock that I can see, including the latest.

**Comment by tomakehurst** [comment]
Fixed in 15413a5f
