### ISSUE TITLE
Return Fault.CONNECTION_RESET_BY_PEER in stateful stub mess up state match.

### ISSUE THREAD

**Issue by zhongf** [tomakehurst/wiremock#1402]
## Bug reports

for folloing stub: 
```
    stubFor(
        post("/oauth")
            .inScenario("auto-retry in case of io error")
            .whenScenarioStateIs(Scenario.STARTED)
            .willSetStateTo("RESET")
            .willReturn(aResponse().withFault(Fault.CONNECTION_RESET_BY_PEER)));
```
WireMock complains no matching stub.
```
-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/oauth                                                     | /oauth
                                                           |
[Scenario 'auto-retry in case of io error' state:          | [Scenario 'auto-retry in case of io error' state: RESET]<<<<< Scenario does not match
Started]                                                   |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

tested with version 2.27.2, 2.26.2, 2.26.3

**Comment by tomakehurst** [comment]
Assuming this happens the second time you make the request this is expected behaviour, since you've moved the scenario state to `RESET` and you don't have a stub matching that state.

**Comment by zhongf** [comment]
hi, thank you for looking at it. 
it happened to the first request.

**Comment by tomakehurst** [comment]
In that case the issue is probably that your HTTP client is silently retrying the request. See https://github.com/tomakehurst/wiremock/issues/1386.

**Comment by zhongf** [comment]
Hi yes, indeed. Thank you!

**Comment by zhongf** [comment]
for the record, and folks comming later with same issue, the client is *reactor-netty* _HttpClient_. Contrary to my expectation, it will retry *all* requests, not just *GET*,  in case of connection reset errors. 

https://github.com/reactor/reactor-netty/blob/5711e2782535a813bbfd22cc5af2def5d7cb9bbc/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L611
