### ISSUE TITLE
Wrong documentation for response templating

### ISSUE THREAD

**Issue by stubents** [tomakehurst/wiremock#1404]
In commit https://github.com/tomakehurst/wiremock/commit/e584b16253d487ffb6dde1e444d4920e05ec3d0d the `requestLine` part of the templating documentation was removed. However this only works for properties, that have a deprecated field in `RequestTemplateModel` like `url` and `path`, however fields like `port`only work via `{{request.requestLine.port}}`.

If I didn't get this wrong, this commit should probabaly get reverted.

**Comment by tomakehurst** [comment]
Docs are correct WRT the latest version: https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestTemplateModel.java#L98
