### ISSUE TITLE
Add support for application/stream+json

### ISSUE THREAD

**Issue by ajeetbansal** [tomakehurst/wiremock#1405]
Please refer: https://github.com/spring-cloud/spring-cloud-contract/issues/1535

We are making use of spring webflux to create reactive rest API's that return application/stream+json so that the reactive web client can consume large datasets returned by the API in a reactive fashion. But we are unable to mock this api using wiremock. 

Is it possible to add support for application/stream+json

**Comment by tomakehurst** [comment]
Closing since this seems to have been due to Spring's consumption of the stream, rather than WireMock producing it.
