### ISSUE TITLE
Wiremock standalone not worku=ing properly with multiple instances pointing to same nfs mount.

### ISSUE THREAD

**Issue by prashant2018** [tomakehurst/wiremock#1408]
Hi,

I deployed multiple instances of standalone wiremock app on pivotal cloud foundry all pointing to same nfs mount. 
When only one instance is there, it works perfectly, but as I increase the number of instances of app it starts behaving unexpectedly.

Issues:
- After recording when I press stop the UI freezes. However, recording files is created and stored on nfs mount.
- While playing the recordings only sometimes I get the response back.

Has anyone faced the same issue and fixed it ? Please help if anyone knows how to fix this.
Thanks

**Comment by tomakehurst** [comment]
Can I suggest reposting this on the mailing list? It's more of a question than a bug report at this stage, and more people will see it this way.

**Comment by prashant2018** [comment]
Sure!
