### ISSUE TITLE
Vulnerability in guava version prior to v.30

### ISSUE THREAD

**Issue by larspettern** [tomakehurst/wiremock#1409]
Code analysis reveals vulnerability in dependency to guava: 

https://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-8908

https://github.com/tomakehurst/wiremock/blob/d43540a4a4421c49a2b866db5a19dca5d428f85b/build.gradle#L39

**Comment by tomakehurst** [comment]
Upgraded in 1b50f705ad204eeed515cf904b43f0459caefe4e
