### ISSUE TITLE
witStatus / withStatusMessage return only status code

### ISSUE THREAD

**Issue by saschpe** [tomakehurst/wiremock#1410]
When stubbing a response with a status code, only the code is set in the response, the message is empty. 

- `.willReturn(WireMock.aResponse().withStatus(404))` does not return a message (behavior change to previous versions)
- Explicitly stubbing a status message with `.willReturn(WireMock.aResponse().withStatus(404).withStatusMessage("Not Found"))` does not help either. The response still only contains a code (404 in this example), but no message
- Version 2.27.2

**Comment by tomakehurst** [comment]
Closing, as this is quite old and both cases work fine for me in the latest version. Please post a test case if it's still an issue and I'll re-open.
