### ISSUE TITLE
Vulnerabilities found in handlebars

### ISSUE THREAD

**Issue by svanpe** [tomakehurst/wiremock#1413]
see https://www.npmjs.com/advisories/1164 : the current version of handlebars contains some vulnerabilities. Would it be possible to upgrade to a new version that fixes it?

Thanks a lot.

**Comment by tomakehurst** [comment]
The Handlebars JS file is will now be filtered out of the standalone build from 2.28.0 onwards.

**Comment by svanpe** [comment]
thanks a lot
