### ISSUE TITLE
Unable to validate Date-Time field is greater than or Less than in mappings json

### ISSUE THREAD

**Issue by PRABAREPO** [tomakehurst/wiremock#1418]
**My Request Body:**
{
  "username": "string",
  "Time": "2021-05-01T08:30:52.123Z",
  "Reference": "string"
}

**My Mappings JSON:**
{
    "request": {
        "method": "POST",
        "urlPattern": "/v1/test",
        "bodyPatterns": [
            {"matchesJsonPath" : "$[?(@.Time <= '2021-19-01T08:30:52.123Z')]"}  ]
    },
    "response": {
        "headers": {
            "Content-Type": "application/json"
        },
        "status": 200,
        "jsonBody":{
        "success": "Time is in Past"
        }
    }
}

Here I want to validate the Time attribute in request whether its less than than or equal to given time in mappings. 
But Its not working as that time field considered as String. 

Could you please help me on how to configure/validate that time attribute in Mappings

**Comment by tomakehurst** [comment]
Please post questions to the mailing list
