### ISSUE TITLE
Feature request: would it be possible to make URL parameter orders irrelevant?

### ISSUE THREAD

**Issue by tongguop** [tomakehurst/wiremock#142]
Right now the URL parameter order is significant. For example, in one of my test, if I have:
?p1=v1&p2=v2, the test is successful. But if i change it to ?p2=v2&p1=v1the test failed. It would be very much helpful to make the order not relevant.

Thanks

**Comment by tomakehurst** [comment]
Now implemented in the `queryParameters` request pattern component.
