### ISSUE TITLE
Shadow org.slf4j:slf4j-api and net.sf.jopt-simple:jopt-simple

### ISSUE THREAD

**Issue by Eleid** [tomakehurst/wiremock#1424]
# Issue
Including `com.github.tomakehurst:wiremock-standalone` creates conflicts with `org.slf4j:slf4j-api` and `net.sf.jopt-simple:jopt-simple` in my project. The same happens for `com.github.tomakehurst:wiremock-jre8-standalone`

I use the `2.27.2` version.

Please add shadowing for these two libraries as well.

The output of `org.basepom.maven:duplicate-finder-maven-plugin` plugin:
```
[WARNING] Found duplicate and different classes in [com.github.tomakehurst:wiremock-jre8-standalone:2.27.1, org.slf4j:slf4j-api:1.7.12]:
[WARNING]   org.slf4j.ILoggerFactory
[WARNING]   org.slf4j.IMarkerFactory
[WARNING]   org.slf4j.Logger
[WARNING]   org.slf4j.LoggerFactory
[WARNING]   org.slf4j.MDC
[WARNING]   org.slf4j.Marker
[WARNING]   org.slf4j.MarkerFactory
[WARNING]   org.slf4j.helpers.BasicMDCAdapter
[WARNING]   org.slf4j.helpers.BasicMarker
[WARNING]   org.slf4j.helpers.BasicMarkerFactory
[WARNING]   org.slf4j.helpers.FormattingTuple
[WARNING]   org.slf4j.helpers.MarkerIgnoringBase
[WARNING]   org.slf4j.helpers.MessageFormatter
[WARNING]   org.slf4j.helpers.NOPLogger
[WARNING]   org.slf4j.helpers.NOPLoggerFactory
[WARNING]   org.slf4j.helpers.NOPMDCAdapter
[WARNING]   org.slf4j.helpers.NamedLoggerBase
[WARNING]   org.slf4j.helpers.SubstituteLogger
[WARNING]   org.slf4j.helpers.SubstituteLoggerFactory
[WARNING]   org.slf4j.helpers.Util
[WARNING]   org.slf4j.spi.LocationAwareLogger
[WARNING]   org.slf4j.spi.LoggerFactoryBinder
[WARNING]   org.slf4j.spi.MDCAdapter
[WARNING]   org.slf4j.spi.MarkerFactoryBinder
```

**Comment by tomakehurst** [comment]
Unfortunately `slf4j` can't be relocated as this would prevent it working when the standalone JAR is used as a dependency.

I seem to remember jopt-simple breaks when you relocate it too, although I've not tested this with the latest version.

**Comment by Eleid** [comment]
Ok, got it! Thanks! I think I, fortunately, solved my issue using the not-standalone library. I have too many dependencies conflicting with your project and with spring-cloud-contract-stub-runner that is fatJar as well. I prepared my own "stub-runner".
