### ISSUE TITLE
Admin API: updating mapping priority for a proxyBaseUrl mapping wipes out the proxyBaseUrl setting

### ISSUE THREAD

**Issue by omairkhawaja** [tomakehurst/wiremock#1425]
Given the following wiremock mapping:
`{
  "id": "00000000-0000-0000-0000-5a11ea9e0000",
  "priority": 99999,
  "request": {
    "method": "ANY",
    "urlPattern": "/api/.*"
  },
  "response": {
    "proxyBaseUrl" : "https://somehost"
  }
}`

A PUT request to http://localhost:8080/__admin/mappings/00000000-0000-0000-0000-5a11ea9e0000 with the body below:
`
{
  "id": "00000000-0000-0000-0000-5a11ea9e0000",
  "priority": 1
}
`

returns the following response:
`{
  "id": "00000000-0000-0000-0000-5a11ea9e0000",
  "request": {
    "method": "ANY"
  },
  "response": {
    "status": 200
  },
  "uuid": "00000000-0000-0000-0000-5a11ea9e0000",
  "priority": 1
}`

showing that the API is wiping out the proxyBaseUrl

**Comment by tomakehurst** [comment]
`PUT` replaces the entire resource (as is typical with REST APIs), so this is to be expected. When you don't provide a `response` element at all, WireMock generates a default.

If you want to preserve `proxyBaseUrl` you'll need to ensure you send it in your `PUT` request body.
