### ISSUE TITLE
Mock/not-mock response on a per request basis.

### ISSUE THREAD

**Issue by sumit1112** [tomakehurst/wiremock#1426]
Hi Team,

I am curious to understand if there is a way that I can mock/not-mock the request on a per configuration basis. Like for example if request accepts email address in request and I provide
1. "invalid@email.com" - response from mockoon must be a mocked response.
2. "valid@email.com" - mocking must not happen but rather it must hit the actual server to get the response. may be via redirecting or calling the actual service and responding the response to the caller.

Regards,

**Comment by tomakehurst** [comment]
Please post questions to the mailing list, per the issue template.
