### ISSUE TITLE
Feature request: add description in StubMapping

### ISSUE THREAD

**Issue by alins** [tomakehurst/wiremock#143]
i believe a simple "description" field would be extremely helpful to have in StubMapping. If you have a lot of stubs it can get a bit hard to manage them, figure out which one i used for what. So the description string can help with that. 

Simple string should be enough, and as far as i can see in the source code fairly simple to implement.

what do you think?
Alin

**Comment by aumohanraj** [comment]
Hello,

Is this still Open?
From wiremock documentation, metadata attribute on stub mapping can be used for storing stub description and tags.

**Comment by tomakehurst** [comment]
Yep, I think now that metadata is available, a separate description field isn't necessary, so closing.
