### ISSUE TITLE
 Initialize a WireMockHandlerDispatchingServlet on sever startup.

### ISSUE THREAD

**Issue by dtuchs** [tomakehurst/wiremock#1436]
## Feature requests

First request to Wiremock standalone server (latest version 2.27.2) always takes a long time (up to 1500 ms) to finish. 
But all of the following requests are very fast. (~100 ms).
I think this is due to lazy loading of WireMockHandlerDispatchingServlet.

Unfortunately there is no way to override programmatic configuration for `ServletHolder`: 
```
     ServletHolder servletHolder = mockServiceContext.addServlet(WireMockHandlerDispatchingServlet.class, "/");
```

Can you add configuration parameter to disable lazy servlet loading? (and call `servletHolder.setInitOrder(1);` for dispatcher servlet)

[This feature has already been mentioned](https://github.com/tomakehurst/wiremock/issues/97#issuecomment-618922016)

**Comment by tomakehurst** [comment]
Have you got some profiling data showing that this is the reason, or is this speculation?

Happy to accept a PR for this if there's some evidence it'll make the expected difference.
