### ISSUE TITLE
Add the ability to simulate slow network

### ISSUE THREAD

**Issue by yogurtearl** [tomakehurst/wiremock#146]
It would be great to have the ability to simulate a slow network. 

You could then sleep between every so many bytes of output to simulate a given speed ( e.g. 100K/s ). This could be set at a global or mapping level.

Also, the slow reading of requests would be useful. That may have to be a global setting.

If I remember right, I saw this in MockWebServer ( https://github.com/square/okhttp/tree/master/mockwebserver ) awhile back.

**Comment by handstandsam** [comment]
@yogurtearl It looks like this feature is now available, at least in the 1.5.7 release. http://wiremock.org/simulating-faults.html#simulating-faults-stub-delays

```java
stubFor(get(urlEqualTo("/delayed")).willReturn(
        aResponse()
                .withStatus(200)
                .withFixedDelay(2000)));
```

This issue can be marked as resolved.

**Comment by yogurtearl** [comment]
@handstandsam withFixedDelay has been there for a while. withFixedDelay is somewhat different than a slow data rate. The delay feature just has 0 bytes until the delay passes and then returns the response at full speed. 

I was asking for something similar to throttling in Mockwebserver: 

https://github.com/square/okhttp/blob/master/mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java#L199

**Comment by handstandsam** [comment]
@yogurtearl Ahh, I see.  Thanks for the clarification.  I can see how that would be useful in a mock version of an application.  In testing... not sure how that would be useful?

**Comment by tomakehurst** [comment]
I think #472 is probably what we're talking about here, so I'll close this and encourage discussion over there.
