### ISSUE TITLE
Handlebar {{eq}} not recognised

### ISSUE THREAD

**Issue by harlalkap** [tomakehurst/wiremock#1470]
Wiremock standalone jar v2.27.2

I am using wiremock standalone jar and while putting a handlebar js expression in response {{eq}} its not recognised by Wiremock.

Response file:
.
.
<type>
{{eq text1 text2}}
<no> 1 </no>
{{else}}
<no> 2 </no>
{{/eq}}

When called getting below error:
Java.lang.IllegalArgumentException: could not find helper: ‘eq’

**Comment by tomakehurst** [comment]
You can only use `eq` as a block element, and you need to combine with `if` if you want `else`, so e.g.

```
{{#if (eq request.query.thing.0 'yes')}}
yes
{{else}}
no
{{/if}}
```

**Comment by harlalkap** [comment]
I tried this but still an issue -
{{#if (eq ‘text1’ ‘text1’)}}
<type> 1 </type>
{{else}}
<type> 2 </type>
{{/if}}

Wiremock version - 2.27.2

**Comment by harlalkap** [comment]
@tomakehurst can you help?

**Comment by tomakehurst** [comment]
Since this is a question, please re-post it to the mailing list.
