### ISSUE TITLE
Allow the Standalone runner to fetch mappings from the classpath

### ISSUE THREAD

**Issue by jamietanna** [tomakehurst/wiremock#1502]
Is it possible to make it so the standalone runner picks up anything on the classpath?

For instance I've shaded the standalone app with a set of stubs, and a custom extension, and I'd like to have standalone not needing a second set of stub mappings on disk as well.

It looks like this isn't quite possible with `--root-dir` provided as an argument to the standalone runner

**Comment by tomakehurst** [comment]
Please post questions to the mailing list per the issue template
