### ISSUE TITLE
https enabled recorded sites do not render the correct page

### ISSUE THREAD

**Issue by rudrathkr** [tomakehurst/wiremock#1510]
1. Start the wiremock server:
java -jar wiremock-jre8-standalone-2.28.0.jar --https-port 8888 --https-keystore ./identity.jks --proxy-all https://spring.io --record-mapping
2. Go to https://localhost:8888
3. Record some operations on UI 
4. Stop the server 
5. Start the server with 
java -jar wiremock-jre8-standalone-2.28.0.jar --https-port 8888
6. Go to https://localhost:8888
7. The page is not coming properly(encrypted data)
Is this a known issue or any workarounds for this

**Comment by tomakehurst** [comment]
This is related to #1271 - WireMock can't yet handle brotli compressed responses.

You can work around this in Firefox by removing `br` from the content encoding setting:

![image](https://user-images.githubusercontent.com/707169/119644811-3bb15480-be15-11eb-9061-f7bf3b78bd8f.png)

**Comment by rudrathkr** [comment]
Thanks Tom worked. 

Just for benefit of everyone:
Go to Firefox -> about:config
Search for encoding-> network.http.accept-encoding.secure-> remove br
Do the steps 1-7 again and it should work.
