### ISSUE TITLE
NPE thrown when recording

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#1528]
See https://groups.google.com/g/wiremock-user/c/WyDnGXRffng/m/cfgGsljtAgAJ

**Comment by tomakehurst** [comment]
Hmm...missing Content-Encoding isn't the problem.

**Comment by jslew** [comment]
@tomakehurst fixed this, please let me know if it's not acceptable.

**Comment by tomakehurst** [comment]
@jslew thanks for providing this. Looks good, so assuming the build stays green I'll merge it.
