### ISSUE TITLE
Add header policy when wiremock bootups

### ISSUE THREAD

**Issue by riteshmatale7** [tomakehurst/wiremock#1544]
Hi Team, 

Just wondering do we have any policy for enabling/disabling headers across all the mappings ? 
Please see below example of a sample request where we're expecting Authorization in header. I want to make this as plug and play -- make this enable/disable without changing the mappings. 

{
	"mappings": [{
			"request": {
				"method": "GET",
				**"headers" : {
					"Authorization" : {
						"matches" : "^Bearer\\s.{54}$"
					}**
				},
				"urlPath": "/xyz"
				}
			},
			"response": {
				"status": 200,
				"headers": {
					"Content-Type": "application/json"
				},
				"bodyFileName": "xyz.json"
			}
		}
	]
}

Thanks,
Ritesh

**Comment by tomakehurst** [comment]
You can achieve this by writing a `RequestFilter` implementation that checks the `Authorization` header before allowing the call to proceed.

Here's an example of how to write a filter: https://github.com/tomakehurst/wiremock/blob/master/src/test/java/com/github/tomakehurst/wiremock/RequestFilterAcceptanceTest.java#L105
