### ISSUE TITLE
Ignore  some fields in xml request matching using wiremock stand alone jar

### ISSUE THREAD

**Issue by ramsirish** [tomakehurst/wiremock#1555]
Hi Team,

We are using wiremock as mocking tool in our tests. We are trying to ignore some fields in xml as we have some fields like date and time dynamically generated which we want to ignore them during request matching. We are using wiremock stand alone jar. Could you please share the best approach to this or if any examples so that it would be helpful to us.

**Comment by ramsirish** [comment]
@tomakehurst pls help

**Comment by tomakehurst** [comment]
Since this is a question rather than a bug, please post it to the mailing list
