### ISSUE TITLE
2.29.0 missing in Central

### ISSUE THREAD

**Issue by tomasbjerre** [tomakehurst/wiremock#1561]
I have noticed the 2.29.0 version is released. But not available in Maven Central.

Is this something being worked on? Do you need help with it? [Here](https://github.com/tomasbjerre/gradle-scripts/blob/285eb004ee8d2053b2cb719ddb44e98e02478cd9/src/main/resources/main.gradle#L446) is how I do it.

**Comment by tomakehurst** [comment]
Here you go: https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8/2.29.0/
