### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by xtaixe** [tomakehurst/wiremock#1569]
Hi. We are seeing slow response time both in local machines and CI, which makes our tests fail in some cases.

I'm attaching a reproducer for a simple test for which I always see response times higher than 500ms and up to 900ms. It just uses the default `WireMockServer` except for `DYNAMIC_PORT`. Any chance you can reproduce this? Otherwise, any ideas on what could be causing this for such a simple case?

WireMock version: 2.29.0

Reproducer: [reproducer.zip](https://github.com/tomakehurst/wiremock/files/6840233/reproducer.zip)

Java Flight Recorder profiling data: [WireMockTest_2021_07_19_130207.jfr.zip](https://github.com/tomakehurst/wiremock/files/6840264/WireMockTest_2021_07_19_130207.jfr.zip)

Issue seen in:
 - macOs Big Sur with GraalVM CE 21.1.0
 - macOs Sierra with OpenJDK 11
 - Docker CentOS based image (CI)

**Comment by xtaixe** [comment]
I was testing more stuff and I just saw that it's only the first request that is slow, if I do more than 1 request in a test, the subsequent ones take less than 20ms...

The problem is that we have tests with a single request... Is WireMock doing some initialization lazily? Is there a way to get a "warmed up" instance ready before running the tests?

Thanks.

**Comment by tomakehurst** [comment]
WireMock isn't particularly great on time to first response at the moment and it's not something I've had time to diagnose.

It initialises most things eagerly, but there are things like the Jackson ObjectMapper that are quite expensive to construct and lazy. I also think there are parts of Jetty that start lazily so this may go some way to explaining it.

Is the issue simply that you're running single test cases from cold and it's slower than you'd like?

Or does the timing of the response matter to the outcome of your test?

**Comment by xtaixe** [comment]
The timing matters. We depend on a library that sends the request on shutdown with a timeout of 1 second. After triggering the shutdown we check WireMock for the request and the test fails (it usually only fails in CI, where it seems WireMock's first response takes more than 1 second).

Unfortunately, the timeout is not configurable... We might look into that but our current workaround is to keep polling WireMock (cause the request was made and eventually the WireMock assertion passes).

Could maybe `verify` and similar methods wait if there's an ongoing request (or if it matches the verify request pattern) until it's done? Or if you think the issue is with generic stuff like the `ObjectMapper` and Jetty, could WireMock do an initial "fake" request (that won't count or be matched by anything) on start or something like that or provide a method to do so manually (e.g. `wireMockServer.initialize()` or `wireMockServer.warmUpWithFakeRequest()`)?

**Comment by tomakehurst** [comment]
Is there anything to stop you sending a dummy request to warm WireMock up before the test case starts?

**Comment by xtaixe** [comment]
Well, I'll need to initialize a client just for that and do it everywhere it's needed... Currently only a couple of tests probably, but still... It seems it would be nice to provide this out-of-the-box to solve cases like this and maybe also provide a more consistent timing experience between multiple requests or if you want for example to measure how long tests take.

**Comment by tomakehurst** [comment]
You could make a call from the WireMock DSL if you wanted to avoid setting up a client e.g. something like this in your pre-test code:

```java
WireMock.verify(0, anyRequestedFor(anyUrl()));
```

**Comment by tomakehurst** [comment]
Actually, it looks like you might have provided some evidence to back this up, so I might look at working on this for the next release:
https://github.com/tomakehurst/wiremock/issues/1436

**Comment by xtaixe** [comment]
`WireMock.verify(0, anyRequestedFor(anyUrl()));` doesn't seem to help with the time to first response... Doesn't a request need to be actually performed and not just a verification?

**Comment by tomakehurst** [comment]
Hmmm...I'd have expected it to help, although I suppose (per the linked issue) because it's a different servlet that it won't warm up everything required.

Since you've given me some data to work with, I'll prioritise looking at #1463.

**Comment by xtaixe** [comment]
Sorry, I'm not sure I follow. Is there anything else after https://github.com/tomakehurst/wiremock/pull/1463 or how will bumping Awaitility help?

**Comment by tomakehurst** [comment]
Sorry, typo. I meant #1436.

**Comment by tomakehurst** [comment]
Although you could possibly wrap your call to `verify(...)` with Awaitility as a workaround for your issue.

**Comment by tomakehurst** [comment]
From your JFR recording it looks like `ObjectMapper` init is a major factor.

![image](https://user-images.githubusercontent.com/707169/126218781-536c524b-1e6e-492a-a56e-4d8a5d1ad37a.png)

Given that in this instance it's the logging code triggering JSON serialisation you could try disabling stub request logging via `options.stubRequestLoggingDisabled(true)`.

**Comment by xtaixe** [comment]
That certainly shaves some time. Since I don't think this can be changed to be the default, can the `ObjectMapper` be created in advance when the `WireMockServer` is created? Is that part of https://github.com/tomakehurst/wiremock/issues/1436 ?

**Comment by tomakehurst** [comment]
I'm playing around with this and changed the `ObjectMapper` cache to be an inheritable thread local so that it can be created once on the main thread.

It works OK so I'll ship it in the next release, but it only seems to have made a few 10s of ms difference unfortunately.

**Comment by tomakehurst** [comment]
I've pushed a few commits to master that improve a bit on the things we've talked about. The first request is still taking a little over 100ms by my testing and a lot of that is Java class loading, which there isn't a huge amount I can do about without major surgery so I'm going to close this off for now.

I've been thinking about a `waitFor` method or some such that's like verify but will block for up to a timeout waiting for the matching event(s).

In the meantime, as a I mentioned, you can achieve the same effect as this with Awaitility.

**Comment by xtaixe** [comment]
Cool. I'll give it a go once there's a new release.
