### ISSUE TITLE
Upgrade JSONPath to 1.2.1 makes available more matching

### ISSUE THREAD

**Issue by filosganga** [tomakehurst/wiremock#197]
The current json-path is the 0.8.1 version that does not support few matches.
Given the JSON: 

```
{
   "ids": [1,2,3,4]
   "idType": "BOOK"
}
```

Primitive matching:

```
"$.ids[?(@ == 1)]"
```

Field matching:

```
"$[?(@.idType == BOOK)]"
```

Will be good to have these very useful matches available, they can be used to cover most of the situation where the JSONP support is required.

I can collaborate with a pull request if it is possible.

**Comment by MadalinaBidilita** [comment]
Hi!

Could you please tell me if this migration to json path v2 is still planned to be done?

Thanks,
Madalina

**Comment by tomakehurst** [comment]
I still expect we'll do it as part of v2 when we upgrade Jetty. But we're struggling to find time to work on it at the moment, so it won't be happening very soon.

**Comment by adrianboimvaser** [comment]
Any news on this?

**Comment by jkubrynski** [comment]
@tomakehurst Could you answer?

**Comment by tomakehurst** [comment]
No progress I'm afraid. I've had very little time to work on a 2.0 release over the last few months.

I'm hoping I'll have some within the next few weeks once I'm past the next milestone on my client project, but it's hard to say. Not something I can easily do in small chunks unfortunately.

**Comment by jkubrynski** [comment]
So maybe put milestone and issues you're planning for 2.0. There are many people interested in using wiremock, so it's big chance to ship it on pull-requests.

**Comment by tomakehurst** [comment]
Agree I should do that. Been meaning to, but haven't due to time.

**Comment by filosganga** [comment]
IMHO the best approach here is to decouple Wiremock API from JsonPath.

**Comment by tomakehurst** [comment]
Can you elaborate?

**Comment by filosganga** [comment]
Never mind, I was wrong.

**Comment by hansjoachim** [comment]
Current master uses jsonpath 2.2.0 (https://github.com/tomakehurst/wiremock/blob/master/build.gradle#L57), so I believe this issue can be marked as resolved. (Possibly alongside #137)
