### ISSUE TITLE
Add a plugin/extension mehanism

### ISSUE THREAD

**Issue by chbatey** [tomakehurst/wiremock#214]
I've previously forked (privately inside a company) to add support for things like proprietary auth mechanisms. I'd rather just take master version + add things to the class path.

I was thinking of adding an interface something like:

``` java
package com.github.tomakehurst.wiremock.http;

public interface RequestResponseExtension {
    ResponseDefinition filter(Request request, ResponseDefinition responseDefinition);
}
```

Then loading all implementations off the class path using https://github.com/ronmamo/reflections (or perhaps java service loader api but this is more work for people providing extensions)

These could then be picked up in the StubRequestHandler and each request/response passed through?

I wasn't planning on adding a way to prime them and just have them all picked up and used by default?

What do you think?

**Comment by Mahoney** [comment]
Personally I'd prefer actively to instantiate any extension objects and pass them in when creating the WireMock server or client over anything reflection based. That makes the construction completely explicit, which makes the extensions composable since the end user can choose how to stick them together and whether or not to use them.

**Comment by chbatey** [comment]
I agree this would be nice for the programmatic API.

**Comment by chbatey** [comment]
Ah I was going to add this but appears you did it already :)  Nice.

new WireMockServer(wireMockConfig().extensions("com.mycorp.BodyContentTransformer", "com.mycorp.HeaderMangler"));

new WireMockServer(wireMockConfig().extensions(BodyContentTransformer.class, HeaderMangler.class));

new WireMockServer(wireMockConfig().extensions(new BodyContentTransformer(), new HeaderMangler()));

**Comment by eliseealex** [comment]
Nice to see this issue. 
I also thought how can I make a dynamic response with WireMock and my approach was quite similar to proposed. But I had problems with the storage and identification of transformers and your approach is much easier and clear. But for generation of response it is also necessary to have a state of transformer (e.g. max value for random int or the regexp to search in body of request and so on).
I think it can look like that:
```java
public abstract class ResponseTransformer<T> implements Extension {

    public abstract ResponseDefinition transform(Request request, ResponseDefinition responseDefinition, FileSource files);

    public boolean applyGlobally() {
        return true;
    }

    public abstract void initialize(T parameter);

    public abstract Class<T> getParamClass();
}
```

What do you think? And the configuration in JSON will look like:

```json
{
...
"response":{
   ...
  "transformers":[
    {
       "name":"randomInt",
       "params":{
         "max":100
       }
    },
    {
       "name":"regexp",
       "params":{
         "pattern":"*."
       }
    }
   ]
  }
}
```

**Comment by tomakehurst** [comment]
I think this is a good idea. Would promote a lot more re-use of extensions I suspect. I'll add this to the list.

**Comment by chbatey** [comment]
@tomakehurst going with the above JSON wouldn't be backward compatible as the existing format is just a list of strings. What would you prefer:
1) Break + document migration
2) Create a second object under response called something like transformer config. 
3) Catch the Jackson failure and try and parse both ways?

I had the same conundrum and now will forever add new information in its own object to make it extensible.

**Comment by tomakehurst** [comment]
Not 1) if that's at all possible.

2) if 3) isn't possible.

3) ideally. Rather than catching an exception, perhaps a custom deserialiser would do the trick though?

**Comment by chbatey** [comment]
3 it is!

**Comment by chbatey** [comment]
@tomakehurst opinion required :) Now that the transformers have state we can't share them between stubmappings. I was thinking of creating a set of transformers per stubmapping when the maping is created? And perhaps keeping global tansformers (assuming they can't have state) in a separate list.

**Comment by tomakehurst** [comment]
Hmmm...this is tricky because it's possible to new up ``Extension`` instances and pass them to ``wireMockConfig()``. Not sure how we'd (tidily) go about making copies bound to different params available to different stubs.

Thinking a solution might be to pass the parameters to ``transform(...)`` and keep backwards compatibility by adding a new superclass to ``ResponseTransformer``. Something along the lines of:

```java
public abstract class ParameterisedResponseTransformer implements Extension {

    public abstract ResponseDefinition transform(Request request, ResponseDefinition responseDefinition, FileSource files);

    public boolean applyGlobally() {
        return true;
    }
}
```

and ``ResponseTransformer`` becomes:
```java
public abstract class ResponseTransformer extends ParameterisedResponseTransformer {

    @Override
    public ResponseDefinition transform(Request request, ResponseDefinition responseDefinition, FileSource files, Parameters params) {
        return transform(request, responseDefinition, files);
    }

    public abstract ResponseDefinition transform(Request request, ResponseDefinition responseDefinition, FileSource files);
}
```
