### ISSUE TITLE
Use version ranges instead of specific depencencies version

### ISSUE THREAD

**Issue by jkubrynski** [tomakehurst/wiremock#224]
Then it won't be necessary to exclude all dependencies due to version mismatch. In Guava probably you could use range [11.0,) instead of version 18.0

**Comment by tomakehurst** [comment]
Hmmm....not a good idea IMO. To do it properly it'd be necessary to test with every combination of versions, which would get big pretty quickly. 

Planning on adding a dependency-free standalone jar at some point soon, which will alleviate this problem.

**Comment by jkubrynski** [comment]
Dependency-free will drive users to define all dependencies needed by wiremock which is not the best idea. I'm not sure you have to check all combinations - usually it's enough to check boundary versions of each dependency

**Comment by tomakehurst** [comment]
Even then, it's still a combinatorial explosion test-wise, with relatively little value added as a result. 

The stanalone jar bakes in all its dependencies under modified packages so going dependency-free just means publishing it with its own pom that doesn't also pull in its dependencies.
