### ISSUE TITLE
Using Regex For Soap Request After Record Mode

### ISSUE THREAD

**Issue by hellishheat** [tomakehurst/wiremock#227]
Hi,

I have just started using standalone Wiremock. It's great.

We use axis to make soap requests, the responses for which I want to use Wiremock. Wiremock records the mappings as follows (The '.....' is mine for abbrev.):
```xml
"request" : {
    "url" : "/axis/services/Document.PrintService",
    "method" : "POST",
    "bodyPatterns" : [ {
      "equalToXml" : "<?xml version=\"1.0\" .....   <name xsi:type=\"xsd:string\">123456</name>\n  </multiRef>\n </soapenv:Body>\n</soapenv:Envelope>"
    } 
```

My problem is that the request will not always have the exact same values, but I want the same response. In the example above (for example) the 123456 could be 654321.

In an attempt to solve this, using 'matches', I changed it to 
```xml
"request" : {
    "url" : "/axis/services/Document.PrintService",
    "method" : "POST",
    "bodyPatterns" : [ {
      "matches" : "<?xml version=\"1.0\" .....   <name xsi:type=\"xsd:string\">[0-9]{6}</name>\n  </multiRef>\n </soapenv:Body>\n</soapenv:Envelope>"
    }
```

This could in theory fix my problem but, instead I get this error:

```
{}string: return code:  500
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;/&gt;
&lt;title&gt;Error 500 Illegal/unsupported escape sequence near index 6287
```

Am I using regex correctly here?

Thanks, Declan

**Comment by Mahoney** [comment]
The entire request body in the matches field must be a valid regex - are there unescaped reserved regex characters in there? Like (,),[,],.,?  Try pasting it into a regex checker to see if it can help you with the syntax.

**Comment by hellishheat** [comment]
Thanks for the reply. I have taken your advice and tried to come up with a regex that is succint and valid. I can't seem to get it to work. Even with the most basic regex pattern:
```json
"request" : {
    "url" : "/axis/services/Document.PrintService",
    "method" : "POST",
	"bodyPatterns": [ {
		"matches": "\bsavePackage\b"
	} ]
```

I know that the request in question will always contain this text (savePackage). But when I include this Mapping, I get a 404. I am tearing my limited hair out over this. Any ideas?

**Comment by hellishheat** [comment]
FYI. I've also tried: 
```json
"request" : {
    "url" : "/axis/services/Document.PrintService",
    "method" : "POST",
    "bodyPatterns": [ {
        "matches": "savePackage"
    } ]
```
And many many other things. I feel I'm missing something fundamental to stubbing soap/xml

**Comment by tomakehurst** [comment]
Is this any good?
```
"bodyPatterns": [ {
        "contains": "savePackage"
    } ]
```

**Comment by hellishheat** [comment]
Hi, this does work and, through a mixture of these patterns, I can achieve my goal.

e.g..

```json
 {"matchesXPath" : "//*[local-name()='savePackage']"},
		  {"contains" : "123456789"}
```
Thanks for your help. I think I need a crash course in XPath, that will help to make wiremock a very powerful tool for my needs. Thanks.
