### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by ebenoist** [tomakehurst/wiremock#23]
It doesn't seem that wiremock supports [Basic Authentication](http://en.wikipedia.org/wiki/Basic_access_authentication). If that is true, is there any plans for support? Should I start mucking around with the code?

Currently I get a 400 from the Wiremock server when I execute:

```
String encoding = Base64.encodeBase64String((userName + ":" + password).getBytes());
DefaultHttpClient httpClient = new DefaultHttpClient();
HttpPost httpPost = new HttpPost(protocol + "://" + host + ":" + port + path + merchantId + "/credentials");
httpPost.setHeader("Authorization", "Basic " + encoding);
try {
    HttpResponse response = httpClient.execute(httpPost);
```

**Comment by puce77** [comment]
+1
I'm also looking for a way to test HTTP(S) Basic Authentication for a Jersey Client:

```java
  ClientConfig clientConfig = new ClientConfig();
  clientConfig.register(HttpAuthenticationFeature.basic(someUserName, somePassword));
  Client client = ClientBuilder.newClient(clientConfig);
```

**Comment by tomakehurst** [comment]
If all you're wanting to do is check that the client sends an appropriate basic auth header, you could just verify the header directly e.g.

```java
verify(getRequestedFor(urlEqualTo("/your-url"))
  withHeader("Authorization", equalTo("Basic <base64 encoded user:pass>"))
```

**Comment by jethroborsje** [comment]
It would be nice if there was a more convenient way to do the authorization header verification.

**Comment by gquintana** [comment]
Ideally, it should support auth scheme negociation as described in §2 Basic Authentication with the API of http://www.baeldung.com/httpclient-4-basic-authentication
Even if in the end, it can only mock basic auth

**Comment by tomakehurst** [comment]
I'd certainly like to make this easier, although it's possible to do pre-emptive now in the 2.0 beta (and from there, mock out the whole interaction).

**Comment by mrdanpsmith** [comment]
I was able to add a test for basic auth using a custom transformer.

Has any thought been given to including some transformers with Wiremock?

(Or should someone start an extensions project?)

**Comment by tomakehurst** [comment]
@mrdanpsmith - I presume you mean a negotiated auth handshake via a transformer?

If so, it'd be great to get that as a PR. I like the idea of having it as an extension but in the core codebase so it can be activated just when needed.

**Comment by mrdanpsmith** [comment]
@tomakehurst - Yes, that is what I'm talking about.

It's good to know that you would consider adding that to the main project.

I'll see if I can find some time to put a PR together.

**Comment by tomakehurst** [comment]
Yes, there's pre-emptive basic auth in 2.x already, but not negotiated.

And yes, 1.x is frozen now.

**Comment by tomakehurst** [comment]
Closing this as it's inactive. I'd still be happy to accept an extension supporting negotiated auth.
