### ISSUE TITLE
Support for Jackson, Gson, JAXB

### ISSUE THREAD

**Issue by RobWin** [tomakehurst/wiremock#237]
Hello,

it would be great, if I could send a Java Object as a response body. 

For example:

```
givenThat(put(urlEqualTo("/test")).willReturn(
                aResponse()
 .withHeader(HttpHeaders.CONTENT_TYPE, "application/json")
                        .withBody(new TestResponse())
                        .withStatus(200)));
```

In this example WireMock could serialize the object to JSON since the responsecontent-type is set to "application/json". It will first try to use Jackson if found in classpath and if not Gson will be used. If you change the content-type to "application/xml" WireMock could serialize to XML using JAXB. If no content-type is defined REST Assured cloud to serialize in the following order:

* Json using Jackson
* Json using Gson
* XML using JAXB

Kind regards,

Robert Winkler

**Comment by tomakehurst** [comment]
I think this is a good thing to have, but again probably not as a core feature, as there are many possible serialisation libraries folks might want to use.

I generally find it's pretty trivial to set up a static method somewhere in my projects to serialise where I need it e.g.
``.withBody(toJson(new InterestingThing()))``

**Comment by RobWin** [comment]
Good point. I will solve it with a static method.
Thx.
