### ISSUE TITLE
Does Wiremock Playback When In Record

### ISSUE THREAD

**Issue by hellishheat** [tomakehurst/wiremock#238]
From the Docs:
 "
    Note

    The recorder will ignore any request matching one it has already captured.
"
It's not clear if that means :

    The request will be routed to the 3rd party service and a live response will be returned. Or,
    The saved response will be returned and the 3rd party service will not be bothered in that case.

Hope I'm not misusing and/or abusing the issues section. Can somebody with the know-how answer my Question around this on Stackoverflow please: 

http://stackoverflow.com/questions/28645588/wiremock-does-wiremock-playback-when-in-record

Thanks

**Comment by tomakehurst** [comment]
Answered on stackoverflow.
