### ISSUE TITLE
wiremock does not work in a different thread

### ISSUE THREAD

**Issue by sathish316** [tomakehurst/wiremock#239]
I'm writing an integration test on a dropwizard resource, which uses Redis workers to process a record asynchronously in a different thread. The resource simply enqueues a message in Redis queue which is processed by a different worker thread. This processing consists of an external API call which i'm trying to mock using wiremock.

Wiremock's mock API works in unit test, resource method, but does not work in worker thread.
However, if i try to access API in both resource method and worker thread, it works. I've tried using both default jersey client provided by dropwizard and Retrofit.

Why does it not work if i only call it from a different thread?
Why does it work if i call in both resource method and worker thread? Is there any initialization which i can invoke in test method itself?

**Comment by tomakehurst** [comment]
There shouldn't be any problem running WireMock on a different thread. I suggest you post some details of your project (source code, configuration, error messages) to the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user) to see if anyone has experienced a similar problem to yours.

**Comment by sathish316** [comment]
wiremock stub was getting reset in test teardown before worker thread could process it. Adding wait using Thread.sleep worked.
