### ISSUE TITLE
Compile Failure on newer commits

### ISSUE THREAD

**Issue by zontreck** [tomakehurst/wiremock#241]
I've pulled the latest code and it seems that it now fails to compile. Is there a new dependency?

If it makes any difference I tried building this on OS X.

wiremock/src/main/java/com/github/tomakehurst/wiremock/common/FatalStartupException.java:33: cannot find symbol
symbol  : constructor RuntimeException(java.lang.String,java.lang.Throwable,boolean,boolean)
location: class java.lang.RuntimeException
        super(message, cause, enableSuppression, writableStackTrace);
        ^
1 error
:compileJava FAILED

**Comment by tomakehurst** [comment]
Seems to compile fine on jdk 7 and 8 in Travis. Which jdk are you using?

**Comment by zontreck** [comment]
Ah i updated and now it builds.. just stops on signArchives..

**Comment by tomakehurst** [comment]
If you do ``./gradlew jar jarAll`` it should build both JARs without signing them (if I remember correctly)
