### ISSUE TITLE
Issue with  playback after trying to play the recorded data

### ISSUE THREAD

**Issue by mytigerlion** [tomakehurst/wiremock#242]
First of all this is a great library..thanks a lot ...find it very useful
I was trying to use the record and playback using the instructions.. i can see that when i record using wiremock as proxy it creates two directories mappings and __files in current direcotry and mappins has the stubs and files has the body of response...
for eg: request to localhost:8080/foo/1 will have two files one in mapping n one in __files
Now i try to playback the data removing all proxy arguments and i get error saying cant find 
__files/foo/1

when it records the file format is mappings/foo.1.1234.json and body.foo.1 in __files

but during playback it tries to look into the tree dir structure....
is there a way to tell wiremock to use the same format for lookup that it used for recording...

ideally i want to copy all these recorded file for my integration tests..where the wiremock is loaded with this recorded data....

**Comment by tomakehurst** [comment]
From what you've described it should be working. I suggest you post the details of what you tried to do (i.e. your full CLI session) on the mailing list to see if anyone can spot the problem.

**Comment by halfer** [comment]
This is a very old issue report, can it be closed? :)

**Comment by tomakehurst** [comment]
I reckon so :-)
