### ISSUE TITLE
Capability to re-write actual request/response

### ISSUE THREAD

**Issue by sailtwist** [tomakehurst/wiremock#243]
Pardon my ignorance if this has already been addressed - I am looking for a way to rewrite actual requests and responses as they are proxied via wiremock.  Is this possible w/ wiremock given the new extension point capability?

Thanks in advance for your answer.
/veli
BTW - this tool is AMAZING!!

**Comment by tomakehurst** [comment]
Unfortunately you can only replace the responses to specific requests, rather than using the original request or response as an input. The response transformer extension isn't any help either because it allows you to transform the response definition (which simply says "go and fetch the actual response from here"), rather than the actual response.

**Comment by tomakehurst** [comment]
Agree this might be a useful additional extension though.

**Comment by sailtwist** [comment]
Where do I vote for such elegant feature? :-)

**Comment by npryce** [comment]
I've also hit this problem.  I need a way to adjust headers coming back from the proxy to (for example) reduce cache expiry times.  We found the hard way that this doesn't work, so would also like to see this feature.

**Comment by tomakehurst** [comment]
I've had similar feedback to this a few times now so clearly we should add this.

I'm really struggling to time-wise to do anything more than merge PRs at the moment. Would you consider creating one?

**Comment by npryce** [comment]
I'll look into it.

**Comment by tomakehurst** [comment]
I've just pushed 2.0.3-beta to Maven central, which includes the ability to transform ``Response``s in addition to ``ResponseDefinition``s. You can also now supply per-stub parameters in both cases.
