### ISSUE TITLE
Multiple responses for the same URL?

### ISSUE THREAD

**Issue by Qunit** [tomakehurst/wiremock#245]
I'm having trouble specifying multiple responses for the same URL. The responses should vary depending on the contents of the request. For example:

        stub.stubFor(
                post(urlMatching(URL_DOMEIN))
                   .withRequestBody(matchingXPath("//*[local-name() = 'Action'][.='" + ACTION_A +"']"))
                        .willReturn(
                                aResponse()
                                        .withHeader("Content-type", "text/xml; charset=UTF-8")
                                        .withBody("myresponse_1")));

        stub.stubFor(
                post(urlMatching(URL_DOMEIN))
                .withRequestBody(matchingXPath("//*[local-name() = 'Action'][.='" + ACTION_B + "']"))
                        .withRequestBody(matchingXPath(ADDITIONAL_XPATH_STATEMENT))
                        .willReturn(
                                aResponse()
                                        .withHeader("Content-type", "text/xml; charset=UTF-8")
                                        .withBody("myresponse_2")));

However it seems it will only remember the "last" stub. Is this expected behaviour?

**Comment by tomakehurst** [comment]
Nope, they should be distinct.

Might be worth calling ``listAllStubMappings()`` after you've created the stubs to check that they're actually different, and turn verbose logging on so you can check what requests it's actually seeing.

**Comment by Qunit** [comment]
In the actual code (not the examples) I was reusing the same MappingBuilder for each subsequent stub action. Works as expected now. Thanks!

**Comment by tomakehurst** [comment]
Glad you got it working!

**Comment by bhavana-gandham** [comment]
Hi Qunit 
I see same problem now.Did you mean you had customised MappingBuilder ?Can you elaborate on the solution pls.

**Comment by rugden** [comment]
@Qunit @bhavana-gandham please share code samples. I'm having a similar issue. how did you resolve yours?

**Comment by xlbruce** [comment]
Having same issue too.
