### ISSUE TITLE
JSON body matching - Error 404 NOT_FOUND

### ISSUE THREAD

**Issue by elibasson** [tomakehurst/wiremock#253]
from http://wiremock.org/stubbing.html i try to run the example 

{
    "request": {
        "method": "POST",
        "url": "/with/json/body",
        "bodyPatterns" : [
            { "equalToJson" : "{ \"houseNumber\": 4, \"postcode\": \"N1 1ZZ\" }", "jsonCompareMode": "LENIENT" }
        ]
    },
    "response": {
            "status": 200
    }
}

i am using with Advanced REST client for Google Chrome to run it but i am getting : Error 404 NOT_FOUND

what is the problem ? i can i fix it

**Comment by tomakehurst** [comment]
Do you mean you're getting a 404 when you try to add the stub or when you attempt to make a request that should match it?

**Comment by elibasson** [comment]
Yes

**Comment by elibasson** [comment]
Java -jar wiremock-1.54-standalone.jar

2015-03-21 17:38:30.612:INFO::Logging to STDERR via wiremock.org.mortbay.log.Std
ErrLog
 /$$      /$$ /$$                     /$$      /$$                     /$$

| $$  /$ | $$|__/                    | $$$    /$$$                    | $$

| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$

| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/

| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/

| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$

| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$

|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/


port:                         8080
enable-browser-proxying:      false
no-request-journal:           false
verbose:                      false
************************************************************************************************
{
    "request": {
        "method": "POST",
        "url": "/with/json/body",
        "bodyPatterns" : [
            { "equalToJson" : "{ \"houseNumber\": 4, \"postcode\": \"N1 1ZZ\" }", "jsonCompareMode": "LENIENT" }
        ]
    },
    "response": {
            "status": 200
    }
}

************************************************
MY : output

<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 NOT_FOUND</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /with/json/body. Reason:
<pre>    NOT_FOUND</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                


************************************************************

the problem : Error 404 NOT_FOUND

**Comment by tomakehurst** [comment]
Are you actually seeing lots of dollar symbols or is that a character set problem?

**Comment by elibasson** [comment]
This is my output :
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 NOT_FOUND</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /with/json/body. Reason:
<pre>    NOT_FOUND</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

**Comment by tomakehurst** [comment]
What is the request you are making?

Is it a POST?

Does it have a body containing the JSON in the stub?

**Comment by elibasson** [comment]
it is post 
![capture1](https://cloud.githubusercontent.com/assets/11585512/6765665/ff81a698-cff2-11e4-9852-5a00279c8381.JPG)

**Comment by elibasson** [comment]
see the attached file
![capture1](https://cloud.githubusercontent.com/assets/11585512/6765671/3e6dc378-cff3-11e4-83da-01dc03f08c11.JPG)
![capture2](https://cloud.githubusercontent.com/assets/11585512/6765673/4205fc62-cff3-11e4-9de4-29f53ed0c5a7.JPG)

**Comment by tomakehurst** [comment]
Looks like you're trying to post the stub definition to the URL you're stubbing.

You need to post the stub definition to http://localhost:8080/__admin/mappings/new

**Comment by elibasson** [comment]
If I understood Should I put the file in the folder under /mappings/new ?

**Comment by tomakehurst** [comment]
No, POST the stub definition to the URL I gave you.

Also, I suggest giving the docs another read, particularly the getting started and stubbing sections. All this is explained pretty exhaustively.

**Comment by elibasson** [comment]
i will try it

**Comment by elibasson** [comment]
Now I get code 201 but the answer is: Response does not contain any data.

I expect to get an answer of "Hello world- Eli Basson!"

I added pictures for this

Where there is a mistake
![1 my file](https://cloud.githubusercontent.com/assets/11585512/6765952/860d8a16-cffc-11e4-897c-053afea39827.JPG)
![after run - no data](https://cloud.githubusercontent.com/assets/11585512/6765953/8a4b5e0a-cffc-11e4-929b-f464ea3beda5.JPG)

**Comment by elibasson** [comment]
how can i fix my mistake as you can see in the new attached file

**Comment by tomakehurst** [comment]
The 201 means the stub mapping has been created successfully. Now you can post a request to http://localhost:8080/with/json/body.

**Comment by elibasson** [comment]
I get a 404 error and it does not work as you will see in pictures


![1](https://cloud.githubusercontent.com/assets/11585512/6766103/cded4aba-d001-11e4-8ba7-485f185d6a94.JPG)
![2](https://cloud.githubusercontent.com/assets/11585512/6766104/d1aae0b8-d001-11e4-8cd5-3a3d30611cc0.JPG)

**Comment by elibasson** [comment]
I returned to the beginning and it does not work as expected

**Comment by tomakehurst** [comment]
I normally try not to respond to questions with RTFM type answers, but in this instance it really seems like you haven't fully understood the concept. 

Can I suggest you give the docs a thorough read before we take this thread any further? Once you've got the right mental model the solution you're looking for should become obvious.

**Comment by elibasson** [comment]
thanks i will read it again and try it
