### ISSUE TITLE
RegEX  - For any number with equalToJson

### ISSUE THREAD

**Issue by elibasson** [tomakehurst/wiremock#254]
Hi , 
I have json file and I have parameter with different number - as you can see in the attached file
Status since parameter could be any number how I can use it with any number 
the number : 1427291960 could be any number

See the attached file

![capture](https://cloud.githubusercontent.com/assets/11649968/6827834/bb8b7284-d312-11e4-9fff-186fe46bd31c.JPG)

**Comment by Mahoney** [comment]
Please could you ask questions on the mailing list (https://groups.google.com/forum/#!forum/wiremock-user) rather than raising them as issues. Thanks.
