### ISSUE TITLE
MatchesXPath does not match unamed namespaces

### ISSUE THREAD

**Issue by davidnewcomb** [tomakehurst/wiremock#259]
In com.github.tomakehurst.wiremock.matching.ValuePatternTest (.java) add the following test:

```
@Test
public void doesMatchStuff() {
	valuePattern.setMatchesXPath("//Request/Stuff");
	assertTrue("Stuff", valuePattern.isMatchFor("<ROOT\n    xmlns:a=\"http://example.com/stuff\">\n    <Request>\n        <Stuff/>\n   </Request>\n </ROOT>\n"));
	assertTrue("Stuff", valuePattern.isMatchFor("<ROOT\n    xmlns=\"http://example.com/stuff\">\n    <Request>\n        <Stuff/>\n   </Request>\n </ROOT>\n"));
}
```
The first assertTrue matches but the second one fails. The only difference is the ":a" namespace.
Lots of xml documents start with xmlns="http://exa... and so none of my playbacks are working.

Trying to tweak //Request/Stuff to //*:Request/Stuff or //*[local-name()='Request']/Stuff don't seem to be able to match either.

I think https://github.com/tomakehurst/wiremock/pull/255 addresses this issue. Any chance you could pull this into the main source?

**Comment by tomakehurst** [comment]
Yeah, I'm planning to merge #255. Just haven't had time yet.
