### ISSUE TITLE
Json Body Matching fail because json-path is very old

### ISSUE THREAD

**Issue by mariuszs** [tomakehurst/wiremock#261]
This code dosent work with wiremock (json-path 0.9.1) and works fine with latest json-path 2.0.0

    private final String json = "{\"foo\":\"Foo\",\"price\":8.95}";

    @Test
    public void shouldMatch() throws Exception {

        Object object = JsonPath.read(json, "$.[?(@.price == 8.95)]");

        assertThat(object).isNotNull();
    }

Why this is important? Because we cannot use JSON body matching for request like this:

    {
      "request": {
        "method": "POST",
        "url": "/with/json/body",
        "bodyPatterns" : [
          { "matchesJsonPath" : "$.[?(@.price == 8.95)]" }
        ]
      },
      "response": {
        "status": 200
      }
    }

**Comment by jkubrynski** [comment]
Any progress with this issue? It's almost impossible to use wiremock with other technologies which use json-path younger than 2 years.

**Comment by mariuszs** [comment]
+1

**Comment by tomakehurst** [comment]
It'll get upgraded in the next major version (where there'll be a few breaking changes). Until then is using the standalone JAR not an option for you?

**Comment by jkubrynski** [comment]
@tomakehurst Any timeline for that? Standalone JAR is a problem - maybe you'll release 2.0.RC or even snapshot into maven central?

**Comment by venkata-kari** [comment]
:+1:

**Comment by venkata-kari** [comment]
+1

**Comment by marcingrzejszczak** [comment]
@tomakehurst - @jkubrynski has a point - can you release a RC?

**Comment by tomakehurst** [comment]
Already have :-)

Admittedly I should probably publicise it a bit better.

**Comment by tomakehurst** [comment]
Check out 2.0.0-beta

**Comment by mariuszs** [comment]
Fixed, thanks
