### ISSUE TITLE
multiple matches in request body not working

### ISSUE THREAD

**Issue by forprem** [tomakehurst/wiremock#264]
I am using multiple matches in request body but it did not working, Is there any alternative for it.

I tried with XPath Matching
{
    "request": {
        "url": "/sample/v2/ws.do",
        "method": "POST",
        "bodyPatterns": [
            {
               "matchesXPath": "//*[local-name()='XMLRequest']/*[local-name()='LoginCredentials'][*[local-name()='UserID']='pmtss']"
            },
            {
               "matchesXPath": "//*[local-name()='XMLRequest'][*[local-name()='Operation']='sample']"
            }
        ]
    },
    "response": {
        "status": 200,
        "body": "Sample Response",
        "headers": {
            "Content-Type": "text/xml"
        }
    }
}

Tried with body pattern contains:
{
    "request": {
        "url": "/sample/us/v2/ws.do",
        "method": "POST",
        "bodyPatterns": [
        { 
            "contains": "<UserID>pmtss</UserID>\n<Operation>summ</Operation>" 
        }

        ]
    },
    "response": {
        "status": 200,
        "body": "<XMLResponse>Sample</XMLResponse>\n",
        "headers": {
            "Content-Type": "text/xml"
        }
    }
}

tried with matches and doesnotMatch

{
    "request": {
        "url": "/sample/v2/ws.do",
        "method": "POST",
        "bodyPatterns": [
            { "matches": "<Token>PaymentMultiple</Token>" },
            { "doesNotMatch": "<Operation>Options</Operation>" }
        ]
    },
    "response": {
        "status": 200,
        "body": "Sample" ,
        "headers": {
            "Content-Type": "text/xml"
        }
    }
}

Please let me know what has to be done for multiple request matching

**Comment by roydekleijn** [comment]
Currently I'm facing the same issue...

**Comment by tomakehurst** [comment]
Folks, to get help with this kind of thing I suggest you:
a) post questions on the mailing list, we use issues for bugs and feature requests (as per the README),
b) post the mappings, HTTP requests that aren't matching, the CLI parameters you used to start WireMock and any log messages you see

**Comment by roydekleijn** [comment]
well, this is not a question.. but a possible bug

My mapping looks like this:

"bodyPatterns": [
            { "matches": "DataRequestEnvelope" },
            { "doesNotMatch": "<DATAID>1112423.*" }
]

The request body contains a soap envelope with 'DataRequestEnvelope' and the following XML fragment: <DATAID>345678998</DATAID>

I expect the defined responseBodyFile is returned...

**Comment by tomakehurst** [comment]
If you think it's a bug could you post the full mapping, request and response? It's hard to replicate only with what you've posted so far.
