### ISSUE TITLE
Feature Request: Command to reset only the request log.

### ISSUE THREAD

**Issue by jkindwall** [tomakehurst/wiremock#266]
Currently, if I want to clear the request log, I need to send a request to /__admin/reset.  But this clears not only the request log but also any stubs I've created, meaning I need to recreate them.

I'd like a command to clear only the request log, leaving any stubs intact.  Something like /__admin/requests/reset would seem to make sense.

**Comment by tomakehurst** [comment]
Definitely a good idea. Best I can offer at the moment is to put it on the ever-growing list, or accept a PR if you're interested in submitting one (this should be very easy to add).

**Comment by chbatey** [comment]
I've raised a PR for this.
