### ISSUE TITLE
Question: Background of com.github.tomakehurst.wiremock.WireMockJUnitRuleTest.WireMockRuleFailThenPass

### ISSUE THREAD

**Issue by clboettcher** [tomakehurst/wiremock#271]
Hi Tom,

I stumbled over com.github.tomakehurst.wiremock.WireMockJUnitRuleTest.WireMockRuleFailThenPass and was wondering what was the background of this test. The @Ignore annotation says "Generates a failure to illustrate a Rule bug whereby a failed test would cause BindExceptions on subsequent (otherwise passing) tests". However, when you comment out that annotation the succeed() Test passes just fine.

I'm asking because I have a similar problem in another library where a server is started in unit tests using a @Rule which fails to release its ports when a tests fails. This causes subsequent tests to fail with a BindException.

Did you manage to identify and resolve the problem? What was it? I would be glad if you could give me some insight on this.

**Comment by tomakehurst** [comment]
Yes, I fixed the problem in commit 5097d54297bd575062121d0749cbc42bc87e18d6. It was simply that the call to reset the server wasn't in a ``finally`` block, so subsequent tests ended up in an invalid state.

This was a sloppy way to test it TBH!

**Comment by clboettcher** [comment]
Thanks for the explanation. My issue was not related.
