### ISSUE TITLE
static stubFor encourages non-threadsafe tests

### ISSUE THREAD

**Issue by Pyrolistical** [tomakehurst/wiremock#273]
If we use WireMock as described in the documentation you will end up with a non-threadsafe test.

This is caused by the static method `WireMock.stubFor(..)`.  Internally it has a `defaultInstance` of `WireMock` configured with the defaults `localhost:8080`.  This means if tests in the same JVM configure different `WireMockServer` hosts or ports, then there will be a race condition.

I propose we move the static method `WireMock.stubFor(..)` to an instance method.  This means everybody will need to manage the life-cycle of their own `WireMock`, but this will make the test threadsafe.

The current workaround is to create your own instance of `WireMock`, but instead of the nice `stubFor` or `givenThat` methods, we have to use the ugly `register` method.

**Comment by Pyrolistical** [comment]
Related to #18

**Comment by Pyrolistical** [comment]
By the way, I am not using JUnit, so the `WireMockRule` doesn't help me.

**Comment by tomakehurst** [comment]
You have another option, which is to new up a ``WireMockServer`` instance per thread and call ``stubFor()`` or ``givenThat()`` on it directly.

And there are times when you want a shared WireMock instance across threads. Thread safety is the responsibility of the caller I'm afraid :-)

**Comment by Pyrolistical** [comment]
Cool, I like the idea of a `WireMockServer` per thread.  We need to document that.

Can you give an example where you want to share a WireMock, asides from using the static `stubFor(..)`?

**Comment by tomakehurst** [comment]
On the last project I did we had a single WireMock instance running with multithreaded tests. Provided you create unique data per test case it works fine and is in many ways a more realistic test.

**Comment by Pyrolistical** [comment]
Yeah I considered that option as well. I just would rather have my tests be in their own universe. I'll have other system tests be more realistic
