### ISSUE TITLE
Play 2.3.8 with Scalatest using Wiremock

### ISSUE THREAD

**Issue by lalkhum** [tomakehurst/wiremock#274]
I recently updated my Play Scala project from play framework version 2.2.2 to 2.3.8, with
  "com.github.tomakehurst" % "wiremock" % "1.47" % "test",

From that time onwards, my unit tests which use Wiremock keeps on failing.

The error looks:

The future returned an exception of type: java.lang.RuntimeException, with message: There is no started application.

Would appreciate in case of any help/suggestions?

class BlahTest extends FunSuite
  with MockitoSugar with ScalaFutures
  with SpanSugar with BeforeAndAfter with BeforeAndAfterAll {

val wiremock = new WireMockServer(wireMockConfig().port(1234)
  .fileSource(new SingleRootFileSource("test/resources")))

override protected def beforeAll() = wiremock.start()

override protected def afterAll() = wiremock.stop()

before {
  Mockito.reset(mockLogger)
  configureFor("localhost", 1234)
  stubFor(post(urlMatching("/somepath"))
    .willReturn(aResponse()
    .withStatus(200)))
}

after {
  WireMock.reset()
}

test("Some test") {
  val f = someObject.method(param1, param2)
// This is the failure point
  whenReady(f, timeout(WiremockTimeout milliseconds)) { answer =>
    // verify
  }
}

**Comment by tomakehurst** [comment]
Please can you post questions like this to the [mailing list](https://groups.google.com/forum/m/#!forum/wiremock-user). I'm neither a scala nor a play Dev so you'll probably have more luck there.
