### ISSUE TITLE
Wiremock always looks for keystore

### ISSUE THREAD

**Issue by abhijith-prabhakar** [tomakehurst/wiremock#275]
Hi,

I have wiremock 1.0.55 and trying to bring server up on TestNG for a general use case.

``` java
@BeforeTest
    public void setUp() {
        wireMockServer = new WireMockServer(wireMockConfig().port(8080));
        wireMockServer.start();
    }
```

But getting an error

java.security.KeyStoreException: problem accessing trust storejava.io.IOException: Invalid keystore format
    at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:75)
    at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
    at wiremock.org.apache.http.conn.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:103)
    at com.github.tomakehurst.wiremock.http.HttpClientFactory.buildAllowAnythingSSLContext(HttpClientFactory.java:84)
    at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:63)
    at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.<init>(ProxyResponseRenderer.java:54)
    at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:94)

**Comment by tomakehurst** [comment]
Which JDK version are you using?

**Comment by abhijith-prabhakar** [comment]
1.7

**Comment by tomakehurst** [comment]
Oracle or openjdk?

**Comment by abhijith-prabhakar** [comment]
oracle

**Comment by tomakehurst** [comment]
Strange. It's well tested with that combination and jvm version is usually the source of problems with keystone formats.

Are you starting your vm with cli params that might affect the keystone it looks for? Or have you installed additional keystores? 

A workaround might be to generate your own keystore and point wiremock at that.

**Comment by abhijith-prabhakar** [comment]
I am using it for pretty basic use case.  I do have couple of other keystores installed on my vm.  I don't understand why I would have to generate keystore.

Can you point me to few test cases with that combination?  I will try to checkout the code and run it locally.

**Comment by tomakehurst** [comment]
There's an example of configuring your own keystore here:
http://wiremock.org/https.html

You can pass ``wireMockConfig()`` into the constructor of ``WireMockServer`` too.

**Comment by chriniko13** [comment]
Hello, I am getting the same for jdk11 (open jdk)

![image](https://user-images.githubusercontent.com/6598271/148789538-18ebbea6-f32d-45a3-b305-724da545a040.png)

wiremock version: 1.58

any ideas why?

thanks in advance.

**Comment by Daemon2017** [comment]
The same problem:

> Caused by: java.lang.AssertionError: Cannot install custom socket factory: [problem accessing trust store]
> 	at org.springframework.cloud.contract.wiremock.WireMockSpring.options(WireMockSpring.java:57)
> 	at org.springframework.cloud.contract.wiremock.WireMockConfiguration.init(WireMockConfiguration.java:96)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
> 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
> 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
> 	... 108 more
