### ISSUE TITLE
Where is import com.github.tomakehurst.wiremock.testsupport.WireMockTestClient

### ISSUE THREAD

**Issue by tshah010** [tomakehurst/wiremock#277]
All your examples use         
testClient = new WireMockTestClient(wireMockServer.port());
but there is no such class as WireMockTestClient in wiremock-1.56-standalone.jar

Where can I find it? Thanks.

**Comment by tomakehurst** [comment]
It's in the test sources, so not in the JAR:
https://github.com/tomakehurst/wiremock/blob/master/src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java

It's in the docs for the sake of example. I wouldn't recommend actually using it for your own testing as it does the bare minimum needed to test WireMock itself. In any case, it's just a wrapper around the Apache HTTP client.

**Comment by mik373** [comment]
Tom, since you don't recommend using the client, what's the best way to do the stateful stub check as shown here http://wiremock.org/stateful-behaviour.html?

**Comment by tomakehurst** [comment]
The docs just use it as an example test client. Any one of RestAssured, Jersey Client, the Apache HTTP client or others will work equally well. That doc example is primarily to demonstrate how to configure a stateful scenario.
