### ISSUE TITLE
Query Param Encoding

### ISSUE THREAD

**Issue by knoppiks** [tomakehurst/wiremock#284]
According to https://en.wikipedia.org/wiki/Percent-encoding
> In the "query" component of a URI (the part after a ? character), for example, "/" is still considered a reserved character but it normally has no reserved purpose, unless a particular URI scheme says otherwise. The character does not need to be percent-encoded when it has no reserved purpose.

I take "does not need to be" to mean: But it could.
Therefor matching an URI for both the "/" and the "%2F" could be wise.

**Comment by smaudet** [comment]
There needs to be a query parameter encoding option, or at least some publicly documented method of attacking this.

I can of course encode my match values manually in my tests, however this seems to be the wrong approach, not to mention it is clunky.

UrlEncoding and or Base64 Encoding would be appreciated.

**Comment by beeva-pablovaliente** [comment]
Is there any progress in this task???

Thanks

**Comment by tomakehurst** [comment]
This should be fixed in v2. Operators now always work on the decoded version.
