### ISSUE TITLE
proxy requests ONLY if the record does not exist inside the cache files

### ISSUE THREAD

**Issue by motherapp** [tomakehurst/wiremock#287]
hi,

I am sorry if it's a duplicate issues, but I did check all previous issues one by one.

AFAIK, currently there are two modes for the standalone server:

record mode: it would proxy all requests

replay mode: it would disable all proxies, use only the cache files for reply.

but sometimes, I only want to replay those requests already existed in the cache file, but for other requests, I don't mind to proxy out the requests to the internet.

is that possible to do that?

thanks.

**Comment by tomakehurst** [comment]
Yes, it's possible to do that. When you enable proxying, any stubs you have locally take precedence, so anything you've previously recorded will be served when the request matches, and the request will only be proxied to the target service if there is nothing matching.
