### ISSUE TITLE
`urlMatching` + withQueryParam = no match

### ISSUE THREAD

**Issue by emma-burrows** [tomakehurst/wiremock#288]
Hello, while using WireMock to test some arbitrary HTTP requests, I came across a combination that doesn't work -- Regex matching on the URL and specifying query parameters. 

This is because the `urlMatching` Regex tries to match the entire URL fragment including the query string, rather than just the path. Which means you can't do Regex matching on the path and also specify the query parameters using `withQueryParams`. 

I suppose the solution would be to have a new `urlPathMatching` which just tries to match the fragment between the host + port and the query string in the same way `urlPathEqualTo` does and exact match (in fact, it took me a long time to notice that the code example in the documentation was using `urlPathEqualTo` and not `urlEqualTo`!).

Anyway, I have illustrated this with the following Scala Spec test and thought I would submit it to your backlog since I couldn't find a similar issue:

```scala
class TestSpec extends Specification {
  val wireMockServer = new WireMockServer(wireMockConfig().port(8080))
  wireMockServer.start()
  WireMock.configureFor("localhost", 8080)

  "WireMock" should {
    "- match exact path and a parameter" in {
      stubFor(get(urlPathEqualTo("/my/resource"))
              .withQueryParam("foo", WireMock.containing("bar"))
              .willReturn(
                  aResponse()
                  .withStatus(200)))

      val request = url(s"http://localhost:8080/my/resource").GET <<? Map("foo" -> "bar")
      val responseFuture = Http(request)

      val response = Await.result(responseFuture, Duration(100, TimeUnit.MILLISECONDS))
      response.getStatusCode mustEqual 200
    }

    // Doesn't work because it tries to match the entire URL including the query parameter
    "- match Regex path and a parameter" in {
      stubFor(get(urlMatching("/mynew/resource"))
              .withQueryParam("foo", WireMock.containing("bar"))
              .willReturn(
                  aResponse()
                  .withStatus(200)))

      val request = url(s"http://localhost:8080/mynew/resource").GET <<? Map("foo" -> "bar")
      val responseFuture = Http(request)

      val response = Await.result(responseFuture, Duration(100, TimeUnit.MILLISECONDS))
      response.getStatusCode mustEqual 200
    }
  }
}
```

**Comment by tomakehurst** [comment]
Hi,

Thanks for pointing this out. Agree it'd be nice to be able to use path regexes with query params.

I'm happy to accept this into the backlog, although I'll warn that it's pretty large now and I'm not getting much (any!) time to work on it.

Happy to accept this as a PR of course, if you feel like creating one.

Tom

**Comment by emma-burrows** [comment]
Haha, I know how it goes. I'll see about a PR but can't guarantee I'll get there before you do!

Emma

**Comment by tomakehurst** [comment]
At the rate I'm going at the moment, hell will freeze over before I get half the stuff I want done, so probably not too much risk of that :-)

**Comment by emma-burrows** [comment]
PR achieved as you can see. Hope it's suitable!

**Comment by tomakehurst** [comment]
Cool, thanks for this. I'll try and find a moment to review it this afternoon.
