### ISSUE TITLE
is match, but method GET is not

### ISSUE THREAD

**Issue by karthikv233** [tomakehurst/wiremock#289]
Hi All,

new to using wiremock. I have a API (eg : xyz/v1/abc/) which I have to proxy to a different server.  I am using JSON approach

My question is 
the java code calls first get for this API and then POST
But when the post is called, i see the following in wiremock logs 
2015-07-16 20:21:32.932 URL /xyz/v1/abc is match, but method GET is not

Can i know how to solve ??

**Comment by tomakehurst** [comment]
As per the README, please can you post this on the mailing list.
