### ISSUE TITLE
javax.servlet jar part of Wiremock Jar. Why? why? why?

### ISSUE THREAD

**Issue by ashish-sharma09** [tomakehurst/wiremock#291]
I am trying to use Wiremock with Spring boot and it conflicts with javax.servlet versions spring boot needs. Why Javax.servlet  is part of Wiremock jar instead of a dependency to allow me to exclude the same.

**Comment by ashish-sharma09** [comment]
Did you get a chance to look into it?

**Comment by tomakehurst** [comment]
Nope

**Comment by ashish-sharma09** [comment]
It would probably be more respectful and appropriate to close the ticket with reasoning rather than just "Nope". By closing the ticket are you also concluding that Wiremock is not compatible with Spring boot?

**Comment by tomakehurst** [comment]
It would definitely be more respectful for you to a) read the docs, b) read the README, c) proof read your own messages a bit more carefully before sending them to avoid sounding like you're hectoring.
