### ISSUE TITLE
Consider downgrading to Jetty 9.2

### ISSUE THREAD

**Issue by jkubrynski** [tomakehurst/wiremock#296]
Jetty 9.3 is known to cause problems with Jersey and it requires Java 8, which causes many problems with projects depending on WireMock

**Comment by marcingrzejszczak** [comment]
This includes this ticket: https://java.net/jira/browse/JERSEY-2940

**Comment by tomakehurst** [comment]
Java 7 went EOL 5 months ago,  so deprecating support for it doesn't seem unreasonable at this point. Keeping it just means having to stick with more obsolete libs e.g. Jetty.

Can you elaborate why Jersey compatibility is a concern (given that it's always possible to use the standalone jar as a dependency if want to avoid wiremock imposing its version on your classpath)? 

Also it looks like they're working on fixing it. I'd be surprised if they remained incompatible for long.

**Comment by jkubrynski** [comment]
Java 7 is EOL, but there is still a lot of projects which use it. 

The problem with Jersey is that if you use Jersey in your application it gets break down in tests due to wiremock dependency. Which means wiremock 2.0 doesn't work in projects using Jersey.

**Comment by tomakehurst** [comment]
That's true, but if everyone took that line it'd have to be supported in perpetuity. Someone has to be first (or at least not last) to drop support. I'm guessing you have a problem with it because you'd like to keep accurest at JDK 7? Is there a specific reason you need to do this?

I'm still not clear why using the standalone dependency isn't a solution to the Jetty/Jersey problem. Have you found this doesn't work for you?

**Comment by marcingrzejszczak** [comment]
@tomakehurst in micro-infra-spring we're starting in memory zookeeper with in memory wiremocks that we feed with stubs downloaded from nexus. We need that to be available at runtime.

**Comment by jkubrynski** [comment]
There are some people using accurest with jdk 7. We dont want to drop
compatibility for now.

I'm not sure what you mean with standalone jar. Usually you have wiremock
in your dependencies, which causes using jetty 9.3. In fact we re even not
able to exclude jetty-server,  as wiremock uses classes introduced in 9.3.

**Comment by tomakehurst** [comment]
So what criteria would you use to decide when it's time to drop support for a JDK, if not EOL?

I mean adding the standalone classifier to your wiremock dependency, then excluding all its transitive dependencies as documented on the site. This will get easier shortly as I'm planning to start releasing the standalone version under a different artifact ID with a minimal POM.

I have just noticed that the new Jetty dependencies aren't shaded (as they changed the package structure between 6 and 9). I'll fix that in 2.0.1, then you should be able to use standalone alongside other Jetty versions.

**Comment by jkubrynski** [comment]
It depends on the number of users on JDK7. If 99% of wiremock users will use JDK7 then dropping the access wouldn't be an option. I think we should assume < 10% is OK to drop support. We'll think about creating separate accurest version for JDK7 just to be able to track downloads. When can we expect 2.0.1?

**Comment by tomakehurst** [comment]
I'll try and push 2.0.1 with that fix sometime today.

< 10% seems pretty limiting. Could be an awfully long time before we get below that number. Also, I'm not sure how to get at that data, other than by straw polling people on the mailing list, which doesn't usually elicit much of a response. I'll put it out there and in this instance and see what kind of feedback I get, but I'm not sure how conclusive it'll be either way.

**Comment by jkubrynski** [comment]
@tomakehurst The question is if you want to loose eg 20% of your users due to JDK8 requirement?

As I said - another artifact with JDK7 compatibility will allow us to track unique downloads

**Comment by marcingrzejszczak** [comment]
@tomakehurst - maybe you need some help with 2.0.1? We can help you if you want to.

**Comment by tomakehurst** [comment]
I'm struggling to get Gradle to do what I want it to. If you know how to configure multiple Maven repo publish targets with different artifact IDs that'd be hugely helpful.

**Comment by marcingrzejszczak** [comment]
@tomakehurst - can you point to the branch? we'll check it out :)

**Comment by tomakehurst** [comment]
It's all in my workspace at the moment. I'll clean up what I have and push it.

To give some background:
* Currently the standalone JAR is build by the ant JarJar plugin and added to the same artifact as the thin JAR, but with a classifier.
* The JarJar plugin's shading is broken and I can't seem to shade out Jetty. Also, it's old and the Shadow plugin is generally better at this so I'd like to switch to that.
* Also (as I mentioned) I'd like to put the standalone JAR into a separate artifact so that it can have its own POM with most of the dependencies removed.

I've got the basic Shadow JAR bit working, but that's about it.

**Comment by tomakehurst** [comment]
I've pushed that now

**Comment by marcingrzejszczak** [comment]
OK I'm there by the computer - maybe let's move to Gitter  https://gitter.im/marcingrzejszczak/wiremock_beta and chat over there?

**Comment by marcingrzejszczak** [comment]
As you said when I ran `shadowJar` the output jar has the relocated packages so in general it's working exactly as you wanted it to work right?

Now you would like to create separate jar tasks? One for the standalone and the other for the standard wiremock?

In boot-microservice we are having two separate poms created for two different artifacts using maven-publish plugin: https://github.com/4finance/boot-microservice/blob/master/gradle/release.gradle#L30

**Comment by tomakehurst** [comment]
Apologies, not been able to get near a keyboard this evening.

Yes, the ``shadowJar`` task is working pretty much correctly, except that I'd like the resulting JAR to have a different name and be published as its own artifact.

Thanks for the pointer to your Gradle project, I'll take a look.

**Comment by tomakehurst** [comment]
OK, copying and tweaking your example got me pretty close. Main problem is that I'm getting a default (i.e. no deps) POM for the thin JAR too. Any idea how to copy the project's dependencies into that one?

**Comment by szpak** [comment]
Have you removed that line?
https://github.com/4finance/boot-microservice/blob/master/gradle/release.gradle#L50

It is needed only for end applications which don't need to have declared dependencies.

If it is not a case please push your changes to a separate branch to take a look at them.

**Comment by tomakehurst** [comment]
Yes, in fact I had to remove that to make it build at all.

**Comment by tomakehurst** [comment]
I've pushed that to the beta branch if you'd like to take a look.

**Comment by szpak** [comment]
IT should be fixed by #298.
