### ISSUE TITLE
Creating Wiremock rules on-the-fly

### ISSUE THREAD

**Issue by cajunesque** [tomakehurst/wiremock#297]
Hi Tom,

Loving wiremock. I have self-served my way thru docs and done quite well with it, but now that I am headed to the next level, I need some ideas. I am "Accessing the stubbing and verification DSL from the rule", and quite a few of them (each wiremock rule extended by my own VirtualLMSservice class with stubs passed to it) as per your docs:
@Rule
public VirtualLMSservice service1 = new VirtualLMSservice(8081, stub1, stub2 );
@Rule
public VirtualLMSservice service2 = new VirtualLMSservice(8082, stub1, stub3);
... one hundred more
and running tests on this "farm" of LMS services, testing throttling, retries, aggregation, etc on their results.

Due to the amount of wiremocks I must create, and the fact that I will create them from data in a database, I need something more like this

@Rule
public VirtualLMSservice[] services;     -or-

@Rule
public Array < VirtualLMSservice >;

Is there any way to do this or at least approximate it? 

Thanks

Mark

**Comment by tomakehurst** [comment]
It sounds like writing your own JUnit rule that wraps a collection of ``WireMockRule``s would make sense. They're pretty easy to write - suggest looking at JUnit's ``ExternalResource`` class as a base.

**Comment by cajunesque** [comment]
Jeez that was fast!
So now I am taking a look at External Resource and it doesnt look so easy to me. (It's still early in the US, and coffee has not kicked in). This is an example I found...
  @Rule
  public ExternalResource resource= new ExternalResource() {
      @Override
      protected void before() throws Throwable {
          myServer.connect();
         };

      @Override
      protected void after() {
          myServer.disconnect();
         };
     };

  @Test
  public void testFoo() {
      new Client().run(myServer);
     }
 }

**Comment by tomakehurst** [comment]
You caught me during lunch :-)

So, the simple way to do it would be something along these lines (no guarantees this will compile!):

```java
private List<WireMockServer> servers;

protected void before() {
  servers = new ArrayList<>();
  // Configure your servers and add them to the list
  for (WireMockServer server: servers) {
    server.start();
  }
}

protected void after() {
  for (WireMockServer server: servers) {
    server.stop();
  }
}

//Some kind of accessor for the stubbing interfaces
public Stubbing getStubbingFor(int index) {
  return servers.get(index);
}
```

This might be a bit slow as you'll be starting the servers sequentially. Pushing the ``server.start()`` calls onto into a thread pool executor would help there.

**Comment by cajunesque** [comment]
I'll give this a try. Don't close this yet! I think this kind of extension to wiremock will be helpful, and I want to post a working example.

**Comment by cajunesque** [comment]
Is this all meant to be wrapped in a 
@Rule
public ExternalResource resource= new ExternalResource() {
...
}
?

**Comment by cajunesque** [comment]
What I have pasted below compiles, but how do I use it in my test class? Something like this?
@Rule(name="VirtualServerFarm")   


public class VirtualLMSServerFarm extends ExternalResource {

        private List<VirtualLMS> virtualLMSes;

        public VirtualLMSServerFarm() {
            virtualLMSes = new ArrayList<VirtualLMS>();
            // read all the outcomesURLs from data
            // create a new VirtualLMS for each
        }

        @Override
        protected void before() throws Throwable {
            for (VirtualLMS virtualLMS: virtualLMSes) {
                virtualLMS.start();
            }
            // for many of these, will take a long time
            // push onto thread pool?
        }

        @Override
        protected void after() {
            for (VirtualLMS virtualLMS: virtualLMSes) {
                virtualLMS.stop();
            }
        }

    }

**Comment by tomakehurst** [comment]
```java
@Rule
public VirtualLMSServerFarm farm = new VirtualLMSServerFarm();
```

**Comment by cajunesque** [comment]
Testing this now. will let you know soon.
