### ISSUE TITLE
Unable to set Transfer-Encoding on response

### ISSUE THREAD

**Issue by matihost** [tomakehurst/wiremock#300]
Wiremock 1.57

Mocking with:

> WireMockServer server = new WireMockServer(wireMockConfig().port(port));server.stubFor(post(urlEqualTo("/test11/post/value?q1=v1&q2=v2")).willReturn(aResponse().withHeader("Transfer-Encoding", "gzip").withHeader("Sample Header Key", "Sample Header Value").withBody("Sample Body")));

Added listener  via
server.addMockServiceRequestListener(...) claims that Response object is:

> Response [status=200, body=[83, 97, 109, 112, 108, 101, 32, 66, 111, 100, 121], headers=HttpHeaders: Transfer-Encoding: [gzip]
> Sample Header Key: [Sample Header Value]
> , configured=true, fault=null, fromProxy=false]

but Transfer-Encoding is not returned.

I would also try to test cases when Transfer-Encoding doesn;t match the payload content to test how app behaves.

**Comment by tomakehurst** [comment]
I'd guess that's Jetty overriding it. Have you tried the 2.0.2-beta version? Jetty is upgraded by 3 versions, so you might not see that behaviour.
