### ISSUE TITLE
Multipart form mock

### ISSUE THREAD

**Issue by shankarRaman** [tomakehurst/wiremock#301]
Hi Tom,
I'd like to mock a multipart form request using wiremock. I am running wiremock as a standalone process. Where I am getting lost, is trying to make the request generic using JSONCompareMode, however I am not having much of a luck. Is it possible to mock mulitpart form requests?
Here's a sample request
 "request" : {
    "url" : "/some-end-point",
    "method" : "POST",
    "bodyPatterns" : [ {
      "equalTo" : "--d62b94e3-c5ae-4b22-a0af-3097bb69e635\r\nContent-Disposition: form-data; name=\"item\"; filename=\"item.json\"\r\nContent-Type: application/json\r\nContent-Length: 940\r\nContent-Transfer-Encoding: binary\r\n\r\n{\"key1\":\"value1\",\"key2\":\"value2\"}\r\n--d62b94e3-c5ae-4b22-a0af-3097bb69e635--\r\n"
    } ]
  }

**Comment by tomakehurst** [comment]
Please can you re-post this on the mailing list. I prefer to keep issues for actual bugs or feature requests.
