### ISSUE TITLE
HttpHeader doesn't override hashcode and equals

### ISSUE THREAD

**Issue by adrianmkng** [tomakehurst/wiremock#315]
The StubMapping object will never be equal if you add headers to the response because the HttpHeaders are using default hashcode and equals.

**Comment by tomakehurst** [comment]
Can you elaborate on the problem this is causing you?

**Comment by adrianmkng** [comment]
I'm building a web ui so that priming and viewing the primes can be done through that. I was just trying to verify the app's behaviour by sending through prime and using the HttpAdminClient to get the StubMappings back to verify my prime actually worked. Unfortunately the test keeps failing because the StubMapping created from the MappingBuilder doesn't equal the StubMapping I receive back from the HttpAdminClient.

**Comment by tomakehurst** [comment]
I'm happy to merge a PR adding these if you want to raise one

**Comment by adrianmkng** [comment]
Will do. Thanks!

**Comment by tomakehurst** [comment]
Just be sure to raise it against the 2.0-beta branch!

**Comment by adrianmkng** [comment]
Just created the pull request #316
