### ISSUE TITLE
verify responses

### ISSUE THREAD

**Issue by mbjelac** [tomakehurst/wiremock#317]
verifying responses in addition to verifying requests would be useful in integration test setups where we are testing both a client and a server (for example, when testing a http-based communication library).

**Comment by tomakehurst** [comment]
Could you elaborate your use case a bit? What underlying problem would this solve?

**Comment by mbjelac** [comment]
this would simplify test fixtures.
in the above case of testing the communication lib, there is a client-side and a server-side component.
currently, the client-side component is tested in one test with WireMock, while the server-side component is tested a separate test with a http client.

in actual usage, the two lib components actually talk to one another, so this could be set up in a single integration test with both the client-side and the server-side lib components.

for testing a feature which requires stuff to be put in both the request and response (headers, for example), the test would consist of:

1. set up client-side, pointing at port X
2. set up server-side, listening at port Y
3. set up WireMock, proxying from X to Y
4. send request with lib
5. verify request stuff
6. verify response stuff

**Comment by tomakehurst** [comment]
Ah, so you're talking specifically about when you're using WireMock as a proxy, so you don't know in advance what response you'll get?

**Comment by mbjelac** [comment]
yes, that's right. the scenario is that both the client and the server are part of the SUT.

**Comment by tomakehurst** [comment]
It's an interesting idea, but I'm not convinced this is good testing practice. I think the principle of keeping test cases focussed on a single thing (and certainly a single system) is a good one. Although it might result in a bit more test code, separating the tests for application vs. its dependency is likely to make for a more manageable test suite over time.

Also, WireMock was intended for testing APIs. A feature like this seems outside of its scope.

**Comment by mbjelac** [comment]
too bad... ok, closing the issue.
