### ISSUE TITLE
fluent api

### ISSUE THREAD

**Issue by mbjelac** [tomakehurst/wiremock#318]
the API consists of a bunch of static methods in the `WireMock` class. the methods are not all part of the same API section - some are for verification, some for stubbing, etc.

it would be more helpful for developers which are using an auto-completion IDE (so, most developers) to have a [fluent API](http://www.martinfowler.com/bliki/FluentInterface.html) which will "guide" the developer in writing WireMock stubbings, verifications, etc.

**Comment by tomakehurst** [comment]
I'm pretty certain WireMock has a fluent API already :-)

I understand that having multiple levels of nesting means that the IDE doesn't always have a suggestion for you, but separating out the matchers, request and response builders make the DSL more composable, e.g. you can write a factory that returns just the response portion of the stub mapping.

**Comment by mbjelac** [comment]
i was kind of expecting such a factory to already be included the box :)

**Comment by tomakehurst** [comment]
When I say "factory" in this instance, I mean one that's specific to your domain (and hence couldn't be delivered out of the box).

**Comment by mbjelac** [comment]
ah, i see...
