### ISSUE TITLE
Deleting the existing stubs.

### ISSUE THREAD

**Issue by casanova2020** [tomakehurst/wiremock#319]
Hi Guys,
we have a scenario, where we need to delete the existing stubs(Without restart / reset).
Is there any plan in roadmap, to support deleting the existing stubs ??

Regards,
Eswar Kumar

**Comment by fipa** [comment]
I'm in the same situation, it would be great to have that feature.

Fernando

**Comment by tomakehurst** [comment]
There's nothing planned for stub deletion at the moment. There is a PR in the works to support editing though. 

Also, you can effectively delete stubs by creating new ones with identical request matchers but different responses i.e. 404 if you want the default behaviour.

**Comment by casanova2020** [comment]
Thanks Tom, I'll have a look at the PR.
