### ISSUE TITLE
Mocking external calls ?

### ISSUE THREAD

**Issue by Paul776** [tomakehurst/wiremock#324]
This is more of a question than an issue (is there an other forum more appropriate for this?)

My rest API has the Facebook login feature and during that flow there is an HTTPS call to the Facebook graph API. 

I would like to make that call so I can run my integration test and without to have a valid Facebook token..

Is there a way with WireMock to archive this ? All the example I saw uses internal url?

thank you

**Comment by tomakehurst** [comment]
Since this is a question (as per the readme) I suggest you post this along with a bit more detail about the interaction you're trying to test on the mailing list.
