### ISSUE TITLE
urlPattern + queryParameters don't match requests

### ISSUE THREAD

**Issue by adam-wojszczyk** [tomakehurst/wiremock#325]
Hi!

The request:
```
/users/10?query=5
```
doesn't match with the following mapping:
```
{
  "request" : {
    "urlPattern" : "/users/[0-9]+",
    "method" : "GET",
    "queryParameters" : {
      "query" : {
        "matches" : "[0-9]+"
      }
    }
  },
  "response" : {
    "status" : 200
   }
}
```

but it matches with the mapping:
```
{
  "request" : {
    "urlPath" : "/users/10",
    "method" : "GET",
    "queryParameters" : {
      "query" : {
        "matches" : "[0-9]+"
      }
    }
  },
  "response" : {
    "status" : 200
   }
}
```

I expect that both should match.

**Comment by tomakehurst** [comment]
``urlPattern`` won't work with query params.

If you use ``urlPathPattern`` (which only matches the URL path to the regex, not the whole thing) in the first example, your test should pass.

**Comment by NitinKVerma** [comment]
hello 
i want to pass array in queryparameters it always says Request was matched

URL: localhost:9090/v1/accounts/balances?accountIds=[4567]&untilDate=null

"request": {
        "urlPathPattern": "/v1/accounts/balances",
        "method": "GET",
        "queryParameters": {
          "accountIds": {
            "matches": "[4567]"
          },
          "untilDate": {
            "matches": "null"
          }
        }
      }

please help !!!
