### ISSUE TITLE
Mocking war file request

### ISSUE THREAD

**Issue by dbclkclk** [tomakehurst/wiremock#326]
Good day:

I have a WAR file that's making an external request to an API. I want to run Selenium Java test cases against it (meaning the WAR file has to be deployed before the Selenium Test case run against it). When the WAR file is deployed, my @before method (JUNIT) defines the wiremock server along with the stub request. 

      @Before
       public void setUp() {

         ResponseDefinitionBuilder responseDefinitionBuilder = new ResponseDefinitionBuilder();
         responseDefinitionBuilder.withBody("" +
                "\"access_token\": \"63561485-6f03-48e4-a50e-5dd5e442fa05\"," +
                "\"token_type\": \"bearer\"," +
                "\"refresh_token\": \"c9a3f20d-08b5-4a92-91a9-c2c2e604699c\"," +
                "\"expires_in\": 1499," +
                "\"scope\": \"read write\"");
         responseDefinitionBuilder.proxiedFrom(this.oauthUri);

         UrlMatchingStrategy urlMatchingStrategy = new UrlMatchingStrategy();
         urlMatchingStrategy.setUrl("");
         MappingBuilder mappingBuilder = new MappingBuilder(RequestMethod.POST,urlMatchingStrategy).willReturn(responseDefinitionBuilder);
         wireMockRule.stubFor(mappingBuilder);

     }

When my test runs, the stub isn't working. I'm wondering if WireMock faciliate stubbing proxy endpoints that WAR request is being made?

The Selenium Java code:

     @Test
     public void testLoginSuccessful()
     {

        waitForElement(By.cssSelector(".login-text-holder .login"));

        click(By.cssSelector(".login-text-holder .login"));

        try {
            Thread.sleep(3000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        setText("#loginForm .login-username","test");
        setText("#loginForm .login-password","test");
        click(By.cssSelector("#loginForm .login-submit"));

        try {
            Thread.sleep(20000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

      }

Thanks.

**Comment by tomakehurst** [comment]
Can I suggest taking a closer look at the docs at http://wiremock.org ?

There's a Java DSL which is much easier to read and write, and is much more likely to produce the correct result.
