### ISSUE TITLE
String Body Parameters

### ISSUE THREAD

**Issue by rodrigoturnes** [tomakehurst/wiremock#328]
Hi,

I'm using wiremock and it's helping a lot with my project development.

I have a problem when I try to send not exact string parameters through request data. It works OK when I use:

"url": "/policy/search",
"bodyPatterns" : [
    { "equalToJson" : "{"session_id":"23232", "results_type": "0"}"}
]

But what happens if I want that results_type accepts ANY incoming string parameter?

Let's say: { "equalToJson" : "{"session_id":"23232", "results_type": "any string"}"}

How can I achieve this?

Thanks!

**Comment by Mahoney** [comment]
Please ask questions  like this on the mailing list:
https://groups.google.com/forum/#!forum/wiremock-user
