### ISSUE TITLE
Required simple wire mock sample

### ISSUE THREAD

**Issue by vayalaivadivel** [tomakehurst/wiremock#333]
Hi Team,
          I implemented rest client using spring by invoke third party rest api. I am able to test my client using JUnit. In that case We need to use WireMock rather than relying on 3rd party service for unit tests. I am completely new in this Wire Mock. Can please guide me to implement thiis? It is very urgent also.

Thanks and Regards,
VADIVEL PM,

**Comment by tomakehurst** [comment]
I suggest you take a look at the Getting Started section on http://wiremock.org. There are plenty of examples with code samples to guide you. 

I also suggest you direct future questions of this nature to the mailing list as more folks will have a chance to respond and we like to keep GH issues for bugs and features.

**Comment by vayalaivadivel** [comment]
Thanks for your quick reply. I have a confident to complete my task soon
