### ISSUE TITLE
Spring Rest Template with Wire Mock

### ISSUE THREAD

**Issue by vayalaivadivel** [tomakehurst/wiremock#336]
Hi Team,
              I have a rest client which is created using Spring rest template. Can we test this using wire mock? If yes, please share some samples regarding this.

**Comment by tomakehurst** [comment]
It's definitely possible to use WireMock in this scenario, but there's nothing you need to do specifically for REST templates as it's an HTTP server and thus agnostic to the client lib you're using.

I suggest getting familiar with the docs and trying the examples then, as I mentioned before, if you have any specific questions post them on the mailing list where the community will see them.
