### ISSUE TITLE
How to implement state transition with proxied stubs

### ISSUE THREAD

**Issue by leoluz** [tomakehurst/wiremock#342]
In our wiremock implementation we are proxying all our requests to the real services to auto generate all the stubs for us. The only stub definition that we have is:
```java
server.stubFor(any(urlMatching(".+"))
                  .atPriority(10)
                  .willReturn(aResponse().proxiedFrom("http://real/service")))
```
The idea is that in the first test execution, all the requests are sent to the real services (enabling recording) but the subsequent ones will be handled by the recorded stubs and responses. This is working just fine. The problem is when I have to implement a scenario that depends on state transition. In this case, the first test execution (that sends all the request to the real services) works, but the mocked ones always returns the same state for a given request.

I checked the wiremock scenarios definition but its seems that it can only be used when you implement all your stubs. Is it possible to use it in my scenario? Would you recommend another approach to address this issue?

Thanks a lot!

**Comment by tomakehurst** [comment]
Hi, please can you post this on the mailing list as per the readme? We prefer to use issues for bugs/feature requests and the mailing list gets more eyes on it.

**Comment by leoluz** [comment]
Sure thing. Sorry, I missed the readme.

Tks!
