### ISSUE TITLE
Java vs Json documentation

### ISSUE THREAD

**Issue by zkendall** [tomakehurst/wiremock#343]
I think it should be explicitly called out that some terms vary between these two methods. 

For example in [Stubbing](http://wiremock.org/stubbing.html), it's not immediately clear that the java versions of matchers are different than the json. For example, "matching" becomes "matches", while "notMatching" becomes, "doesNotMatch".

In the documentation, one or the other example is used, but I don't see each difference aren't explicitly listed.

**Comment by tomakehurst** [comment]
True, there are some discrepancies in the names but I believe they're all documented explicitly.

What would you suggest specifically?

**Comment by zkendall** [comment]
I guess, I see them each listed for both in the headers matching section. I didn't see this when I was trying to match bodies. Would help if an example of each is demonstrated in the body matching section, instead of only two of the four.

**Comment by tomakehurst** [comment]
OK, I'll have a look at enhancing that a bit next time I'm documenting.
