### ISSUE TITLE
Vagrant vm box url no longer exists

### ISSUE THREAD

**Issue by jdeff** [tomakehurst/wiremock#357]
After cloned the repo and running `vagrant up` for the first time, I was running into an issue finding the box to download. It looks like `https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box` no longer exists.

```
 ❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box' could not be found. Att
empting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box' (v0) for provide
r: virtualbox
    default: Downloading: https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

I was able to work around this by just setting `config.vm.box` to "ubuntu/trusty64" in the Vagrantfile, but someone might want determine what the correct value for wiremock should be.

**Comment by tomakehurst** [comment]
Thanks for pointing this out. I haven't needed the VM for a while so hadn't noticed, but I'll push an update with a URL that works.

**Comment by eis** [comment]
This is still an open issue.

**Comment by tomakehurst** [comment]
TBH I just don't have the bandwidth for this at the moment. I haven't needed the VM for a long time, so it's never going to make it hear the top of the list.

I'm happy to accept a PR fixing this, but otherwise it's going to stay broken I'm afraid.

**Comment by eis** [comment]
Added PR. Original box seems nowhere to be found, so used another that has the relevant dev tools.
