### ISSUE TITLE
HTTP/2 + TLS support

### ISSUE THREAD

**Issue by lpandzic** [tomakehurst/wiremock#362]
Hello,

do you support (or plan to) HTTP/2 with TLS?

**Comment by tomakehurst** [comment]
Definitely plan to support it. Haven't had a chance to look into what's missing yet, although since 2.x uses Jetty 9 I'm hoping it won't be much more than flipping a config switch.

**Comment by lpandzic** [comment]
As far as I understand, Jetty 9.3 is required for HTTP/2 support and wiremock uses Jetty 9.2.

**Comment by tomakehurst** [comment]
Ok, that's a bit unfortunate. We're holding off upgrading to Jetty 9.3 as it forces us to drop JDK7 support.

I've been thinking it might be a good idea to start releasing an additional build with 9.3 in it to solve this problem. This might be another good reason to do so.

**Comment by samuel-soubeyran** [comment]
Some work related to that is happening in #407.

@tomakehurst, @dsyer  I'm also interested in HTTP2 support for mocking services over grpc. I'll try to make a PR but if you have any pointers in term of what it entails and where are the places that require change it would be helpful.

**Comment by samuel-soubeyran** [comment]
I was able to upgrade to jetty 9.3 fairly easily (some changes in CustomizedSslContextFactory), but I am stuck with ALPN. Not sure how to tackle that :-/.
https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html.
It seems that we must add a jar in the Xbootclasspath that depends on the version of the JDK we're running . That seems like a strong constraint especially if we're not running standalone.

**Comment by tomakehurst** [comment]
As mentioned earlier in the thread, the issue with the Jetty upgrade is that 9.2 is the last version that supports Java 7, so upgrading means dropping Android support, which would make a lot of people pretty unhappy.

I would still welcome a PR that builds an additional JAR for Jetty 9.3 and adds HTTP/2 support.

**Comment by samuel-soubeyran** [comment]
Got it,
The way I was seeing it is to do a temporary PR that doesn't build the additional JAR. We can then see what changes are involved and from here gather input on how to proceed to build the different  JAR.

Does that sounds good ?

**Comment by tomakehurst** [comment]
Sorry for the delayed reply. Yes, I'm happy to use a throwaway PR as a review mechanism if that's how you'd like to proceed.

**Comment by samuel-soubeyran** [comment]
Sorry, it took me a while to free some time.
Here #887 is an initial attempt for review.

**Comment by alinpa** [comment]
Any update on this thread?

**Comment by scullinan** [comment]
@tomakehurst it's been 2 years since your last comment on this thread. Do you still have the same concerns you had back then about the upgrade to jetty 9.4 given Android now has some Java 8 support?
HTTP/2 is a really big gap IMO, would be good to get this supported.

**Comment by tomakehurst** [comment]
Jetty 9.4 + HTTP/2 is already supported in the jre8 build.

Announcements on the mailing list e.g. for [the 2.25.0 release](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/wiremock-user/http$2F2%7Csort:date/wiremock-user/bxG2-yb-u-Y/YlRq94niBQAJ) are usually a better bet than old GH issues for up-to-date info (I don't get round to issue gardening very much at the moment).

**Comment by lpandzic** [comment]
I guess this issue can be closed then?
