### ISSUE TITLE
Format of request/response body

### ISSUE THREAD

**Issue by KevinChiuKooppi** [tomakehurst/wiremock#365]
Hi,
I am new in WireMock, and I was trying to test the basic GET method. My mapping is like:
```
{
	"request":
	{
		"urlPattern": "/user/1",
		"method": "GET"
	},
	
	"response":
	{
		"status": 200,
	    "headers":
	    {
			"Content-Type": "application/json"
	    },
	    "body": "{\"id\": \"1\", \"login\": \"test\", \"www\": \"www.test.com\"}"
	}
}
```

Then my question arises:
When I try to change the request body into : 
`"body": "{"id": "1", "login": "test", "www": "www.test.com"}"`

which I think it's easier for reading and testing. But it doesn't work unfortunately. I wonder at this stage, is there any solutions?

Thanks a lot in advance :+1:

**Comment by tomakehurst** [comment]
As per the README, please can you re-post this on the mailing list?
