### ISSUE TITLE
Classpath problems with Servlet API

### ISSUE THREAD

**Issue by walec51** [tomakehurst/wiremock#366]
Wiremock includes some very old Jetty API's which have the old Servlet API.
org.mortbay.jerry:servlet-api:2.5-20081211

This can cause classpath problem in projects that use newer 3.1 Servlet API's. For example you can get a method not found exception for ServletContext.getClassLoader if the interface from Jetty takes precedence in the classpath.

**Comment by tomakehurst** [comment]
Presume you're looking at 1.x?

**Comment by tomakehurst** [comment]
v2 has an up-to-date servlet API dependency.
