### ISSUE TITLE
How to Use Json File in withRequestBody()

### ISSUE THREAD

**Issue by umar1990** [tomakehurst/wiremock#367]
I am new to wiremock and i found this very easy to understand and use. 
I went thru the wiremock documentaion but only found api for using json file at the response(aResponse()..withBodyFile("myresponse.json")). 
Is there a way to achieve the same for request??Something like withRequestBody("myrequest.json")

**Comment by tomakehurst** [comment]
As per the README, please can you post questions to the mailing list, thanks.
