### ISSUE TITLE
Problems with scenarios

### ISSUE THREAD

**Issue by macscripter** [tomakehurst/wiremock#370]
Hello!

First of all, THANK YOU VERY MUCH FOR THIS AMAZING SOFTWARE!

I have a problem with a stateful execution.

I copied directly from http://wiremock.org/stateful-behaviour.html

this code in the mappings dir:

`{
"scenarioName": "To do list",
"requiredScenarioState": "Started",
"request": {
"method": "GET",
"url": "/todo/items"
},
"response": {
"status": 200,
"body" : "Buy milk"
}
}

{
"scenarioName": "To do list",
"requiredScenarioState": "Started",
"newScenarioState": "Cancel newspaper item added",
"request": {
"method": "POST",
"url": "/todo/items",
"bodyPatterns": [
{ "contains": "Cancel newspaper subscription" }
]
},
"response": {
"status": 201
}
}

{
"scenarioName": "To do list",
"requiredScenarioState": "Cancel newspaper item added",
"request": {
"method": "GET",
"url": "/todo/items"
},
"response": {
"status": 200,
"body" : "Buy milkCancel newspaper subscription"
}
}`

After, I run wiremock server in standalone mode:
java -jar wiremock-1.57-standalone.jar

After I execute the first scenario (GET):

http://localhost:8080/todo/items

I get the

<items> <item>Buy milk</item> </items>

Fine.

After I execute http://localhost:8080/todo/items (POST) with the json object (application/json):

{"value":"Cancel newspaper subscription"}

And I get:

<title>Error 404 NOT_FOUND</title> 

And when I try to execute http://localhost:8080/todo/items (GET)
I get the the same as in the first scenario.....

<items> <item>Buy milk</item> </items>

Could someone explain me where am I wrong?

Thank you in advance!

Best regards

**Comment by tomakehurst** [comment]
As per the readme please can you post questions to the mailing list.

**Comment by macscripter** [comment]
OK, I just did it. Sorry...
Thank you, Tom, for your help!

Best regards
