### ISSUE TITLE
Dynamic Response/Mathematical Operation

### ISSUE THREAD

**Issue by SumeetCh** [tomakehurst/wiremock#374]
Hi 

Is it possible to do mathematical operations on the mock response message ? Example if consumer send a $ amount of 3.00 in request, can you subtract the same from a base value and return the response back ?

I am new to mockwire so any response is highly appreciated.

**Comment by tomakehurst** [comment]
It's possible to do this by writing a response transformer extension or using one written by someone else e.g. https://github.com/adamyork/wiremock-velocity-transformer

**Comment by SumeetCh** [comment]
Thanks for the response. Is there a possibility we can inject a script or property file from where we can dictate the transformation.

**Comment by tomakehurst** [comment]
You'd need to write your own response transformer implementation to do this

**Comment by SumeetCh** [comment]
Thanks for the response. By any chance we can use regular expression in matchesJsonPath or equalToJson to make the request values dynamic ? If yes can you sight me an example

Cheers
Sumeet

**Comment by tomakehurst** [comment]
Unfortunately you can't use regexes with either of those match types.

**Comment by AlixBa** [comment]
FTR (even it's a little too late, I think), [this](https://github.com/teads/wiremock-extensions) exists.
