### ISSUE TITLE
DB clears after process shutsdown ?

### ISSUE THREAD

**Issue by SumeetCh** [tomakehurst/wiremock#375]
Hi 

I am trying to run wiremock in standalone mode and it work pretty well for my use case. I am just mapping JSON request/response pairs. The DB/Cache clears off when the wiremock shuts down, is there a way to persist data on wiremock ? Or restore what was there before shut down.

Regards
Sumeet

**Comment by tomakehurst** [comment]
Just call ``WireMock.saveMappings()`` if you're using the Java client, or POST an empty request to ``/__admin/mappings/save`` if you're configuring it over HTTP.

The mappings will be written to the ``mappings`` dir on the file system, and be read next time WireMock starts.
