### ISSUE TITLE
Wiremock 2.0.11-beta is not available from maven central

### ISSUE THREAD

**Issue by mariuszs** [tomakehurst/wiremock#376]
Please publish https://github.com/tomakehurst/wiremock/releases/tag/2.0.11-beta

**Comment by tomakehurst** [comment]
I was planning on merging a couple more PRs first. Was there something specific you wanted to see released?

**Comment by mariuszs** [comment]
I thought that it is as already released, because it is tagged.

**Comment by tomakehurst** [comment]
Apologies, I must have pushed the tag by accident.
