### ISSUE TITLE
Query param decoding in stubbing vs verifying

### ISSUE THREAD

**Issue by rowanhill** [tomakehurst/wiremock#377]
Hi there,

I think I'm missing something simple, so please tell me if so. I say that because I'm kind of amazed I haven't noticed this before now, but...

Am I right in saying that the handling of URL decoding in query parameter values is different between stubbing (where no decoding happens) and verifying (where decoding does happen)?

From a quick poke around (on both tag [1.58](https://github.com/tomakehurst/wiremock/tree/1.58) and [2.0.11-beta](https://github.com/tomakehurst/wiremock/tree/2.0.11-beta)), it looks like it's down to a difference between how query params are pulled out of a full URI string from a Jetty request (stubbing) vs a journal request (verifying).

For the former, [`Jetty6HttpServletRequestAdapter#queryParameter(String)`](https://github.com/tomakehurst/wiremock/blob/1.58/src/main/java/com/github/tomakehurst/wiremock/jetty6/Jetty6HttpServletRequestAdapter.java#L159) / [`JettyHttpServletRequestAdapter#queryParameter(String)`](https://github.com/tomakehurst/wiremock/blob/2.0.11-beta/src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServletRequestAdapter.java#L158) calls `splitQuery(request.getQueryString())`, where request is a Jetty HttpServletRequest. The comment on getQueryString notes "The value is not decoded by the container".

For the latter, `LoggedRequest#queryParameter(String)` references the collection set up in the constructor as `splitQuery(URI.create(url))` (in both [1.58](https://github.com/tomakehurst/wiremock/blob/1.58/src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java#L71) and [2.0.11-beta](https://github.com/tomakehurst/wiremock/blob/2.0.11-beta/src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java#L72). Here the url string is parsed by URI.create first, so splitQuery calls `uri.getQuery()` to get the query string. The JDK docs for that note "all sequences of escaped octets are decoded".

All this leads to the slightly surprising behaviour that the following test fails:

```java
@Test
public void queryParamsWhenStubbingAreEncodedButQueryParamsWhenVerifyingAreDecoded() {
    // given we stub using an undecoded param value
    wireMockRule.stubFor(get(urlPathEqualTo("/test"))
            .withQueryParam("q", equalTo("a:b"))
            .willReturn(aResponse()));

    // when we make a request with Jersey, which encodes the param to a%3Ab
    Response response = ClientBuilder.newClient()
            .target("http://localhost:8080/test").queryParam("q", "a:b")
            .request()
            .get();

    // then verifying with the uncoded param succeeds, but the request did not match
    wireMockRule.verify(getRequestedFor(urlPathEqualTo("/test"))
            .withQueryParam("q", equalTo("a:b")));
    assertThat(response.getStatus()).isEqualTo(200); // fails - actual is 404
}
```

Similarly, if we always use an encoded value when interacting with wiremock (i.e. `equalTo("a%3Ab")`), then the verify will fail, but the request will be matched successfully.

Some questions:
a) Am I being stupid?
b) Is this behaviour intentional? If so, how come? Is it documented somewhere? (I couldn't see where)
c) If not, I guess changing it would be big and breaking, but perhaps the upcoming 2.0 release might be the time to do it?

Thanks for any clarification!

**Comment by tomakehurst** [comment]
I'll try and take a more detailed look at this this evening, but I suspect you're right.

You're not the first to have complained about encoding when matching query params, and I've fought my own battles with it recently.

Agree entirely it should be fixed before coming out of beta. I'll make sure that happens as/when I've confirmed there's an inconsistency. TBH even if there isn't, I'd rather always match on decoded values so I'll ensure it works that way.

**Comment by tomakehurst** [comment]
Fixed in v2

**Comment by kothja** [comment]
I am facing similar encoding issue for query parameter key. The stub does not match if the query param key contains encoded charaters.
