### ISSUE TITLE
Feature Request - URI path in recorded request filenames

### ISSUE THREAD

**Issue by adamrudolph** [tomakehurst/wiremock#380]
This is a great tool.  After using it for awhile, especially the Record and Playback feature, the recorded requests (under mappings and __files) get flooded with files.

In order to manage files easier, a run-time option to record requests using URI path would be a great feature.

Example:
request to /customers/profiles 
would create files:
mappings/customers/profiles/
__files/customers/profiles/

Ideally replacing characters like "~" would be removed from path.

**Comment by tomakehurst** [comment]
I think I actually implemented this way originally, but I got annoyed with everything being nested n levels deep, so I flattened it out. I guess it could be enabled via a parameter.

**Comment by tomakehurst** [comment]
New recorder coming in #674 will have more flexible options for filename generation
