### ISSUE TITLE
Unable to bind JSON to object. Reason: Unrecognized field "message" 

### ISSUE THREAD

**Issue by deepak891** [tomakehurst/wiremock#382]
Mode : standalone.
Exception : Unable to bind JSON to object. Reason: Unrecognized field "message"  

Sample of file used :

{
"request": {
        "method": "GET",
        "url": "vehicle/getAllModelInfo/FordChina/env/A"
    },
    "response": {
        "status": 200,
       
        "transformers": ["body-transformer"],
    "message": null,
    "vehicle": [
        {
            "imgURL": null,
            "key": 1,
            "currency": "¥",
            "vehicleName": "福克斯",
            "startingPrice": 12,
            "fuelEfficiencyFrom": "****"
.....}]
}

Is there a way I can add custom field in standalone.

**Comment by tomakehurst** [comment]
As per the README, please can you post questions on the mailing list.
