### ISSUE TITLE
Please add API into com.github.tomakehurst.wiremock.http.Request to get Form parameters Or Request parameters

### ISSUE THREAD

**Issue by haducloc** [tomakehurst/wiremock#384]
Hi,

I am using WireMock 2.0.10-beta version. I didn't see any API for getting Form parameter or Request parameter in com.github.tomakehurst.wiremock.http.Request class

API Proposal

    Request.formParameter(key);

OR

    Request.getParameter(key); // For both query parameters & form parameters.

Thank you!

**Comment by tomakehurst** [comment]
I guess if the idea in #383 got implemented, we'd have to add this to Request class so if it's OK with you I'll close this one.
