### ISSUE TITLE
Misleading matchingJsonPath functionality

### ISSUE THREAD

**Issue by EugeneAbramchuk** [tomakehurst/wiremock#388]
Hi guys, I made a small observation about the _matchingJsonPath_ functionality.

http://wiremock.org/stubbing.html makes a statement:

> The path syntax is implemented by the JSONPath library. A JSON body will be considered to match a path expression if the expression returns either a non-null single value (string, integer etc.), or a non-empty object or array.

JSONPath, in case of a mismatch (no objects matched the criteria) returns an empty non-null object (in my case an empty LinkedHashMap). Wiremock treats this, however, as a match, because the object is not null. This seems rather misleading as nothing really matched the given JSON path.

The code in question is in _com.github.tomakehurst.wiremock.matching.ValuePattern#isJsonPathMatch_

```
        Object obj = JsonPath.read(value, matchesJsonPath);
        if (obj instanceof JSONArray) {
            return ((JSONArray) obj).size() > 0;
        }

        if (obj instanceof JSONObject) {
            return ((JSONObject) obj).size() > 0;
        }

       return obj != null;
```

As the result is not matched (no JSON elements such as JSONObject or a JSONArray are returned), the final return is the fallback.
It seems a bit more logical to me to make the last return check if the object is empty in addition to not being null - in this case an empty match will fail the match.

Code to verify the behaviour

```
public void test() {
    String json = "{\n" +
            "  \"RequestDetail\" : {\n" +
            "    \"ClientTag\" : \"test111\"\n" +
            "  }\n" +
            "}";
    ValuePattern pattern  = new ValuePattern();
    pattern.setMatchesJsonPaths("$.RequestDetail.?(@=='test222')");
    boolean matches = pattern.isMatchFor(json);
    assertFalse(matches);
}
```

**Comment by EugeneAbramchuk** [comment]
Since failing the matched JSONArray or JSONObject, JSONPath returns a Map, I added the clause:

            if (obj instanceof Map) {
                return !((Map) obj).isEmpty();
            }

It took care of the problem - the patch is attached.
[ValuePattern.patch.txt](https://github.com/tomakehurst/wiremock/files/229596/ValuePattern.patch.txt)

**Comment by tomakehurst** [comment]
This is a reasonable point, thanks for the heads-up. I'm totally refactoring the matching code at the moment, so I'll incorporate your suggestion when I get to the JSONPath part.

**Comment by EugeneAbramchuk** [comment]
Consider returning false as a fallback too, if the matching object is not an JSONObject, JSONArray or a Map, something might have been broken and it's best to fail fast, so to say.

**Comment by tomakehurst** [comment]
Agree that's a sensible approach

**Comment by mttkay** [comment]
I just stumbled upon this. Is this even correct to begin with, i.e. not producing a match if the array exists, but is empty? Looking at http://jsonpath.com/, if you replace that sample array with an empty one, and evaluate `$.phoneNumbers`, it will produce an empty array (`[]`). In Wiremock, this currently produces no match at all.

I think presence of an array, even when empty, should produce a positive match?
