### ISSUE TITLE
Wiremock in ui automator android test

### ISSUE THREAD

**Issue by prudencioj** [tomakehurst/wiremock#389]
Hey I'm trying to setup a mock server in my ui automator test. 

But I'm getting the following error:

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClientBuilder;
	at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:45)

Do you have any idea what the problem may be?

**Comment by tomakehurst** [comment]
Please can you re-post on the mailing list as per the README. One of the Android devs on there might be able to help.
