### ISSUE TITLE
Unable to form a URL in Wire Mock

### ISSUE THREAD

**Issue by pgenthusiast** [tomakehurst/wiremock#391]
I am using wire mock for the first time. I have a service which returns back an xml response when an xml request is sent. Now I have to stub the url(a different one) such that I form a request and send it to this wire mock server, which returns back a response.
Issue is I'm not able to form a different url(not the actual url which I invoke to the service) in the wire mock.
Share your valuable suggestions & thoughts.

**Comment by tomakehurst** [comment]
Please can you post this on the mailing list as per the README. I suggest you also supply a bit more detail e.g. the exact request and response and any code you've already written.

**Comment by pgenthusiast** [comment]
Where do I see this mailing list in README, to post the details

**Comment by tomakehurst** [comment]
There's a link on wiremock.org
