### ISSUE TITLE
Problem with `equalTo` with URL-encoded query param values

### ISSUE THREAD

**Issue by sikron** [tomakehurst/wiremock#394]
Hi,
i think the `equalTo` has a problem with query param values, which are URL-encoded. In the following the query param `q` has a value of `>` (GT), which is `%3E` in URL-encoded.

I think this is related to #284 .

Example test with TestNG and Spring RestTemplate:
`
    @Test
    public void testQueryParamUrlEncoded(){

        wireMockServer = new WireMockServer();
        wireMockServer.start();

        givenThat(
                get(urlPathEqualTo("/test"))
                        .withQueryParam("q", equalTo("%3E"))    --returns 404
                        .withQueryParam("q", containing("3E"))   --works correctly
                        .willReturn(aResponse())
        );

        HttpEntity httpEntity = new HttpEntity<>(new HttpHeaders());
        System.out.println(new RestTemplate().exchange("http://localhost:8080/test?&q=%3E",
                HttpMethod.GET, httpEntity, String.class));

        wireMockServer.stop();
    }
`

**Comment by tomakehurst** [comment]
Thanks for pointing this out. I'm currently doing a major re-write of the matching code and I'm planning to address this as part of it.

**Comment by sikron** [comment]
great, thx!

**Comment by tomakehurst** [comment]
This should be fixed in v2. Operators now always work on the decoded version.
