### ISSUE TITLE
Unable to mock 302 Redirection

### ISSUE THREAD

**Issue by SuyashKutumbe** [tomakehurst/wiremock#395]
Hello,

I am very new to GitHub and wiremock so pardon me in case of any mistakes.
Is it possible to use WireMock to test HTTP 302 redirection?
What I have done is, as soon as I hit a URL, the respective servlet should redirect to another servlet.

Can I test this functionality using wiremock? 
I searched on internet but didn't get required information. 
Let me know if you need more information.

Thanks in advance.

**Comment by EugeneAbramchuk** [comment]
Yes, you can: http://wiremock.org/proxying.html

See an example of mapping below

```
{
    "priority": 9,
    "request": {
        "method": "ANY",
        "urlPattern": ".*"
    },
    "response": {
        "proxyBaseUrl": "https://hostname:port"
    }
}
```

**Comment by SuyashKutumbe** [comment]
Thanks for the quick reply. I will try your suggestion. If it doesn't work in my case then will reopen the issue.
