### ISSUE TITLE
2.0 backlog for release

### ISSUE THREAD

**Issue by pimterry** [tomakehurst/wiremock#399]
Hi Tom,

Thanks for building WireMock, we've been using it (and contributing back) at [Softwire](http://softwire.com) on all sorts of projects for years now, and it's been great!

We're looking at dedicating some more substantial time to open-source contribution right now. We might have some developers with some free time available to donate to open-source projects that we know and love, and Wiremock's definitely up there. We're also really looking forward to a final release for 2.0.

Do you have a backlog of tasks or a specific plan of things that need to happen before 2.0 is ready? If you had some extra developers available to help get there, do you have an idea what they'd need to be looking at? We potentially have people who'd like to help out quite substantially, but we'd much rather organise our time around a specific plan of things to work on, since it's a bit easier to manage for everybody.

No worries if not, just interested if there is any way we could get involved and help get the beta over the line.

**Comment by tomakehurst** [comment]
Hi Tim,

That's a very generous offer! I'm trying to limit the changes necessary to make 2.0 final, as it's dragged on too long already. There's one more small breaking change I need to make to the API, then hopefully that's it.

However, there's a ton of stuff I'd like to do but haven't been able to get anywhere near. Some of it is quite small like switchable support for chunked vs. content length encoded responses. Some a bit larger like a templating extension (by popular demand).

If you're around London, perhaps we could meet up and talk sometime?

Cheers,
Tom

**Comment by rowanhill** [comment]
Hi Tom,

As it happens, it was me that just suggested this to Tim. Although Softwire's based in London, but Tim's busy sunning himself elsewhere, so it's probably best I pick this up from here.

Helping out with a later 2.x release also sounds like a great way of us contributing, if there's some substantial work there (i.e. getting 2.0 out the door was just one idea, I'm not wedded to it).

If this sounds like something that could work for you, how about you pop over to the Softwire offices (in Kentish Town) at some point in the near-ish future, and we dig into it a bit more?

Let me know, and we can arrange something in a medium a bit more suitable than GitHub :)

Rowan

**Comment by pimterry** [comment]
I assume you two have had a chat now, so I'm going to close this ticket.

**Comment by tomakehurst** [comment]
Indeed we have. Thanks for raising this.
