### ISSUE TITLE
Matching with urlPathMatching is not exact

### ISSUE THREAD

**Issue by zuckel** [tomakehurst/wiremock#408]
( The same problem existed for `urlPathEqualTo()` and was fixed in https://github.com/tomakehurst/wiremock/issues/323. )

The following stub

    stubFor(post(urlPathMatching("/endpoint/user/12345/success")).willReturn(aResponse().withStatus(500)));

will return 500 also on shorter URLs like `http://localhost:8090/endpoint/user/12345`

Following the documentation and also in regard to the sister functionality of `urlPathEqualTo()`, I think `urlPathMatching()` should do an exact match as well.

As a fix, it should be sufficient to get the actual path first like in the `urlPathEqualTo()` case and then match without appending `.*`.

**Comment by zuckel** [comment]
Edit: Was referencing the wrong issue.

**Comment by zuckel** [comment]
This seems to be fixed on 2.0-beta sometime after 2.0.11-beta.

**Comment by tomakehurst** [comment]
Glad to hear it's working for you now. I've completely re-written the matching code in the latest release, so that should have done it.
