### ISSUE TITLE
Wiremock to serve Images

### ISSUE THREAD

**Issue by debraj-manna** [tomakehurst/wiremock#413]
Can wiremock be used to create a mock endpoint that will serve images stored on local disk (`Content-Type: image/jpeg`) ? I am on Wiremock 1.58. I am not able to find this in the docs.

**Comment by tomakehurst** [comment]
Please just post questions on the mailing list, as per the README.

**Comment by debraj-manna** [comment]
Thanks Tom.

I posted it here because I did not find this information in the doc. I
thought if the feature is there but not in the doc then may be you will
consider this as a issue to add in the documentation.
