### ISSUE TITLE
Memory cleaning problems - Slow response times

### ISSUE THREAD

**Issue by sky-tiagoalves** [tomakehurst/wiremock#416]
I've been experiencing some problems with the wiremock standalone. Removed all transformers and tested this against just the standalone.
It's not cleaning it's memory properly and once it reaches it's heap limit, it starts getting incredibly slow responding. Anyone else experiencing this?

**Comment by tomakehurst** [comment]
As per the README, please can you post questions on the mailing list, and provide some more detail about your test setup - code, stub mappings, how you're generating load and how much.
