### ISSUE TITLE
wire mock query parameter

### ISSUE THREAD

**Issue by ajit-infostretch** [tomakehurst/wiremock#418]
i want to mock service for invalid username and password,
how to configure user and password query parameters such that when i hit URL with wrong user name and password, it will return invalid user response.

my major worry is query parameters contains what to put instead of contains which can check if admin is not passed as an value for user and password then it will send response invalid user.

http://localhost:8080/sendmessage.php?user=123&password=123 , this URL should return invalid user

following is my requrest
{
  "request":
    {
	 
      "urlPattern": "/sendmessage.php\\?user=[A-Za-z0-9_]+&password=[A-Za-z0-9_]+",
      "method": "GET",
	  "queryParameters": {            
			"user": {
                "contains": "admin"
            },	
			"password": {
                "contains": "admin"
            }
        }
	  
    },

  "response":
    {
      "status": 200,
      "headers":
        {
          "Content-Type" : "application/json",
		  "Connection" :"Keep-Alive",
		  "Date" : "Fri, 27 May 2016 05:47:42 GMT",
		  "Keep-Alive" : "timeout=5, max=100",		  
		  "Server" : "Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4",
		  "Transfer-Encoding" : "chunked",
		  "X-Powered-By" :"PHP/5.4.33"
        },
      "body": "{\"status\": \"Invalid User\"}"
    }
}

**Comment by tomakehurst** [comment]
As per the README please can you post questions (vs. bugs or features) on the mailing list.
