### ISSUE TITLE
Wiremock giving wrong response for multiple query parameters(need to obey order)

### ISSUE THREAD

**Issue by kapilag** [tomakehurst/wiremock#422]
I have a use case where we need to differentiate mocks based on multiple query parameters like

localhost:9000?firstname=kapil&lastname=aggarwal | should return body as "hello kapil aggarwal"
localhost:9000?firstname=kapil | should return body as "hello kapil" 
Stub code for the above is 

```
 stubFor(get(urlPathEqualTo("/login")).withQueryParam("firstname",equalTo("kapil")).withQueryParam("lastname",equalTo("aggarwal"))
                .willReturn(aResponse().withStatus(301).withBody("Hello  Kapil Aggarwal")));
        stubFor(get(urlPathEqualTo("/login")).withQueryParam("firstname",equalTo("kapil"))
                .willReturn(aResponse().withStatus(301).withBody("Hello Kapil")));
```

Now if i query mock server with `localhost:9000/login?firstname=kapil&lastname=aggarwal` it always return me "Hello Kapil"

Workaround for this would be to change the sequence but i really dont want my team to keep this hack in mind as there will be 100 of req/resp which we need to mock & will be mocking in future.

Can you please help in fixing this or Am i doing something wrong?

**Comment by tomakehurst** [comment]
As per the README please can you post questions on the mailing list, thanks.
