### ISSUE TITLE
When started WireMock server through java code using "xterm" gives 404 as response

### ISSUE THREAD

**Issue by narayandanak** [tomakehurst/wiremock#427]
1. Using java code I am trying to invoke xterm as follows. Please note that I am using TestNG and starting the WireMock server in @BeforeSuite method

String  wireMockJarLocation = "/home/bbp-ubuntu/TestMachineShare/keywordsTest/";
String commandStr = "java -jar " + wireMockJarLocation + "wiremock-1.58-standalone.jar --port 8097";
p = new ProcessBuilder("xterm", "-e", commandStr).start();

2. xterm starts and WireMock is printed on it and shows that WireMock is bound to the port 8097

3. Wait for 300 seconds with Thread.sleep(); such that I can check through browser if the required response is returned or not

4. When try to hit the mock URL "http://localhost:8097/suggest/SuggRequest?json=1&c=3&hl=en&gl=gb&query=a" following happens.
Browser says "HTTP ERROR 404"
Problem accessing /__files/suggest/SuggRequest. Reason:   NOT_FOUND

5. Now close the xterm by CTRL+c and stop the java code execution. Invoke the server from a terminal  on the same port and everything works fine

Note: I have no break points and I am not running java code in debug mode

**Comment by narayandanak** [comment]
I tried with infinite loop in java execution mode (not debug) but no luck. I kept getting 404 response.

**Comment by tomakehurst** [comment]
As per the README please can you post questions on the mailing list, thanks.

**Comment by narayandanak** [comment]
I have updated my query to the google groups. Request you to hqve a look.
