### ISSUE TITLE
How to set priority for standalone wiremock

### ISSUE THREAD

**Issue by kameshwarichivukula** [tomakehurst/wiremock#429]
Hi,

I have an application where I need to record requests and serve them later from the stored files. this works fine. However, if the request doesnt find any of the files, I want to give a customized message. I tried adding a file to mappings with regex url /something/* and priority as 4/10 and a corresponding file in __files. It still gives me that generic error saying problem accessing __files. 

Its an else condition I want to handle if none of the files serve the request **/something/thing?parameter=x&parameter2=y** - need a customised message. Your ideas would be appreciated. Thanks in advance!

Note: Running wiremock as standalone.

Kam

**Comment by tomakehurst** [comment]
As per the README, please can you post questions on the mailing list, thanks.
