### ISSUE TITLE
How do you only record requests that try to access a certain port?

### ISSUE THREAD

**Issue by jlebrech** [tomakehurst/wiremock#431]
I tried to use `--proxy-all="http://localhost:3000"` to capture anything my angular app tries to get from my rails app but instead it proxied stuff from port `3000` to port `8080` which wasn't what I was looking for.

I just want my api calls which are on port 3000 to be recorded.

Hope that makes sense.

**Comment by tomakehurst** [comment]
As per the README, please can you post this (with some more details and code) on the mailing list.
