### ISSUE TITLE
Choose available port

### ISSUE THREAD

**Issue by mortalisk** [tomakehurst/wiremock#434]
Hi, is there a way to get wiremock to choose an available port, and then get this prot for use in tests? If not, it is difficult to use this in a setting where other tests, or perhaps even the same tests are running concurrently.

**Comment by tomakehurst** [comment]
If you're starting WireMock from within Java via ``WireMockServer`` or ``WireMockRule``, pass ``wireMockConfig().dynamicPort()`` to the constructor.

Then you can call ``wireMockServer.port()`` (or the same for the rule) to get the port.

**Comment by mortalisk** [comment]
Thanks, that is very helpful :)
