### ISSUE TITLE
Resource keystore not found

### ISSUE THREAD

**Issue by lazaronixon** [tomakehurst/wiremock#435]
Resource keystore not found using Arquillian and OSX, on windows not problem.
Problem seems to be on Resources.getResource("keystore").toString() at
com.github.tomakehurst.wiremock.junit.WireMockRule
com.github.tomakehurst.wiremock.common.HttpsSettings

`    @Rule
    public WireMockRule wireMockRule = new WireMockRule(8989);`

**Comment by lazaronixon** [comment]
changed
 `private String keyStorePath = Resources.getResource("keystore").toString();`
to 
`private String keyStorePath = Thread.currentThread().getContextClassLoader().getResource("keystore").toString();`
and it is working now.

**Comment by tomakehurst** [comment]
Since ``Resources.getResource(...)`` delegates to the thread classloader, I can't understand why this should fix it.

Would you be able to supply a test case that demonstrates this?

**Comment by lazaronixon** [comment]
https://github.com/lazaronixon/wiremock-test/
1.52 [OK]
2.1.7 [Resource keystore not found]

**Comment by lazaronixon** [comment]
Fixed with 2.1.10
