### ISSUE TITLE
Json serialization NPE encountered in 2.1.0-beta

### ISSUE THREAD

**Issue by kjetilv** [tomakehurst/wiremock#437]
Hi, I just tried out 2.1.0-beta and got this new NPE for one of my backends:

[https://gist.github.com/kjetilv/22f912cf2786a9d415c9a063c1d66d76](https://gist.github.com/kjetilv/22f912cf2786a9d415c9a063c1d66d76)

Looks like it has something to do with a missing HTTP method attribute somewhere, which messes up serialization of an object during logging.

Any hints? Actual bug? Need more info?

**Comment by tomakehurst** [comment]
Couldn't reproduce. Not sure how it's possible to make the Servlet API return a null for the request method. Please re-open if you have any code you can share.
