### ISSUE TITLE
Stable 2.x version?

### ISSUE THREAD

**Issue by cguedes** [tomakehurst/wiremock#439]
Hi,

Is there any plan for a stable 2.x (non beta) version?

**Comment by tomakehurst** [comment]
Yup, very soon. Just sorting out docs and final compatibility fixes.

**Comment by cguedes** [comment]
@tomakehurst thanks for the update. Please give feedback here..

**Comment by tomakehurst** [comment]
I announce new releases on the mailing list. Suggest keeping an eye on that for updates.
