### ISSUE TITLE
Please add instructions for how to build and install locally

### ISSUE THREAD

**Issue by dsyer** [tomakehurst/wiremock#444]
I want to try the latest version, but it's not in a public Maven repo (as far as I know). Happy to build it locally, but "gradle install" doesn't work, and neither does "gradle publish". Something in the README maybe?

**Comment by tomakehurst** [comment]
It will be shortly. Just takes a while to sync across.

You can temporarily use oss.sonatype.org if you want it immediately.

**Comment by dsyer** [comment]
Thanks. What about if I make changes locally. How can I install those and test them?

**Comment by tomakehurst** [comment]
I've added some basic build instructions to the README

**Comment by tomakehurst** [comment]
Looks like install is broken somehow by the presence of two artifacts. I'll add it to the list to fix...

**Comment by Bdthomson** [comment]
Any idea how to get around this and install to local maven repository? Trying to test local changes also.
