### ISSUE TITLE
If-None-Match in request causes failure

### ISSUE THREAD

**Issue by weaverjeff** [tomakehurst/wiremock#447]
running wiremock using standalone jar v2.1.1-beta.  When request contains If-None-Match wiremock returns error:  java.lang.IllegalStateException: No value for If-None-Match

This works in 1.x standalone jar tested with wiremock-1.57-standalone.jar

**Request** 
GET http://<url>:8080/service/query HTTP/1.1
**If-None-Match:** 
Host: <hostname>:8080
Accept-Encoding: gzip
Connection: Close

**Response**
HTTP/1.1 500 Server Error
Date: Tue, 28 Jun 2016 20:40:06 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html; charset=ISO-8859-1
Content-Length: 359
Connection: close
Server: Jetty(9.2.z-SNAPSHOT)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /service/query. Reason:
<pre>    java.lang.IllegalStateException: No value for If-None-Match</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

**Comment by tomakehurst** [comment]
Could you post the stack trace?

And also, could you try it with the latest rc version? I fixed a couple of bugs with the matching code last night.

**Comment by tomakehurst** [comment]
Fixed by 3ba037ce9b8af310e62176ee38cb4c2e8957072b
