### ISSUE TITLE
NullPointerException in 2.1.0-beta, when ClasspathFileSource is pointing to resources inside a jar

### ISSUE THREAD

**Issue by otrosien** [tomakehurst/wiremock#449]
In my project I am packaging json stubs inside a jar, which breaks in 2.1.0-beta. See
https://github.com/ePages-de/restdocs-wiremock/issues/6

Problem is line 85 of JsonFileMappingsSource. `mappingFile.getUri().getPath()` returns `null` for a resource that is not in a resource folder, but coming from inside a jar file. 

```
mappingFile.getUri().getPath().replace(mappingsFileSource.getUri().getPath(), "");
```

Stacktrace:

```
java.lang.NullPointerException
    at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.getFileName(JsonFileMappingsSource.java:85)
    at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:72)
    at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:87)
    at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:83)
..
```

**Comment by otrosien** [comment]
If you want to see it in action, run `./gradlew build` on this feature branch: https://github.com/otrosien/restdocs-wiremock/tree/feature/wiremock_2_1_0_beta

**Comment by otrosien** [comment]
@tomakehurst  Thumbs up for the immediate fix. I just tried 2.1.4-rc3 but when looking at the release source jar (and still getting the same NPE) could it be that the release is broken or somehow missed to include the fix?

**Comment by tomakehurst** [comment]
I haven't pushed a new release yet as I was waiting for some feedback on another bug fix before doing so. I'll hopefully have done that by the end of today.

Perhaps you could build from source in the meantime?

**Comment by otrosien** [comment]
@tomakehurst sorry, my mistake. I'll try via maven local, and will report back if that fixes my problem.

**Comment by otrosien** [comment]
Looking good. :+1:

**Comment by tomakehurst** [comment]
Thanks!
