### ISSUE TITLE
[ - Illegal character in the query

### ISSUE THREAD

**Issue by senseysensor** [tomakehurst/wiremock#45]
In wireMock 1.33 I have error 500 with such URL:

_http://pagestat.mmi.bemobile.ua/pagestat/PageStatEntry?cookie=BBCD40B5E60A4809B65493C5368D0EBE&time=1376479473847&location=http%3A%2F%2Flocalhost%3A51385%2Ftest_1.html&referrer=&is_flash=1&session_id=796223628&version=3.0.91/1.48&sw=1920&sh=1080&scd=32&spd=32&param1=~cm_banners~&result=[{%22link%22:%22http%3A%2F%2Falpinists.com.ua%2Fiframe.html%22,%20%22pos%22:%22512%22},{%22link%22:%22http%3A%2F%2Fi.holder.com.ua%2Fh%2F3%2F2%2F302_1.swf%3Flink1%3Dlocal%22,%20%22pos%22:%22258%22}]_

That's because of "[" character.
Any chances to fix an issue in nearest time... please? Is critical for me :(
Thanks in advance!

**Comment by ckurban** [comment]
Hi Tom , Any update on this issue as I have the same issue. OR would you suggest any work around ?

**Comment by tomakehurst** [comment]
No progress on this, but if you're able to escape the characters in the URL your client is sending that should work around the problem.

**Comment by wojciechbulaty** [comment]
I had an issue with this in an old legacy application when doing a record/replay. It was hard to change that application so I had to make a fix in Wiremock. I have got a fix for this but did not have the time to merge it back yet. I have put it on my todo list now and once prioritized will merge it to Wiremock master.

**Comment by tomakehurst** [comment]
I'd be keen to see how you've fixed that. The reason I haven't tackled it yet is that the `URI` class (which is the source of overly strict parsing) is used all over the place and fixing it properly would mean a wholesale replacement of it.

I'd actually like to write my own URL wrangling library so that I can solve this problem generically, but also to provide a richer API for query splitting etc.

**Comment by wojciechbulaty** [comment]
When I said "a fix" I probably should have said "a working temporary workaround" :) What I have done is I am encoding the URL if it cannot be parsed by URI.encode wherever it is called.

```java
    private static CharSequence reEncode(String s) {
        try {
            return URLEncoder.encode(URLDecoder.decode(s, UTF_8), UTF_8);
        } catch (UnsupportedEncodingException e) {
            throw new IllegalArgumentException(s);
        }
    }

    public static String reEncodeParametersIfNeeded(String url) {
        try {
            return URI.create(url).toString();
        } catch (IllegalArgumentException e) {
            String reEncodedUrl = reEncodeParameters(url);
            notifier().info("Could not parse URL " + url + " because of " + e.getMessage() + ". ReEncoded url from " + url + " to " + reEncodedUrl);
            return reEncodedUrl;
        }
    }```

**Comment by pupattan** [comment]
Hey,

I am facing the same issue while using standalone jar file .
Is the there any workaround or fix for the same ?

HTTP ERROR: 500

Problem accessing /api/resource[name]/data. Reason:

    java.lang.IllegalArgumentException: (GET /api/resource[name]/data)@2014851095 wiremock.org.eclipse.jetty.server.Request@78183017 does not have a getUri or getHttpURI method

Powered by Jetty://



Thanks

**Comment by tomakehurst** [comment]
See #713
