### ISSUE TITLE
Listen for directory changes

### ISSUE THREAD

**Issue by ksokol** [tomakehurst/wiremock#452]
First of all, thank your for WireMock! I'm really happy with it and I want to give something back.

Here is my feature request (for discussion):

In recent times I'm using WireMock in conjunction with Docker (e.g. [rodolpheche/wiremock](https://hub.docker.com/r/rodolpheche/wiremock/)) inside a larger setup primarly focused on integration testing and local test development with docker-compose.
Currently, one need to restart WireMock to take new mappings and/or response files under `__files` into account. This puts some burden on the developers (e.g. me) who are in charge of developing new integration tests. They need to restart one particular Docker container (WireMock) to enable new mappings in their tests.

Java 7 gives us the ability to listen for changes in directories.

The question is should WireMock listen in `__files` and `mappings` directory for changes? Would it shorten our turn around in developing e.g. integration tests? I think so.

What do you think? Is it feasible to add such a feature?
I can lend a helping hand.

**Comment by tomakehurst** [comment]
Are you aware that hitting ``/__admin/mappings/reset`` will reload the mappings from the filesystem?

I appreciate this isn't quite as slick as it listening to the FS, but might solve your problem.

I think it's probably feasible to add this feature. My only reservation is about maintaining Android compatibility. Are you aware of whether file listening would cause any issues when run on Android?

**Comment by ksokol** [comment]
Unfortunately, maintaining compatibility with Android isn't possible. Android compiles against the Java 6 API whereas my feature request requires at least Java 7. It would break Android support. In addition, Android provides its own [API](https://developer.android.com/reference/android/os/FileObserver.html).

Anyway, I found a simple way how I can reload mappings on-the-fly with the given WireMock API (`resetToDefaultMappings()`).

Because I'm running WireMock in a very special project setup and my feature request would break Android support, I will close this issue.

**Comment by tomakehurst** [comment]
OK, thanks anyway!

**Comment by dmholmes** [comment]
I'd like to see this addressed. Can it be reopened?
