### ISSUE TITLE
Setting binding address not possible via JUnit Rule and standalone server

### ISSUE THREAD

**Issue by jarl-dk** [tomakehurst/wiremock#454]
I can see that configuring the binding address is possible when using as a non-Junit instance:
The docs (http://wiremock.org/java-usage.html#the-client) has example like

```
import static com.github.tomakehurst.wiremock.client.WireMock.*;
configureFor("wiremock.host", 8089);
```

and

```
WireMock wireMock = new WireMock("some.host", 9090, "/wm");
```

However setting the binding address is not possible (http://wiremock.org/junit-rule.html#server-configuration) or at least not documented when using Wiremock as a JUnit rule, which I find a bit sad now that it is implemented. The same holds for usage as a standalone server.
- For JUnit Rule it seems like binding address is implemented (https://github.com/tomakehurst/wiremock/blob/90ed9c9675a6bafb815aefa653795b80383bd074/src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java#L192-L195) but not documented.
- For the Standalone server, it seems to be implemented partially, as fields and CLI options are implemented (https://github.com/tomakehurst/wiremock/blob/90ed9c9675a6bafb815aefa653795b80383bd074/src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java#L90) but I am not sure they are propagated. Anyway it is not documented on http://wiremock.org/running-standalone.html.

**Comment by tomakehurst** [comment]
What you're doing in the example you've pasted is setting the address the client connects to, for when you want to talk to a remote WireMock server. This doesn't set the bind address.

However, you're correct that there's a missing setter from the config builder that supplies the rule, so I'll add that in the next release.

I'm about to switch to a new website design with the docs significantly updated, so the CLI option will appear in there.

**Comment by tomakehurst** [comment]
No, sorry I'm wrong! There is already a setter for the bind address.

See here: http://new.wiremock.org/docs/configuration/#network-ports-and-binding
