### ISSUE TITLE
Using Wiremock 2.x from Scala

### ISSUE THREAD

**Issue by aeons** [tomakehurst/wiremock#457]
I am trying to use Wiremock 2.1.6 from Scala. However, something has changed in the types of the mapping builders, so that scalac cannot typecheck it anymore.

The first stubbing example in the documentation:

```java
stubFor(get(urlEqualTo("/some/thing"))
        .willReturn(aResponse()
            .withHeader("Content-Type", "text/plain")
            .withBody("Hello world!")));
```
results in this error when compiling:
```
type mismatch;
    found   : ?0(in value <local TestSpec>) where type ?0(in value <local TestSpec>) <: AnyRef
    required: com.github.tomakehurst.wiremock.client.RemoteMappingBuilder[_ <: AnyRef, _ <: com.github.tomakehurst.wiremock.client.ScenarioMappingBuilder]
    get(urlEqualTo("some/thing")).willReturn(
```
The method `willReturn` is defined in the `RemoteMappingBuilder` interface
```java
public interface RemoteMappingBuilder<M extends RemoteMappingBuilder, S extends ScenarioMappingBuilder> {
    ...
    M willReturn(ResponseDefinitionBuilder responseDefBuilder);
}
```
It seems to me that Scala is not happy about the generic interface `RemoteMappingBuilder` being used without type parameters in `M extends RemoteMappingBuilder`.

Any suggestions on how to work around this?

(I also posted this on SO: http://stackoverflow.com/questions/38301631/wiremock-2-x-in-scala)

**Comment by tomakehurst** [comment]
As this is a question, please can you post it on the mailing list. 

I'm not a Scala dev, but perhaps @Mahoney can weigh in.

**Comment by aeons** [comment]
Sure.

**Comment by mriehl** [comment]
Was there any resolution to this? Casting all the time is ugly and unusable. I'll jump ship if that is the case, but it would be nice to at least document here which decisions you took?
Thanks.

**Comment by tomakehurst** [comment]
We're working on a fix but it's taking a while. Maintaining some semblance of backwards compatibility is going to be hard.

Breaking Scala certainly wasn't intentional. I'm not a Scala expert and hadn't appreciated that its generics system will reject code that javac had no problem with.

**Comment by mriehl** [comment]
Cool, thanks. That's also the first time I come across something like this :/
