### ISSUE TITLE
Combine default matchers with customMatcher

### ISSUE THREAD

**Issue by AlixBa** [tomakehurst/wiremock#459]
Hi,

I would like to combine the default matchers (url, method, query params, etc) with a customMatcher of my own. From the tests I did, if I specify a customMatcher it overrides existing matchers and only use the custom one. (<- this point is not very clear in the doc)

Ideally I would have something like:

``` json
{
  "request": {
    "method": "POST",
    "url": "/url",
    "customMatcher": { // or something like customPattern
      "name": "json-path-matcher",
      "parameters": {
        "jsonPath": "$.value",
        "operator": "equalsTo",
        "value": "nullOrEmpty"
      }
    }
  },
  "response": {
    "status": 204
  }
}
```

Do I have to extend `RequestPattern` and re-inject all request's fields inside customMatcher or is there a simpler way to do this?

Thanks

**Comment by tomakehurst** [comment]
Yeah, unfortunately there isn't an easy way to do this at the moment. And I can see the benefit of combining. I'll give some thought about how that can be added without too much pain.

**Comment by AlixBa** [comment]
is something like this a big deal / a good way to go?

```json
"request": {
  "additionalPatterns": [{
    "name": "myPattern",
    "parameters": {}
  }]
}
```

**Comment by scottaj** [comment]
This just bit us today. We didn't understand that it would only use the custom matcher and now need to back out some stuff we did and rethink it. 

I'm not sure where to start with this, but if someone can point me in the right direction I'd be happy to take a stab at it.

**Comment by tomakehurst** [comment]
Not totally ideal, but you can use the DSL to construct and use a request pattern inside your custom matcher e.g.

```java
RequestPattern requestPattern = get(urlEqualTo("/things")).build().getRequest();
MatchResult match = requestPattern.match(request);
```

**Comment by cydergoth** [comment]
+1
