### ISSUE TITLE
Mocking Server Sent Events or Long Poll

### ISSUE THREAD

**Issue by leslie-leder** [tomakehurst/wiremock#460]
Is there a way to stub server sent events (SSE)?
Or just to flush parts of the (long poll) response step by steps?

**Comment by tomakehurst** [comment]
Currently no. But these would make interesting features.

**Comment by redijedi** [comment]
Has there been any movement on this idea? I've hacked together an option to put a 50ms break between each line of content in the response. It's not particularly pretty, but it does the job.

**Comment by tomakehurst** [comment]
There hasn't unfortunately. Would be great to have a full solution to this in WireMock.

**Comment by liwp** [comment]
For anyone else who stumbles here after a google search... I was able to mock a canned SSE response with wiremock, which is returned by `WebClient` as a `Flux` 'stream' (in Kotlin):

```kotlin
 val eventStream = """
        id:10
        event:random
        data:751025203

        id:11
        event:random
        data:-1591883873

        id:12
        event:random
        data:-1899224227
        """.trimIndent()

        wiremock
            .stubFor(
                get(urlPathEqualTo("/sse"))
                    .willReturn(okForContentType("text/event-stream", eventStream)
            )

    val events = client.getEvents().collectList().block()!!
```

**Comment by hantsy** [comment]
But I can not make it work with Quarkus, https://github.com/quarkusio/quarkus/discussions/35224
