### ISSUE TITLE
Can I set filter on wiremock?

### ISSUE THREAD

**Issue by hjzheng** [tomakehurst/wiremock#464]
I want to add 'Access-Control-Allow-Origin' for all the mock request, it is best to add the configuration on jetty server.

**Comment by tomakehurst** [comment]
The only way to do this without hacking WireMock up currently is to write a ``ResponseDefinitionTransformer`` or ``ResponseTransformer`` extension.

But I agree this would be useful, so I'm planning on working on an easier way to do it.
