### ISSUE TITLE
Support response dribbling

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#472]
Support releasing of the HTTP response in small chunks over a configurable time period.

Useful for testing Hystrix.

**Comment by oliverlockwood** [comment]
For reference of anyone else who is interested, there are some related discussions about this item [here](https://groups.google.com/forum/#!searchin/wiremock-user/delay%7Csort:relevance/wiremock-user/rp9wyDx-9P8/jBAW9sPkCAAJ).
