### ISSUE TITLE
Wrong Content Returned in Parallel Proxied Requests on 2.x

### ISSUE THREAD

**Issue by mpiggott** [tomakehurst/wiremock#473]
Experimenting with Wiremock 2.1.8 standalone in our functional tests I discovered that when many proxied requests occur concurrently (in our case the ~200 js files in the pre-minified/combined app) some requests will be randomly served content from other requests.

This is with a trivial setup, the only stub is `wireMockServer.stubFor(WireMock.any(WireMock.urlMatching(".*")).atPriority(10).willReturn(
        WireMock.aResponse().proxiedFrom("http://localhost:9999")));`

Switching to 1.58 without any code changes appears to work successfully.

**Comment by tomakehurst** [comment]
Thanks for letting me know. I've replicated this in a test case now.
