### ISSUE TITLE
HTTP ERROR: 500 in Proxy mode

### ISSUE THREAD

**Issue by Emmerson-Miranda** [tomakehurst/wiremock#474]
Hello 

When I call the Wiremock Proxy I'm getting an HTTP error 500, It happen always I call the API with the header "Content-type", the error seems to be only in wiremock side because backend's log all is OK.

I started the proxy server with next configuration:

> java -jar wiremock-standalone-2.1.8.jar --preserve-host-header --match-headers="Authorization,Accept,Content-Type" --proxy-all="https://192.168.100.100:8243" --record-mappings --verbose --https-port=8888  

I call the proxy using curl:

> $ curl -k  -X GET --header "Content-Type: application/json" --header "Authorization: Bearer 4ebd64c5d16b78202bcee2315716bfa3" "https://localhost:8888/calc/1.0/add?x=1&y=3"

Then I get next error:

> <html>
> <head>
> <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
> <title>Error 500 </title>
> </head>
> <body>
> 
> <h2>HTTP ERROR: 500</h2>
> 
> <p>Problem accessing /calc/1.0/add. Reason:
> <pre>    java.lang.RuntimeException: java.io.FileNotFoundException: ./__files/body-1.0-add-EwswN.0/add (No such file or directory)</pre></p>
> 
> <hr /><i><small>Powered by Jetty://</small></i>
> </body>
> </html>
> $ 

Best Regards,
Emmerson.

**Comment by tomakehurst** [comment]
Tried to replicate this as closely as I could and couldn't get it to return a 500.

Which platform are you running on? And are you certain WM has write access to the __files dir (and its children)?

**Comment by MavoCz** [comment]
I'm having the same problem. For me this happens for all requests for which the server returns 204 response and no body data. Wiremock proxy then internally throws the exception above and instead of 204 response returns HTML exception.

**Comment by tomakehurst** [comment]
Since I couldn't reproduce this last time, please can you post your full logs, code and startup CLI params if you're running standalone.

**Comment by MavoCz** [comment]
Sure, here it is. I run it as standalone. Its a request to dynamics CRM.


c:\Users\Mavo\IdeaProjects\WireMock\Dynamics2>java -jar wiremock-standalone-2.2.1.jar --port=8081 --proxy-all="https://xxx.crm4.dynamics.com" --record-mappings --verbose
2016-10-07 15:46:47.573 Verbose logging enabled
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2016-10-07 15:46:48.818 Verbose logging enabled
2016-10-07 15:46:48.869 Recording mappings to .\mappings
 /$$      /$$ /$$                     /$$      /$$                     /$$
| $$  /$ | $$|__/                    | $$$    /$$$                    | $$
| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/
| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$
| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/

port:                         8081
proxy-all:                    https://xxx.crm4.dynamics.com
preserve-host-header:         false
enable-browser-proxying:      false
record-mappings:              true
match-headers:                []
no-request-journal:           false
verbose:                      true

2016-10-07 15:47:24.565 Proxying: POST https://voldrich.crm4.dynamics.com/api/data/v8.1/CloseIncident
2016-10-07 15:47:35.228 Request received:
127.0.0.1 - POST /api/data/v8.1/CloseIncident

Authorization: [Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlliUkFRUlljRV9tb3RXVkpLSHJ3TEJiZF85cyIsImtpZCI6IlliUkFRUlljRV9tb3RXVkpLSHJ3TEJiZF85cyJ9.eyJhdWQiOiJodHRwczovL3ZvbGRyaWNoLmNybTQuZHluYW1pY3MuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMmY1ZDhmZTUtNThiNy00NTc5LThjMjItMTdhMDA2N2QzYmRmLyIsImlhdCI6MTQ3NTg0Nzc0NiwibmJmIjoxNDc1ODQ3NzQ2LCJleHAiOjE0NzU4NTE2NDYsImFjciI6IjEiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiZThmZDExYTEtODliYS00M2MxLTk0ZDgtZWYxMDRiYmE0MjQxIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJWb2xkxZlpY2giLCJnaXZlbl9uYW1lIjoiTWF0b3XFoSIsImlwYWRkciI6Ijk0LjExMy4xMTEuOTEiLCJuYW1lIjoiTWF0b3XFoSBWb2xkxZlpY2giLCJvaWQiOiIzN2YwMTQwYy0wN2Q4LTQ5NDctYWI1Zi0zMjJlZGViZTUwZGIiLCJwdWlkIjoiMTAwM0JGRkQ5QTU1ODM4NiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IkgtZm5vZFVNeHhSWFF1cEw5ci15eTFyZnRRT3d5VkNEUFNGR3pUeDBKM0UiLCJ0aWQiOiIyZjVkOGZlNS01OGI3LTQ1NzktOGMyMi0xN2EwMDY3ZDNiZGYiLCJ1bmlxdWVfbmFtZSI6Im1hdG91c0B2b2xkcmljaC5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJtYXRvdXNAdm9sZHJpY2gub25taWNyb3NvZnQuY29tIiwidmVyIjoiMS4wIiwid2lkcyI6WyI2MmU5MDM5NC02OWY1LTQyMzctOTE5MC0wMTIxNzcxNDVlMTAiXX0.nTbovfp8FKVSHcf09kinADGfLepFp7TyjXAmgawFtl-O1hSqI-Jii01YOhtd9XKZqkG1FQk8Q6-o5D-NMGG9bSRVdFvdAlwT1QNCgf9Yak3p3qjkKucOgnVd2uTn4D5ghgLy_0KHAmfrusp5RAEhvWiYo4IXFA6RBckLclP8R5WvwzGwZMloIQRW9d2qOwQb5G6Gx8srcCbkLcZr4yN9U3CjR2IDIPmnMijjTO-U3U9A9fJCxbEfXIzKREIyodaC8A_WURqW6x9BtLynO3XqJ-62brTNnxaVpVZ4sT4NuuK4YY9Zx2Z1twaDauu0NADSNIamPcwz-RZ1SswEauARwg]
Accept: [application/json]
User-Agent: [Jersey/2.23.2 (HttpUrlConnection 1.8.0_92)]
Connection: [keep-alive]
Host: [localhost:8081]
Content-Length: [239]
Content-Type: [application/json]
{"Status":5,"IncidentResolution":{"subject":"Problem resolved","timespent":120,"incidentid@odata.bind":"https://xxx.crm4.dynamics.com/api/data/v8.1/incidents(ea9e62a8-90df-e311-9565-a45d36fc5fe8)","description":"This was a hard one"}}


Matched response definition:
{
  "status" : 200,
  "proxyBaseUrl" : "https://xxx.crm4.dynamics.com"
}

Response:
HTTP/1.1 204
Cache-Control: [no-cache]
Pragma: [no-cache]
Expires: [-1]
Server: [Microsoft-IIS/8.5]
REQ_ID: [5fff4a26-3131-4772-9443-f320cfb8c50f]
Set-Cookie: [ReqClientId=c89137c1-35e2-433c-a6ea-b3941dc8a055; expires=Thu, 07-Oct-2066 13:47:27 GMT; path=/; secure; HttpOnly, crmf5cookie=!XJjWFRagu51G922vpwah6jvLfRGOsYfoQ+ItzWO8WobK4lukwYTJJlI5P2zTFPs+RRtrKKOqrYeDRg==;secure; path=/]
OData-Version: [4.0]
X-AspNet-Version: [4.0.30319]
X-Powered-By: [ASP.NET]
Date: [Fri, 07 Oct 2016 13:47:36 GMT]
Strict-Transport-Security: [max-age=31536000; includeSubDomains]



2016-10-07 15:47:35.235 Recording mappings for /api/data/v8.1/CloseIncident

**Comment by MavoCz** [comment]
Managed to find the html exception sent by wiremock to my client code instead of response:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/data/v8.1/CloseIncident. Reason:
<pre>    java.lang.RuntimeException: java.io.FileNotFoundException: .\__files\body-v8.1-CloseIncident-bXnfy.1\CloseIncident (The system cannot find the path specified)</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

**Comment by MavoCz** [comment]
Found the error in wiremock code. In method
com.github.tomakehurst.wiremock.common.ContentTypes#determineFileExtension

```
String path = URI.create(url).getPath();
        if (path.indexOf('.') != -1) {
            return path.substring(path.lastIndexOf('.') + 1, path.length());
        }
```
since path contains a dot in /api/data/v8.1/CloseIncident it uses 1/CloseIncident as extension.

**Comment by MavoCz** [comment]
I have commented the code out, tried again and can confirm that it works. Request passes without problems and response is saved as a txt.

**Comment by tomakehurst** [comment]
Thanks for the update. Will fix this in the next release.
