### ISSUE TITLE
Problem with headers name having underscore

### ISSUE THREAD

**Issue by jomaora** [tomakehurst/wiremock#476]
Hello, I'm new using wiremock. I have to mock an endpoint having some important information within he headers. The main header is "X_WASSUP_USER_GID". I can see on my rest client that the headers is sent (as shown by the following printscreen - I have also seen the header on Charles)

<img width="1340" alt="capture d ecran 2016-08-05 a 14 55 07" src="https://cloud.githubusercontent.com/assets/7602475/17437244/dd621ac8-5b1c-11e6-8600-3002f8768b84.png">

But on wiremock logs, the headers is not present. 

![capture d ecran 2016-08-05 a 14 56 38](https://cloud.githubusercontent.com/assets/7602475/17437251/e65e1514-5b1c-11e6-9dfe-9b4874a658f9.png)

This is my mapping definition:

```
{
    "request": {
        "method": "GET",
        "url": "/wassup",
        "headers" : {
            "X_WASSUP_USER_GID" : {
                "equalTo" : "gid301"
            }
        }
    },
    "response": {
        "status": 200,
        "bodyFileName": "gid301.json",
        "headers": {
            "Content-Type": "application/json"
        }
    }
}
```

Is there something wrong or is just that wiremock does not support this kind of headers?
Thanks

**Comment by tomakehurst** [comment]
Works fine for me. Suggest double-checking that the mapping file is in the right folder.

**Comment by TonyTSharp** [comment]
Hello! I have got almost same issue. I send a request to the wiremock with a header containig underscore (x-my_header). Then I go to the request log, find this request. But there is no that header. If I change underscore to hyphen, I can see it in the log. It seems like an any filter that drop "incorrect" headers. Maybe I lost any setting?
Thanks.

**Comment by tomakehurst** [comment]
@TonyTSharp please can you share full instructions including how you're starting WireMock and configuring stubs etc.?

Happy to reopen and mark as a bug if I can replicate this.
