### ISSUE TITLE
Bug when generating the verification textual result for unmatched query param

### ISSUE THREAD

**Issue by GheorgheBurcea** [tomakehurst/wiremock#484]
In version 2.1.9 of WireMock, the following faulty behavior can be observed related to query parameters :
- define an expected request which contains query param A with value ValA
- make a call to the WireMock server using query param A , but the value ValXYZ
- verify that the request contained query param A with value ValA.
- verification throws VerificationException
- the message of VerificationException doesn't show the query param of expected request correctly. It shows the actual query param (ValXYZ) as expected query param.

The scenario is illustrated in the following app:

```
  import com.github.tomakehurst.wiremock.WireMockServer;
  import com.github.tomakehurst.wiremock.client.RemoteMappingBuilder;
  import com.github.tomakehurst.wiremock.client.VerificationException;
  import com.github.tomakehurst.wiremock.http.RequestMethod;
  import com.github.tomakehurst.wiremock.matching.RequestPatternBuilder;
  import org.apache.http.client.methods.HttpGet;
  import org.apache.http.impl.client.HttpClients;
  import java.io.IOException;

  import static com.github.tomakehurst.wiremock.client.WireMock.*;
  import static com.github.tomakehurst.wiremock.client.WireMock.equalTo;
  import static com.github.tomakehurst.wiremock.client.WireMock.verify;

  public class ForTest3{

  public static void main(String[] args){

     /* start server and configure client */
    int portNumber = 2900;
    WireMockServer wireMockServer  = new WireMockServer(portNumber);
    wireMockServer.start();
    configureFor("localhost",portNumber);

   /* define expectation */
    RemoteMappingBuilder<?, ?> rmb = request("GET",urlPathEqualTo("/test"))
            .withQueryParam("firstParam",equalTo("firstValue"))
            .withQueryParam("secondParam",equalTo("secondValue"))
            .withHeader("aHeader",equalTo("aHeaderValue"))
            .willReturn(aResponse().withHeader("Content-Type","text/plain").withStatus(200).withBody("Success"));
    stubFor(rmb);

    /* execute a request */
    try {
        HttpGet httpGet = new HttpGet("http://localhost:2900/test?firstParam=unexpectedParam&secondParam=anotherUnexpectedParam");
        httpGet.setHeader("aHeader", "aHeaderValue");
        HttpClients.createDefault().execute(httpGet);
    }catch (IOException exc){
        shutdownServer();
        throw new RuntimeException(exc);
    }

    /* check actual interactions */
    RequestPatternBuilder rpb = new RequestPatternBuilder(RequestMethod.GET, urlPathEqualTo("/test"))
            .withHeader("aHeader",equalTo("aHeaderValue"))
            .withQueryParam("firstParam",equalTo("firstValue"))
            .withQueryParam("secondParam",equalTo("secondValue"));
    try {
        verify(1, rpb);
    }catch (VerificationException exc){
        System.out.println("THE MESSAGE:"+ exc.getMessage());
    }

    /* stop server */
    shutdownServer();
}
}
```

The displayed result is

> THE
>     MESSAGE:No requests exactly matched. Most similar request was:  expected:<
> GET
> /test?firstParam=unexpectedParam&secondParam=anotherUnexpectedParam
> aHeader: aHeaderValue> but was:<
> GET
> /test?firstParam=unexpectedParam&secondParam=anotherUnexpectedParam
> aHeader: aHeaderValue>

Besides the issue above , may I suggest making the generated verification message a bit more readable? For instance, to clearly state which is the verb, the headers. And maybe some way of pointing out the difference between the actual and the expected request.
I am suggesting this, because we use WireMock in Integration testing and End To End Testing and the messages are usually read by testers, not developers.

**Comment by tomakehurst** [comment]
Replicated this now. Thanks for reporting.

**Comment by GheorgheBurcea** [comment]
Hi, 
May I ask if you planned in which version of WireMock this bug will be fixed? 
Regards

**Comment by tomakehurst** [comment]
Most likely the next one

**Comment by tomakehurst** [comment]
Not sure when I fixed this, but fixed it is.
