### ISSUE TITLE
Resetting Scenarios is not Resetting the Scenarios in wiremock standalone 2.1.12

### ISSUE THREAD

**Issue by tateexon** [tomakehurst/wiremock#495]
I am seeing an issue where the resetting of the scenarios is not working.

Steps to reproduce:
1. Add some files with scenarios.
2. Start the mock.
3. Run the tests to go through the scenarios.
4. Make the scenario reset call to wiremock.
5. Run the tests to go through the scenarios.

I am expecting the scenarios to reset when making the reset call.
http://host:port/__admin/scenarios/reset
I do indeed fill out both the host and port correctly in that call.

I see this appear in the terminal output:
Received request to /scenarios/reset with body

And then my first call to a url that hits a scenario immediately provides the last state of the scenario instead of the Started state and causes my test to fail.

I am currently working around the issue by killing wiremock and restarting it.

**Comment by fernandofederico1984** [comment]
I'm having the same problem.

**Comment by tomakehurst** [comment]
I followed your steps but couldn't reproduce the problem. Please could you post a unit test case or a script that reliably reproduces it?

**Comment by nabsofken** [comment]
I am having the same issue with wiremock standalone 2.5.0

**Comment by nabsofken** [comment]
@tateexon I found the solution (at least to my problem), I was sending a GET request when it should be a POST request. With this I was able to reset all scenarios. Hope this helps you too

**Comment by AndresTapiero72** [comment]
I am having the same issue with wiremock standalone 2.26.3
@tomakehurst
