### ISSUE TITLE
Would it be possible to have multiple instances of a scenario running?

### ISSUE THREAD

**Issue by Eamerial** [tomakehurst/wiremock#498]
Basically, we would like to run some scenarios in parallel, simulating a chat, and test it with multiple chat sessions at the same time. The scenario allows us to simulate a specific conversation, and having something like session based scenarios would allow us not to mix the conversations between chat sessions.

**Comment by tomakehurst** [comment]
That's an interesting idea.

How would WireMock determine which scenario to apply for a given request?

**Comment by Eamerial** [comment]
we could configure a variable to be passed in either through a request header or a query parameter.

This would imply two configuration parameters, one to define the variable name, and the other to define the variable location ( for example having as default variables "sessionId" and "query)

Then wiremock would keep a map of state engine pointers  for each scenario (each entry in the map would basically be a scenario instance).  Every time the variable would come in, the value would be checked against the map. If existing it would get the current stage on that instance, and if not it would create a new instance with whatever first stage value the scenario defined.

This could cause a lot of unfinished scenario instances, that could be resolved by some timeout cleanup or limiting the amount of concurrent scenario instances, for example... or some other handier method.

**Comment by tomakehurst** [comment]
If you're using request parameters to differentiate, you could achieve this right now as effectively you're talking about different stub mappings. Granted there'd be a bit of duplication, but you could manage that pretty well in the calling code.

**Comment by Eamerial** [comment]
In our particular case I believe the application is using cookies which, granted, we could also use to differentiate. 

The problem would be that it would require to duplicate the stub creation for as many sessions as you would like to have, as well as having a pre-determined set of session cookies whereas with a multi-scenario aware stub server we could have the session generation be also dynamic, and have it scale for as many sessions as we would need.

The multi-scenario feature would also allow multiple parallel tests running instead of a server per setup.

It is mainly interesting for CD/CI environments where multiple products/modules might be building and testing at the same time, for local builds it's not really an issue.

**Comment by Eamerial** [comment]
Hi Tom,

I'm closing this one. I made an extension for it.

Thanks, v.

**Comment by tomakehurst** [comment]
Nice work, thanks for letting me know.

**Comment by sberriman** [comment]
@Eamerial Is there any public release or documentation on your extension? I have a need to do a similar thing, and don't want to reinvent the wheel! :)

**Comment by Eamerial** [comment]
Sorry for the late response, If you're still interested I can check if I can make it public in github

**Comment by andrewhebert** [comment]
@Eamerial I could use a similar thing.  I'd be interested if it could be made public in github.

**Comment by twistedpair** [comment]
@Eamerial I too would find that gist helpful! :smile:

**Comment by royashcenazi** [comment]
Hey @mindprogenitor, came across this as I want to use the extension you wrote, but not readme in the repo :| can you point me to some documentation on how to use it?

**Comment by mindprogenitor** [comment]
Hi Roy,

  Haven't really updated this extension for quite some time now, I wrote some documentation for it at the time for the company I wrote it for, let me see if I can find it and add it to the repo.

**Comment by royashcenazi** [comment]
Thanks, @mindprogenitor! though not needed, found a different solution for my issue.

**Comment by mindprogenitor** [comment]
Good stuff... will hold the doc update then.



cheers,

v.
---- On Fri, 07 May 2021 09:52:00 +0200 royashcenazi ***@***.***> wrote ----




Thanks, https://github.com/mindprogenitor! though not needed, found a different solution for my issue.
