### ISSUE TITLE
RequestPattern breaks  hashCode contract

### ISSUE THREAD

**Issue by ukcrpb6** [tomakehurst/wiremock#501]
RequestPattern breaks java hashCode contract with respect to equals.

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.

```
A = {
  "urlPath" : "/test",
  "method" : "GET"
}
B = {
  "urlPath" : "/test",
  "method" : "GET"
}
A equals B = true
B equals A = true
A.hashCode equals B.hashCode = false
```

this is because hashCode includes `matcher, defaultMatcher` whereas equals does not

**Comment by tomakehurst** [comment]
Thanks for pointing this out. Is this causing a discernable impact somewhere?

**Comment by sta-szek** [comment]
You can use pojo-tester (that I developed) to avoid such a bugs in the future. 
I tests your equals and hashcodes (and more) automatically and find bugs in implementation on test phase.
See more at www.pojo.pl ;)

**Comment by tomakehurst** [comment]
Thanks, will check that out!

**Comment by tomakehurst** [comment]
Ah, shame it's Java 8 upwards. WireMock needs to stay on 7 for a while longer unfortunately.

**Comment by sta-szek** [comment]
Oh 😞 why not switching to 8 :) ?

**Comment by tomakehurst** [comment]
I did briefly in the 2.0-beta, but to howls of complaint. There are still too many folks stuck on 7 so I'm going to wait a while before making the switch.

**Comment by sta-szek** [comment]
So looking forward to java 8 ;)

BTW I you are still interested in `pojo-tester` features (more stable pojo-methods, avoid boilerplate tests), before completly switching to java 8, and using intellij you can switch to java8 in Project Structure ;)

![image](https://cloud.githubusercontent.com/assets/6240704/19050493/19dc8450-89af-11e6-9ed6-42e20cb82838.png)
