### ISSUE TITLE
How to extend wiremock to enable runtime feature of recording and playing back

### ISSUE THREAD

**Issue by nicejack79** [tomakehurst/wiremock#503]
Hi,

I have requirement where I need to see if passed request param has any saved mapping if it does then respond to the request using saved mapping. If not then call actual service and save it for future calls.

I was trying to find the example or documentation but unable to. Please let me know on how I can do if possible some documentation?

**Comment by nicejack79** [comment]
BTW, i am NOT using standalone jar.

**Comment by tomakehurst** [comment]
Please can you post questions (as opposed to bugs/features) on the mailing list, as per the README.
