### ISSUE TITLE
find mock files on classpath

### ISSUE THREAD

**Issue by jbadeau** [tomakehurst/wiremock#504]
What would be really nice is to be able to package mock files in a jar and share them. This doesn't seem possible at the moment. Is this planned?

**Comment by tomakehurst** [comment]
It's not documented at the moment, but there is ``ClasspathFileSource`` which I think  might do what you're looking for.

**Comment by martin-tarjanyi** [comment]
I'm also missing this feature. I've tried the `[usingFilesUnderClasspath](http://wiremock.org/docs/configuration/)` configuration option, but it doesn't seem to work when I run my app as a jar.

**Comment by tomakehurst** [comment]
You're going to have to give me a bit more to go on than that. What error are you seeing? Code? Sure the files are in the right place in the jar?

**Comment by martin-tarjanyi** [comment]
Sorry for the lack of details.

This is my little [project](https://github.com/martin-tarjanyi/spring-practice/tree/wiremock/classpath_issue). A spring Boot application (on port 9999) which starts a WireMock server (port 8080). Configuration: [WireMockService](https://github.com/martin-tarjanyi/spring-practice/blob/wiremock/classpath_issue/src/main/java/com/martin/service/WireMockService.java)

[Location of my stubs](https://github.com/martin-tarjanyi/spring-practice/tree/wiremock/classpath_issue/src/main/resources/wiremock/__files)

When I run it from IDE (IntelliJ) everything works fine. But when I try to run it as a jar, I get an exception:
http://pastebin.com/Sf6ZChLV

For example http://localhost:8080/hello produces this error.

**Comment by tomakehurst** [comment]
Thanks for all the detail. Investigating.

**Comment by tomakehurst** [comment]
Your build puts `wiremock/__files` under `BOOT-INF/classes` in the JAR file. I'm afraid I don't know much about how Spring Boot manages the classpath, but if you can persuade it to place those dirs under the root (as with an ordinary JAR build) that might fix it.

**Comment by balajeetm** [comment]
Hi All,

I want to reopen this issue.
I'm building a simple fat jar (jar with dependencies) which contains the __files and mappings in the classpath (under a folder called stubs). I can see that wiremock is not responding with any of this files but I could see, its picked up the right resource - jar.

This is my configuration 
ClasspathFileSource fileSource = new ClasspathFileSource("stubs/");
mockServer = new WireMockServer(port, fileSource, false);

When i peek into the classpathfileresource, I can see it pick the right jar
System.out.println(fileSource.getUri());

Output:
jar:file:/path/to/fat_jar.jar!/stubs/ 

Can someone tell me the right way to go about this?

**Comment by balajeetm** [comment]
Hi,

I got this working.
The thing is for a FileSystemFileResource, redundant "/"(slashes) still resolve to the file
```
Eg. stubs//mappings
```

But for a classpathfileresource, using jars, redundant slashes lead to issues.
I would still raise this a bug.

@tomakehurst ,
What do you think?

**Comment by tomakehurst** [comment]
I guess we could strip redundant slashes in WireMock. I doubt I'll manage to work on this any time soon, but I'm happy to receive a PR.

**Comment by polaroi8d** [comment]
This issue is still consist?

**Comment by tomakehurst** [comment]
Yeah, nothing has happened since the last comment. My offer to merge a PR still stands.

**Comment by BoukeNijhuis** [comment]
Hi,

I use the following simple workaround.

WireMockServer wireMockServer = new WireMockServer(options().fileSource(new ClasspathFileSourceWithoutLeadingSlash()));
wireMockServer.start();

/*
 * Without this class Wiremock tries to find the mappings directory under /mappings and the classloader will not find this
 * directory because of the leading slash. This class removes the leading slash and as a consequence the classloader
 * will find the mappings directory.
*/
class ClasspathFileSourceWithoutLeadingSlash extends ClasspathFileSource {

    ClasspathFileSourceWithoutLeadingSlash() {
        super("");
    }

    @Override
    public FileSource child(String subDirectoryName) {
        return new ClasspathFileSource(subDirectoryName);
    }
}

**Comment by brmeyer** [comment]
PR attempt: https://github.com/tomakehurst/wiremock/pull/944

**Comment by vivin** [comment]
For the initial issues, I was able to get `usingFilesUnderClasspath` to work by prefixing the path with `BOOT-INF/classes`. My mapping files are under `src/main/resources/wiremock` so instead of using `wiremock` as the path, I modified it to `BOOT-INF/classes/wiremock`.

**Comment by tomakehurst** [comment]
@vivin thanks for sharing this. Good to know there's a workaround.

**Comment by mikhail-putilov** [comment]
> There are two different issues discussed in this thread. Regarding the original issue, i.e. the Spring Boot problem, you can solve it by adding this to your pom. In my case, the final jar is called "app.jar", you might need to configure that. And I have the files under src/main/resources/wiremock.
> 
> ```
>   <build>
>     <plugins>
>       <plugin>
>         <artifactId>maven-antrun-plugin</artifactId>
>         <executions>
>           
>           <execution>
>             <id>addWiremockFilesOnRootLevel</id>
>             <phase>package</phase>
>             <configuration>
>               <target>
>                 <zip destfile="${project.build.directory}/app.jar" update="yes" compress="false">
>                   <zipfileset dir="${project.build.directory}/classes/wiremock" prefix="wiremock"/>
>                 </zip>
>               </target>
>             </configuration>
>             <goals>
>               <goal>run</goal>
>             </goals>
>           </execution>
>         </executions>
>       </plugin>
>     </plugins>
>   </build>
> ```

Thanks for sharing this!

I spent some time trying to figure it out, what I did wrong. Here is my final setup:

* I use `${build.finalName}` instead of `app.jar`: `<zip destfile="${project.build.directory}/${build.finalName}.jar" update="yes" compress="false">`
* I tried to make it work without `wiremock` folder under `src/main/resources`, it did not work out. I don't know why
* I made spring boot to run wiremock as a bean:
```java
@Bean(initMethod = "start", destroyMethod = "stop")
    WireMockServer wireMockServer() {
        WireMockConfiguration cfg = new WireMockConfiguration()
                .port(8080)
                .extensions(new ResponseTemplateTransformer(true), new Webhooks())
                .usingFilesUnderClasspath("wiremock");
        return new WireMockServer(cfg);
    }
```

**Comment by pards** [comment]
For the Spring Boot executable jar vs IDE:

Assuming your stubs and mappings are in `src/main/resources/wiremock/__files` and `src/main/resources/wiremock/mappings` then this code should work when running from either your IDE or from the executable jar file produced by the spring-boot-maven-plugin

`
@Bean
public Options wireMockOptions() throws IOException {
    return WireMockSpring.options()
            .port(8080)
            .fileSource(fileSource("wiremock"))
            ;
}

private FileSource fileSource(String path) {
    FileSource fs = null;
    try {
        fs = new ClasspathFileSource(path);
    }
    catch(Exception x) {
        log.debug("Running via executable jar; using BOOT-INF folder.");
        fs = new ClasspathFileSource("BOOT-INF/classes/" + path);
    }
    return fs;
}
`
