### ISSUE TITLE
Add an extension point for transforming recordings as they're made

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#506]

**Comment by marksievers** [comment]
Is this providing ReponseTransformers at time of stub declaration, rather than at WireMockRule creation time? 

Something like this?

```java
        stubFor(post(urlEqualTo("/foobar)"))
                        .willReturn(aResponse()
                                        .withHeader("Content-Type", "application/json")
                                        .withBody("....")
                                        .withTransformer(new CustomerTransformer(testState))));
``` 

This would be a great addition to the API.

**Comment by tomakehurst** [comment]
This particular issue is actually about being able to apply a transformation to recordings rather than stubs. I've had quite a few requests recently for various tweaks to the recorder's output that are quite context specific, so I thought an extension point would be the best way to accommodate these.

I can definitely see the usefulness of what you're describing though. IIRC the only reason I didn't do it was time constraints.

I'd happily accept a PR if you're up for it.

**Comment by marksievers** [comment]
@tomakehurst Sweet. Will take a look a solution for this after I get a PR for https://github.com/tomakehurst/wiremock/issues/517 ready and merged.

**Comment by tomakehurst** [comment]
Done in #674
