### ISSUE TITLE
EnableRecordMappings on, multiple mappings with the same URL. Wiremock does not serve mappings in proper order

### ISSUE THREAD

**Issue by antogc** [tomakehurst/wiremock#509]
Hi Tom, 

First of all, congrats for the great job with Wiremock, is really  a awesome tool. 

I'm using wiremock as a version comparator tool. The idea is,  two  versions of the same tool, using wiremock as a proxy server, the first iteration we run the first version with wiremock with the enableRecordMappings to true. The idea is to store diferent calls to upstream services. The second iteration (using the second version), will use recorded mappings to ensure the response from upstream server are exactly the same. Obviously, the calls are exacly the same in both iterations. 

The issue comes when we have several calls to the same URL but with different responses. Wiremock is returning always (2nd iteration) the first mapping stored. 

It would be great that wiremock were aware about the order in which calls are requested. 

Another way would be that wiremock could "consume" mappings, I mean, once a mapping is returned in a request, it will be removed form the mapping lists. If the mapping lists has the the right order (sorted by creation date ASC) we could ensure all mappings are returned in the right order. 

Any idea?

Thanks in advance,

**Comment by tomakehurst** [comment]
At present you're out of luck I'm afraid.

You're not the first to have asked for something like this, and I have a to-do list item to better support this kind of case.

Watch this space!
