### ISSUE TITLE
Not able to create mappings with ID using REST API

### ISSUE THREAD

**Issue by ike18t** [tomakehurst/wiremock#516]
Documentation doesn't show an example of how to create a mapping with an id using the REST API, it only shows edit.  I've tried what I thought might work but with no success.

![screen shot 2016-10-18 at 11 56 31 am](https://cloud.githubusercontent.com/assets/166701/19485740/006fb5b0-952a-11e6-8824-19dc3d958bde.png)

**Comment by tomakehurst** [comment]
The problem is the /foo on the end of the URL. Please can you post future questions to the mailing list as per the README.
