### ISSUE TITLE
Slowness when using "jsonBody" to pass formatted JSON response

### ISSUE THREAD

**Issue by tfinleybb** [tomakehurst/wiremock#518]
At first I had mocked API responses that specified a body with unformatted JSON. I decided to change the reformat the responses into formatted JSON using "jsonBody" to make them easier to read, and I found that the response times are WAY longer than when I used unformatted JSON. It would be nice if there were a way to mitigate this.

**Comment by tomakehurst** [comment]
Please can you provide a test case that demonstrates this?
