### ISSUE TITLE
ResponseDefinitionBuilder.like() doesn't keep original transformer parameters

### ISSUE THREAD

**Issue by Eamerial** [tomakehurst/wiremock#521]
During the like operation, the transformer parameters are not copied. This means that chaining extensions will be cumbersome if extensions beyond the first one in the chain use any parameters, the previous extensions need to make sure the parameters are inserted back in the response definition.

This can be achieved generically by listing the transformer parameters and re-add them to the response definition, but I don't think that is the extension.

I would just add the transformer parameters by default, since extensions shouldn't know in advance if any other extension will be used, and if it is, which one will be used (I would expect). This is aggravated by the fact that the transformers are kept in a hash, so the order in which the transformers are applied is not easy to enforce (perhaps a nice feature request).

Cheers

**Comment by tomakehurst** [comment]
Thanks for pointing this out. I really need to find a usable reflection-based test util for this - I keep missing this part when I add attributes to model classes.
