### ISSUE TITLE
wiremock transformer is not replacing the json path with value instead returns null

### ISSUE THREAD

**Issue by balasara** [tomakehurst/wiremock#523]
Request Json is :
{
	"overrideStandardShippingAsFree":false,
	"requestInfos":
	[
		{
			"skuId":"4423521",
			"itemSeqNumber":"hgvbh",
			"postalCode":"55423",
			"poBox":false,
			"quantity":1,
			"fulfillmentType":"SHIPPING"
			
		}
		]
	
}

I need to send the response based on the request.For say i need to send the skuId as response.I have used the wiremock transformer

stubFor(post(urlEqualTo("/url")).withRequestBody(matchingJsonPath("$.requestInfos[0].skuId"))
.willReturn(aResponse()
.withStatus(200)
 .withHeader("content-type", "application/json")
.withBody("{\"responseName\": \"$($.requestInfos[0].skuId)\"}") 
 .withTransformers("body-transformer")));

It is returning null in the place of the json path $($.requestInfos[0].skuId)\"}

**Comment by tomakehurst** [comment]
Sorry, I should have been more explicit - you'll need to post this on the wiremock-body-transformer project. The maintainers are unlikely to see it here either.
