### ISSUE TITLE
Can we stub file downloads? For Android?

### ISSUE THREAD

**Issue by mikelupo** [tomakehurst/wiremock#524]
For Android.

We are testing a REST API service (from the Android client's perspective). Our project is in its infancy. We have WM responding to REST API requests. Thank you for that!

What about requests for content? For example, an HTTP request for a .mp4 file.
http://foo.bar.com/my/content/some.mp4
I've tried to garner this information from the docs, examples, but as such they are not geared towards Android.

I imagine that the the file would reside in my Resources (or even better, on my SD card), but not clear on how I'd form the aResponse with it.

Any insight is appreciated.

Thanks!

**Comment by tomakehurst** [comment]
I suggest encoding the file as base 64 and configuring your stub response with that (using the `base64Body` attribute instead of `body`).

As per the README, please can you post future questions on the mailing list.
