### ISSUE TITLE
urlPathEqualTo decodes the path before matching, urlEqualTo does not

### ISSUE THREAD

**Issue by zuckel** [tomakehurst/wiremock#527]
I'm having problems with a case where parts of the URL path are URL encoded.
`.urlEqualTo()` matches as expected, but `.urlPathEqualTo` does not.
The reason for this is that the path is decoded in UrlPathPattern using `URI.create(url).getPath()`.
`.getPath()` does URL decoding. The correct method would be `.getRawPath()`.

```java
@Test
public void matchingUrlPathsWithEscapeCharacters() {
   stubFor(get(urlPathEqualTo("/%26%26The%20Lord%20of%20the%20Rings%26%26")).willReturn(aResponse().withStatus(HTTP_OK)));
    assertThat(testClient.get("/%26%26The%20Lord%20of%20the%20Rings%26%26").statusCode(), is(HTTP_OK));
}
```

**Comment by tomakehurst** [comment]
Right, I can see the problem. I'll merge your PR.

**Comment by tomakehurst** [comment]
Ah hang on, it's not a PR. Could you raise one for the commit you've linked to on this thread?

**Comment by zuckel** [comment]
Sorry, I'm not super experienced with GitHub, but I thought I created #528 as a PR... Do I need to rebase something?

**Comment by tomakehurst** [comment]
Ah yeah you did create a PR. It's just that the linked commit is on your own branch. Thanks, I'll merge that.
