### ISSUE TITLE
False positives for "near misses" when using multiple Wiremock instances

### ISSUE THREAD

**Issue by wITTus** [tomakehurst/wiremock#530]
Hi,

using multiple Wiremock instances, e.g. like this:

```
    @Rule
    public WireMockRule wiremockA = new WireMockRule(8086);

    @Rule
    public WireMockRule wiremockB = new WireMockRule(8087);
```

and calling e.g. `wiremockB.verify()` may report near misses for stubs registered on `wiremockA`.

Note that `wiremockB` is registered on a different port. I can't think of any scenario in which this behavior is expected.

Might be due to a static method invocation at: https://github.com/tomakehurst/wiremock/blob/982236cbcc308ee3747480941ca9ab197f9a0394/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java#L396 which makes use of a static default instance. Maybe the non-static method call which goes by the same name would yield the correct behavior?

Best Regards,
Sascha

**Comment by tomakehurst** [comment]
This was a bug a while ago, when the static method was being called. But now it's using the instance method (including where you've linked to) and I can't replicate the bug you're describing.

Please could you supply a test case?

**Comment by wITTus** [comment]
You're right. Upgrading from 2.1.2 to 2.3.1 solved the problem. I did not catch the `All` in `findAllNearMissesFor`.

Besides, upgrading broke several tests making use of JSON path, which led me to the question if there's any migration guide available?

Thank you and keep up the good work!

**Comment by tomakehurst** [comment]
There was an upgrade to the JSONPath library version recently, which probably explains the broken tests (unfortunately, it's not a standard and doesn't seem to be strict about keeping backwards compatible between minor versions). I can only suggest taking a look at their site.
