### ISSUE TITLE
Can we add the shutdown API command to the API Reference?

### ISSUE THREAD

**Issue by halfer** [tomakehurst/wiremock#545]
The API reportedly supports `__admin/shutdown` as per the [notes here](http://wiremock.org/docs/running-standalone/) but it is not mentioned [here at all](http://wiremock.org/docs/api/). Is this an oversight, and if so can it be rectified?

Thanks!

**Comment by tomakehurst** [comment]
It is, and yes it can.

**Comment by halfer** [comment]
Great, thanks. If it is something a non-Java person can help with, do let me know. Or is it just a case of regenerating things in Swagger?

**Comment by tomakehurst** [comment]
It's just a case of adding it to the RAML spec (from which the Swagger spec is generated). At the moment I'm the only one who can re-publish the site, but if you'd like to update the RAML, I'll happily accept a  PR.

**Comment by halfer** [comment]
This has been merged, will close.

@tomakehurst, would you [regen the API docs](http://wiremock.org/docs/api/) when you get a mo? I expect it is just a button push?
