### ISSUE TITLE
How to use urlPathPrefix in WireMock?

### ISSUE THREAD

**Issue by sammizo** [tomakehurst/wiremock#558]
Hi,

Could you give me an idea about using the WireMock constructor with the urlPathPrefix?
I am not sure if it needs anything set up in the standalone-running WireMockServer. It clearly doesn't work with the default setup of WireMockServer.

Thank you,
Michael

**Comment by tomakehurst** [comment]
As per the README, please post questions to the mailing list rather than opening issues.
