### ISSUE TITLE
Feature Request: Ability to have mappings recorded un-gzipped even when the server responds with a gzipped response.

### ISSUE THREAD

**Issue by yogurtearl** [tomakehurst/wiremock#56]
It could be useful to have mappings recorded uncompressed. This would allow for easier editing of the body files. Of course, you would want to remove "Content-Encoding" : "gzip" from the response header as well. 

Maybe it could be a command line option --store-mappings-uncompressed

**Comment by txjohng** [comment]
Hi guys, this feature would be a super useful feature where I work. Is there anyway to get this change into the next release?  thanks!

**Comment by tomakehurst** [comment]
GZip support now in 2.0.7-beta
