### ISSUE TITLE
WiremockRule is initialied twice 

### ISSUE THREAD

**Issue by arnzel** [tomakehurst/wiremock#566]
Hi,

when i use the following everything is okay

    	@Rule
	        public WireMockRule wireMockRule = new WireMockRule(10000);

But when i use the following, the Wiremockrule is initialized twice and i get an error "Address is already used"

    	@Rule
	        public WireMockRule w(){
		    return new WireMockRule(10000);
	        }

**Comment by tomakehurst** [comment]
I didn't even know the second form was valid, but if so it's probably JUnit that's causing the double instantiation.

**Comment by arnzel** [comment]
I am not sure. When i use annother rule, for an example "TemporaryFolder" this does not happen.

**Comment by arnzel** [comment]
I think it is because "WiremockRule" implements both "MethodRule" and "TestRule". Is ist neccessary to implement both ?

**Comment by tomakehurst** [comment]
That sounds entirely plausible. The reason it implements both is for backwards compatibility with older JUnit versions.

Is there a specific reason you need to use the second form?

**Comment by arnzel** [comment]
yes, i want to create the port in a dynamic way(not always 10000 like in my example).

**Comment by tomakehurst** [comment]
OK, somewhere down the line I'm probably going to rewrite the rule classes, so I'll bear this in mind.

Meanwhile, writing your own rule that only implements `TestRule` wouldn't be difficult if you wanted to go down that route. You could just copy the existing one and drop the `MethodRule` part.

**Comment by arnzel** [comment]
okay this is acceptable workaround. Thanks !
