### ISSUE TITLE
Store values between requests

### ISSUE THREAD

**Issue by viniciusffj** [tomakehurst/wiremock#569]
Hi.

I'm using wiremock and I need a feature that I'm not sure if it already exists.

I've created a mock that has 3 requests (let's say A, B, C).
In request A, the first one, I receive a dynamic-value parameter that I'll need in request C, the last one.

Does exist any feature to store this parameter in request A and use it in request C?

**Comment by tomakehurst** [comment]
This feature doesn't exist, and I don't think it's something I'd want to add to WireMock's core as it seems hard to generalise without a lot of complexity.

You could probably achieve this for the specific case you'd like to implement by writing an extension.

**Comment by viniciusffj** [comment]
@tomakehurst I agree it shouldn't be part of wiremock's core.

I just created this issue to make sure I don't reinvent the wheel.

**Comment by tomakehurst** [comment]
Cool

**Comment by rubyjt479** [comment]
Is there is an existing extension that can achieve this?

**Comment by tomakehurst** [comment]
Not that I'm aware of at the moment. If you'd like to be the first to build one, I'll happily link it from wiremock.org!

**Comment by viniciusffj** [comment]
@rubyjt479 @tomakehurst In the project that I was working we created a small extension to do this

We didn't publish it because we did a simple solution that only solved our problems
