### ISSUE TITLE
Mapping from multiple sources not working

### ISSUE THREAD

**Issue by lsuski** [tomakehurst/wiremock#576]
Hi,
I realized recently that there is no way to setup WireMock for with multiple mapping and files sources. In my case I have some base library with base mappings and 2 end applications with additional mappings. To make this work I wrote custom implementation of FileSource able to handle multiple classpath and file locations. the only problem is with getUri() method which in fact is never used and I left it empty. I could make a PR if you find this functionality useful.

**Comment by tomakehurst** [comment]
Can I suggest you create a separate project? I'd be happy to link to it from the site once it's published.

**Comment by lsuski** [comment]
Ok, I'll prepare some and give you a link here

**Comment by tomakehurst** [comment]
Thanks

**Comment by szjani** [comment]
Hi @tomakehurst 
I subscribed to this issue since I also faced with this one a while ago. I cannot provide you any examples right now, I'm just wondering why you have closed it.

**Comment by lsuski** [comment]
Hi @szjani, 
I should prepare sample but I forgot about it, I was busy and didn't use wiremock for a long time, I can upload my working class for this scenario but at the end of July.

**Comment by tomakehurst** [comment]
Happy to re-open when this is ready

**Comment by lsuski** [comment]
This is class which works for me - some methods are not implemented because I didn't need them.
https://gist.github.com/lsuski/d8453532fa6f31011251df8746cb3784
