### ISSUE TITLE
Response Templating : get first value / get nth value of a query parameter, how is this handled by handlebars ?

### ISSUE THREAD

**Issue by StefH** [tomakehurst/wiremock#582]
The documention states

> 
> request.query.<key>- First value of a query parameter e.g. request.query.search
> 
> request.query.<key>.[<n>]- nth value of a query parameter (zero indexed) e.g. request.query.search.[5]

So does this mean that I can use both syntax always ?
If my request is like `/x?p=1&p=2`, I can use :

1. request.query.p --> returns "1"
2. request.query.p.[0] --> --> returns "1"

?

**Comment by tomakehurst** [comment]
Can you post questions on the mailing list rather than opening issues as per the README please.

**Comment by StefH** [comment]
Sorry.
