### ISSUE TITLE
Inaccurate timestamps in AdminRequestHandler logs

### ISSUE THREAD

**Issue by GBear26** [tomakehurst/wiremock#587]
Excerpt of logging output showing AdminRequestHandler's "Request received: ..." logs with out-of-sequence timestamps alongside other logs with in-sequence timestamps. 

```
2017-01-20T15:48:55.038Z
2017-01-20T15:48:55.039Z
2017-01-20T15:48:55.041Z
2017-01-20 10:48:55.46 Request received:
2017-01-20 10:48:55.113 Request received: 
2017-01-20T15:48:55.117Z
2017-01-20 10:48:55.143 Request received:


```
It's as if the .46 in the first "Request received: ..." log should be .046.  This appears consistent with the implementation.  When AdminRequestHandler logs using the com.github.tomakehurst.wiremock.common.ConsoleNotifier, it does so using new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S") to format the current Date. According to https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html, 

> For [Number] formatting, the number of pattern letters is the minimum number of digits, and shorter numbers are zero-padded to this amount. For parsing, the number of pattern letters is ignored unless it's needed to separate two adjacent fields.

  This leads me to believe the format string used should be "yyyy-MM-dd HH:mm:ss.SSS". (two more S chars).

Here's a failing jUnit test:
```
    @Test
    public void format_returnsStringWithCorrectMillisPart() throws Exception {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
        long timeEndingIn004 = Instant.now().getEpochSecond() * 1000 + 4;

        String formattedDate = df.format(new Date(timeEndingIn004));

        String formattedMillisPart = formattedDate.substring(formattedDate.lastIndexOf(".") + 1);
        assertEquals("004", formattedMillisPart);
    }
```
Fails with `org.junit.ComparisonFailure: expected:<[00]4> but was:<[]4>`. After appending two "S" to the format string, the test passes.

**Comment by tomakehurst** [comment]
Yep, agree. I'll switch to the format you've suggested.
