### ISSUE TITLE
Charset of response is not UTF-8 on Windows

### ISSUE THREAD

**Issue by ffremont** [tomakehurst/wiremock#588]
In standalone mode, when i post utf-8 mock from postman, my browser show response with windows charset.
I don't find solutions even with transformers to force utf-8 data in response.

My data is based on UTF-8
Java file.encoding : cp1252 
it's not normal, my reponse http://localhost:8080/a must be in UTF-8 charset because all of web resources are often in UTF-8.

![capture](https://cloud.githubusercontent.com/assets/5568721/22211570/b2c5d9c4-e18d-11e6-933c-9d7b292916e7.PNG)
![capture_](https://cloud.githubusercontent.com/assets/5568721/22211646/0ac25c56-e18e-11e6-8497-0b759472f47c.PNG)

Do you have a solution ?

**Comment by tomakehurst** [comment]
For future ref, please can you post questions on the mailing list as per the README.

Meanwhile, have you tried setting the charset explicitly in the java command?

**Comment by ffremont** [comment]
Yes, i tried to force "file.encoding" to UTF-8 and it's solves my issue.
But, i can not use this because my JVM uses other soft.

In fact, i use wiremock in maven plugin mode in a Jenkins environment. I can not afford to globify the Maven configuration for a Wiremock bug.

The best practice is not to rely on system encoding.

I will post on the mailing list, thank you,
