### ISSUE TITLE
ResponseTemplateTransformer and withBodyFile (v2.5.0)

### ISSUE THREAD

**Issue by chriswhite199** [tomakehurst/wiremock#593]
`ResponseTemplateTransformer` doesn't appear to be able to use `withBodyFile` (and if this is intentional, I don't see a warning in the documentation noting as such).

Looks like the following code in `ResponseTemplateTransformer.transform` is where the issue is - as `responseDefinition.getBody()` returns null when `responseDefinition.bodyFileName` is populated

        if (responseDefinition.getBody() != null) {
            Template bodyTemplate = uncheckedCompileTemplate(responseDefinition.getBody());
            String newBody = uncheckedApplyTemplate(bodyTemplate, model);
            newResponseDefBuilder.withBody(newBody);
        }

**Comment by tomakehurst** [comment]
Thanks for pointing this (somewhat glaring omission) out. Fix on the way.
