### ISSUE TITLE
Speed up wiremock

### ISSUE THREAD

**Issue by zaffranad** [tomakehurst/wiremock#596]
Hi everyone.

First of all, I wanted to send you all a big thank you for your work on wiremock.
It is a life savior for our tests. A very useful tool.

Then, my issue is, as you may have guess from the title, concerning the performance of wiremock.
We use it mainly for replaying stubbed answers from one our partners. Answers are REST endpoint responses to some requests and the response is JSON formatted.

Wiremock works great but we are facing some strange issue: wiremock, even requested locally from the same machine, responds really slowly. Slowly is maybe not the best term, but we see response times around 800ms /900ms when our partners (remote partners) respond in real life around 300ms.

The gap seems huge since the partners respond something from a real calculation. 
Is there something we may have missed from the wiremock configuration, or a way to speed up everything?

As an additional information, we of course do not use the delay configuration that may be useful to force wiremock to respond at a specific delay.

Hoping my question is clear (english is not my first language).

Regards

**Comment by tomakehurst** [comment]
In a typical setup WireMock usually replies in the 5-20ms range, so there's clearly something about your configuration that's making it run slowly.

Can I suggest you post this as a question on the mailing list, along with your code, stubs and a few details about how you're running it (OS, hardware/VM etc.)

**Comment by zaffranad** [comment]
problem solved by upgrading from 2.1.x to 2.5.1!
Thanks

**Comment by tunovic** [comment]
When I upgrade from 2.6.0 to 2.7.0 or 2.8.0 the Maven build time goes up from about 3 minutes to about 10 minutes. This is the only dependency that is changed. I don't know to what it is related? But it sounds similar to initial thread.

**Comment by tomakehurst** [comment]
You're going to have to give me a bit more than that if I'm going to have any chance of replicating the problem.

How many stubs do you have? What features do they use? How big are the request and response payloads? Are you using json or XML?

**Comment by tunovic** [comment]
private static final WireMockServer wireMockServer = new WireMockServer(options().port(PORT)
            .notifier(new Slf4jNotifier(true)));

90 stubs
25 xml
65 json

1 to 59 KB

**Comment by tomakehurst** [comment]
OK. Realistically I'm not going to be able to diagnose a performance problem based on what you've posted, so I'm going to suggest you run a profiler against your project and see where the bottleneck is. I'll be more than happy to accept a fresh bug report if you find that something WireMock has regressed.
