### ISSUE TITLE
WireMockRule cause error 500 when getInputStream from urlConnection

### ISSUE THREAD

**Issue by Aure77** [tomakehurst/wiremock#597]
Is it normal that the code above cause a HTTP response code: 500 ? :
```
public class MyTest {

    @Rule
    public WireMockRule wireMockRule = new WireMockRule(7032);

    @Test
    public void exampleTest() throws IOException {
        stubFor(get(urlEqualTo("/my/resource"))
                .withHeader("Accept", equalTo("text/xml"))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withHeader("Content-Type", "text/xml")
                        .withBody("<response>Some content</response>")));

        URLConnection urlConnection = new URL("http://localhost:7032/my/resource").openConnection();
        Assert.assertNotNull(urlConnection.getInputStream()); // java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:7032/my/resource
    }

}
```

It's throw 

> java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:7032/my/resource

I am using Wiremock 2.5.1 with JUnit 4.12.

**Comment by tomakehurst** [comment]
Works OK for me, same versions and test code.

Had to comment out the Accept header to get a 200 though as your URLConnection doesn't have it set.

**Comment by Aure77** [comment]
I also test without accept header but I have same issue. Further more, in debug using breakpoint before openConnection, I can't call this URL through my brosser (i never get response...). I also try using mappings folder with same issue. I am using JDK 1.7_79 and maven-compiler-plugin target and source are set to 1.6 (may this config can cause problem ?)

**Comment by tomakehurst** [comment]
Current WireMock JDK support is 7+ so I'm surprised it's working at all.

If bumping the Java version doesn't work, I suggest enabling verbose logging. WireMock should log the reason it's returning a 500.

**Comment by Aure77** [comment]
I found the problem. My projet (target 1.6) is using servlet-api 2.5 as dependency to compile my sources (I am using an old application server).
```
<dependency>
	<groupId>javax.servlet</groupId>
	<artifactId>servlet-api</artifactId>
	<version>2.5</version>
	<scope>provided</scope>
</dependency>
```
But it is in conflict with Wiremock jetty servlet api version 3.1 causing error 500...
Any solution to isolate wiremock test dependencies (I can upgrade my project to servlet api 3.1) ?

**Comment by tomakehurst** [comment]
That's a hard one to solve unfortunately, other than by running WireMock in a separate process.
