### ISSUE TITLE
Max number of concurrent requests with fixedDelayMilliseconds

### ISSUE THREAD

**Issue by juribes** [tomakehurst/wiremock#598]
I am using a stand alone wiremock (wiremock-standalone-2.5.0.jar)
I have a stub like this:
{
    "request": {
        "method": "GET",
        "urlPattern": "/path/to/my/resource.*"
    },
    "response": {
        "status": 200,
        "jsonBody": {
			"Decisions": {"rootFolder": "Allow" }
		},
		"headers": {
			"Content-Type": "application/json"
		},
		"fixedDelayMilliseconds": 15000
    }
}

When I launch a test with jmeter (10 threads, 1 loop) I get this 
![image](https://cloud.githubusercontent.com/assets/8532620/22531096/ef71fa58-e8ac-11e6-8831-2c2860d7928e.png)

4 groups of responses. The first one has 15 seconds of delay (as expected) then the second group near 2x15 sec, then the third group near 3x15 sec of delay and the pattern continues.

Is it a limit of requests with delay simultaneously?

log:
timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,grpThreads,allThreads,Latency,IdleTime
1485991132330,15066,HTTP Request,200,OK,Thread Group 1-3,text,true,,237,20,20,15066,0
1485991132380,15016,HTTP Request,200,OK,Thread Group 1-4,text,true,,237,20,20,15016,0
1485991132291,15106,HTTP Request,200,OK,Thread Group 1-2,text,true,,237,20,20,15106,0
1485991132229,15167,HTTP Request,200,OK,Thread Group 1-1,text,true,,237,20,20,15167,0
1485991132430,15012,HTTP Request,200,OK,Thread Group 1-5,text,true,,237,16,16,15012,0
1485991132480,15009,HTTP Request,200,OK,Thread Group 1-6,text,true,,237,15,15,15009,0
1485991132530,29875,HTTP Request,200,OK,Thread Group 1-7,text,true,,237,14,14,29875,0
1485991132581,29826,HTTP Request,200,OK,Thread Group 1-8,text,true,,237,13,13,29826,0
1485991132681,29727,HTTP Request,200,OK,Thread Group 1-10,text,true,,237,13,13,29727,0
1485991132631,29780,HTTP Request,200,OK,Thread Group 1-9,text,true,,237,11,11,29780,0
1485991132731,29714,HTTP Request,200,OK,Thread Group 1-11,text,true,,237,10,10,29714,0
1485991132782,29709,HTTP Request,200,OK,Thread Group 1-12,text,true,,237,9,9,29709,0
1485991132831,44577,HTTP Request,200,OK,Thread Group 1-13,text,true,,237,8,8,44577,0
1485991132933,44479,HTTP Request,200,OK,Thread Group 1-15,text,true,,237,7,7,44479,0
1485991132882,44531,HTTP Request,200,OK,Thread Group 1-14,text,true,,237,6,6,44531,0
1485991132983,44435,HTTP Request,200,OK,Thread Group 1-16,text,true,,237,5,5,44435,0
1485991133032,44418,HTTP Request,200,OK,Thread Group 1-17,text,true,,237,4,4,44418,0
1485991133083,44413,HTTP Request,200,OK,Thread Group 1-18,text,true,,237,3,3,44413,0
1485991133133,59279,HTTP Request,200,OK,Thread Group 1-19,text,true,,237,2,2,59279,0
1485991133183,59232,HTTP Request,200,OK,Thread Group 1-20,text,true,,237,1,1,59232,0

**Comment by tomakehurst** [comment]
The default number of container threads is quite small and delays are blocking at the moment, so you won't get much throughput with big delays like that. 

I suggest raising the container threads parameter to something like 200-400.

**Comment by juribes** [comment]
Hi, @tomakehurst changing that parameter works perfectly in standalone and java version. The Defaults value has an error in the documentation here http://wiremock.org/docs/configuration/

> // Set the number of request handling threads in Jetty. **Defaults to 10.**
> .containerThreads(5)

and here http://wiremock.org/docs/running-standalone/

> --container-threads: The number of threads created for incoming requests. **Defaults to 200.**

It looks like the default is 6 in doth cases.

Thx for your help, bug fixed!

**Comment by tomakehurst** [comment]
Good catch, thanks for pointing that out.

**Comment by azeem1396** [comment]
Hi @tomakehurst ,

I am running wire mock as a standalone service with the following configurations
1. container threads 400
2. async response enabled
3. async response threads 100

The number of CPUs assigned to the service is 500 milliCPUs

**Issue** 
While hitting 8 concurrent requests to the mock server, I face inconsistent behaviour. Only a couple of times response is received for all 8 requests.

Please suggest the ideal configuration for the 8 concurrent requests.

**Comment by tomakehurst** [comment]
@azeem1396 I suggest you jump on the new Slack community and ask this question there: https://join.slack.com/t/wiremock-community/shared_invite/zt-1mkbo0zlx-gxeZdTJ15Kchdt888Fn_1A
