### ISSUE TITLE
note: "The recorder will ignore any request matching one it has already captured."

### ISSUE THREAD

**Issue by ph-ms** [tomakehurst/wiremock#601]
Here's an enhancement request ...

http://todobackend.com/ has specs (JavaScript in a WebPage) that will CORS attach to any of the multitude of backends that are compliant, and pass.

If you put WireMock in the middle to record that traffic, the tests should **still pass**, but the saved off journal will not be sufficient for a playback/simulation as it's a map of responses to request not a journal of all requests and responses.

Now, I'm not suggesting that playback should be able to magically work in that situation, just that an adept programmer can take the serialized journal of interactions and dynamically reprogram WireMock between test method interactions.  This reprogramming would be an 'expectations' mode of operation if you don't have it already.

**Comment by tomakehurst** [comment]
Have you seen https://github.com/tomakehurst/wiremock/issues/546?

I think what's proposed there would satisfy your requirement.

**Comment by tomakehurst** [comment]
New recorder being implemented in #674
