### ISSUE TITLE
Logging response via standalone server?

### ISSUE THREAD

**Issue by EllaVader** [tomakehurst/wiremock#602]
Is there anyway to enable logging via the standalone server?  Not logging to the output console via the --verbose argument, but rather directing the logs to a file?  It would be really slick to configure a way to log the response from a request to a file if we could indicate the directory location and the filename+{some timestamp}.  

And to even build on that have the directory location be dynamic enough to be created if if doesn't exists and to allow it to be based off of some token.  For example, I'd like logs to get written to a logs/{environment}/ImagesResponse-{yyyyMMddHHmmss}.txt and the {environment} would be obtained from something in the request URL path (depending on the testing environment we are testing against).

I don't like having to write a custom transformer for every single one of the mocks we are setting up just to get the response to log to a file.  Plus it makes the command to start standalone wiremock really long.  For example, this is what I'm using to start up the standalone server because I've written transformers for every one of our requests so far.  Is there an easier way to start up all these transformers?

java -cp "wiremock-responses-1.0.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --verbose --port 8888 --extensions extension.manheim.InLaneTransformer,extension.manheim.BuyerAccountTransformer,extension.manheim.PurchaseAPITransformer,extension.manheim.ConsignmentTransformer

**Comment by tomakehurst** [comment]
There isn't an in-built way to do this, but you could write a generic extension of the type `PostServeAction` that logs completed requests to a file format of your choosing.

**Comment by EllaVader** [comment]
That's what I thought. Thanks  Tom!

Janine

**Comment by tomakehurst** [comment]
No probs

**Comment by keithdtyler** [comment]
I simply redirect the WM output to a file: `java -jar wiremock*.jar >> logfile`

I run multiple WMs at once for different endpoints and they each pipe to a distinct logfile and it works well.

**Comment by joseslneto** [comment]
Hello guys, while running **wiremock-standalone**, you have any example of how to put all wiremock logs into a file (not stay just in stdout)?

**Comment by robertofabrizi** [comment]
> Hello guys, while running **wiremock-standalone**, you have any example of how to put all wiremock logs into a file (not stay just in stdout)?

I'm trying it but unsuccessfully, setting -D properties to logging config files doesn't seem to work :-(
