### ISSUE TITLE
Lack of compatibility with Jetty 9.4

### ISSUE THREAD

**Issue by pivovarit** [tomakehurst/wiremock#603]
I am using newest Spring Boot 1.5.1.RELEASE and experiencing problems with newest Jetties.

JettyFaultInjectors are using _getSocket()_ method that is not present in the _9.4.1.v20170120_

**Comment by tomakehurst** [comment]
Are you using the standalone artifact?

**Comment by pivovarit** [comment]
@tomakehurst um, thanks :) it seems like I managed to move everything forward, closing.
