### ISSUE TITLE
Make WireMockServerRunner implementation more re-usable

### ISSUE THREAD

**Issue by sgoeschl** [tomakehurst/wiremock#608]
Hi folks,

for my current project I needed to record multiple URLs using the stand-alone wire mock which is technically possible but not exposed in `WireMockServerRunner` - in reality it would be hard to configure anyway :-)

In theory I could inherit from `WireMockServerRunner` and overwrite `addProxyMapping` but this method is private. 

Not a big deal - having said that does a PR makes sense to make the implementation of `WireMockServerRunner` more reusable?

Thanks in advance, 

Siegfried Goeschl

**Comment by tomakehurst** [comment]
Might be worth checking out this thread: https://github.com/tomakehurst/wiremock/pull/573

**Comment by sgoeschl** [comment]
I guess it could solve my problem in the long run :-)
