### ISSUE TITLE
Issue when upgrading from 1.45 to current version

### ISSUE THREAD

**Issue by Regisc** [tomakehurst/wiremock#610]
So, I have some old project and I want to upgrade dependencies. Everything is smooth but I have an issue with wiremock. I did change from
      
    <dependency>
        <groupId>com.github.tomakehurst</groupId>
        <artifactId>wiremock</artifactId>
        <version>1.45</version>
        <classifier>standalone</classifier>
        <scope>test</scope>
    </dependency>

to

    <dependency>
        <groupId>com.github.tomakehurst</groupId>
        <artifactId>wiremock-standalone</artifactId>
        <version>2.5.1</version>
        <scope>test</scope>
    </dependency>

but my tests are failing with some exception:

    java.lang.IllegalArgumentException: (POST /__admin/mappings)@403719840 wiremock.org.eclipse.jetty.server.Request@181046a0 does not have a getUri or getHttpURI method
	    at com.github.tomakehurst.wiremock.jetty9.JettyUtils.getUri(JettyUtils.java:44)
	    at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.isBrowserProxyRequest(WireMockHttpServletRequestAdapter.java:214)
	    at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:54)

I did check what is happening using a debugger, and I end here:

    public static URI getUri(Request request) {
        try {
            return toUri(request.getClass().getDeclaredMethod("getUri", new Class[0]).invoke(request, new Object[0]));
        } catch (Exception var4) {
            try {
                return toUri(request.getClass().getDeclaredMethod("getHttpURI", new Class[0]).invoke(request, new Object[0]));
            } catch (Exception var3) {
                throw new IllegalArgumentException(request + " does not have a getUri or getHttpURI method");
            }
        }
    }

In this method, I get a security exception (`var4`):

    java.lang.SecurityException: class "javax.servlet.http.HttpUpgradeHandler"'s signer information does not match signer information of other classes in the same package

Is this a known issue? If so, how do I fix it?

**Comment by tomakehurst** [comment]
Please could you post your full set of dependencies? I can't replicate this and the exception suggests it's to do with the Jetty version (although why it's happening via the shaded version in the standalone JAR I can't understand)

**Comment by Regisc** [comment]
Hi, thanks for your answer, here's a `mvn dependency:tree` output:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ acknoo-manager ---
[INFO] com.koaly.acknoo:acknoo-manager:war:0.1-SNAPSHOT
[INFO] +- org.mariadb.jdbc:mariadb-java-client:jar:1.5.8:runtime
[INFO] +- net.sf.ehcache:ehcache-core:jar:2.6.11:compile
[INFO] +- org.springframework:spring-web:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-webmvc:jar:4.3.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.3.6.RELEASE:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.8.6:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.6:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.6:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.1:runtime
[INFO] |  \- ch.qos.logback:logback-core:jar:1.2.1:runtime
[INFO] +- org.slf4j:slf4j-api:jar:1.7.23:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.23:compile
[INFO] +- org.slf4j:log4j-over-slf4j:jar:1.7.23:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.23:compile
[INFO] +- org.springframework:spring-core:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-beans:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-context:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-context-support:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-tx:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-jdbc:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-aop:jar:4.3.6.RELEASE:compile
[INFO] +- org.springframework:spring-orm:jar:4.3.6.RELEASE:compile
[INFO] +- cglib:cglib:jar:3.2.4:compile
[INFO] |  +- org.ow2.asm:asm:jar:5.1:compile
[INFO] |  \- org.apache.ant:ant:jar:1.9.6:compile
[INFO] |     \- org.apache.ant:ant-launcher:jar:1.9.6:compile
[INFO] +- org.springframework.data:spring-data-jpa:jar:1.11.0.RELEASE:compile
[INFO] |  \- org.springframework.data:spring-data-commons:jar:1.13.0.RELEASE:compile
[INFO] +- org.springframework.security.oauth:spring-security-oauth2:jar:2.0.12.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:3.2.8.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:3.2.8.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-web:jar:3.2.8.RELEASE:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] +- org.hibernate:hibernate-entitymanager:jar:5.2.8.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.2.8.Final:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  \- org.jboss:jandex:jar:2.0.3.Final:compile
[INFO] |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:compile
[INFO] |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  +- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.6.6:compile
[INFO] |  \- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.1.Final:compile
[INFO] +- org.hibernate:hibernate-c3p0:jar:5.2.8.Final:compile
[INFO] |  \- com.mchange:c3p0:jar:0.9.5.2:compile
[INFO] +- com.mchange:mchange-commons-java:jar:0.2.11:runtime
[INFO] +- org.hibernate:hibernate-validator:jar:5.4.0.Final:compile
[INFO] |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  \- com.fasterxml:classmate:jar:1.3.1:compile
[INFO] +- joda-time:joda-time:jar:2.9.7:compile
[INFO] +- org.joda:joda-money:jar:0.12:compile
[INFO] +- org.jadira.usertype:usertype.core:jar:6.0.1.GA:compile
[INFO] |  \- org.jadira.usertype:usertype.spi:jar:6.0.1.GA:compile
[INFO] +- org.jadira.cdt:cdt:jar:6.0.1.GA:compile
[INFO] |  +- com.googlecode.libphonenumber:libphonenumber:jar:7.0.4:compile
[INFO] |  +- org.jadira.bindings:bindings:jar:6.0.1.GA:compile
[INFO] |  \- net.sf.oval:oval:jar:1.84:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.1.1:compile
[INFO] +- org.aspectj:aspectjrt:jar:1.8.10:compile
[INFO] +- org.aspectj:aspectjweaver:jar:1.8.10:compile
[INFO] +- org.springframework:spring-aspects:jar:4.3.6.RELEASE:runtime
[INFO] +- org.projectlombok:lombok:jar:1.16.14:provided
[INFO] +- com.google.guava:guava:jar:21.0:compile
[INFO] +- com.google.code.findbugs:jsr305:jar:3.0.1:compile
[INFO] +- javax.servlet.jsp:jsp-api:jar:2.1:provided
[INFO] +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:provided
[INFO] +- ro.isdc.wro4j:wro4j-core:jar:1.8.0:compile
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] +- jstl:jstl:jar:1.2:compile
[INFO] +- commons-io:commons-io:jar:2.5:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- com.h2database:h2:jar:1.4.193:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- org.powermock:powermock-module-junit4:jar:1.7.0RC2:test
[INFO] |  \- org.powermock:powermock-module-junit4-common:jar:1.7.0RC2:test
[INFO] |     +- org.powermock:powermock-reflect:jar:1.7.0RC2:test
[INFO] |     \- org.powermock:powermock-core:jar:1.7.0RC2:test
[INFO] +- org.powermock:powermock-api-mockito:jar:1.7.0RC2:test
[INFO] |  +- org.powermock:powermock-api-mockito-common:jar:1.7.0RC2:test
[INFO] |  |  \- org.powermock:powermock-api-support:jar:1.7.0RC2:test
[INFO] |  \- org.mockito:mockito-core:jar:1.10.19:test
[INFO] |     \- org.objenesis:objenesis:jar:2.1:test
[INFO] +- org.springframework:spring-test:jar:4.3.6.RELEASE:test
[INFO] +- com.jayway.jsonpath:json-path:jar:2.2.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.2.1:compile
[INFO] |     \- net.minidev:accessors-smart:jar:1.1:compile
[INFO] +- com.jayway.jsonpath:json-path-assert:jar:2.2.0:compile
[INFO] |  \- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] +- org.assertj:assertj-core:jar:3.6.2:test
[INFO] +- org.assertj:assertj-guava:jar:3.1.0:test
[INFO] +- org.assertj:assertj-joda-time:jar:2.0.0:test
[INFO] +- com.github.tomakehurst:wiremock:jar:standalone:1.57:test
[INFO] |  +- org.mortbay.jetty:jetty:jar:6.1.26:test
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:test
[INFO] |  |  \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.2.3:test
[INFO] |  |  \- org.json:json:jar:20090211:test
[INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:4.9:test
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5:test
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.1:test
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:test
[INFO] |  \- xmlunit:xmlunit:jar:1.6:test
[INFO] +- org.eclipse.jetty:jetty-webapp:jar:9.2.13.v20150730:test
[INFO] |  +- org.eclipse.jetty:jetty-xml:jar:9.2.13.v20150730:test
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.2.13.v20150730:test
[INFO] |  \- org.eclipse.jetty:jetty-servlet:jar:9.2.13.v20150730:test
[INFO] |     \- org.eclipse.jetty:jetty-security:jar:9.2.13.v20150730:test
[INFO] |        \- org.eclipse.jetty:jetty-server:jar:9.2.13.v20150730:test
[INFO] |           +- org.eclipse.jetty:jetty-http:jar:9.2.13.v20150730:test
[INFO] |           \- org.eclipse.jetty:jetty-io:jar:9.2.13.v20150730:test
[INFO] +- org.eclipse.jetty:jetty-jsp:jar:9.2.13.v20150730:test
[INFO] |  +- org.eclipse.jetty.toolchain:jetty-schemas:jar:3.1.M0:test
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:test
[INFO] |  +- javax.servlet.jsp:javax.servlet.jsp-api:jar:2.3.1:test
[INFO] |  +- org.glassfish.web:javax.servlet.jsp:jar:2.3.2:test
[INFO] |  +- org.eclipse.jetty.orbit:javax.servlet.jsp.jstl:jar:1.2.0.v201105211821:test
[INFO] |  +- org.glassfish.web:javax.servlet.jsp.jstl:jar:1.2.2:test
[INFO] |  +- org.glassfish:javax.el:jar:3.0.0:test
[INFO] |  \- org.eclipse.jetty.orbit:org.eclipse.jdt.core:jar:3.8.2.v20130121:test
[INFO] \- org.mortbay.jetty:jsp-api-2.1-glassfish:jar:2.1.v20100127:test
```

**Comment by tomakehurst** [comment]
Any change you could post the `<dependencies>` block from your POM? I'd like to be able to replicate the problem, and it'll be a bit tricky reconstructing it from a dependency report.

**Comment by Regisc** [comment]
Here it is:

    <dependencies>
        
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${version.mariadb}</version>
            <scope>runtime</scope>
        </dependency>

        
        <dependency>
            <groupId>net.sf.ehcache</groupId>
            <artifactId>ehcache-core</artifactId>
            <version>${version.ehcache}</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${version.spring}</version>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${version.jackson2}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${version.jackson2}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${version.jackson2}</version>
        </dependency>

        
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${version.logback}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${version.slf4j}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>${version.slf4j}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
            <version>${version.slf4j}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jul-to-slf4j</artifactId>
            <version>${version.slf4j}</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${version.spring}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib</artifactId>
            <version>${version.cglib}</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
            <version>${version.spring-data}</version>
            <exclusions>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-beans</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-core</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>aspectjrt</artifactId>
                    <groupId>org.aspectj</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-aop</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-context</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-tx</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-orm</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>${version.spring-security-oauth}</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring-beans</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-core</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-context</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-jdbc</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-aop</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-web</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-webmvc</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-entitymanager</artifactId>
            <version>${version.hibernate}</version>
            <type>jar</type>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-c3p0</artifactId>
            <version>${version.hibernate}</version>
            <type>jar</type>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.mchange</groupId>
            <artifactId>mchange-commons-java</artifactId>
            <version>${version.mchange-commons-java}</version>
            <scope>runtime</scope>
        </dependency>

        
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${version.hibernate-validator}</version>
        </dependency>

        
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>${version.joda-time}</version>
        </dependency>

        
        <dependency>
            <groupId>org.joda</groupId>
            <artifactId>joda-money</artifactId>
            <version>${version.joda-money}</version>
        </dependency>
        <dependency>
            <groupId>org.jadira.usertype</groupId>
            <artifactId>usertype.core</artifactId>
            <version>${version.jadira}</version>
        </dependency>
        <dependency>
            <groupId>org.jadira.cdt</groupId>
            <artifactId>cdt</artifactId>
            <version>${version.jadira}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-joda</artifactId>
            <version>2.1.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${version.aspectj}</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${version.aspectj}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
            <version>${version.spring}</version>
            <scope>runtime</scope>
        </dependency>

        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${version.lombok}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${version.guava}</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>${version.jsr305}</version>
        </dependency>

        
        <dependency>
            <groupId>javax.servlet.jsp</groupId>
            <artifactId>jsp-api</artifactId>
            <version>${version.jsp}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.orbit</groupId>
            <artifactId>javax.servlet</artifactId>
            <version>${version.servlet}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ro.isdc.wro4j</groupId>
            <artifactId>wro4j-core</artifactId>
            <version>${version.wro4j}</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>jstl</groupId>
            <artifactId>jstl</artifactId>
            <version>${version.jstl}</version>
        </dependency>

        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${version.commons.io}</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>${version.commons.lang}</version>
        </dependency>

        
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${version.h2}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>${version.powermock}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito</artifactId>
            <version>${version.powermock}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${version.spring}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>spring-core</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>${version.json-path}</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <version>${version.json-path}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${version.assertj-core}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-guava</artifactId>
            <version>${version.assertj-guava}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-joda-time</artifactId>
            <version>${version.assertj-joda}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>${version.wiremock}</version>
            <classifier>standalone</classifier>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-webapp</artifactId>
            <version>${version.jetty}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-jsp</artifactId>
            <version>${version.jetty}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mortbay.jetty</groupId>
            <artifactId>jsp-api-2.1-glassfish</artifactId>
            <version>${version.jsp-api}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by tomakehurst** [comment]
Thanks

**Comment by tomakehurst** [comment]
Sorry about the long delay. Your dependency report is still showing WireMock 1.57. Can suggest fixing that and trying again?

**Comment by Regisc** [comment]
Hi, I updated both of my previous comments, the dependency tree is now with 2.5.1 (2.6 didn't propagate enough) and the full dep. block now has properties so you can copy/paste it easily.

**Comment by tomakehurst** [comment]
And you're still seeing exactly the same error?

**Comment by Regisc** [comment]
My test is still failing, yes, will check if the stacktrace is exactly the same tomorrow

**Comment by aman9bits** [comment]
Hey, did anyone find a fix for this?

**Comment by chrisberkhout** [comment]
I was also having an error like that:

    java.lang.SecurityException: class "javax.servlet.ServletResponse"'s signer information does not match signer information of other classes in the same package

Coming from `JettyHttpServer.java:117`. That file imports a lot of `org.eclipse.jetty.servlet.*` stuff, but also `javax.servlet.DispatcherType`.

Tried rebuilding the standalone jar with extra shading:

    relocate "javax.servlet", "wiremock.org.javaxservlet"

But then ran into other problems:

    [error]    java.lang.IllegalArgumentException: resource keystore not found. (Preconditions.java:145)
    [error] wiremock.com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    [error] wiremock.com.google.common.io.Resources.getResource(Resources.java:197)
    [error] com.github.tomakehurst.wiremock.core.WireMockConfiguration.<init>(WireMockConfiguration.java:51)

**Comment by tomakehurst** [comment]
I'll be adding that shading into the next release. I didn't do it originally as it broke earlier versions of Jetty, but it seems Jetty 9 doesn't mind it being in a different package.

**Comment by chrisberkhout** [comment]
Actually, maybe that shading still breaks things.

On the first run it works, but after stopping the WireMockServer, waiting a bit and rerunning in the same JVM, I get this error:

```
2017-06-21 18:57:27.554:INFO:woejs.Server:ForkJoinPool-1-worker-1: jetty-9.2.z-SNAPSHOT
2017-06-21 18:57:27.572:WARN:/__admin:ForkJoinPool-1-worker-1: unavailable
wiremock.javax.servlet.UnavailableException: Servlet class com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet is not a javax.servlet.Servlet
        at wiremock.org.eclipse.jetty.servlet.ServletHolder.checkServletType(ServletHolder.java:491)
        at wiremock.org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:356)
        at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:870)
        at wiremock.org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at wiremock.org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at wiremock.org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at wiremock.org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at wiremock.org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at wiremock.org.eclipse.jetty.server.Server.start(Server.java:387)
        at wiremock.org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at wiremock.org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at wiremock.org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:130)
```
([full output](https://gist.github.com/chrisberkhout/2024182bf7d01868a4b4dca11deee6a2))

A [StackOverflow answer](https://stackoverflow.com/questions/22710535/servlet-class-is-not-a-javax-servlet-servlet/22711641#22711641) suggests this exception "typically happens if you embed the javax.servlet package into your bundle".

**Comment by tomakehurst** [comment]
Thanks for pointing this out. Guess I'll be pulling the shading back out.

**Comment by ShubhamGupta29** [comment]
I am facing this issue in 2.21.0, can anyone help with this?

**Comment by ncjones** [comment]
I saw a similar issue from the standalone server when stubbing a request with a "+" in a query param.
