### ISSUE TITLE
Standalone wiremock - overload rootdir during run

### ISSUE THREAD

**Issue by jerzynowakowski** [tomakehurst/wiremock#612]
I have a complex setup where wiremock is used as an external proxy for recording and replaying HTTP traffic

I tried to start wiremock programmatically, but wiremock proxy must be started before the whole test setup starts.
In this case, only standalone option was possible. Otherwise, I could not start the wiremock server.

The only challenge is to overload the rootDir once the process is started.
If it is possible programmatically using external commands without stopping the process, then I could get to the recordings easily, without killing and starting the process to overload the recordings path for replay

Is it possible to overload rootDir for the standalone wiremock once it is started?
Is there some extension? Please advise

**Comment by tomakehurst** [comment]
Since this is a question rather than a bug, I suggest posting it over on the mailing list as per the README.
