### ISSUE TITLE
Mock Freeze test

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [tomakehurst/wiremock#619]
Here is the log
RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
The test run normally in IntelliJ idea , but freeze when i run mvn clean verify

**Comment by tomakehurst** [comment]
As per the README, please can you post questions on the mailing list rather than opening a ticket.

For someone to be able to help you I suggest including:
* Full stacktraces
* Test code
* Setup/configuration details
