### ISSUE TITLE
Response Templating is not working for me...response is not as transformed as expected.

### ISSUE THREAD

**Issue by KavitaSharma1234** [tomakehurst/wiremock#621]
made a stub as mentioned below:

public void stub(){    
stubFor(get(urlEqualTo("/another/Endpoint/123?name=abc")).
            willReturn(aResponse()
                    .withStatus(200)
                    .withBody("{\"name\": \"$(name)\"}")
                    .withTransformers("body-transformer")));
 }
passing below details in Rule and Test

    @Rule
    public WireMockRule wiremockRule = new WireMockRule(8844);

    @Test
    public void anything() throws Exception{
        System.setProperty("user.dir", "C:\\Users\\kavita\\.m2\\repository\\com\\github\\tomakehurst\\wiremock-standalone\\2.5.1");

        Process p = Runtime.getRuntime().exec("java -cp \"wiremock-body-transformer-1.1.4.jar;wiremock-standalone-2.5.1.jar\" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --verbose --extensions com.opentable.extension.BodyTransformer");

    after calling the stub here i am getting the response as mentioned below not as i expected:

{"name": "$(name)"}

note: i am using java 1.7 and jars as mentioned above.

Kindly tell if need any correction.

**Comment by tomakehurst** [comment]
Looks like you're attempting to use Open Table's extension rather than the built in one, so I can't help you I'm afraid. Suggest you open a ticket on their project.

**Comment by KavitaSharma1234** [comment]
i am simply want to implement response templating and not sure what do you mean by "Open Table's extension" here.

can you give me one working example(code)to implement response templating?

it would really help me as i am just a beginner.

**Comment by tomakehurst** [comment]
`--extensions com.opentable.extension.BodyTransformer` - that's Opentable's extension, not WireMock's

**Comment by KavitaSharma1234** [comment]
that i already used as mentioned above in my query:

java -cp \"wiremock-body-transformer-1.1.4.jar;wiremock-standalone-2.5.1.jar\" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --verbose --extensions com.opentable.extension.BodyTransformer

**Comment by KavitaSharma1234** [comment]
below is the code i am using and its not working

public class RspTemplating  {                                                                                                                                                                                                
                                                                                                                                                                                                                             
public void makestub() {                                                                                                                                                                                                     
                                                                                                                                                                                                                             
/*                                                                                                                                                                                                                           
    stubFor(get(urlEqualTo("/another/Endpoint/123?name=kavi")).                                                                                                                                                              
            willReturn(aResponse()                                                                                                                                                                                           
                    .withStatus(200)                                                                                                                                                                                         
                    .withBody("{\"name\": \"$(name)\"}")                                                                                                                                                                     
                    .withTransformers("body-transformer")));                                                                                                                                                                 
*/                                                                                                                                                                                                                           
                                                                                                                                                                                                                             
    stubFor(post(urlEqualTo("/another/Endpoint"))                                                                                                                                                                            
                   .withRequestBody(equalToJson("{\n" +                                                                                                                                                                      
                           "    \"foo\": {\n" +                                                                                                                                                                              
                           "        \"bar\": \"opentable\"\n" +                                                                                                                                                              
                           "    }\n" +                                                                                                                                                                                       
                           "}"))                                                                                                                                                                                             
            .willReturn(aResponse()                                                                                                                                                                                          
                    .withStatus(200)                                                                                                                                                                                         
                    .withBody("{\n" +                                                                                                                                                                                        
                            "    \"fooname\": {\n" +                                                                                                                                                                         
                            "        \"bar\": $(bar)\n" +                                                                                                                                                                    
                            "    }\n" +                                                                                                                                                                                      
                            "}")                                                                                                                                                                                             
                    .withTransformers("body-transformer")));                                                                                                                                                                 
                                                                                                                                                                                                                             
   /* Response response= given().                                                                                                                                                                                            
            when().contentType("application/json").                                                                                                                                                                          
            get("http://localhost:8055/another/Endpoint/123?name=kavi").                                                                                                                                                     
            then().log().all().statusCode(200).                                                                                                                                                                              
            extract().response();*/                                                                                                                                                                                          
                                                                                                                                                                                                                             
                                                                                                                                                                                                                             
    Response response1= given().                                                                                                                                                                                             
            when().log().all().contentType("application/json").body("{\n" +                                                                                                                                                  
            "    \"foo\": {\n" +                                                                                                                                                                                             
            "        \"bar\": \"opentable\"\n" +                                                                                                                                                                             
            "    }\n" +                                                                                                                                                                                                      
            "}").                                                                                                                                                                                                            
            post("http://localhost:8035/another/Endpoint").                                                                                                                                                                  
            then().log().all().statusCode(200).                                                                                                                                                                              
            extract().response();                                                                                                                                                                                            
}                                                                                                                                                                                                                            
                                                                                                                                                                                                                             
   // WireMockServer wm1 = new WireMockServer(WireMockConfiguration.options());                                                                                                                                              
                                                                                                                                                                                                                             
                                                                                                                                                                                                                             
    @Rule                                                                                                                                                                                                                    
    public WireMockRule wiremockRule = new WireMockRule(8035);                                                                                                                                                               
    public WireMockRule wm = new WireMockRule(WireMockConfiguration.options().extensions(new ResponseTemplateTransformer(true)));                                                                                            
                                                                                                                                                                                                                             
    /* public interface WiremockExtension {                                                                                                                                                                                  
        ResponseDefinition filter(Request request, ResponseDefinition responseDefinition);                                                                                                                                   
        String getName();                                                                                                                                                                                                    
        boolean isGlobal();                                                                                                                                                                                                  
    }*/                                                                                                                                                                                                                      
                                                                                                                                                                                                                             
    @Test                                                                                                                                                                                                                    
    public void anything() throws Exception{                                                                                                                                                                                 
       // wm1.start();                                                                                                                                                                                                       
       System.setProperty("user.dir", "C:\\Users\\kavita\\.m2\\repository\\com\\github\\tomakehurst\\wiremock-standalone\\2.5.1");                                                                                           
       Process p = Runtime.getRuntime().exec("java -cp \"wiremock-body-transformer-1.1.4.jar:wiremock-standalone-2.5.1.jar\"  --verbose --extensions com.opentable.extension.BodyTransformer");                              
        makestub();                                                                                                                                                                                                          
                                                                                                                                                                                                                             
       // wm1.stop();                                                                                                                                                                                                        
    }                                                                                                                                                                                                                        
    }

**Comment by tomakehurst** [comment]
Suggest you have a thorough read of this: http://wiremock.org/docs/response-templating/
