### ISSUE TITLE
Test failure when attempting to build latest master

### ISSUE THREAD

**Issue by hansjoachim** [tomakehurst/wiremock#623]
(Sorry about the contentless initial post)

When attempting to build latest master (633f3cc33bc04a9b38cd503b36a3f571c7756a0d), I get the following error message due to a failing test:
```
:test

com.github.tomakehurst.wiremock.PostServeActionExtensionTest > providesServeEventWithResponseFieldPopulated FAILED
    java.lang.AssertionError: 
    Expected: is <418>
         but: was <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at com.github.tomakehurst.wiremock.PostServeActionExtensionTest.providesServeEventWithResponseFieldPopulated(PostServeActionExtensionTest.java:128)

773 tests completed, 1 failed
:test FAILED
```

I haven't looked into this test in details, but it seems to fail consistently, I'm running OpenJDK `1.8.0_121` on Ubuntu 16.10.

**Comment by Smedzlatko** [comment]
I have the same issue. It seems that tests are not deterministic when runnin `./gradlew clean test
` locally. Sometimes, the build passes and sometimes it fails. I have found two tests with this non-deterministic behavior: 

- PostServeActionExtensionTest > providesServeEventWithResponseFieldPopulated
- PostServeActionExtensionTest > triggersActionWhenAppliedToAStubMapping

**Comment by tomakehurst** [comment]
Thanks. I see this myself occasionally. I have a rough idea why, just haven't had a chance to fix yet.

**Comment by tkruse** [comment]
Also seeing tests sometimes passing, sometimes failing, with 2.5.1 and 2.6.0. In my case multiple test methods run the same GET query one, and verify(1, ...) sometimes results in 
```
Expected exactly X requests matching the following pattern but received X + 1
```

Setup is:
```
@ClassRule
    public static final WireMockClassRule MOCK = new WireMockClassRule(wireMockConfig().dynamicPort().dynamicHttpsPort());

@Before
    public void setUp() {
        MOCK.resetAll();
    }
```

**Comment by tomakehurst** [comment]
@tkruse  - this doesn't look like the same issue as the one described above. Would you mind opening a new one and posting your full test code (or a test case the reliably reproduces the problem)?

**Comment by tomakehurst** [comment]
Not seen this failure for quite a while so I'm assuming it's gone
