### ISSUE TITLE
WireMock vs HoverFly Evaluation

### ISSUE THREAD

**Issue by Osipion** [tomakehurst/wiremock#626]
I'm evaluating WireMock and HoverFly for testing mobile clients, as well as general purpose service virtualization, in a large corporation with a multitude of clients and backend services. To do so I've written [a general article on the two](https://github.com/Osipion/NotesOnTestAutomation/blob/master/service-virtualization/article.md). I was able to persuade SpectoLabs to take a quick look at it and give feedback. I was wondering if any of the WireMock contributors would be able to tell me if there's anything we've missed? Thanks in advance for any help. If there's a better way to raise this request, please let me know.

**Comment by tomakehurst** [comment]
Generally I think this is a very well-written article, and a good preface to the subject for someone wishing to understand it.

A few points I'd make:
1) I'm not sure I'd agree with the definition of mocking you've used. I think Martin Fowler's is about as close to official as you can get: https://martinfowler.com/articles/mocksArentStubs.html. In particular I think the key differentiator from stubs is behavioural verification. WireMock has a load of explicit features for this (not sure about Hoverfly).

2) WireMock also does forward proxying. It's badly named (`--enable-browser-proxying` in the CLI for instance), but it works. It doesn't do MITM HTTPS in that mode however, which I believe Hoverfly does, albeit with all the usual problems with serving the wrong certificate. Hoverfly is generally a slicker experience when using forward proxying as far as I can tell, although I'm planning to improve this in WireMock in the near future.

3) WireMock's real strength (and arguably its biggest benefit over Hoverfly) is the DSL + request matcher. The majority of WireMock users in my experience don't use proxying at all, but will entirely fake the bits of the API they depend on via either the DSL or the JSON equivalent. The flexibility of the matcher system means that it's possible to work with data that varies enough per-request to prevent exact matching (e.g. when timestamps are involved), and set low-priority catch-all stubs for when a specific match isn't available (e.g. a custom 404 response).

4) WireMock's other major strength is fault injection. You can add fixed or randomly distributed delays, send corrupt HTTP responses or close the socket prematurely. It's amazing how easy it is to discover bugs or misconfiguration in your HTTP client doing this kind of thing.

**Comment by Osipion** [comment]
@tomakehurst thanks so much for this, and apologies for taking a while to get back to you. It's a good whack of feedback :-). I'll include & link it in the article and our decision making.
