### ISSUE TITLE
FR: make NearMissCalculator customizable

### ISSUE THREAD

**Issue by rauch** [tomakehurst/wiremock#629]
Guys,

Would be nice to have a possibility to turn off NearMissCalculator in case we don't care of details of missmatches:

com.github.tomakehurst.wiremock.core.WireMockApp:171
`private void logUnmatchedRequest(LoggedRequest request) {
        List<NearMiss> nearest = nearMissCalculator.findNearestTo(request);
        String message = "Request was not matched:\n" + request;
        if (!nearest.isEmpty()) {
            message += "\nClosest match:\n" + nearest.get(0).getStubMapping().getRequest();
        }
        notifier().error(message);
    }`

`nearMissCalculator.findNearestTo(request)` is too slow for some cases

**Comment by tomakehurst** [comment]
Can you provide some more details? How slow are we talking and under what circumstances?
