### ISSUE TITLE
Standalone jar dependencies are not fully shadowed

### ISSUE THREAD

**Issue by jbohmann** [tomakehurst/wiremock#630]
The standalone artifact shades/shadows many of Wiremock's dependencies, but not all. For example, in our project we're using handlebars, which is conflicting (AbstractMethodError) with Wiremock's handlebars. We've downgraded to 2.4.1 (from 2.5.1) as it looks like handlebars was added in 2.5.0. This has solved the handlebars issue for us, but we'd like to stay current with Wiremock and avoid 3rd party conflicts in the future.

We could try and manage all of Wiremock's dependencies manually and hope that the versions we're using are compatible, but we'd rather use the standalone shadowed jar option. Our project uses Jetty, Spring, etc...many of the same dependencies as Wiremock.

Is there a reason not ALL dependencies are being shadowed?

**Comment by tomakehurst** [comment]
Some deps can't be shadowed because they do class loading from class names in strings etc. However, not shading Handlebars is just an oversight so I'll add this.

**Comment by tomakehurst** [comment]
Fixed by 08a817936df1b2836f9915e06e8ce60cc2ec40c8
