### ISSUE TITLE
Feature suggestion: add MongoDb mappings source

### ISSUE THREAD

**Issue by jcotado** [tomakehurst/wiremock#631]
We just had to implement this - might be useful to others. Here's a rough and ready example:
https://gist.github.com/jcotado/4b2628c96f1c5b2087fd23b897be58b4

**Comment by tomakehurst** [comment]
Looks good.

I'd suggest making it a free-standing project though, rather than putting it in core WireMock. Happy to link to it from the External Resources page on the site, and/or put it in the wiremock GitHub organisation.
