### ISSUE TITLE
Request not reaching WireMock

### ISSUE THREAD

**Issue by frucinbagam** [tomakehurst/wiremock#633]
I have recorded the requests and responses but when I replay them, only one of the request doesn't seem to reach wiremock hence it is not using the response. Weird thing is that, this works fine in all other machines except for the one that is in cloud. Is there anything specific to firewall that I should check here?

**Comment by tomakehurst** [comment]
Since this is a question rather than a bug, please re-post on the mailing list as per the README.

Also, I suggest you post some details about your setup - code, how you're starting WireMock, requests you're making to it.
