### ISSUE TITLE
Not able to match % in query parameters

### ISSUE THREAD

**Issue by anudeep-mj** [tomakehurst/wiremock#637]
If my request has a query parameter such as %5C, the request doesnt seem to match.

for example

"ex_UniqueName" : {
    	"matches" : "asdf%5Cjkl"
 }

gives a file not found exception. It works fine if i remove %

**Comment by tomakehurst** [comment]
As per the README, please can you post questions over on the mailing list. I also suggest you post the full details of the request you made.
