### ISSUE TITLE
Upgrade to jetty 9.4 and in the process java 8

### ISSUE THREAD

**Issue by hcf** [tomakehurst/wiremock#644]
At my organisation we are using jetty 9.4, and since jetty is not embedded in the standalone jar, we can not currently use wiremock 2.6.1. I have therefore updated wiremock to the latest jetty and jackson versions, and in the process also changes source and target compatibility to java 8.

PR coming.

**Comment by tomakehurst** [comment]
Not sure what you mean about jetty not being in the standalone version. It definitely is.

I'm happy to accept a PR that adds an extra jar to the build with upgraded jetty, but not one that drops jdk7 support in the existing ones.

**Comment by hcf** [comment]
@tomakehurst that was some really bad research on our part, so sorry for the insinuations :(

Jetty 9.3 and up seems to require jdk8, so need for me to create the PR. Thanks for the quick feedback :)

**Comment by tomakehurst** [comment]
No worries :-)

**Comment by ArashRajaeeyan** [comment]
@tomakehurst what do you think about having it as a configurable options? people can turn on or off jetty 9.4 and java8 based on the environment they are using

**Comment by tomakehurst** [comment]
If only it was that simple :-)

There are some backwards-incompatible API changes in Jetty 9.3 upwards, which means there needs to be two different set of abstractions in WireMock. I think the only realistic way to do this is to split the source tree into Jetty 9.2 and Jetty 9.4+ parts, and release two separate JARs.
