### ISSUE TITLE
Add support for Gherkin Syntax

### ISSUE THREAD

**Issue by SxMShaDoW** [tomakehurst/wiremock#648]
Hi all,

Is there support for Gherkin syntax instead of mapped jsons? 

As a developer, I would like to have a friendly interface to generate mapped jsons, so that I can quickly read and write wiremocks. 

Requirement:
* It would be great if there was support for [Gherkin Syntax](https://github.com/cucumber/cucumber/wiki/Gherkin) as it can be really tough to read through JSON for requests. 
* Frameworks like [karate](https://github.com/intuit/karate) have been successful on using Gherkin syntax in the API space. 

Example:
``` 
{
    "request": {
        "method": "GET",
        "url": "/some/thing"
    },
    "response": {
        "status": 200,
        "body": "Hello world!",
        "headers": {
            "Content-Type": "text/plain"
        }
    }
}
```

could be written like:
```
Feature: Wiremock 'hello world' example
Scenario: retrieve a Hello World response

Given url 'http://myhost.com/some/thing'
When method get
And header Content-Type = 'text/plain'
Then status 200
And match response ==' Hello World'
```

**Comment by keithdtyler** [comment]
I bet you could write a set of step definitions that would generate the JSON for you from such a scenario. Your Gherkin looks like an application configuration, not a BDD test. Seems to me Gherkin is a poor fit for application configuration. I'd hate to imagine, say, trying to configure Apache HTTPD with a Gherkin syntax.
Gherkin's job is to provide flexible terminology on top of specific functionality. It would be pretty novel for an application to rigidly hard-define the step definitions.

**Comment by tomakehurst** [comment]
I agree with @keithdtyler here - you should use Gherkin for business domain language aimed at non-technical domain experts. If your audience is technical enough to understand HTTP then they should also be fine with (neatly factored) code. 

Gherkin has a big abstraction cost, and it's only worth paying for it if it's enabling significantly better cross-functional collaboration than code would IMO.
