### ISSUE TITLE
Multiple scenarios in request?

### ISSUE THREAD

**Issue by keithdtyler** [tomakehurst/wiremock#649]
Let's say I want to confirm the operation of an process that will involve sending three different REST requests. In order for this to be successful, I need to know that each request has been sent. I am not sure, however, whether the order of these requests will be deterministic (they may even be parallel). 

What I'd like to do is have a mapping that can trigger on a combination of states. Such as:

First request mapping:
```
    "scenario": "FirstRequest",
    "newScenarioState": "Sent",
```

Second request mapping: 
```
    "scenario": "SecondRequest",
    "newScenarioState": "Sent",
```

Final request mapping might be something like this:
```
    "scenarios": [
        {"scenario": "FirstRequest",
        "requiredScenarioState": "Sent"},
        {"scenario": "SecondRequest",
        "requiredScenarioState": "Sent"} 
    ], ....
```

Is this possible?

**Comment by keithdtyler** [comment]
Incidentally, is there a way to define a request mapping for when a scenario is *not* in a given state? For example `"requiredNotScenarioState": "Started"`

**Comment by tomakehurst** [comment]
Since this is a question, please could you post it on the mailing list. Trying to keep issues down to just bugs and feature requests.
