### ISSUE TITLE
Support Loading of Stubs from MongoDB

### ISSUE THREAD

**Issue by nWhitehill** [tomakehurst/wiremock#651]
Hello. I just wanted to find out how the community would feel about adding the functionality of loading mock responses from a MongoDB. This would be very similar to the existing capabilities of reading from a directory but would have the added benefit of having mock response being managed, and stored in a database that multiple Wiremock servers could consume from.

**Comment by tomakehurst** [comment]
I'd be against adding this to the core product, but very much in favour of it existing as an extension project. Since it's possible to supply your own `MappingSource` implementation, this is the hook you could use.

Also happy to put it under the `wiremock` GH org (which I'll move this project under when I get time).

**Comment by nWhitehill** [comment]
Sounds good Tom. I will explore this option and get back to you (and the community) if it leads to anything useful. Do you want to close this issue or leave it open for a little to track progress on this?

**Comment by tomakehurst** [comment]
Happy to close it and track progress in an issue on your project.

Having enough trouble staying on top of WireMock's issues as it is 🙂

**Comment by nWhitehill** [comment]
One last question before I close out Tom. I was planning on working on this feature for the company I work at. Our legal team is asking if you can provide me with a CLA to sign? Just so I can work on this and contribute it back on company time.

**Comment by tomakehurst** [comment]
If you're writing it as a freestanding project then that shouldn't be necessary as you'll own the copyright, not me.

**Comment by andrew-kratik** [comment]
Hi @nWhitehill 
Do you have any progress on this item? I'm ready to contribute if you already started development of this feature.

Thanks!

**Comment by tomakehurst** [comment]
Closing this, as I think this ought to be a separate project.
