### ISSUE TITLE
Request Matching not working

### ISSUE THREAD

**Issue by krisrr3** [tomakehurst/wiremock#653]
Hi guys,

I am building a Spring-Integration application an one of the components makes a REST call, which I am trying to mock out with WireMock in my integration test.

The failure I am getting is actually

> com.github.tomakehurst.wiremock.client.VerificationException: A request was unmatched by any stub mapping. Closest stub mapping was:  expected:<
POST
/pa/his/v1/ev> but was:<
POST
/pa/his/v1/ev>

The rest call of the Api Client component fails with a 404.

My question is, how do I investigate the problem here? The actual and expected seem to be the same, but still the matching is failing.

`	@Test
	public void testEv_success() throws InterruptedException, JSONException {
		receiptNumber = TestUtil.generateReceiptNumber();
		logger.debug("Receipt Number : " + receiptNumber);
		
		String requestBody = TestUtil.createSampleInputMessage(receiptNumber);
		
		System.out.println("Expected Post msg by EvApiClient :" + requestBody);
		
		
		stubFor(post(urlEqualTo(TestUtil.EVENT_URL))
		            //.withHeader("Content-Type", equalTo("application/json"))
		            //.withRequestBody(equalToJson(requestBody))
		           
		        );
		
		
		ResponseEntity response = restTemplate.getForEntity("http://localhost:9966/__admin", String.class);
		
		System.out.println("Printing Expected response :" + response);

		sendToJmsOutChannel.send(MessageBuilder.withPayload(TestUtil.createSampleInputMessage(receiptNumber)).build());

		verify(postRequestedFor(urlEqualTo(TestUtil.EVENT_URL)));`

**Comment by tomakehurst** [comment]
As per the README, please can you post questions on the mailing list.

**Comment by lapkoigor** [comment]
I have the same issue in 20% on test runs.
