### ISSUE TITLE
Trailing Forward Slash being added to Proxy URL 

### ISSUE THREAD

**Issue by kobrien** [tomakehurst/wiremock#655]
Hi I'm using wiremock to mock an external supplier service as part of our automated tests, However I've ran into some difficulty proxying the requests as wiremock seems to be adding a forward slash to the end of the SOAP endpoint. I was able to modify the codebase to strip any trailing slashes and it works fine.

Here is an example of the slash being added to the end of the endpoint (I just made up the test endpoint for demonstration purposes)

> kieran@localhost:~/workspace/gitlab/wiremockdemo/lib$ java -jar wiremock-standalone-2.6.0.jar --record-mappings --verbose --port 8888 --proxy-all="http://testwebservice/endpoint"
> 2017-04-20 14:36:23.807 Verbose logging enabled
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 2017-04-20 14:36:24.186 Verbose logging enabled
> 2017-04-20 14:36:24.231 Recording mappings to ./mappings
>  /$$      /$$ /$$                     /$$      /$$                     /$$      
> | $$  /$ | $$|__/                    | $$$    /$$$                    | $$      
> | $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
> | $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
> | $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/ 
> | $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$ 
> | $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
> |__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/
> 
> port:                         8888
> proxy-all:                    http://testwebservice/endpoint
> preserve-host-header:         false
> enable-browser-proxying:      false
> record-mappings:              true
> match-headers:                []
> no-request-journal:           false
> verbose:                      true
> 
> 2017-04-20 14:36:28.583 Proxying: POST **http://testwebservice/endpoint/**
> 

The "Proxying" message above (notice the forward slash that has been added to the end of it) was printed after I sent the following request 

> kieran@localhost:~$ date
> Thu 20 Apr 14:36:26 IST 2017
> kieran@localhost:~$ curl -X POST localhost:8888
> 

Here is a fix that works for me, I modifed the ProxyResponseRenderer.java method to remove any forward slashes if they are present

> public static HttpUriRequest getHttpRequestFor(ResponseDefinition response) {
>  final RequestMethod method = response.getOriginalRequest().getMethod();
>  String url = response.getProxyUrl();
>  if (url.endsWith("/")) {
>       url = url.substring(0, url.length() - 1);
>  }
> 
>  return HttpClientFactory.getHttpRequestFor(method, url);
> }

**Comment by tomakehurst** [comment]
Are you certain it isn't your client that's adding the slash?

**Comment by kobrien** [comment]
Hi @tomakehurst , my client in this case is cURL so I don't think so. I have tried again with Insomnia REST client and seen similar results

**Comment by tomakehurst** [comment]
Right, I see. Guess that ought to be fixed then.

**Comment by kobrien** [comment]
I can open a pull request for this if you like?

**Comment by tomakehurst** [comment]
That would be great, thanks.

**Comment by wojciechbulaty** [comment]
I think this fix removes any training slashes, so if they existed to start with, they will be removed as well. So if your app requires a trailing slash, it will never get it after this fix.

Right now one of my apps during a recording with this change instead returning HTTP 200 does a HTTP 302 and redirects to the URL with a / at the end.

**Comment by tomakehurst** [comment]
Hmmm....OK. Any ideas how we can fix this properly?

**Comment by wojciechbulaty** [comment]
I will to have a look when I have a moment, for now I have just removed this fix entirely from my branch. May be somebody else can have a look in the meantime?

**Comment by theangrydev** [comment]
It looks like curl is what was adding the trailing slash in the first place:
https://curl.haxx.se/mail/archive-2016-08/0027.html

**Comment by theangrydev** [comment]
Also note that `org.apache.http.client.utils.URIUtils` will interpret the URI of e.g. `http://localhost:10101` as `/` in the `public static URI rewriteURI(URI uri, HttpHost target, boolean dropFragment)` method used by the Apache HTTP client.

Looks like this is a common "fix" made by client libraries. I think the original change should be reverted. The test that was added around trailing slashes for non empty context paths still passes. I will submit a PR in a minute.

**Comment by alexeyvino** [comment]
I think this is breaking for us the other way. We have an API endpoint that throws 404 if you add a trailing slash. So when I'm running a standalone WireMock with --proxy-all="https://www.blablabla.com/webservices/bla" it adds trailing '/' and causes 404 response. It works fine with 2.12.

**Comment by theangrydev** [comment]
@alexeyvino Which HTTP client are you using to make the request?

**Comment by alexeyvino** [comment]
@theangrydev Apache CXF 3.1.10

**Comment by theangrydev** [comment]
@alexeyvino I would first confirm whether Apache CXF 3.1.10 is the one adding the trailing slash or not. If it is, this is not a WireMock issue since it is correctly preserving the original request path.

**Comment by alexeyvino** [comment]
@theangrydev It cannot. It works fine without WireMock proxying.

**Comment by theangrydev** [comment]
@alexeyvino There is a subtle difference you may not be aware of, can you take a look at the test `clientLibrariesTendToAddTheTrailingSlashWhenTheContextPathIsEmpty` because what might be happening is your client is adding a trailing slash because the context path is empty when you talk to WireMock. Without WireMock, it may not be adding a trailing slash since the context path is not empty.

**Comment by theangrydev** [comment]
@alexeyvino A possible workaround for you would be to set --proxy-all="https://www.blablabla.com/webservices"

And make requests to the /bla context path.

**Comment by alexeyvino** [comment]
@theangrydev You're right, that worked. I suspected that might be the case (adding slash by client in case of empty context path). Thank you!
