### ISSUE TITLE
equalToJson with ignoreArrayOrder only ignores some reordering.

### ISSUE THREAD

**Issue by stahl** [tomakehurst/wiremock#661]
Using equalToJson with ignoreArrayOrder set to true only seems to ignore some reordering.

```
  @Test
    public void equalToJsonIgnoreArrayOrder()
        throws Exception
    {
        String a1 = "[1, 2, 3, 4]";
        String a2 = "[4, 3, 2, 1]";
        String a3 = "[3, 2, 4, 1]";

        StringValuePattern pattern = equalToJson(a1, true, false);
        MatchResult result = pattern.match(a2);

        assertTrue("Should match array with elements in reverse order",
                   result.isExactMatch());

        result = pattern.match(a3);
        assertTrue("Should match array with elements in \"random\" order",
                   result.isExactMatch());
    }
```

This test fails for me using wiremock 2.6.0 on a mac with java 1.8.0_121.

**Comment by stahl** [comment]
https://github.com/tomakehurst/wiremock/pull/519 seems to fix the issue. Any plan on accepting that pull request?

**Comment by stahl** [comment]
https://github.com/tomakehurst/wiremock/pull/519 fails on the following test though: 
```
assertFalse(WireMock.equalToJson("[1, 2, 3, 4]",
                                                            true,
                                                            false)
                                     .match("[1, 3, 2, 4, 5, 6]")
                                     .isExactMatch());
```

**Comment by tomakehurst** [comment]
I need to find some time to spend on this. I can see the problem, but I'm dubious about that PR because it works around the problem rather than fixing it at source.

Thanks for the additional test case, that's useful to have.

**Comment by tomakehurst** [comment]
Closing this issue. Conversation to continue on #519.
