### ISSUE TITLE
how to mock POST request with a file in the request body

### ISSUE THREAD

**Issue by srivi1225** [tomakehurst/wiremock#663]
Hi,

i am new to wiremock and i am trying to mock a soap end point in which i want to give xml in the request and it produce a xml output.

it should return a success response if some xml data like firstname, lastname matches with the request data.

**Comment by tomakehurst** [comment]
I suggest reading the following two pages in the documentation:
http://wiremock.org/docs/stubbing/
http://wiremock.org/docs/request-matching/

If there's anything specific you need help with after that, then please post questions on the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user).

**Comment by srivi1225** [comment]
Hi @tomakehurst ,

i tried to add equaltoxml, xpath it is wotking with single node (<firstName>abc</firstName>)if i give full xml it is failing. could you please suggest me is there any possibility to give xml file in the request. 

thank you

**Comment by YagneshShah** [comment]
+1 to the mentioned question.
Is there any way to pass the file path within request body in the mapping file?

We do similar thing in Response as:
"bodyFileName": "../mockDataForMappings/CreateContactResponse-Example.xml"

Is there a way to do similar thing within request mock?

**Comment by tomakehurst** [comment]
Please can you direct questions to the mailing list as per the README, thanks.

**Comment by Noor-Mohamed-G** [comment]
i want to know how to pass xml in request 
like in reponse "bodyFileName"
