### ISSUE TITLE
Failed reading proxy response: Undefined error: 0 while proxying https

### ISSUE THREAD

**Issue by jvermeir** [tomakehurst/wiremock#664]
Hi, I’m having trouble using Wiremock and https. My config file (in /mappings) looks like this:

```
{  "request": {
    "method": "GET",
    "url": "/some/thing"},
  "response": {
    "status": 200,
    "body": "Hello world!",
    "headers": {
      "Content-Type": "text/plain"}}}
```

and I’m starting Wiremock (v2.6.0) like this:

```
java -jar wiremock-standalone-2.6.0.jar --enable-browser-proxying --port 8080 --verbose --print-all-network-traffic --https-port 8083
```

now this command (the http version):

```
wget -e use_proxy=yes -e https_proxy=localhost:8083 -e http_proxy=localhost:8080 http://www.google.com/some/thing
```

works fine, but with https it fails:

```
wget -e use_proxy=yes -e https_proxy=localhost:8083 -e http_proxy=localhost:8080 https://www.google.com/some/thing

--2017-05-10 11:38:09--  (try: 2)  https://www.google.com/some/thing
Connecting to localhost|::1|:8083... connected.
Failed reading proxy response: Undefined error: 0
Retrying.
```

And Wiremocks logging shows this:

```
2017-05-10 11:41:47.100 Opened Socket[addr=/0:0:0:0:0:0:0:1,port=63290,localport=8083]
2017-05-10 11:41:47.145 Incoming bytes: CONNECT www.google.com:443 HTTP/1.0
User-Agent: Wget/1.12 (darwin10.3.0)


2017-05-10 11:41:47.146 Closed Socket[addr=/0:0:0:0:0:0:0:1,port=63290,localport=8083]
2017-05-10 11:41:47.147 Closed Socket[addr=/0:0:0:0:0:0:0:1,port=63290,localport=8083]
2017-05-10 11:41:48.151 Opened Socket[addr=/0:0:0:0:0:0:0:1,port=63292,localport=8083]
```

What could be wrong here?

**Comment by ghaddink2** [comment]
I'm experiencing exactly the same problem :(  Anybody any ideas?

**Comment by tomakehurst** [comment]
You're attempting forward proxying through WireMock over HTTPS, which it doesn't yet support.

Suggest you switch to reverse proxying (i.e. via `--proxy-all`), which does support HTTPS.

**Comment by jvermeir** [comment]
Ok, thanks, I’ve solved the problem by recording like this:

```
java -jar wiremock-standalone-2.6.0.jar --proxy-all="https://www.example.com/" --record-mappings --https-port 8443
```

and then 

```
curl "https://localhost:8443/"
```

this results in a recording in /mappings and /__files
[stacktrace.txt](https://github.com/tomakehurst/wiremock/files/992239/stacktrace.txt)
. Then I started Wiremock in playback:

```
java -jar wiremock-standalone-2.6.0.jar --port 8080 --verbose --print-all-network-traffic --https-port 8443
```
and it serves up the recorded page as expected.

So that works, but now I keep getting a stack trace for every URL. see attached file (stacktrace.txt).

**Comment by jvermeir** [comment]
[stacktrace.txt](https://github.com/tomakehurst/wiremock/files/992246/stacktrace.txt)

**Comment by tomakehurst** [comment]
Do you see any errors if you omit the network traffic printing?

**Comment by jvermeir** [comment]
yes, that's better. thanks.
