### ISSUE TITLE
Question: Is it possible to transform query parameters for a redirect URL?

### ISSUE THREAD

**Issue by kobrien** [tomakehurst/wiremock#667]
As part of a product booking, I am returning a mocked payment response from our external payment service. The response is being redirected to another part of our codebase which manages the payment process. However I need to include some query parameters in this redirect (such as payment ID etc.) and these are normally generated by the external service on the fly based on the payment information being passed in. 
Is there any way I can use the wiremocks extensions API to transform this redirect URL to include what I need? I would like the transformation class to dynamically create the full redirect URL string (including the query params) 

Example mapping:
```
{
    "request": {
        "bodyPatterns": [
            {
                "contains": "<paymentService"
            }
        ],
        "method": "POST",
        "urlPath": "/"
    },
    "response": {
        "bodyFileName": "paymentSuccess.xml",
        "proxyBaseUrl": "https://www.webservice.com/some/jsp.do",

        "transformers": [
      "paymentID-transformer"
    ]
    }
}
```

Thanks!
Kieran

**Comment by kobrien** [comment]
I have the feeling this can help me somehow but not sure how to go about implementing it https://github.com/tomakehurst/wiremock/pull/641

**Comment by tomakehurst** [comment]
When you way "redirect URL" you mean the URL onto which the request is proxied?

If so, then #641 will allow you to specify the `proxyBaseUrl` parameter as a Handlebars template with the model described here: http://wiremock.org/docs/response-templating/

**Comment by paztis** [comment]
Hi

Here we talk about renaming the URL not the proxyBaseUrl.

Ex: inputUrl: http://wiremockserver/a/b/.*
ProxyBaseUrl: http://realServer
OutputUrl: http://realServer/d/e/.*

For now we will always have http://realServer/a/b/.* Without any way to change it.

A new param like urlRewritemight be useful for this (like in classic proxy jobs)

**Comment by kobrien** [comment]
Hi all, this is a very old thread and to be quite honest I'm not sure what we ended up doing to achieve the result we needed. In any case I am going to go ahead and close this question now. Thanks for your hep! Kieran

**Comment by paztis** [comment]
You want me to open a new ticket ?
My requirement is the URL rewriting which is not possible for now.
