### ISSUE TITLE
Provide standalone JAR files for 2.6.x

### ISSUE THREAD

**Issue by kenorb** [tomakehurst/wiremock#671]
I can see in Maven repo standalone JAR files such as: [`wiremock-1.58-standalone.jar`](http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/1.58/), but I don't see it under [2.6.x folder](http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/2.6.0/). Can you please provide such?

**Comment by tomakehurst** [comment]
He standalone JAR is under its own artifact from 2.x onwards. Suggest checking the getting started doc.

**Comment by kenorb** [comment]
Ok, found it.

Link: http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.6.0/wiremock-standalone-2.6.0.jar

**Comment by kenorb** [comment]
Ok, found it at the following link:

    http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.6.0/wiremock-standalone-2.6.0.jar
