### ISSUE TITLE
Support @Rule annotation on method

### ISSUE THREAD

**Issue by syhily** [tomakehurst/wiremock#673]
Tks for your cool job, this test tool saved me a lot of time.
But I met a strange issue currently. I have written some code like below:

```java
@Rule
public WireMockRule baseServer() {
    return new WireMockRule(options().port(serverPort()).bindAddress("127.0.0.1").notifier(new ConsoleNotifier(true)), false);
}
```

I marked the `@Rule` annotation on a method instead the field. Because I need to lazy initialize `WireMockRule` and inject the  port which dynamic generated from spring boot to create the real instance. But writing in this way would failed to bind the port.

So I have to modify the code like below:

```java
private volatile WireMockRule mockRule;

@Rule
public synchronized WireMockRule baseServer() {
    if (mockRule == null) {
        mockRule = new WireMockRule(options().port(serverPort()).bindAddress("127.0.0.1").notifier(new ConsoleNotifier(true)), false);
    }
    return mockRule;
}
```

Writing in this way could finally resolve the port binding issue, but it's kind of ugly.

**Comment by tomakehurst** [comment]
So you're saying the second version always works but the first doesn't?

Any idea why there's a difference? I'd have thought if in the first case the method is getting called before the port is allocated then that would happen in the second instance too?

**Comment by syhily** [comment]
Year, the second one work perfectly. But the first one would just fail.
Sample reproduce code:
```java
import org.junit.rules.MethodRule;
import org.junit.rules.TestRule;
import org.junit.runner.Description;
import org.junit.runners.model.FrameworkMethod;
import org.junit.runners.model.Statement;

public class TheRuleRunningTwice implements MethodRule, TestRule {

    @Override
    public Statement apply(Statement base, Description description) {
        return apply(base, null, null);
    }

    @Override
    public Statement apply(Statement base, FrameworkMethod method, Object target) {
        return new Statement() {
            @Override
            public void evaluate() throws Throwable {
                System.out.println("Start Mock Server");
                try {
                    before();
                    base.evaluate();
                } finally {
                    after();
                }
            }
        };
    }

    protected void before() {
        // NOOP
    }

    protected void after() {
        // NOOP
    }
}
```

```java
import org.junit.Rule;
import org.junit.Test;

public class RuleTest {

    @Rule
    public TheRuleRunningTwice rule() {
        return new TheRuleRunningTwice();
    }

    @Test
    public void show() throws Exception {

    }
}
```

Your would see, the `Start Mock Server` printed twice.

**Comment by syhily** [comment]
Implement both `TestRule` and `MethodRule` would cause the Rule class called twice if you put the `@Rule` annotation on a rule method.

**Comment by tomakehurst** [comment]
Right, got it. Time to drop support for old versions of JUnit then I guess! Thanks for the report.
