### ISSUE TITLE
Unable to run in a Java 6 Environment

### ISSUE THREAD

**Issue by jaschenk** [tomakehurst/wiremock#678]
Currently unable to use WireMock in a Java 6 Environment.

Receiving: java.lang.UnsupportedClassVersionError: com/github/tomakehurst/wiremock/junit/WireMockRule : Unsupported major.minor version 51.0

Is only Java 8 Supported with WireMock?

Thanks,
Jeff

**Comment by tomakehurst** [comment]
Java 6 for 1.x. Java 7 for 2.x
