### ISSUE TITLE
Support 'connection reset by peer' fault

### ISSUE THREAD

**Issue by andre2i** [tomakehurst/wiremock#686]
Hello,
I wanted to get the community opinion about implementing a new type of fault which would terminate the connection with a RST message and cause a SocketException to be thrown on the client side. I think it would be useful for increasing the test coverage levels of the http clients.

Thanks!

**Comment by tomakehurst** [comment]
If you know a way to get past Java's socket abstraction sufficiently to do this, I think it would be a great addition. I'll happily merge.

**Comment by andreiacob** [comment]
Sounds great! Also, do you have a CLA that I would need to sign in order to contribute?

**Comment by tomakehurst** [comment]
Nope, no CLA required at this point.

**Comment by tomakehurst** [comment]
I'm going to close this as I assume there'll be a PR opened as/when you work on this.
