### ISSUE TITLE
Identical Requests Return Varying Headers

### ISSUE THREAD

**Issue by herikwebb** [tomakehurst/wiremock#688]
Submitting the same exact request returns different response headers. The former of which causes issues and results in an error. I do not specify Content-Length in the request. It is my understanding that wiremock should return "transfer-encoding: chunked" by default it Content-Length is not specified.

Age →0
Connection →Keep-Alive
**Content-Length →167**
Content-Type →application/json
Date →Fri, 16 Jun 2017 15:06:39 GMT
Proxy-Connection →Keep-Alive
Server →Jetty(9.2.z-SNAPSHOT)

Connection →Keep-Alive
Content-Type →application/json
Date →Fri, 16 Jun 2017 15:10:56 GMT
Proxy-Connection →Keep-Alive
Server →Jetty(9.2.z-SNAPSHOT)
**transfer-encoding →chunked**

**Comment by tomakehurst** [comment]
Please could you post your stub mapping and full request traces so I can try to replicate the problem?

**Comment by tomakehurst** [comment]
Not enough detail to reproduce. Please re-open if you'd like to add some.
