### ISSUE TITLE
How to specify multiple "matchesXPath" expressions?

### ISSUE THREAD

**Issue by HARIKRISHNAPALEMPATI** [tomakehurst/wiremock#692]
This is my request body

"request": {
      "url": "/soaptest",
      "method": "POST",
      "bodyPatterns" : [
          {
              "matchesXPath" : "SOAP-ENV:Envelope/SOAP-ENV:Body/reportXml:GetReportXml//reportXml:First[text()='VALSAMMA']",
              "xPathNamespaces" : {
                  "SOAP-ENV" : "http://schemas.xmlsoap.org/soap/envelope/",
                  "reportXml" : "http://CreditGateWay/Ecommerce/Services/CreditCheck"
              }
          }
      ]
  }

It is giving expected response based on first name in request xml. 
But I want to get get response based on multiple matching criteria in request. For example based on first name and last name.

I have tried like this.

"request": {
      "url": "/soaptest",
      "method": "POST",
      "bodyPatterns" : [
          {
              "matchesXPath" : {
"SOAP-ENV:Envelope/SOAP-ENV:Body/myreport:GetReportXml//myreport:First[text()='cent']",
"SOAP-ENV:Envelope/SOAP-ENV:Body/myreport:GetReportXml//myreport:Last[text()='joe']",
            }
              "xPathNamespaces" : {
                  "SOAP-ENV" : "http://schemas.xmlsoap.org/soap/envelope/",
                  "myreport" : "http://schemas.xmlsoap.org/soap/encoding/"
              }
          }
      ]
  }

It is not working. Could you please suggest me the correct syntax.

**Comment by tomakehurst** [comment]
As per the readme please can you post questions on the mailing list.
