### ISSUE TITLE
Correct encoding of query string parameters?

### ISSUE THREAD

**Issue by jmdacruz** [tomakehurst/wiremock#695]
There are a few issues related to this that have been closed, but I'm not sure if this is a new one or I'm messing something up.

I'm trying to match a query parameter that looks something like this: `$filter={"key": "value"}` (that is, requires URL encoding in both the parameter name and value). I'm using the REST API for loading mappings. When hitting wiremock using Python's `requests` library, the `absoluteUrl` field on the request (obtained by hitting `/__admin/requests`) shows the parameter encoded as follows: `...?%24filter=%7B%22key%22%3A+%22true%22%7D`

I've tried creating the mapping using multiple formats, including:
```json
{
"queryParameters" : {
        "%24filter" : {
          "equalTo" : "%7B%22key%22%3A+%22true%22%7D"
        }
      }
}
```

But I don't seem to be able to find the right combination for the matching to take place. What am I doing wrong?

**Comment by tomakehurst** [comment]
As per the README, please post questions on the mailing list.

**Comment by jmdacruz** [comment]
oops, my bad. I just posted a question on the mailing list, thanks!

**Comment by jmdacruz** [comment]
For future reference, if somebody finds this issue here, the question was posted here: https://groups.google.com/forum/#!topic/wiremock-user/TuBSu5j25ts (Cc: @tomakehurst )
