### ISSUE TITLE
Couldn't find a way to manually activate a Scenario

### ISSUE THREAD

**Issue by balajeetm** [tomakehurst/wiremock#696]
Hi,

Thanks for the wonderful tool.

I've a set of contracts written for different scenarios.
For example
* Error Scenario / Service Unavailable
* Dependent Service Unavailable
* Success Scenario

The tests that I've written are behaviour driven, so the application constructs the query and requests the stub.
When I start the test, I want to activate a scenario, so that for the same kind of request, the application under test (AUT), can get different responses from the stub.

How can this be done?

Regards

**Comment by tomakehurst** [comment]
As per the README, please can you post questions to the mailing list.
