### ISSUE TITLE
WireMock for Jetty should use LocalConnector and LocalEndPoint

### ISSUE THREAD

**Issue by joakime** [tomakehurst/wiremock#699]
Currently, WireMock is using the HttpChannel and other Jetty internals with little to no regard to the rapidly changing internals of Jetty.

A fake network connector is already provided by Jetty via the [`LocalConnector`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/LocalConnector.java) and `LocalEndPoint` objects, please use them instead.

If there is some feature missing from LocalConnector or LocalEndPoint that WireMock needs, then please let us know at https://github.com/eclipse/jetty.project

**Comment by tomakehurst** [comment]
If we switch to a fake network connector, then presumably that means the app won't accept requests over the network?

**Comment by tomakehurst** [comment]
Would break WireMock's core function, so won't fix
