### ISSUE TITLE
Jetty HttpConfiguration is incorrectly used

### ISSUE THREAD

**Issue by joakime** [tomakehurst/wiremock#700]
In [com/github/tomakehurst/wiremock/jetty9/JettyHttpServer](https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java) the HttpConfiguration is improperly used.

If you have a server with 2 connectors (one on http/1.x and another on https/1.x) then the HttpConfiguration belonging to the http/1.x connector should have "secure" configuration references to the https/1.x connector (scheme and port)
The HttpConfiguration belonging to the https/1.x connector should be based on the http/1.x connector.

aka

``` java
HttpConfiguration httpsConfig = new HttpConfiguration(httpConfig);
```

**Comment by tomakehurst** [comment]
What is the impact of not doing this? Have you observed a visible problem in the current setup?

**Comment by tomakehurst** [comment]
No apparent issue here, won't fix.
