### ISSUE TITLE
The hard-coded values of `ignoreArrayOrder` and `ignoreExtraElements` cause problems when recording

### ISSUE THREAD

**Issue by Zomis** [tomakehurst/wiremock#707]
I discovered this while investigating #691 and consider it to be another bug.

`StubbingMappingJsonRecorder.valuePatternForContentType` contains the code `return equalToJson(request.getBodyAsString(), true, true);`

This leads to only one recording being made for these requests:

        request[0] = "{\"columns\": [{\"name\": \"x\",\"y\": 3},{\"name\": \"agreementnumber\",\"a\": 1},{\"name\": \"agreementstatus\",\"b\": 2}]}";
        request[1] = "{\"columns\": [{\"name\": \"agreementnumber\",\"a\": 1},{\"name\": \"agreementstatus\",\"b\": 2}]}";

And these:

        request[0] = "{\"columns\": [1, 2, 3]}";
        request[1] = "{\"columns\": [2, 1, 3]}";

With the following test code:

    public class Buggtest {
    
        public static final String URL = "/post";
        public static final String PROXYBASEURL = "http://httpbin.org";
    
        public static void main(String[] args) {
            WireMockServer wireMockServer=null;
            try {
                wireMockServer = new WireMockServer(options()
                        .port(8099)
                        .notifier(new ConsoleNotifier(true)));
                wireMockServer.start();
                FileUtils.cleanDirectory(new File("/tmp/mappings"));
                FileUtils.cleanDirectory(new File("/tmp/__files"));
                wireMockServer.enableRecordMappings(new SingleRootFileSource("/tmp/mappings"), new SingleRootFileSource("/tmp/__files"));
                configureFor("localhost", 8099);
                stubFor(post(urlEqualTo(URL)).willReturn(aResponse().proxiedFrom(PROXYBASEURL)));
    
                call();
    
                wireMockServer.stop();
            }
            catch (Exception e){
                e.printStackTrace();
            }
            finally {
                if (wireMockServer!=null && wireMockServer.isRunning()) {
                    wireMockServer.stop();
                }
            }
        }
    
        private static void call() {
            String[] request = new String[2];
            request[0] = "{\"columns\": [{\"name\": \"x\",\"y\": 3},{\"name\": \"agreementnumber\",\"a\": 1},{\"name\": \"agreementstatus\",\"b\": 2}]}";
            request[1] = "{\"columns\": [{\"name\": \"agreementnumber\",\"a\": 1},{\"name\": \"agreementstatus\",\"b\": 2}]}";
    
    
            for (int i = 0; i < request.length; i++) {
                System.out.println("Doing request: " + request[i]);
                Response r = given().contentType("application/json").body(request[i]).when().post("http://localhost:8099"+ Buggtest.URL);
                String body = r.getBody().asString();
                System.out.println("Request response:\n------8<----------------------------" );
                System.out.println(body);
                System.out.println("--------------------------------------->8-------");
    
            }
        }
    
    }

Expected behavior: Two files should be recorded, one for each request.
Actual behavior: Only one file is recorded.

Caused by: `return equalToJson(request.getBodyAsString(), true, true);`

Possible fix: Make it possible somehow to inject values for `ignoreArrayOrder` and `ignoreExtraElements` for the `EqualToJsonPattern` when recording.

**Comment by tomakehurst** [comment]
This will be made configurable in the new recorder being worked on.

Additionally there will be more flexibility around what to do with multiple identical requests.

**Comment by MasonM** [comment]
The PR for the new recorder is at PR #674. It doesn't address this use case yet (though it does add a new extension endpoint to transform the stub mappings), but that wouldn't be difficult to add. Here's an idea:
add a new option called "requestBodyPattern" like the following:
```js
"requestBodyPattern": {
    "matcher": "auto|equalTo|equalToXml|equalToJson",
    "matchOptions": {
        "caseInsensitive": true, // only when "equalTo" is used
        "ignoreArrayOrder": true, // only when "equalToJson" is used
        "ignoreExtraElements": true // only when "equalToJson" is used
    }
}
```

Passing "auto" for "matcher" would preserve the current behavior of using the content type to determine the matcher, so that'd be the default. Once it determines a matcher, it'd apply any applicable options under "matchOptions". For example, if you wanted to use the "auto" matcher, but have it preserve array ordering if it goes with "equalToJson", you'd pass:

```json
"requestBodyPatttern": {
    "matcher": "auto",
    "matchOptions": { "ignoreArrayOrder": false } 
}
```

@tomakehurst any thoughts?

**Comment by Zomis** [comment]
@MasonM It seems like your JSON there is what is supposed to go into a mappings.json file, but my issue is mostly about **recording**. It needs to be programmatically possible to record with different values for `ignoreArrayOrder` and `ignoreExtraElements`. AFAIK it is not possible to specify these kind of JSON-params when recording.

**Comment by MasonM** [comment]
@Zomis The new recorder in PR #674 is an API endpoint (`/__admin/recordings/snapshot`) that accepts a JSON string with various options, so I'm proposing a new option here. These options aren't persisted to the mapping files, they're just for customizing the recording process.

The API is also available as an extension: [wiremock-snapshot](https://github.com/MasonM/wiremock-snapshot).

**Comment by tomakehurst** [comment]
@MasonM yes, that's exactly what I had in mind.
