### ISSUE TITLE
Why does your code not at all considering my port configuration 

### ISSUE THREAD

**Issue by popkutty** [tomakehurst/wiremock#709]
WireMockServer wireMockServer = new WireMockServer(8084);
    stubFor(get(urlEqualTo("/bla/bla"))
            .willReturn(aResponse()
                .withHeader("Content-Type", "application/json")
                .withBody(readFile())));
    wireMockServer.start();
    Thread.sleep(10000000);

what is wrong with this? why does it start server at 8084 rather it says so error stating the following
DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://localhost:8080][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 50]
Exception in thread "main" com.github.tomakehurst.wiremock.client.VerificationException: Expected status 201 for http://localhost:8080/__admin/mappings but was 404
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:314)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:299)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:94)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:248)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:243)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:94)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:98)

**Comment by tomakehurst** [comment]
You've set the WireMock server port to 8084, then you've tried to hit it on 8080.

You probably want to call `WireMock.configureFor("localhost", 8084);`

**Comment by popkutty** [comment]
WireMockServer wireMockServer = new WireMockServer(8084);
    stubFor(get(urlEqualTo("/bla/bla"))
    .willReturn(aResponse()
    .withHeader("Content-Type", "application/json")
    .withBody(readFile())));
    wireMockServer.start();
    WireMock.configureFor("localhost", 8084);
    Thread.sleep(10000000);


no luck
thanks for reply.

**Comment by popkutty** [comment]
HttpAdminClient port is still 8080

private <B, R> R executeRequest(RequestSpec requestSpec, PathParams pathParams, B requestBody, Class<R> responseType, int expectedStatus) {
        String url = String.format(ADMIN_URL_PREFIX + requestSpec.path(pathParams), scheme, host, port, urlPathPrefix);
        RequestBuilder requestBuilder = RequestBuilder

**Comment by popkutty** [comment]
Are you starting some servlet in a path and adding mapping through HTTP? For java configuration you could add mapping via normal function call right. Will make your job easier. @tomakehurst

**Comment by popkutty** [comment]
Changing order does the trick. Thank you. 

 WireMockServer wireMockServer = new WireMockServer(8084);
    WireMock.configureFor("localhost", 8084);
    wireMockServer.start();
    stubFor(get(urlEqualTo("/bla/bla"))
    .willReturn(aResponse()
    .withHeader("Content-Type", "application/json")
    .withBody(readFile())));
    Thread.sleep(10000000);

**Comment by tomakehurst** [comment]
Can I suggest you try what I posted?

**Comment by popkutty** [comment]
I tried and changed the order. You better add this to read me. Most of people not use 8080, definatly want to change the port. So please mention the config in readme for different port.

**Comment by tomakehurst** [comment]
http://wiremock.org/docs/java-usage/#configuring-for-static-calls
