### ISSUE TITLE
Requests hang when running standalone with `--verbose` in a detached Docker container

### ISSUE THREAD

**Issue by chrisberkhout** [tomakehurst/wiremock#714]
I'm submitting this to document the issue, but there's probably no change required in WireMock.

I start WireMock in standalone mode via `docker-compose`, as a dependency of my test run container. Everything works fine without `--verbose`. With `--verbose` it works for a while, then gets to a point where it will accept a request but not answer it, causing timeouts. It works if the output is printed out in the terminal, by running it in the foreground. It works if the output is redirected to a file.

Logging is done synchronously. When `--verbose` is on it will log between receiving a request and responding to it. I suspect I'm getting the problem because the call to write the log output is blocking.

This kind of blocking does happen, for example, if you pipe to `less` and don't page through it quickly enough. It may be that Docker is mismanaging the output of the detached container. However, just `cat`ing a log of the 2MB output in a detached container does work.

I'm using Docker 17.05.0 on Linux.

#### Workarounds:
* Don't use `--verbose`
* Run WireMock in the foreground
  (e.g. `docker-compose up wiremock` in separate terminal before bringing up the other containers)
* Redirect the output to a file

**Comment by tomakehurst** [comment]
Thanks for writing this up.

I'll close this for now as (like you say) it doesn't seem there's anything to be done on the WireMock side.

It might be worth posting a note on a mailing list and linking to this issue, just to boost visibility.

**Comment by cemartins** [comment]
Actually, even without `--verbose`, I observe the same behaviour - wiremock docker will accept a request but not answer it, causing timeouts.
I am using gatling to load test an application which makes calls to wiremock stubs. With `--verbose` the container stops responding after 1 test. Without `--verbose` it stops responding after 3 tests.
