### ISSUE TITLE
How to deploy wiremock in Cloud Foundry

### ISSUE THREAD

**Issue by pradeepkusingh** [tomakehurst/wiremock#716]
Team,

I am looking for an option to deploy wiremock in cloud foundry, can you please help? Already posted in the mailing list and didn't get any response. Sorry to post here. Hope someone will answer it.

**Comment by tomakehurst** [comment]
As per the readme, please post questions on the mailing list.

Although, this particular question might stand a better chance of being answered on stackoverflow.

I'd also suggest posting a little more detail about the issues you're having deploying.
