### ISSUE TITLE
CORS OPTIONS headers not working when using a remote server

### ISSUE THREAD

**Issue by jsanta** [tomakehurst/wiremock#721]
Hi.
I'm currently using wiremock on a remote server outside my network.
Using the current configuration for the OPTIONS method like:
```json
{
  "priority":10,
  "request": {
    "method": "OPTIONS",
    "urlPattern": ".*"
  },
  "response": {
    "status": 200,
    "headers": {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin" : "*",
        "Access-Control-Allow-Methods" : "*",
        "Access-Control-Allow-Headers": "Accept, Content-Type, Content-Encoding, Server, Transfer-Encoding, X-Requested-With, X-Authorization",
        "X-Content-Type-Options" : "nosniff",
        "x-frame-options" : "DENY",
        "x-xss-protection" : "1; mode=block"
    }
  }
}
```

works perfectly if I'm connecting from the same network.
After uploading the same mapping files to a remote server, I'm getting this error message:

> XMLHttpRequest cannot load http://my_remote_server:port/api/endpoint. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://my_local_ip:local_port' is therefore not allowed access. The response had HTTP status code 404.

I currently solved it by duplicating my request mappings, changing the method to OPTIONS and deleting the response leaving only a status 200.

Is there any way to get CORS working without this dirty workarounds?

**Comment by tomakehurst** [comment]
As per the readme please post questions to the mailing list.

Also suggest posting a bit more detail about how you're calling the endpoint and how you loaded the mappings into the remote server.

**Comment by jsanta** [comment]
OK not making any more questions.

I uploaded all my wiremock folder (including __files, mappings and a custom response folder for static response files) to the server.
Running the server using `java -jar /opt/wiremock/wiremock-standalone-2.6.0.jar --port 8090  --verbose`
No firewall issues detected as the request  gets to the server, but goes directly to the error endpoint:
```json
{
  "priority":10,
  "request": {
    "method": "ANY",
    "urlPattern": ".*"
  },
  "response": {
    "status": 404,
    "jsonBody": {"status":"Error","message":"Endpoint not found"},
    "headers": {
      "Content-Type": "application/json"
    }
  }
}
```

The calls are being done through a Ionic app, using Angular. I'm debugging the app through the browser. No issues either in the browser.

Please point me out if there's any other information you require to attend the issue (ignore the question about dirty workarounds).
Thanks!

**Comment by ashishgodani** [comment]
Even I am facing the same issue

**Comment by binque** [comment]
+1
