### ISSUE TITLE
Breaking change on HttpAdminClient constructor

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#732]
Restore overload that supports host header but without proxy settings.

**Comment by ggranberry** [comment]
Looking to start contributing to Wiremock. Would this be a good first pull request?

**Comment by tomakehurst** [comment]
Yes, that would be incredibly useful (and not too difficult!)

**Comment by MasonM** [comment]
Looks like this was fixed in 51d5ec3fee64e4569ee11ca65ec42d89cbf8f9f7

**Comment by tomakehurst** [comment]
It was actually fixed by @ggranberry a while before that, but as usual I've been too lazy to close the issue.
