### ISSUE TITLE
NPE in toString() of NearMiss with requestPattern

### ISSUE THREAD

**Issue by koscejev** [tomakehurst/wiremock#734]
This fails with NPE if `getStubMapping()` returns `null`:
```
        RequestPattern requestPattern =
            firstNonNull(this.requestPattern, getStubMapping().getRequest());
```

**Comment by tomakehurst** [comment]
I'm guessing you've seen this when you've got no stub mappings registered?

If so, this is fixed in 351c7b24486acf606fb2a35da8648d9d1218da10

I'll close for now. Please let me know if this doesn't fix it and I'll re-open.

**Comment by koscejev** [comment]
Does that mean that the provided unit test now passes after the fix?

**Comment by tomakehurst** [comment]
No, but the request pattern shouldn't ever be null. And this fixes the case where a null was being passed to the constructor.
