### ISSUE TITLE
How to make test cases for file upload.

### ISSUE THREAD

**Issue by mukeshsudarsanan** [tomakehurst/wiremock#736]
i have one api with file upload options as .csv file. and writing wiremock test cases for it but whenever it hits the this url i am getting body as null

can any one tell me how to set content for for csv upload for integration test. 
---------------------------------------------------------------------------------------------------
 @RequestMapping(method=POST) 
public ResponseEntity<Collection<Result>> upload(@RequestBody MultipartFile body)
            throws Exception {
....
    }
---------------------------------------------------------------------------------------------------

now my test case is like below i am making it as byte[] and setting content 

    public void shouldRespondUploadService() throws Exception {
        MockHttpServletRequestBuilder request = post("/upload").
                .content(makeFileUploadByteArray("__files/upload.csv"))
                .contentType(MediaType.MULTIPART_FORM_DATA);

        mockMvc.perform(request).
                andExpect(status().isOk());
    }

**Comment by tomakehurst** [comment]
As per the README, please post questions to the mailing list.
