### ISSUE TITLE
The wiremock can't detect the conflict

### ISSUE THREAD

**Issue by yourwafer** [tomakehurst/wiremock#740]
<img width="658" alt="dd" src="https://user-images.githubusercontent.com/5535122/29550416-34d888be-8740-11e7-9445-ea4c220e81a7.png">
<img width="642" alt="ee" src="https://user-images.githubusercontent.com/5535122/29550419-37d61900-8740-11e7-84da-1388e122e3c1.png">

**The wiremock can't detect the conflict.
Is there a way to export this error?**

**Comment by tomakehurst** [comment]
I think you need to send this to the Spring Cloud Contract project rather than WireMock.
