### ISSUE TITLE
Intercepting requests to a live server

### ISSUE THREAD

**Issue by adriannotimportant** [tomakehurst/wiremock#742]
HI,

I have an application that uses a third party API to make requests to an third party server at thirdparty.com. I do not specify the thirdparty server name in my code and it cannot be changed
It works well and I would like to add some JUnit testing using WireMock.

I read the proxying documentation but that sounds more like the WireMock server will run locally and the requests to be tested are local requests. 
Is here any way this could be done?

Thank you

**Comment by tomakehurst** [comment]
As per the readme please can you post questions that aren't bug reports or feature requests to the mailing list.
