### ISSUE TITLE
Wiremock use default keystore

### ISSUE THREAD

**Issue by graczun** [tomakehurst/wiremock#748]
Hi,
**Problem description:**
I've got a solution that check https certificate provided on page with certificate stored in my database. I wanted to use wiremock rule to simulate https server on local environment. In this situation I've created own key store with self signed certificate. As you mentioned in documention in HTTPS section I've provided this key store with password to WireMockRule. I've noticed that it still use default key store instead provided one.

**Expected test result:**
After that I've created two tests which valid both scenarios:  proper certificate(same as in provided in KS - proper test) and proper certificate from some https web page(expected failing because certificate is different than provided in KS - negative test).

**Actual test result:**
Both tests throws javax.net.ssl.SSLHandshakeException (same as you mentioned on your documentation in HTTPS section). For one test its expected solution (negative test). After reading your workaround provided in documentation I've used TrustSelfSignedStrategy. After using this strategy, both test returns valid certificate (which is not good result for negative test). After look into TrustSelfSignedStrategy I've noticed that it only checks lenght of certification chain on server, so It will accept all provided certification - which is wrong solution, because I need some validation, not only checking size of it.

After that I've look why my solution throws javax.net.ssl.SSLHandshakeException even when I provided KS to wiremockrule with the same certificate that i want to valid. After some digging in java libraries I found that method: sun.security.ssl.ClientHandshaker::serverCertificate(CertificateMsg var1). **In this method var1.getCertificateChain() returns certificate provided in your default key store (even after i provided my own key store to wiremockrule).**

**Workaround:**
After noticed that behavior I've check what will happen if I would not provide own keystore but use your defualt one to generate self-signed certificate. In this case both scenarios was correct -  proper test results proper validation and negativ test throws SSLHandshakeException. No TrustSelfSignedStrategy was need to use.

**Comment by tomakehurst** [comment]
So you're saying you think there's a bug causing WireMock to use its own keystore even when you've asked it to use the one you've created?

If so, please can you post some code that replicates the problem so that I can investigate?

**Comment by graczun** [comment]
Exactly. Here is a code which I need to test:
```
    public static boolean isCertificateValid(String httpsUrl, String certificate) {
        SSLContext sslContext = null;
	try (InputStream certInputStream = new ByteArrayInputStream(certificate.getBytes(StandardCharsets.UTF_8))) {
	    CertificateFactory cf = CertificateFactory.getInstance("X.509");
	    Certificate ca = cf.generateCertificate(certInputStream);
	    String keyStoreType = KeyStore.getDefaultType();
	    KeyStore keyStore = KeyStore.getInstance(keyStoreType);
	    keyStore.load(null, null);
	    keyStore.setCertificateEntry("ca", ca);

	    String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
	    TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
	    tmf.init(keyStore);

	    sslContext = SSLContext.getInstance("TLS");
	    sslContext.init(null, tmf.getTrustManagers(), null);
	}
        URL url = new URL(httpsUrl);
        HttpsURLConnection con = (HttpsURLConnection) url.openConnection();
        con.setSSLSocketFactory(sslContext.getSocketFactory());
        con.connect();
        return true;
    }
```

After providing wiremock rule like this:

```
    @Rule
    public static WireMockRule wireMockRule = new WireMockRule(wireMockConfig().httpsPort(8443)
            .trustStorePath(TEST.class.getClassLoader().getResource("certs/keystore.jks").getPath())
            .trustStorePassword("password"));
```
I've test this method with parameters : ( "https://localhost:8443" , _certificate in  PEM format_)
Method `sun.security.ssl.ClientHandshaker::serverCertificate(CertificateMsg var1)` still gets your default KS
of course you need to provide new KS and generate self signed certificate and provide it in PEM format.

In case when I provide certificate from your default key store, everything works fine.

**Comment by tomakehurst** [comment]
You need to call `keystorePath(...)` rather than `trustStorePath(...)` in the configuration builder.

**Comment by graczun** [comment]
oh, I've didn't see that. Sorry for confusion :(
