### ISSUE TITLE
Is it possible to make wiremock record different requests in the same file?

### ISSUE THREAD

**Issue by silversky023** [tomakehurst/wiremock#755]
Hi,
 Sorry i dont know where else to ask this. I am new to wiremock. In the past couple of days I worked on it, and  my configuration works fine, it does what i want it to do. But i want to  enhance it in such a way that it is easier to use.  By the way i am not stubbing manually, I am using the WireMockServer and  created a configuration to start and record the requests and responses.

    public static void mockServerStart(String proxyHost, int proxyPort,
			int mockPort) throws IOException, InterruptedException {

		// setting options required by wiremock
		MockHelper mockHelper = new MockHelper();
		mockHelper.setOptions();
		log.info(" [x] Root dir : " + mockHelper.wireMockRootDir);
		// create root directories if necessary
		createDirectories(mockHelper);
		// initialising wiremock
		wireMockServer = new WireMockServer(WireMockConfiguration.options()
				.port(mockPort).withRootDirectory(mockHelper.wireMockRootDir)
		// .notifier(new ConsoleNotifier(true))
		);
		wireMockServer.start();
		log.info(" [x] Starting mock server");
		log.info(" [x] Starting mock server recording");
		if (mockHelper.wireMockRecord) {
			// cleaning the previous stubs else it keeps on creating new files
			// without deleting the older ones
			cleanDirectories(mockHelper);
			wireMockServer.startRecording("http://" + proxyHost + ":"
					+ proxyPort);
		}
	}

It works fine, but the only thing is I need to turn a Boolean switch ON/OFF for it to work. In HoverFly we didn't need to do that. It will start recording if we just delete the previously recorded file. I want to have that functionality in wiremock.

So is it possible to make wiremock write in the same file, if it is then it will make my code easier.

Or is there any other way to do this, from java code. If so please let me know.

**Comment by silversky023** [comment]
Hi,
 Sorry i dont know where else to ask this. I am new to wiremock. In the past couple of days I worked on it, and  my configuration works fine, it does what i want it to do. But i want to  enhance it in such a way that it is easier to use.  By the way i am not stubbing manually, I am using the WireMockServer and  created a configuration to start and record the requests and responses.

    public static void mockServerStart(String proxyHost, int proxyPort,
			int mockPort) throws IOException, InterruptedException {

		// setting options required by wiremock
		MockHelper mockHelper = new MockHelper();
		mockHelper.setOptions();
		log.info(" [x] Root dir : " + mockHelper.wireMockRootDir);
		// create root directories if necessary
		createDirectories(mockHelper);
		// initialising wiremock
		wireMockServer = new WireMockServer(WireMockConfiguration.options()
				.port(mockPort).withRootDirectory(mockHelper.wireMockRootDir)
		// .notifier(new ConsoleNotifier(true))
		);
		wireMockServer.start();
		log.info(" [x] Starting mock server");
		log.info(" [x] Starting mock server recording");
		if (mockHelper.wireMockRecord) {
			// cleaning the previous stubs else it keeps on creating new files
			// without deleting the older ones
			cleanDirectories(mockHelper);
			wireMockServer.startRecording("http://" + proxyHost + ":"
					+ proxyPort);
		}
	}


It works fine, but the only thing is I need to turn a Boolean switch ON/OFF for it to work. In HoverFly we didn't need to do that. It will start recording if we just delete the previously recorded file. I want to have that functionality in wiremock.

So is it possible to make wiremock write in the same file, if it is then it will make my code easier.

Or is there any other way to do this, from java code. If so please let me know.

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as stated in the README.
