### ISSUE TITLE
The import com.github.tomakehurst.wiremock.client.WireMock cannot be resolved

### ISSUE THREAD

**Issue by pravinohal** [tomakehurst/wiremock#757]
I'm trying to use Wiremock standalone. This is how I'm using the maven dependency
  </dependencies>
<dependency>
    	<groupId>com.github.tomakehurst</groupId>
    	<artifactId>wiremock-standalone</artifactId>
    	<version>2.8.0</version>
    </dependency>
    <dependency>
	    <groupId>junit</groupId>
	    <artifactId>junit</artifactId>
	    <version>4.12</version>
	    <scope>test</scope>
	</dependency>	
  </dependencies>
The Jar is installed properly but when I try to access the Library using import it thows below error
The import com.github.tomakehurst.wiremock.client.WireMock cannot be resolved

**Comment by tomakehurst** [comment]
That sounds like a build tool issue rather than something WireMock specific. I suggest you post on the support list for whatever build tool you are using.
