### ISSUE TITLE
Dynamic responses for date using wiremock

### ISSUE THREAD

**Issue by nagarjuna1304** [tomakehurst/wiremock#758]
I am trying to mock a valid dynamic date in response.I need to mock dynamic dates like we have a feature in SoapUI as below

{
  "Body": {
    "SummaryResponse": {
      "id": "002108aa-f363-4c3d-ada4-6ffd5d20ae3a",
      "UserSummary": [
        {
          "user": "1334",
          "grade": "A",
          "date": "${date}"
        }
      ]
    }
  }
}

Under the script we can add below code

import java.text.SimpleDateFormat;
import java.util.Date;

SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
context.date = sdf.format((new Date()-4));

Using soapUI we can able to send dynamic date value to end user using above snippet.
Is this possible in Wiremock to send dynamic response? (I want this logic to be implemented in response )

**Comment by tomakehurst** [comment]
At the moment you'd need to write a `ResponseDefinitionTransformer` that inserts the date into the appropriate place.

There is a feature in the pipeline to support injection of additional context data via your own code when response templating, which would look pretty similar to the SoapUI approach.

**Comment by nagarjuna1304** [comment]
Hi tomakehurst,

Thanks for the reply

Here I'm not using wiremock related code. just mocking request and response as in JSON format.below are the request and response

Request:

{
  "id": "36a99d71-f239-30a8-82c0-e8a8fabffb3a",
  "uuid": "36a99d71-f239-30a8-82c0-e8a8fabffb3a",
  "request": {
    "url": "/api/user/v2/details/20001",
    "method": "POST"
    
  },
  "response": {
    "status": 200,
    "bodyFileName": "body-234567714.json",
    "headers": {
      "Content-Type": "application/json"
      
    }
  }
}

Response:

{
    "userPayments": {
        "userId": "20001",
        "scheduledPayments": [
        {
            "userNumber": "7714",
            "userDate": "08/18/2017",
            "maxAmt": "xxxx"
        }
        ]
    }
}

In the above response userDate field which should dynamically change? is there any possible..Could you please help me on this

**Comment by tomakehurst** [comment]
There's currently no way to do this other than by writing a transformer I'm afraid.

**Comment by nagarjuna1304** [comment]
Thank you for your valuable reply

**Comment by tomakehurst** [comment]
Actually a slightly easier way to do this would be to create a handlebars helper. Still involves code but less than writing a transformer.

**Comment by miguepintor** [comment]
@tomakehurst about the handlebars helper, to do that you have to recompile your own wiremock jar or could you do it passing it to a transformer?
Also, is there any possibility to pass a context to "response-template" ?
Thx for your support

**Comment by tomakehurst** [comment]
No the templating transformer is built in, so you don't have to build your own JAR. It now supports injection of dates.

You can pass parameter from your stub definition to the response template model (in addition to the request).

All documented here: http://wiremock.org/docs/response-templating/

**Comment by tomakehurst** [comment]
Closing, as this was implemented in 646f85df7aec0132e3c09cede7804b3c9c0ce948

**Comment by PraveenKumarDN** [comment]
@tomakehurst How to parse for the value of below soap request?
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inc="http://www.service-now.com/incident">
soapenv:Header/
soapenv:Body
ser:request
ser:requestId654321</ser:requestId>
ser:reasonhello world</ser:reason>
</ser:request>
<sys_id>Kkpravee_Test</sys_id>
</soapenv:Body>
</soapenv:Envelope>

I have tried with belows but still getting null in the response:

ser:uniqueResponseId$(Body.request.requestId.value)</ser:uniqueResponseId>
ser:uniqueResponseId$(Body.ser:request.ser:requestId.value)</ser:uniqueResponseId>
Please help me where am i doing wrong.
https://github.com/opentable/wiremock-body-transformer/issues/28 

Note:
Working fine in json and xml but issue at wsdl soap ui api request response interpolations.
