### ISSUE TITLE
Access query parameter that contain square brackets using handlebars template

### ISSUE THREAD

**Issue by ikhz** [tomakehurst/wiremock#760]
Hi, there is a need to get query parameter that contain square brackets in template eg:
`localhost:8080/some_url/?filter[order_id]=123`
I need to get value of `filter[order_id]`, valid handlebars template for it is:
`"{{ request.query.[filter[order_id\]] }}" `
checked here http://tryhandlebarsjs.com/

my JSON API request:
`{"request": {"urlPath": "/some_url/", "method": "GET"}, "response": {"body": "{{ request.query.[filter[order_id\\]] }}", "status": 200, "transformers": ["response-template"]}}`

but get 500 on request accessing this stub:
`
wiremock.com.github.jknack.handlebars.HandlebarsException: inline@7c8b8743:1:17: found: '[filter[order_id\'
{{ request.query.[filter[order_id\]] }}`

how can I get this query parameter?

**Comment by smalot** [comment]
No news ?
Seems to be still there  :(

**Comment by sudheerah** [comment]
Is this issue still exist?

**Comment by nick-kompas-cko** [comment]
I am also experiencing this, nearly 3 years later

**Comment by prichieri** [comment]
Any news on this?

**Comment by tomakehurst** [comment]
Here's how you do it:

```
{{lookup request.query 'filter[order_id]'}}
```

**Comment by tomakehurst** [comment]
Marking as a feature request to remind me to add a doc note.

**Comment by RibsaS** [comment]
thanks @tomakehurst 
`{{lookup request.query 'filters%5B0%5D%5Bvalue%5D'}}` worked for me to `get filters[0][value]`

**Comment by tomakehurst** [comment]
Documented this in 74058e87

**Comment by chitharanjanIT** [comment]
{{lookup request.query 'filters%5B0%5D%5Bvalue%5D'}} This is not working for me, This is returning entire query params like below

{filters[0][value]&#x3D;NSW, criteria.assetType&#x3D;assetchithatype, criteria.brand&#x3D;NRMA, criteria.campaignCode&#x3D;mockcampaign, criteria.coverType&#x3D;mockCoverType, criteria.coverage&#x3D;mockCoverage, criteria.lineOfBusiness&#x3D;mockLineOfBusiness, criteria.salesChannel&#x3D;mockSalesChannel, criteria.transactionType&#x3D;NEW_BUSINESS, product&#x3D;MOTOR_MOCK}

**Comment by chitharanjanIT** [comment]
My requirement is to read a query parameter with **dot** criteria.coverType
