### ISSUE TITLE
Response is always null from ResponseTransformer or ResponseDefinitionTransformer implementations

### ISSUE THREAD

**Issue by svrajasekar** [tomakehurst/wiremock#762]
Below is my code snippet. "deployHandler" is the implementation of ResponseDefinitionTransformer class. The getBody method of ResponseDefinition parameter that gets passed to "transform" method  always contains null. Am I doing something wrong?. Also "Content-Length" parameter when included in the stub mapping throws NullPointerException when WireMock server attempts to load the stub in to its instance.

		
		wireMockConfig = WireMockConfiguration.wireMockConfig();
		wireMockConfig.extensions(deployHandler);
		wireMockConfig.port(deployPort);

		wireMockServer = new WireMockServer(wireMockConfig);

		for(Document stub : stubs) {
			wireMockServer.addStubMapping(StubMapping.buildFrom(stub.toJson()));
		}
		
		MappingBuilder mappingBuilder = WireMock.any(WireMock.anyUrl());
		wireMockServer.stubFor(mappingBuilder.willReturn(WireMock.aResponse()
				.withTransformers("DeployHandler")
				.withTransformerParameter("serviceName", serviceName)
				.withTransformerParameter("consoleTransactionId", consoleTransactionId)
		));
		
		// Start the deployment service
		wireMockServer.start();

**Comment by tomakehurst** [comment]
Are you managing response bodies as files or inlining them in your stub definitions? If files, then `getBody()` is null because it's only populated when an inline body is specified. For files you instead need to pull them from the `FileSource` passed into the transformer using the body path attribute.

Please can you post code snippet + stack trace for the 2nd problem you've described.

**Comment by svrajasekar** [comment]
Thanks for the response tomakehurst.

I am actually storing the stub mappings in a database and load it using addStubMapping method of the wiremock server object. It successfully loads the mappings. But when I send a request using postman, no content returns. But the status is 200 and the Transfer Encoding is "chunked"

**Comment by svrajasekar** [comment]
I work for HCL Technologies in India and we are building a solution on top of WireMock. We have also put the link in our web application like "Powered by WireMock + your logo". We have a urgent requirement for a client based out of Singapore and I am working hard to complete it as early as possible. Please help.

**Comment by tomakehurst** [comment]
OK, I'm happy to help, but with a few provisos:

* Since this is an implementation question, not a bug report please can you re-post on the mailing list
* Include answers to the questions I asked in my original reply.
* Ideally post the code for your transformer so I can see what you're trying to do

**Comment by svrajasekar** [comment]
tomakehurst:

Here is my transformer code. getBody() always returns null. Please note that responses are inlined in the stub. Some of the responses are pretty much big. Should response body appear in a single line in the stub?

package com.hcltech.vse;

import com.github.tomakehurst.wiremock.client.ResponseDefinitionBuilder;
import com.github.tomakehurst.wiremock.common.FileSource;
import com.github.tomakehurst.wiremock.extension.Parameters;
import com.github.tomakehurst.wiremock.extension.ResponseDefinitionTransformer;
import com.github.tomakehurst.wiremock.http.Request;
import com.github.tomakehurst.wiremock.http.ResponseDefinition;

public class DeployHandler extends ResponseDefinitionTransformer {
	public DeployHandler() {
	}
	
	public boolean applyGlobally() {
		return false;
	}
	
	public String getName() {
		return "DeployHandler";
	}
	
	@Override
	public ResponseDefinition transform(Request request, ResponseDefinition responseDef, FileSource fileSource, Parameters params) {
		System.out.println();
		System.out.println(request.getBodyAsString());
		System.out.println();
		System.out.println(responseDef.getBody());
		
		String transformedResponse = transformResponse(responseDef.getBody());
		
		return ResponseDefinitionBuilder.like(responseDef).but().withBody(transformedResponse);
	}
	
	private String transformResponse(String responseBody) {
		String transformedResponse = null;
		// transformation logic omitted for space conservation
		return transformedResponse;
	}
}

**Comment by svrajasekar** [comment]
tomakehurst:

Below bodyPatterns evaluation fails. That is why I am not getting the  response in the transformer. Seel the request XML below.

"bodyPatterns: [
            {
                "matchesXPath" : "//*[local-name()='accountNumber']/text()='145711450'"
            }, 
            {
                "matchesXPath" : "//*[local-name()='assignedServiceFilterType']/text()='SP'"
            }, 
            {
                "matchesXPath" : "//*[local-name()='productState']/text()='AS'"
            }, 
            {
                "matchesXPath" : "//*[local-name()='productStatus']/text()='AC'"
            }
]
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">  
  <SOAP-ENV:Header> 
    <ns2:MessageHeader xmlns:ns2="http://csi.cingular.com/CSI/Namespaces/Types/Public/MessageHeader.xsd" xmlns="http://csi.cingular.com/CSI/Namespaces/Types/Public/CingularDataModel.xsd">  
      <ns2:TrackingMessageHeader> 
        <version>v112</version>  
        <messageId>135.163.193.218:-45dad65e:15bd43965ac:-7810</messageId>  
        <timeToLive>118000</timeToLive>  
        <conversationId>11234123521235112341235212351123</conversationId>  
        <dateTimeStamp>2017-05-10T15:53:40.180Z</dateTimeStamp> 
      </ns2:TrackingMessageHeader>  
      <ns2:SecurityMessageHeader> 
        <userName>buyonline</userName>  
        <userPassword>buyonline504</userPassword> 
      </ns2:SecurityMessageHeader>  
      <ns2:SequenceMessageHeader> 
        <sequenceNumber>1</sequenceNumber>  
        <totalInSequence>1</totalInSequence> 
      </ns2:SequenceMessageHeader> 
    </ns2:MessageHeader> 
  </SOAP-ENV:Header>  
  <SOAP-ENV:Body> 
    <ns2:InquireFiberServiceAssignedProductDetailsRequest xmlns:ns2="http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireFiberServiceAssignedProductDetailsRequest.xsd" xmlns="http://csi.cingular.com/CSI/Namespaces/Types/Public/CingularDataModel.xsd" xmlns:ns3="http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireUnifiedCustomerLoginProfileResponse.xsd" xmlns:ns4="http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireAvailableFiberServiceAppointmentsRequest.xsd">  
      <ns2:ProductFilterDetails> 
        <ns2:GlobalCustomerDetails> 
          <ns2:productStatus>AC</ns2:productStatus>  
          <ns2:productState>AS</ns2:productState>  
          <ns2:CustomerIdentifier> 
            <ns2:accountNumber>145711450</ns2:accountNumber> 
          </ns2:CustomerIdentifier>  
          <ns2:assignedServiceFilterType>SP</ns2:assignedServiceFilterType> 
        </ns2:GlobalCustomerDetails> 
      </ns2:ProductFilterDetails> 
    </ns2:InquireFiberServiceAssignedProductDetailsRequest> 
  </SOAP-ENV:Body> 
</SOAP-ENV:Envelope>

**Comment by svrajasekar** [comment]
When I pasted the above XML, some of the > symbol went missing. But the XML in my code is proper.

**Comment by tomakehurst** [comment]
Yeah, that's kinda hard to read. Could you re-post but inside a code block (the <> symbol in the editor)? That'll make it a lot easier.

Also, could you post your full stub mappings rather than just the body matchers, and the stacktrace for the exception.
