### ISSUE TITLE
Allow jsonBody in request bodyPatterns

### ISSUE THREAD

**Issue by Preylien** [tomakehurst/wiremock#763]
There should be an option to use jsonBody in the request bodyPatterns as an additional matcher like in the response. You can use equalToJson but it requires the entire message to be escaped.

**Comment by tomakehurst** [comment]
I have a better plan: deprecate `jsonBody` and implement smarter deserialisation in order to allow JSON wherever there's a string value expected. This would mean you can use the same key (e.g. `body` in the response case) regardless of what format you choose.
