### ISSUE TITLE
Json body matcher issue

### ISSUE THREAD

**Issue by svrajasekar** [tomakehurst/wiremock#765]
Below is my stub and when I hit the service, reports 404 as a result of mismatch. I am using WireMock 2.8.0.  Please see under the stub for the actual console output. That is for just one body pattern. What am I doing wrong?

{
    "id" : "e26688a4-1013-424a-bf02-ff803bc935de",
    "request" : {
        "url" : "/operation10",
        "method" : "POST",
        "bodyPatterns" : [ 
            {
                "equalToJson" : "{ \"dateAccepted\" : \"2012-06-14T11:30:40-0700\" }"
            }, 
            {
                "equalToJson" : "{ \"languageCode\" : \"en\" }"
            }, 
            {
                "equalToJson" : "{ \"termsKey\" : \"f0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130d\" }"
            }, 
            {
                "equalToJson" : "{ \"termsType\" : \"electronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosure\" }"
            }, 
            {
                "equalToJson" : "{ \"termsVersion\" : 1 }"
            }
        ]
    },
    "response" : {
        "status" : "200",
        "headers" : {
            "Content-Type" : "application/json"
        },
        "body" : "{\"dateAccepted\":1.339698639E12,\"languageCode\":\"en\",\"termsKey\":\"f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9f0a6f2aa-8e68-45ae-a875-84444ef113e9\",\"termsType\":\"terms\",\"termsVersion\":1}",
        "fixedDelayMilliseconds" : 0
    },
    "uuid" : "e26688a4-1013-424a-bf02-ff803bc935de"
}

CONSOLE OUTPUT:
=============
2017-09-27 18:00:45 INFO  RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2017-09-27 18:00:45 INFO  Request received:
0:0:0:0:0:0:0:1 - POST /operation10

Cookie: [modalDisplayedForStartupEpoch=1506509579726]
Accept: [*/*]
User-Agent: [Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0]
Connection: [keep-alive]
Host: [localhost:2081]
Accept-Language: [null]
Accept-Encoding: [gzip, deflate]
Content-Length: [1048]
Content-Type: [application/json; charset=UTF-8]
{
    "languageCode": "en",
    "dateAccepted": "2012-06-14T11:30:40-0700",
    "termsVersion": 1,
    "termsType": "electronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosureelectronicDisclosure",
    "termsKey": "f0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130df0a6f2aa-8e68-45ae-a875-84444ef1130d"
}

2017-09-27 18:00:45 INFO  Request does not match pattern:
{
  "url" : "/operation10",
  "method" : "POST",
  "bodyPatterns" : [ {
    "equalToJson" : "{ \"dateAccepted\" : \"2012-06-14T11:30:40-0700\" }",
    "ignoreArrayOrder" : false,
    "ignoreExtraElements" : false
  } ]
}
Match details: url=match, method=match, headers=match, queryParams=match, cookies=match, body=no-match
2017-09-27 18:00:45 INFO  Matched response definition:
{
  "status" : 900,
  "body" : "Virtual Service: No responses matched the given request"
}

Response:
HTTP/1.1 900
(no headers)

**Comment by tomakehurst** [comment]
Hi, as I mentioned before please can you post questions to the mailing list rather than opening issues. I try to keep issues for bugs and feature requests, and I'm struggling to stay on top of them even with that in place.

Thanks.
