### ISSUE TITLE
Multiple entries in a cookie causes 500 on wiremock server

### ISSUE THREAD

**Issue by hunzai** [tomakehurst/wiremock#766]
I am not sure it is a feature or an issue but wanted to report here. Usually we will not send a duplicated entry in the cookie but if we do then it should try to match the request and return e.g. a 404. 

Example request
`curl --cookie "s=1234; s=1234" '<wiremock_url>' -v`

Response
`> Host: wiremock1-uat.snc1:8083
> User-Agent: curl/7.52.1
> Accept: */*
> Cookie: s=1234; s=1234
> 
< HTTP/1.1 500 Server Error
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 419
< Connection: close
< Server: Jetty(9.2.z-SNAPSHOT)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /<PATH>. Reason:
<pre>    java.lang.IllegalArgumentException: Multiple entries with same key: s=1234 and s=1234</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>`

**Comment by tomakehurst** [comment]
There's a fix on the way: https://github.com/tomakehurst/wiremock/pull/756

**Comment by hunzai** [comment]
@tomakehurst thanks! I am looking forward.

**Comment by tomakehurst** [comment]
Fixed in 827e7ccb3edcb15bb78e68add74adee536e921b2
