### ISSUE TITLE
Query Parameter's not matching 

### ISSUE THREAD

**Issue by JeevFresno** [tomakehurst/wiremock#773]
I am using wiremock as Standalone server and creating the mapping using Admin API through Json 
and mapping is being created successfully. Here is the mapping 
{
  "id" : "21fba65e-23ce-4be9-82c1-02a779dd669c",
  "request" : {
    "urlPattern" : "v1/safe/files/1234/url?tokenCreator=Creator&tokenExpires=1800",
    "method" : "GET"
  },
  "response" : {
    "status" : 201,
    "body" : "this will return the body",
    "headers" : {
      "Content-Type" : "application/json"
    }
  },
  "uuid" : "21fba65e-23ce-4be9-82c1-02a779dd669c",
  "persistent" : true
}

and i sending the request mapping request as 
http://localhost:8080/v1/safe/files/1234/url?tokenCreator=Creator&tokenExpires=1800

Wiremock verbose response:

Closest match:
{
  "urlPattern" : "/v1/safe/files/1234/url?tokenCreator=Creator&tokenExpires=1800",
  "method" : "GET"
}
2017-10-11 09:05:34.871 Request received:
0:0:0:0:0:0:0:1 - GET /v1/safe/files/1234/url?tokenCreator=Creator&tokenExpires=1800

Authorization: [Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbGxpX2lkdCI6IkFwcGxpY2F0aW9uIiwic3ViIjoidXJuOmVsbGk6c2VydmljZTplZGVsaXZlcnkiLCJhdWQiOiJ1cm46ZWxsaTpzZXJ2aWNlOm1lZGlhIiwic2NvcGUiOiJhcGlwbGF0Zm9ybSIsImlzcyI6InVybjplbGxpOnNlcnZpY2U6aWRzIiwianRpIjoiNmZkMTI2ZDctMzRjOC00YTM4LTliNjgtZDM1MTkyYjRiNjJiIiwiaWF0IjoxNTA3NzM3OTM0LCJleHAiOjE1MDc3MzgyMzR9.hj5tiKmEG2HAtL-BxqWuGTYNRkPJdRcBYaArY4JS9tw]
Host: [localhost:8080]
Accept: [application/json]
X-Correlation-Id: [ce24b495-14be-4433-85cb-86f8e25584dd]

Matched response definition:
(no response definition configured)

Response:
HTTP/1.1 404
(no headers)

Any help or feedback would be very helpful. Where i am going wrong?

**Comment by tomakehurst** [comment]
Please post questions on the mailing list as per the README

**Comment by JeevFresno** [comment]
Thank you for letting me know. I already posted the question 
thanks
