### ISSUE TITLE
How to parse a request body with an array of strings

### ISSUE THREAD

**Issue by yourganesan** [tomakehurst/wiremock#779]
Hi - I have post request API which accepts an array/list of strings and returns a json matching the data in the input list. Assume an example with a rest api accepting a list of customer names and returning the list of customer details for those input customers. How do we write request matching and how do we parse the list of strings and modify the response templates using the input customer names. Can you give some pointers?

**Comment by tomakehurst** [comment]
As per the readme please post questions to the mailing list.
