### ISSUE TITLE
Wiremock stops responding after running for a while 

### ISSUE THREAD

**Issue by elangomca** [tomakehurst/wiremock#781]
I am running wiremock in standalone mode i have exposed 7 services each on different port to mock different external systems we interface with.  We use this server in our development and QA environment. After running for a while we found java wiremock stops. I am not sure what is the issue 
java -Xms1024m -Xmx1024m -jar wiremock-standalone-with-log-2.8.0.jar --port 1111 --root-dir D:/qa_wiremock/qa > 1111.log

I have enabled the log and found the following error 
wiremock_1111.log:wiremock.org.eclipse.jetty.io.EofException: null
wiremock_1111.log:      at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.writeAndTranslateExceptions(WireMockHandlerDispatchingServlet.java:165)
wiremock_1111.log:Caused by: java.io.IOException: Broken pipe
wiremock_1111.log:05:41:07.221 [qtp849596823-21 - /user/2LDBPHXJ] DEBUG wiremock.org.eclipse.jetty.io.WriteFlusher - write exception
wiremock_1111.log:wiremock.org.eclipse.jetty.io.EofException: null

We are running in a amazon m4 large (2 vcpu, 8gb mem)

**Comment by tomakehurst** [comment]
If you're keeping it running for a long time you'll need to limit the request journal, otherwise it keeps growing indefinitely and consumes all the heap space.

Please post further questions to the mailing list.
