### ISSUE TITLE
Support for Magic String and Dates

### ISSUE THREAD

**Issue by iamshreeram** [tomakehurst/wiremock#782]
Is there a way to handle magic strings and dates. I want response body to contain few data from GET URL or the body of POST method.  
Example :
If request URL is like, example.com/resources/getweather?state=AR&id=123

Response should be
{
"state":"AR" 
"id":"123" 
"weather":"72"
}

[The state and id in response varies based on request been sent]

**Comment by tomakehurst** [comment]
Check out the response templating feature.

Please post future questions on the mailing list as per the readme.
