### ISSUE TITLE
NoSuchMethodError when mocking GET request in Wiremock

### ISSUE THREAD

**Issue by ryzhman** [tomakehurst/wiremock#785]
#I have a method that calls a 3rd party server with GET, POST and DELETE requests. To mock server's responses I decided to use Wiremock and it works fine for DELETE and POST calls. However, the problem appears when I try to mock GET request. Here is what I get from response.getEntity() in getStatistics() method:

`<h2>HTTP ERROR: 500</h2> <p>Problem accessing /v1/solutiondata/stats. Reason: <pre>    `java.lang.NoSuchMethodError: `javax.servlet.http.HttpServletResponse.getHeader(Ljava/lang/String;)Ljava/lang/String;</pre></p>

Here is a ServerUtils.getStatistics() method I want to test:

`... try (CloseableHttpClient client = `HttpClientBuilder.create().setDefaultRequestConfig(requestBuilder.build()).setDefaultCredentialsProvider(cr`edsProvider).build()) {            
`URIBuilder builder = new URIBuilder(SystemProperties.getServerAddress() + "/v1/data/stats");             
`HttpGet get = new HttpGet(builder.addParameter("name", name).build());              
`HttpResponse response = client.execute(get);             
`if (response.getStatusLine().getStatusCode() == 200) {                 
`return new JSONObject(EntityUtils.toString(response.getEntity(), "UTF-8"));             
`} ...

And here is a test itself: 

`@Rule     
`public WireMockRule wireMockRule = new WireMockRule(WireMockConfiguration.options().port(8000)); 
`@Test     public void getStatisticsTest() throws JSONException{         
`wireMockRule.stubFor(get(urlPathEqualTo("/v1/data/stats")) 
`//                .withHeader("Content-Type", equalTo("text/plain"))  
`//                .withQueryParam("name", containing("testName"))                
`.willReturn(aResponse()                         
`.withStatus(200)                        
`.withBody("{\"name\":\"testName\"," +                                
 `"\"id\":\"#123\"," +                                 
`"\"anon\": \"100\"," +                                
 `"\"urls\":\"150\"}")));          
`JSONObject jsonWithResult = new JSONObject("{\"name\":\"testName\"," +                
 `"\"id\":\"#123\"," +                 
`"\"anon\": \"100\"," +                
 `"\"urls\":\"150\"}");         
`assertEquals(jsonWithResult, ServerUtils.getStatistics());          
`verify(1, getRequestedFor(urlEqualTo("/v1/data/stats"))                 
`.withQueryParam("name", equalTo("testName")));     
`}

I have already tried adding the latest servlet-api (4.0) to my pom.xml (test scope), but it didn't make a difference.

Adding explicit content-type also didn't help.

Stub mapping is created well (I can get it from wireMockRule.getStubMappings()). If I use created stub mapping in a form of JSON in standalone wiremock instance it works as expected and catch corresponding calls.

**Comment by tomakehurst** [comment]
Suggest you dump out your dependencies and find out what's pulling in the Servlet API dependency. Bear in mind several dependencies embed it directly (Jetty being one of these), so explicitly adding a dependency on it won't necessarily fix the problem.

Please post future questions to the mailing list as per the README.
