### ISSUE TITLE
Using Custom Handlebars helpers in Standalone

### ISSUE THREAD

**Issue by yishaic** [tomakehurst/wiremock#789]
I want to use a custom handlebars helper for response templating which I will write, but in wiremock standalone. Is that possible? Didn't find a way to do it in the docs. 
Can it be integrated as a helper to be available in the classpath when I start the wiremock standalone server?

In my case, the need is for a dynamic response which is generated with some calculations on the current timestamp (e.g. the timestamp of the current rounded hour - 1508947200).

**Comment by tomakehurst** [comment]
At this point you'd need to build your own standalone JAR to achieve this, as there isn't a configuration option for adding helpers.

A few people have been asking about working with dates in templates recently, and I'd like to add a set of helpers as standard for this e.g. to calculate offsets from the current time, render dates in different formats etc.

I'd happily receive a PR to add this to WireMock if you'd like to go down that route.

**Comment by yishaic** [comment]
Thanks for your response.
Maybe I can do that by using my own extension and then adding it to the classpath? as was done [here](https://github.com/adamyork/wiremock-velocity-transformer)?

I think dynamic dates helpers would be useful, indeed. Would love to help with a PR but I still have to decide whether I will got that road.
Specifically regarding render dates in different formats, I think most of it is already available with the functionality of the string helpers of java handlebars.

**Comment by tomakehurst** [comment]
Helpers aren't a full extension in their own right, they're added during construction of the `ResponseTemplatingTransformer` extension, so you can't at present specify them on the command line.

As I mentioned, at this point you'll need to "re-bake" your own WireMock JAR with these added.

**Comment by alexanderm2018** [comment]
Hi Tom,
Could you add a handlebars helper which can iterate over set of data x amount of time 
 {{#times 10}}
    test
  {{/each}}

**Comment by asarkar** [comment]
@yishaic I've a similar need (see https://github.com/tomakehurst/wiremock/issues/1000) and would appreciate if you can tell me what you ended up doing.

**Comment by yishaic** [comment]
@asarkar I've ended up using other internal service in our system for this specific request mock. Unfortunately I didn't have the time to make a PR for wiremock and that was the fastest solution.
