### ISSUE TITLE
Mocking an external site

### ISSUE THREAD

**Issue by skartikreddy** [tomakehurst/wiremock#792]
Hi,

I am new to wiremock.
I got struck at a point where I need to mock an external site, say http://smarttrains.com. 
While doing this I would like return response based on the end point. Let's say, http://smarttrains.com/add/bob return a json {"Added":"bob"}.
The issue here is I wont be having a port number on which smarttrains is running. All i want to do is to mock requests(said, i have all requests) coming to that site and send response according to request.

I did some work where I mocked an internal site say Product-catalog. I mocked it successfully because i know the port on which the requests where made, so i started wiremock server on that particular port.
It was like http://localhost:8888/product/add.

I need to do the same mocking but for an external site now.

Please help me in this regards.

Thanks in advance

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the readme

**Comment by skartikreddy** [comment]
Hi,

I am new to wiremock.
I got struck at a point where I need to mock an external site, say
http://smarttrains.com.
While doing this I would like return response based on the end point. Let's
say, http://smarttrains.com/add/bob return a json {"Added":"bob"}.
The issue here is I wont be having a port number on which smarttrains is
running. All i want to do is to mock requests(said, i have all requests)
coming to that site and send response according to request.

I did some work where I mocked an internal site say Product-catalog. I
mocked it successfully because i know the port on which the requests where
made, so i started wiremock server on that particular port.
It was like http://localhost:8888/product/add.

I need to do the same mocking but for an external site now.

Please help me in this regards.

Thanks in advance
