### ISSUE TITLE
Spurious failure with "request was unmatched by any stub matching" since upgrade to WireMock 2.9.0

### ISSUE THREAD

**Issue by trejkaz** [tomakehurst/wiremock#795]
Without changing any of our own code, updating from WireMock 2.8.0 to 2.9.0 causes many tests to fail with spurious "unmatched request" errors.

Example test:

    @Test
    public void testAuditLogRequestHeader() throws Exception
    {
        callingOurStuffHere();
        verify(postRequestedFor(urlEqualTo("/1/team/log/get_events"))
                   .withHeader("Authorization", WireMock.equalTo("Bearer " + TOKEN))
                   .withRequestBody(equalToJson("{}")));
    }

Failure text:

    com.github.tomakehurst.wiremock.client.VerificationException: A request was unmatched by any stub mapping. Request was: 
    
    	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequests(VerificationException.java:92)
    	at com.github.tomakehurst.wiremock.junit.WireMockRule.checkForUnmatchedRequests(WireMockRule.java:90)
    	at com.github.tomakehurst.wiremock.junit.WireMockRule.access$000(WireMockRule.java:34)
    	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:74)
    	at com.acme.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
    	at com.acme.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
    	at com.acme.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
    	at com.acme.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
    	at com.acme.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
    	at com.acme.common.test.rules.Timeout$CustomFailOnTimeout$StatementRunner.run(Timeout.java:137)
    	at java.lang.Thread.run(Thread.java:745)

The odd thing is how it doesn't actually print out anything...

This appears to occur consistently for tests using `verify(postRequestedFor(...))` but tests using `stubFor(post(...))` still pass.

**Comment by trejkaz** [comment]
LOL, well... I guess this answers the last part of the question:

{noformat}
            return new VerificationException(String.format("A request was unmatched by any stub mapping. Request was: ",
                    unmatchedRequests.get(0)));
{noformat}

**Comment by trejkaz** [comment]
Extra strangeness, I breakpointed in the place where it was throwing the error, and evaluated:

```
WireMock.postRequestedFor(WireMock.urlEqualTo("/1/team/log/get_events"))
        .withHeader("Authorization", WireMock.equalTo("Bearer [token redacted]"))
        .withRequestBody(WireMock.equalToJson("{}"))
        .build()
        .match(unmatchedRequests.get(0))
        .isExactMatch()
```

This returns true... so the request _did_ match, but was on the list of unmatched requests for some reason.

**Comment by tomakehurst** [comment]
Did it do this consistently or intermittently? Could you supply a full test case that replicates this?

**Comment by trejkaz** [comment]
I'm working at removing both our framework and Dropbox's API from the picture but it's taking a while. It happens every single test run, though, so I expect it to be fully reproducible. Problem is, I might end up with a test case which, although standalone, still contains our real credentials to connect to Dropbox. :|

**Comment by trejkaz** [comment]
Here's where we are so far. I redacted the token out but I've removed all instances of the Dropbox library itself and it's still getting the same unmatched result.

```
import java.io.IOException;

import com.github.tomakehurst.wiremock.core.WireMockConfiguration;
import com.github.tomakehurst.wiremock.junit.WireMockRule;
import org.apache.commons.io.input.ProxyInputStream;
import org.apache.http.HttpHost;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.conn.routing.HttpRoute;
import org.apache.http.conn.ssl.NoopHostnameVerifier;
import org.apache.http.conn.ssl.TrustSelfSignedStrategy;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.message.BasicHeader;
import org.apache.http.ssl.SSLContexts;
import org.junit.Rule;
import org.junit.Test;

import static com.github.tomakehurst.wiremock.client.WireMock.*;

public class TestWiremockIssue
{
    @Rule
    public final WireMockRule wireMockRule = new WireMockRule(WireMockConfiguration.wireMockConfig().httpsPort(8443));

    private static final String TOKEN = "[REDACTED]";


    @Test
    public void testAuditLogRequestHeader() throws Exception
    {
        codeUnderTest();

        verify(postRequestedFor(urlEqualTo("/1/team/log/get_events"))
                   .withHeader("Authorization", equalTo("Bearer " + TOKEN))
                   .withRequestBody(equalToJson("{}")));
    }

    Object codeUnderTest() throws Exception
    {
        HttpPost request = new HttpPost("https://api.dropbox.com/1/team/log/get_events");
        request.addHeader(new BasicHeader("Authorization", "Bearer " + TOKEN));
        request.addHeader(new BasicHeader("Content-Type", "application/json"));
        request.addHeader(new BasicHeader("Accept", "application/json"));
        request.setEntity(new StringEntity("{}", ContentType.APPLICATION_JSON));
        request.removeHeaders("Content-Length");

        CloseableHttpClient httpClient = createClient();
        CloseableHttpResponse response = httpClient.execute(request);

        if (response.getStatusLine().getStatusCode() == 200)
        {
            return new ProxyInputStream(response.getEntity().getContent())
            {
                @Override
                public void close() throws IOException
                {
                    super.close();
                    response.close();
                    httpClient.close();
                }
            };
        }
        else
        {
            return null;
        }
    }

    private CloseableHttpClient createClient() throws Exception
    {
        return HttpClientBuilder.create()
                                .disableAuthCaching()
                                .disableAutomaticRetries()
                                .disableCookieManagement()
                                .disableRedirectHandling()
                                .disableContentCompression()
                                .setSSLContext(SSLContexts.custom().loadTrustMaterial(null, new TrustSelfSignedStrategy()).build())
                                .setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE)
                                .setRoutePlanner((httpHost, httpRequest, httpContext) ->
                                                     new HttpRoute(new HttpHost("localhost", 8443, httpHost.getSchemeName())))
                                .build();
    }
}

```

**Comment by trejkaz** [comment]
Should note that I've tried to remove Commons HTTP from the code a couple of times, and each time it resulted in a different error, and I haven't quite figured out what I did wrong when replacing it with `java.net` calls.

**Comment by tomakehurst** [comment]
OK, thanks for posting the test case. I'll try and take a look.

**Comment by trejkaz** [comment]
On breakpointing it and stepping around, it looks like the response I get back is 404.

I don't really use this `verify(...)` style in any of my own tests so I don't know how it's supposed to work, but in my own tests, I'm using `stubFor(...)` before doing the action, and I get a 200 response. And with this other style where it's checked after doing the action, I'm not entirely sure how it's supposed to work.

But in this particular case, if I do change out their style for my usual stubbing style, the test passes...

**Comment by tomakehurst** [comment]
OK, so you're not actually creating any stubs here. WireMock's default behaviour is to fail your test if you've made requests that it hasn't been able to match, on the assumption that this probably means you've missed something. This is analogous to the approach some object mocking tools take where unexpected calls are considered errors.

Two options to fix this:

1. Stub the call being made so that there's something to match it (I'd consider this best practice)
2. Disable the failure behaviour by setting `failOnUnmatchedRequests` to false in the rule constructor.

**Comment by trejkaz** [comment]
I've ended up updating all the tests using verify to use stubFor instead, and they're passing, so I'll just close this. Thanks for the info.
