### ISSUE TITLE
Detailed matching report is missing

### ISSUE THREAD

**Issue by marcingrzejszczak** [tomakehurst/wiremock#798]
Problem:

For some reason when running WireMock server with stubs from JSONs, when there is no match I don't get this beautiful diff report.

How to replicate it:

First build the stubs locally (you'll be able to see the JSON stubs under `target/stubs/.../mappings`

```
$ cd producer-with-stubs-per-consumer
$ ./mvnw clean install
```

Next, change the name that will be sent to WireMock (https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/consumer_with_stubs_per_consumer/src/test/java/com/example/BeerControllerTest.java#L55) from `marcin` to sth else e.g. `fooo` and run that test. That way a request with a non matching name should be received and in the report I'd expect to see a nonmatching Json Path.

This might be helpful (maybe) - https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/provider/wiremock/WireMockHttpServerStub.java#L106-L110 - cause this is how we start the WireMock server.

**Comment by tomakehurst** [comment]
Diff reports are now written to the log in addition the response
