### ISSUE TITLE
Query Parameter Does not Work in Redirect URI with Response Templating

### ISSUE THREAD

**Issue by bh84** [tomakehurst/wiremock#800]
I am attempting to use response templating to map a query parameter (redirect_uri) from the request  to the Location header of the response. The redirect_uri that is provided in the request contains a query parameter within it. The '=' within the query parameter portion of the redirect_uri gets translated into &#x3D; 

**Request**

`http://localhost:8080/oauth2/v1/authorize?client_id=client_confidential_cdn&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%3Fstate%3Dcompleted&display=popup&response_type=code`

**Mapping**

```{
  "request" : {
    "urlPath" : "/oauth2/v1/authorize",
    "method" : "GET",
    "queryParameters" : {
      "client_id" : {
        "matches" : "(.*?)"
      },
      "redirect_uri" : {
        "matches" : "(.*?)"
      },
      "display" : {
        "matches" : "popup"
      },
      "response_type" : {
        "matches" : "code"
      }
    }
  },
  "response" : {
    "status" : 302,
    "jsonBody" : {},
    "headers" : {
      "Cache-Control" : "no-store",
      "Content-Type" : "application/json;charset=UTF-8",
      "Date" : "Tue, 24 Oct 2017 23:49:55 GMT",
      "Location" : "{{request.query.redirect_uri}}&code=abc123",
      "Pragma" : "no-cache",
      "X-Application-Context" : "passport-ist:redis,jpa,local,cloud:0",
      "X-Vcap-Request-Id" : "4a799646-783f-43de-71d8-09248cff0d98"
    },
    "transformers": ["response-template"]
  }
}

**Comment by tomakehurst** [comment]
This is due to Handlebars escaping the content. You can avoid this with triple braces e.g.

```
{{{request.query.redirect_uri}}}
```

**Comment by bh84** [comment]
This worked. Thanks for the help!

**Comment by ramswaroop** [comment]
Just a qq for @tomakehurst, I see in the docs that we can use the data sent in the request in the response like `{{request.query.redirect_uri}}` but is there any way to access the data in my java code itself. I couldn't find any such documentation on the same.
