### ISSUE TITLE
URL Matching With Optional Query Params

### ISSUE THREAD

**Issue by chrisBLIT** [tomakehurst/wiremock#806]
Have a question, working on some spring contract tests using wire mock.  I'm testing a call that has optional request params, I want my stub to reflect this, so that if I test against the stub I can leave out the optional params and it will still be valid.  Here is an example of what I have to date:

```java
MvcResult result = mockMvc
                .perform(get(BASE_URL + "example?startDateTime=2012-10-01T09:45Z&endDateTime=2012-10-01T09:45:00Z"+ "&type=NBQ&pageNumber=0&pageLimit=10").accept(MediaType.APPLICATION_JSON_VALUE))

                .andExpect(status().isOk()).andDo(WireMockRestDocs.verify()
                        .wiremock(WireMock.get(urlPathMatching(BASE_URL + "example"))
                        		.withQueryParam("startDateTime", WireMock.matching(ISO8601_FORMAT))
					.withQueryParam("endDateTime", WireMock.matching(ISO8601_FORMAT))
					.withQueryParam("type", WireMock.matching(".*"))
					.withQueryParam("pageNumber", WireMock.matching("[0-9]*"))
					.withQueryParam("pageLimit", WireMock.matching("[0-9]*"))
                        ).stub("view/getOneEvent"))
                .andReturn();
```

In the above example startDateTime is the only required param needed.  so I would like the rest of the queryParams to be optional.  I tried adding the regex "?" but I think it might be the param key that is causing the issue.

Is there an easy way in this case to have my queryParams as optionals?  it would perhaps be good to have the key as a pattern matcher? (or perhaps i'm going about this totally the wrong way)

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.
