### ISSUE TITLE
Unable to read attributes from request body in response matching

### ISSUE THREAD

**Issue by balajeetm** [tomakehurst/wiremock#809]
**Request Body**
{
  "store": "1234",
  "pointOfSale": "81",
  "currency": "GBP"
}

**Mappings**
{
  "request": {
    "url": "/request",
    "method": "POST",
    "headers": {
      "Content-Type": {
        "equalTo": "application/json"
      }
    }
  },
    "response": {
    "status": 200,
    "bodyFileName": "request.json",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers": ["response-template"]
  }
}

**request.json**
{
  "Id": "123e4567-e89b-12d3-a456-426655440000",
  "state": "open",
  "store": "{{jsonPath request.body '$.store'}}",
  "pointOfSale": "81"
}

**Expected Response**
Status Code - 200
Response body:
{
  "Id": "123e4567-e89b-12d3-a456-426655440000",
  "state": "open",
  "store": "1234",
  "pointOfSale": "81"
}

**Actual Response **
Status Code - 500
com.github.jknack.handlebars.HandlebarsException: inline@68d3aa18:7:14: could not find helper: &apos;jsonPath&apos;
  &quot;store&quot;: &quot;{{jsonPath request.body $.store}}&quot;,

**Comment by tomakehurst** [comment]
Please post questions on the mailing list as per the README
