### ISSUE TITLE
Using Wiremock Client to connect to a standalone instance using client authentication

### ISSUE THREAD

**Issue by dan-thomson-bbc** [tomakehurst/wiremock#810]
Hi,
I have a standalone wiremock process running with the following setup:

```
mockServer = new WireMockServer(wireMockConfig().httpsPort(8443)
                                                    .keystorePath(getSystemProperty(SSL_KEY_STORE))
                                                    .keystorePassword(getSystemProperty(SSL_KEY_STORE_PASSWORD))
                                                    .trustStorePath(getSystemProperty(SSL_TRUST_STORE))
                                                    .trustStorePassword(getSystemProperty(SSL_TRUST_STORE_PASSWORD))
                                                    .needClientAuth(true)
```

Is it possible to connect to this instance from a remote host using the wiremock client?

I am trying to instantiate an instance of com.github.tomakehurst.wiremock.client.Wiremock so that I can pass a custom truststore and keystore so that the client can use to interact with the remote standalone instance. Is there a way to do this? It looks like I can't configure the HTTP Client used by the client.Wiremock instance. 

Thanks in advance for any help!

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.
