### ISSUE TITLE
How do we mock an external third party service call

### ISSUE THREAD

**Issue by sachinstar2010** [tomakehurst/wiremock#819]
I have a problem with Wiremock in mocking a third party call. Let us say we use a third party SDK which internally uses an Amazon AWS Post call. I am not able to mock this call. Can you help me with the way forward? @tomakehurst

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README

**Comment by sachinstar2010** [comment]
Done. @tomakehurst
