### ISSUE TITLE
2.12.0 breaks getRequestedFor method when used with withFixedDelay

### ISSUE THREAD

**Issue by galan** [tomakehurst/wiremock#822]
The behavior of `getRequestedFor` seems to be changed from 2.11.0 to 2.12.0, which breaks our existing tests that rely on the `withFixedDelay(..)` method. If we want to verify that the request did not returned 
```java
		rest.given(
			get(urlEqualTo("/dummy?aaa=123"))
				.willReturn(aResponse()
					.withFixedDelay(1100)
					.withStatus(200)
					.withBody("ok")));

		// something like client.target(..).async().get(); which returns immediately
		doTheRestCall(); 

		// this call works prior 2.12.0 and breaks now. Should ensure that call not has been returned
		rest.verify(0, getRequestedFor(urlEqualTo("/dummy?aaa=123")));
		// after waiting the fixedDelay the check is valid
		sleep("1100ms");
		rest.verify(1, getRequestedFor(urlEqualTo("/dummy?aaa=123")));
```

If the semantics of `getRequestedFor(..)` has changed, what would be the new way to verify this?

**Comment by tomakehurst** [comment]
Yes, the semantics have changed between these versions. Arguably a breaking change, I know, but I felt that since you're validating receipt of the request rather than it being responded to that it made more sense.

**Comment by galan** [comment]
I understand that.
How could I test the code now? My client waits for a specific time, if the response takes longer it should return. `.async().get().get(1, TimeUnit.SECONDS);`
I have to validate that code, while `getRequestedFor` should return all requests that have been made, another method like `getReturnedRequestsFor` (or some other naming) would be helpful for such cases. Maybe I missed some method that do the equivalent?

**Comment by tomakehurst** [comment]
Closing dormant issue
