### ISSUE TITLE
feign mock list of object withbody in stubfor

### ISSUE THREAD

**Issue by 4040** [tomakehurst/wiremock#829]
Hi team am new to wiremock trying to achieve to return list of object  by withbody in stubfor
below is feign client
 
@FeignClient(name="hystrix")
public interface FeignService {

    @RequestMapping(method= RequestMethod.GET, value = "location")
	public List<Room> room(@RequestParam("size") String size );
}

am able mock and return with string.but how to mock  with json file which will have list of object or with any method to set value in wiremock???.kindly help on this

thank in advance

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.
