### ISSUE TITLE
DatatypeConverter unavailable on Android

### ISSUE THREAD

**Issue by Mauin** [tomakehurst/wiremock#840]
`javax/xml/bind/DatatypeConverter` is a class that is unavailable on Android.
Thus it breaks newer Wiremock versions which use `DatatypeConverter` for Android clients.

I propose to find another solution that does not rely on `DatatypeConverter` by default to make newer Wiremock versions compatible with Android. I've seen other projects also implement runtime checks if these classes exist in the current runtime and otherwise fall back to other implementations.

There might be other classes as well inside the code that are incompatible with Android. But removing `DatatypeConverter` would be a start.

Happy to contribute if you agree with finding a solution for this.

**Comment by tomakehurst** [comment]
Argh, damn. Thanks for pointing this out.

The reason for changing was performance - another user had discovered that `DataTypeConverter` was quite a lot quicker than the Guava implementation.

I think a runtime toggle as you describe would make a lot of sense, and if you could contribute a PR that would be awesome.

What this also tells me is that we really need an Android CI build in the Travis config. Is this something you'd feel like tackling also?

**Comment by Mauin** [comment]
Sounds good. I'll go with the runtime toggle then, using the faster `DatatypeConverter` by default and falling back to the Guava implementation if `DatatypeConverter` is not available. I'll try to get this done over the weekend.

As for the Android CI build I can take a look at that. I'll create a separate issue for it.

**Comment by tomakehurst** [comment]
Great, thanks for your help with this!

I'll keep an eye out for the PR and get it through asap when it arrives.

**Comment by Mauin** [comment]
Just checked with the final v2.14.0 release and can confirm that Wiremock properly works again on Android! Thanks for releasing the changes.
