### ISSUE TITLE
Usage of File instead of Path and Paths for backward compatibility

### ISSUE THREAD

**Issue by edamyanov** [tomakehurst/wiremock#843]
After version 2.10.1 in this [commit](https://github.com/tomakehurst/wiremock/commit/870bea08105bb52b862e1d0df42cb83daf400023#diff-b7e911d0638032925a68f823e7589b3b)  were imported Path and Paths in the file AbstractFileSource.java. When using wiremock with android these two imports were introduced only with API level 26 and above. Most of the android apps are supporting older versions of API levels for which wiremock version 2.10.1 will be the last one which they could update to.  I suggest a PR  [https://github.com/tomakehurst/wiremock/pull/842](PR)

**Comment by tomakehurst** [comment]
Thanks for reporting this.

This is the 2nd Android regression reported today. The reporter of the first is going to work on an Android test project + Travis build so hopefully this won't happen quite as often.

**Comment by tomakehurst** [comment]
Fixed in 957185267af4dc81b2a03bf609e3239990f6e72a and the linked PR.
