### ISSUE TITLE
Usage of javax.xml.bind.DatatypeConverter in Encoder breaks android compatibility

### ISSUE THREAD

**Issue by MarcoLied** [tomakehurst/wiremock#845]
With this [change](https://github.com/tomakehurst/wiremock/commit/06c18a35657fe6cf2df5140a14aa62750b7e2248) of `Encoder` you broke the android compatibility of wiremock, given that android does not provide any `javax.xml.bind` class which can be seen [here](https://developer.android.com/reference/javax/xml/package-summary.html).

Was it really neccessary to move away from `com.google.common.io.BaseEncoding` or `java.util.Base64` like one [commit](https://github.com/tomakehurst/wiremock/commit/4394028d6fccc3751f87bda076088a96916f3aee) before?

**Comment by tomakehurst** [comment]
See:
https://github.com/tomakehurst/wiremock/pull/844, https://github.com/tomakehurst/wiremock/issues/840 and https://github.com/tomakehurst/wiremock/pull/796.

For future ref, I suggest doing a quick search before posting a new issue.
