### ISSUE TITLE
About use "queryParameters".

### ISSUE THREAD

**Issue by SilenceCarrot** [tomakehurst/wiremock#848]
Hello, Okami，I need your help very anxious.

first, the wiremock version is wiremock-standalone-2.13.0.jar, yes , it's running as a standalone process.

second, across terminal，run:
`curl -X POST --data '{"request":{"queryParameters":{"key1":{"equalTo":"value1"}},"method":"GET","url":"/interface24"},"response":{"body":"interface24","status":"200"}}' http://127.0.0.1:8089/__admin/mappings`

now, I want quest this stubbing. So I run:
`curl 'http://127.0.0.1:8089/interface24?key1=value1'`

!!!!!My God!!!!!!!!!!!!!!!!   no match!
response:
![image](https://user-images.githubusercontent.com/15966265/34818776-cce07cf4-f6f6-11e7-8b01-b9373e056324.png)

Can you answer me？ Why？ See the response, why this url are different that the request url and stubbing url.

Hope your message. Thank you very match.

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.

**Comment by SilenceCarrot** [comment]
Sorry. I tried do this. 
but I do not have permission.
![image](https://user-images.githubusercontent.com/15966265/34819455-c00d0982-f6f8-11e7-98c3-c4027663a9c8.png)
