### ISSUE TITLE
Xml.prettyPrint fails with recent xalan versions

### ISSUE THREAD

**Issue by darkmuse** [tomakehurst/wiremock#849]
Can the dependencies of Wiremock be updated to run with later versions of xalan library (2.7.2)?

```
java.lang.IllegalArgumentException: Not supported: indent-number
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
	at com.github.tomakehurst.wiremock.common.Xml.prettyPrint(Xml.java:43)
	at com.github.tomakehurst.wiremock.matching.EqualToXmlPattern.getExpected(EqualToXmlPattern.java:88)
```

**Comment by tomakehurst** [comment]
I can't see any reason why not. Feel like creating a PR?

**Comment by darkmuse** [comment]
The only reason I could think not to is if there are incompatible versions of TransformerFactoryImpl out there. And I would guess there is because XML processing in Java seems like quite a minefield.

**Comment by tomakehurst** [comment]
Having refreshed my memory of this, there's no explicit Xalan dependency in the dependency tree, it's just using the JVM core library stuff.

I take it you're seeing this error in a project that does explicitly import Xalan?

**Comment by tomakehurst** [comment]
It's also odd that the Xalan version doesn't support that attribute. Suggests the Xalan imported by Serenity is older than than the JVM version.
