### ISSUE TITLE
Allow response bodies in HTTP 401 responses

### ISSUE THREAD

**Issue by avanderveen** [tomakehurst/wiremock#852]
Currently, specifying a body for a stubbed HTTP 401 response is [not allowed](https://github.com/tomakehurst/wiremock/blob/a6240e3685925a0630788baa3db04536e84dc294/src/test/resources/test-requests/401-example.json). However, the [HTTP spec](https://tools.ietf.org/html/rfc7235#section-3.1) does not explicitly forbid HTTP 401 responses from specifying a body.

Could you update WireMock to allow HTTP 401 response bodies (or to add a configuration override)?

I can submit a PR, but I'm not sure where the restriction is enforced (and I can't seem to find it).

**Comment by tomakehurst** [comment]
I think you've misunderstood the example you've linked to. Bodies are permitted, and that example demonstrates this. I just happen to have chosen the text "Not allowed!".

**Comment by avanderveen** [comment]
Sorry about the misunderstanding!

I'm using Apache HTTP client in my tests, which doesn't do very well with chunked transfer encoding by default (if there's no Content-Length header, then it doesn't process the response body). So, when Jetty responded without the Content-Length header, it appeared as if the response body was missing.

My mistake. I've since updated my HTTP client configuration, and thinks are working again.

Thanks for your time, and for the quick response!
