### ISSUE TITLE
com.github.tomakehurst.wiremock.client.VerificationException: Expected status 2xx for https://mockedservice.com:443/__admin/mappings but was 503

### ISSUE THREAD

**Issue by JunyingGaoNancy** [tomakehurst/wiremock#856]
com.github.tomakehurst.wiremock.client.VerificationException: Expected status 2xx for https://mocked.comService.com:443/__admin/mappings but was 503

com.github.tomakehurst.wiremock.client.VerificationException: Expected status 2xx for https://mocked.comService.com:443/__admin/reset but was 503

The above error is thrown from time to time, but sometimes it's ok

**Comment by tomakehurst** [comment]
Please post questions on the mailing list as per the README.
