### ISSUE TITLE
the response with Chinese is garbled

### ISSUE THREAD

**Issue by HelloXiaoHe** [tomakehurst/wiremock#859]
Hi,could you help me,I meet some trouble.
the json like this
{
    "request": {
        "url": "/api/templated"
    },
    "response": {
        "body": "中文"
    }
}

Running as a Standalone Process 
java -Dfile.encoding=UTF-8 -jar wiremock-standalone-2.14.0.jar -global-response-templating -verbose

![default](https://user-images.githubusercontent.com/23098688/35312264-9229721a-00f5-11e8-984e-98e06796959a.png)

**Comment by tomakehurst** [comment]
Try adding this to the response:

```json
"headers": {
  "Content-Type": "text/plain; charset=UTF-8"
}
```

**Comment by HelloXiaoHe** [comment]
thanks! it works well.
Is it necessary to set the default charset in the code？

**Comment by tomakehurst** [comment]
Yes, because otherwise your browser will just default to your system's character set, which is usually not UTF-8.

**Comment by HelloXiaoHe** [comment]
what I expect is，don't need to set the charset in the json, but to verify the code and set the headers with the default value "Content-Type": "text/plain; charset=UTF-8",
Did I make myself clear?☺

**Comment by tomakehurst** [comment]
Not really, sorry!

**Comment by HelloXiaoHe** [comment]
It doesn't matter，i think i can solve it
