### ISSUE TITLE
Avoid to stub again a request which has been already stubbed before

### ISSUE THREAD

**Issue by quirimmo** [tomakehurst/wiremock#862]
I am new to Wiremock and I am trying to use it in order to stub my API requests/responses.

I tried to start the recording mode through the UI at the address:

`http://localhost:xxxx/__admin/recorder`

And through the CLI with the command:

`java -jar wiremock-standalone-2.13.0.jar --port 9090 --record-mappings --proxy-all="my-api-url"`

The recording mode works fine but I have two different issues depending on how I do start the recording mode.

- If **starting from the CLI,** it will not record stubs if already recorded in a previous session (which is want I want to), but it will put the body of the responses inside the __files subfolder, and create a link inside the mappings (I do want them inline in the mappings folder instead)

- If **starting from the UI**, it will record them properly inline in the mappings files, but in future sessions it will record the stubs again even if the same request has been already stubbed in a previous session

Could anyone make a bit of clarity on that please? What's the best way for achieving what I am looking for please?

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README

**Comment by quirimmo** [comment]
Hi @tomakehurst , 

I am sorry I did read about the mailing list a bit later this post, and I've already published in the Google Group as well. 
May I ask you to get you some info in order to go through the right direction please? 

Thanks a million
Best Regards
