### ISSUE TITLE
Improve wiremock response time

### ISSUE THREAD

**Issue by javiercardoso** [tomakehurst/wiremock#864]
Hi guys, does it exist some configuration to improve the mock server response time? We're having some issues in our tests because sporadic timeouts coming from wiremock. Maybe some configuration running the standalone process or with the matching strategy could help. I'm looking for it in the docs (http://wiremock.org/docs/running-standalone/) but without success.

Thanks so much!

**Comment by tomakehurst** [comment]
Please post questions on the mailing list as per the README.

In this case you'll need to post some detail about: the stubs you've created, configuration options you've started WireMock with and the volume of traffic you're pushing to it.
