### ISSUE TITLE
Intermittent issue with Wiremock and Spring Boot 2.0.0.RC1 

### ISSUE THREAD

**Issue by cyrillk** [tomakehurst/wiremock#867]
I'm not sure if it's a `spring boot` or `wiremock` issue.. But looks like there is some incompatibility. There is a new version of Spring Boot which was released just a few days ago. A few of our integration tests started to fail intermittently (it was all good with a previous version of Spring Boot 2.0.0.M7). Please, see the code below.

Suppose we have a simple spring boot application

```java
@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}
```

with a simple controller which proxies the request to somewhere else (that's what we are going to test with Wiremock actually)

```java
@RestController
public class HelloController {

    private static final ParameterizedTypeReference<String> TYPE_REF = new ParameterizedTypeReference<String>() {
    };

    private final WebClient webClient = WebClient.builder().baseUrl("http://localhost:9999").build();

    @GetMapping("/hello")
    public Mono<String> handle() {
        return webClient.get().uri("/remote").exchange().flatMap(f -> f.bodyToMono(TYPE_REF));
    }
}
```

and a set of tests

```java
import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.ok;

@RunWith(SpringRunner.class)
@SpringBootTest
public class HelloControllerTest {

    private WireMockServer wireMockServer;

    @Autowired
    private HelloController helloController;

    @Before
    public void before() {
        wireMockServer = new WireMockServer(9999);
        wireMockServer.start();
    }

    @After
    public void after() {
        if (wireMockServer.isRunning()) {
            wireMockServer.stop();
        }
    }

    @Test
    public void testThisThing() {
        final String expected = "this thing";
        wireMockServer.givenThat(get("/remote").willReturn(ok(expected)));
        StepVerifier.create(helloController.handle()).expectNext(expected).expectComplete().log().verify();
    }

    @Test
    public void testThatThing() {
        final String expected = "that thing";
        wireMockServer.givenThat(get("/remote").willReturn(ok(expected)));
        StepVerifier.create(helloController.handle()).expectNext(expected).expectComplete().log().verify();
    }
}
``` 

which always succeed when run independently. But stuck if run together.

UPDATE: demo project which has tests described above https://github.com/cyrillk/demo-spring-boot-metrics

**Comment by tomakehurst** [comment]
Is there any reason you're not using the Spring Boot WireMock integration library?

i.e. this one: http://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.1.2.RELEASE/#_spring_cloud_contract_wiremock

**Comment by cyrillk** [comment]
@tomakehurst No. I'll give it a try. But how is it different? It is doing the same, isn't it?

**Comment by tomakehurst** [comment]
The Spring Boot version manages the WireMock lifecycle differently. The problem you're describing often happens because your app is being started/stopped at the test class scope, whereas WireMock is being restarted per test case. This means that your app's HTTP connection pool contains dead connections that aren't (it seems) always pruned properly, meaning they're treated as active and cause a hang.

So to both of you, I'd strongly suggest trying the Spring team's way.

**Comment by cyrillk** [comment]
@tomakehurst I've updated the code to use `org.springframework.cloud:spring-cloud-contract-wiremock:2.0.0.M5` and it seems to be fine now. I can't reproduce it with `spring-cloud-contract-wiremock` anymore. Though, I'm surprised to learn that they might behave differently. Thank you for your help!

**Comment by cyrillk** [comment]
@matei-dragu the code below works for me with `org.springframework.cloud:spring-cloud-contract-wiremock:2.0.0.M5` dependency

```java
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.wiremock.AutoConfigureWireMock;
import org.springframework.test.context.junit4.SpringRunner;
import reactor.test.StepVerifier;

import static com.github.tomakehurst.wiremock.client.WireMock.*;

@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureWireMock(port = 9999)
public class HelloControllerTest {

    @Autowired
    private HelloController helloController;

    @Test
    public void testThisThing() {
        final String expected = "this thing";
        givenThat(get("/remote").willReturn(ok(expected)));
        StepVerifier.create(helloController.handle()).expectNext(expected).expectComplete().log().verify();
    }

    @Test
    public void testThatThing() {
        final String expected = "that thing";
        givenThat(get("/remote").willReturn(ok(expected)));
        StepVerifier.create(helloController.handle()).expectNext(expected).expectComplete().log().verify();
    }
}
```

**Comment by tomakehurst** [comment]
Good stuff. I'll close this off then.
