### ISSUE TITLE
WireMock: Not found match for second request. Return 404 error

### ISSUE THREAD

**Issue by lmdic** [tomakehurst/wiremock#868]
Wiremock 2.6.

I want to get stub response for the next request:

` Login`

So to do this I put in folder `wiremock/mappings` file

`login_mapping_response.json`
Here content of this file:

```
{
  "request": {
    "method": "POST",
    "url": "/api/login"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    }
  }
}
```
I send POST http request `/api/login`

As result I success get STUB response from WireMock. Nice.

Now I want to add second stub for request `/api/profile?token=stub_token_value`

So to do this I put in folder `wiremock/mappings `file

`profile_mapping_response.json`

Here content of this file:

```
{
  "request": {
    "method": "GET",
    "url": "/api/profile"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    }
  }
}
```
I restart wiremock and I send GET http request `/api/profile?token=stub_token_value`

As result WireMock success return response for request` /api/login`.
BUT not found match for second request `/api/profile`. And as result return HTTP status **404**.

P.S. I start WireMock like this:

`java -jar wiremock-standalone-2.6.0.jar --port 8080 --enable-browser-proxying -verbose`

Here response of WireMock:

```
2018-02-02 15:50:25.184 Request was not matched:
{
  "url" : "/api/profile?token=stub_token_value",
  "absoluteUrl" : "http://myhost:8080/api/profile?token=stub_token_value",
  "method" : "GET",
  "clientIp" : "172.27.202.1",
  "headers" : {
    "Connection" : "keep-alive",
    "User-Agent" : "okhttp/3.8.0",
    "Host" : "myhost:8080",
    "Accept-Encoding" : "gzip",
    "Content-Type" : "application/json"
  },
  "cookies" : { },
  "browserProxyRequest" : false,
  "loggedDate" : 1517579425105,
  "bodyAsBase64" : "",
  "body" : "",
  "loggedDateString" : "2018-02-02T13:50:25Z"
}
Closest match:
{
  "url" : "/api/profile",
  "method" : "GET"
}
```

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the readme.

Might also be worth upgrading to the latest version.
