### ISSUE TITLE
How to upload stubs to existed server

### ISSUE THREAD

**Issue by azadykhin** [tomakehurst/wiremock#875]
Hello, we have wiremock on existed server (someserver:18281) and it works. So, could you help me please how I can upload my stubs there?

I've tried:

WireMock wireMock = new WireMock();
		WireMock.configureFor(someserver, 18281);
		wireMock.loadMappingsFrom("src/test/resources");

But I'm getting error org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

Help, please. This is new for me so I'm kinda slow in this and can't figure out what should I do :) Thank you

**Comment by alexandermomot** [comment]
@azadykhin WireMock.configureFor()... is for a static endpoint and settings, but in your latter string you asking for instantiated wiremock client, and it knows nothing about your static endpoint and wiremock client. 

Example above should work with your code:
```
Wiremock client = new WireMock(someserver, 18281);  
client.loadMappingsFrom("src/test/resources");
```

Thereby you shouldn't use .configureFor() method at all
