### ISSUE TITLE
JSONPathMatcher does not work for Body matching

### ISSUE THREAD

**Issue by aledaccas** [tomakehurst/wiremock#879]
The JSONPathMatcher does not match a json body request. (Using the IRequestBuilder .WithBody())
This is because the RequestMessageBodyMatcher only uses the .Body property and not the .BodyAsJson property.
to get working, either Body and BodyAsJson must be filled with the body string from request.

**Comment by tomakehurst** [comment]
Is this a question about WireMock.Net?

**Comment by aledaccas** [comment]
Yes, this issue occurs in WireMock.Net.

I believe this error occurs because the class WireMock.Util.BodyParser, Method Parse checks if the request content-type is application/json, then only fills the BodyAsJson property, leaving the Body property null.
The WireMock.Matchers.Request.RequestMessageBodyMatcher class, method IsMatch, only sends the Body property (null) to the JSONPathMatcher, so the score is always 0.

Regards,

Alexandre

**Comment by tomakehurst** [comment]
WireMock.Net is nothing to do with WireMock I'm afraid, so you'll need to report the issue over on their GitHub project.
