### ISSUE TITLE
TransformerParamerters are ignored

### ISSUE THREAD

**Issue by bduisenov** [tomakehurst/wiremock#880]
Transformer parameters for `ResponseTemplateTransformer` are not applied.

for example:
```java
    @ClassRule
    public static WireMockRule wireMockRule = new WireMockRule(wireMockConfig()
        .extensions(new ResponseTemplateTransformer(true))
        .dynamicPort());
    .....
    stubFor(get(urlPathMatching("/some/path/(.*)"))
                .willReturn(aResponse()
                        .withStatus(OK.value())
                        .withHeader(CONTENT_TYPE, APPLICATION_JSON)
                        .withBodyFile("some/file.json")
                        .withTransformerParameter("variable", "123456")));
```
```json
{"test": "{{variable}}"}
```

Will not replace `variable` in `file.json`

**Comment by Apolayo27** [comment]
How implement this?

I have the same problem

**Comment by califlower** [comment]
Same issue, transformer parameters are not applied

**Comment by Apolayo27** [comment]
> Same issue, transformer parameters are not applied

fix the problem by adding in json   "nameparameter": "{{parameters.nameparameter}}" and in the response add  .withTransformerParameter("nameparameter", "
value you want")

**Comment by califlower** [comment]
@Apolayo27 you're a godsend, thank you
