### ISSUE TITLE
What is the best way to configuring multiple proxy urls for multiple services in wiremock?

### ISSUE THREAD

**Issue by achyutha526** [tomakehurst/wiremock#884]
I am using wiremock for service virtualization. I am using proxying functionality to forward all the unmatched requests to the live url. The problem is I am virtualizing 5 different services, how can I provide proxy urls for each service to forward it to corresponding live url in case of mismatch?As of now I am using 5 different json files with proxyBaseUrl and high priority and setting them by default after starting the service. 

Is there any better way to configure multiple proxy urls for multiple services?

{ "request": { "method": "POST", "urlPattern": "/a/.*" }, "response": { "proxyBaseUrl" : "https://srvc1.com" }, "priority": 10 }
{ "request": { "method": "POST", "urlPattern": "/b/.*" }, "response": { "proxyBaseUrl" : "https://srvc2.com" }, "priority": 10 }
.
.
.
{ "request": { "method": "POST", "urlPattern": "/e/.*" }, "response": { "proxyBaseUrl" : "https://srvc5.com" }, "priority": 10 }

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.
