### ISSUE TITLE
Refuses to match POST request with a query string

### ISSUE THREAD

**Issue by robfletcher** [tomakehurst/wiremock#889]
If I do 
```
    stubFor(
      post("/whatever")
        .withQueryParam("aParam", equalTo("covfefe"))
        …
```

The stub refuses to match any request I send it. It seems to translate the query string expectation into expecting form encoded body parameters instead.

For example, I'll get a failure like this:
```
    com.github.tomakehurst.wiremock.client.VerificationException: A request was unmatched by any stub mapping. Closest stub mapping was:  expected:<
    POST
    /ops

    aParam: covfefe
    > but was:<
    POST
    /ops?aParam=covfefe

    aParam: covfefe
    >
```

To work around this I have to include the query string parameter(s) with the expected URL.

**Comment by tomakehurst** [comment]
This is because the `post(...)` override that takes a string matches the path and query (equivalent to the `urlEqualTo` operator). If you switch to `post(urlPathEqualTo("/whatever"))` this should work OK.

I probably need to add a health warning in the diff report about this.

**Comment by robfletcher** [comment]
Cool. That works well.
