### ISSUE TITLE
Ability to change / reread root folder for "mappings" & "__files" via API

### ISSUE THREAD

**Issue by penzeliz** [tomakehurst/wiremock#892]
My test setup is of the following: I have multiple (currently about 10, but increasing) message sets (some of them containing hundreds of messages/mappings).
Currently I'm spinning up a standalone Wiremock process before each component test with the proper `--root-dir` settings. However it would be quite useful for me to just simply repoint the `--root-dir` via the API. I know I could use POST `/__admin/mappings`, but in some cases it would mean pushing lot of mappings. Also I would like to keep mappings/files as separate artifact folders. Oh, and the tests themselves are written in .NET...

Please let me know if there is an already existing alternative path to achieve what I wanted here :)

I'm also happy to contribute if I can get some pointers where to start looking in the project

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README
