### ISSUE TITLE
convert pojo (list of object) to json in java using jackson

### ISSUE THREAD

**Issue by nagarjuna1304** [tomakehurst/wiremock#894]
Hi Team,

I'm facing while converting simple JSON to POJO object
Below is my snippet

{
  "Products": [
    {
      "id": 23001,
      "type": "SHIRT",
      "description": "Mens Wear Dresses",
      "price": 850,
      "brand": "PETER_ENGLAND"
    }
  ]
}

Products.class
----------------
public class Products {
	
	private int id;
	private String type;
	private String description;
	private Double price;
	private String brand;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Double getPrice() {
		return price;
	}
	public void setPrice(Double price) {
		this.price = price;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}

}

Product.class
--------------
import java.util.List;

public class Product {
	
	private List<Products> products = null;

	public List<Products> getProducts() {
	return products;
	}

	public void setProducts(List<Products> products) {
	this.products = products;
	}

}

JsonJacksonObjectMappingDemo.class
------------------------------------------

import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

@JsonIgnoreProperties(ignoreUnknown = true)
public class JsonJacksonObjectMappingDemo{

	public static void main(String[] args) throws JsonParseException,
			JsonMappingException, IOException {
		// TODO Auto-generated method stub
		Jackson2Example obj = new Jackson2Example();
		obj.run();
	}

	private void run() throws JsonParseException, JsonMappingException,
			IOException {

		Product pro = null;

		try {
			ObjectMapper mapper = new ObjectMapper().configure(
					DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

			// Convert JSON string to Object
			String jsonInString = "{\"Products\": [{\"id\": 23001,\"type\": \"SHIRT\",\"description\": \"Mens Wear Dresses\",\"price\": 850,\"brand\": \"PETER_ENGLAND\"}]}";
			pro = mapper.readValue(jsonInString, Product.class);
			System.out.println(pro);

			// Convert Object to JSON

			String prodToString = mapper.writerWithDefaultPrettyPrinter()
					.writeValueAsString(pro);
			System.out.println("Object to Json --> " + prodToString);

		} catch (JsonGenerationException e) {
			e.printStackTrace();
		} catch (JsonMappingException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

	}

}

Im getting below as **output**:
com.ObjectToJson.Product@b97c004
Object to Json --> {
  "products" : null
}

I could not able to convert JSON to/from Java Objects using JACKSON API.

Please any one help me out on this.

**Comment by tomakehurst** [comment]
I don't think this has anything to do with WireMock. Suggest posting on stackoverflow.
