### ISSUE TITLE
how to handle special character "\"  in body response

### ISSUE THREAD

**Issue by bearxc** [tomakehurst/wiremock#901]
I have a special  case and want the exactly   following body response 
"Response":"\/Date(1520598541000)\/"

so far , I do not know how to do with   "\" .  

I tried set as    "Response":"\\/Date(1520598541000)\\/" 
                       "Response":"\\\\/Date(1520598541000)\\\\/" 
                        "Response":"\b/Date(1520598541000)\b/" 

none of them works .

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the issue template and readme. Please also post full code samples output.
