### ISSUE TITLE
bodyFileName file upload endpoint

### ISSUE THREAD

**Issue by stefanoj3** [tomakehurst/wiremock#903]
- wiremock version: 2.8.0
- configuration dove via __admin api
- configuration used:
```
{
  "id" : "my_id",
  "name" : "my_name",
  "request" : {
    "url" : "/some/url",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "bodyFileName": "a_file.json",
    "headers" : {
      "Content-Type" : "application/json"
    }
  },
  "uuid" : "bb38abae-f611-4561-9c02-af9d33badd33",
  "persistent" : true
}
```

This is something in between a bug and a feature request (or maybe just documentation request).

The api allows me to specify a `bodyFileName` but then I have no way to upload such file via api (no documented one at least, unless I'm missing it).

Is there any endpoint to do that? if not would be nice to either add it or reject the api call when this property is there, since seems to be supported but it's not apparently.

**Comment by tomakehurst** [comment]
Not documented yet, shamefully, but this has been there since December:
https://github.com/tomakehurst/wiremock/blob/9991b850abcfbb0d2066166aefacf651d6d9fa3f/src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java#L605

You'll need to upgrade to the latest version to get it.

**Comment by stefanoj3** [comment]
Thanks, if you point me where the documentations lives I will try and find some time to create a PR and document it :)

**Comment by tomakehurst** [comment]
It's all in Markdown docs under https://github.com/tomakehurst/wiremock/tree/master/docs-v2 if you fancy writing it up.

**Comment by stefanoj3** [comment]
I'll take a look, thanks.

**Comment by douglasknudsen** [comment]
This is rather cool API, but does not appear to be available using mocklab.io?  GET https://mydomain.mocklab.io/__admin/files  fires a HTTP 500   Maybe this API is just not available?    Locally POST is not working either 2.18 in use here

**Comment by tomakehurst** [comment]
Yeah, not implemented in MockLab yet, but on the roadmap.

Can you elaborate the problem you're seeing using this with WireMock?

**Comment by douglasknudsen** [comment]
Thanks Tom.  I had a thought to use one mapping file to point to an external JSON response file where I can just update the JSON response file when needed.  In fact I was thinking of a 1-MANY use case here where bodyFileName could use a queryparam from the request  to setup one mapping "stub" file to handle 5000 some requests I am setting up.  In the end I can just create 5000 mappings, just makes that 'stubs' view in mocklab kind of frown at me :)

**Comment by tomakehurst** [comment]
Closing, as this is now documented in 5e3c1ed741996bed006ab16734bbe780f9aaccad
