### ISSUE TITLE
Wrong content-length during record after modify body by ResponseTransformer

### ISSUE THREAD

**Issue by piotrbo** [tomakehurst/wiremock#907]
Hello,
I need to replace an absolute url in response with wiremock in proxy mode.
During record after modify body by ResponseTransformer I'm getting wrong (not updated) Content-Length .
When I try to update Content-Length in the ResponseTransformer, a final result is headers are missing e.g. Set-Cookie.
steps to reproduce:

1) wiremock-standalone-2.14.0.jar

2) prepare a HTTP server with response:
headers
  Set-Cookie: IReallyNeedThisCookie
body
  test for headers issue

or use http://www.mocky.io/v2/5ab204022e000081004cbf2f

3) Prepare wiremock ResponseTransformer and add it as --extension:
`import com.github.tomakehurst.wiremock.common.FileSource;
import com.github.tomakehurst.wiremock.extension.Parameters;
import com.github.tomakehurst.wiremock.http.*;

import java.util.regex.Pattern;

public class ReplaceResponseTransformer extends SuperResponseTransformer {
    static Pattern mockyPattern = Pattern.compile("for headers");

    @Override
    public Response transform(Request request, Response response, FileSource files, Parameters parameters) {

        String body = response.getBodyAsString();

        if (body != null && mockyPattern.matcher(body).find()) {
            body = body.replaceAll(mockyPattern.pattern(), "for HTTP HEADERS");

            return Response.Builder.like(response).body(body)
                    .headers(updateContentLength(response.getHeaders(), body.length()))
                    .build();
        }
        return response;
    }

    private HttpHeaders updateContentLength(HttpHeaders headers, int bodyLength) {
        HttpHeaders newHttpHeaders = HttpHeaders.noHeaders();

        for (HttpHeader header : headers.all()) {

            if (header.key().equalsIgnoreCase("Content-Length")) {
                newHttpHeaders.plus(new HttpHeader(header.key(), bodyLength + ""));
            } else {
                newHttpHeaders.plus(header);
            }
        }
        return newHttpHeaders;
    }

    @Override
    public boolean applyGlobally() {
        return true;
    }
}`

4) /usr/bin/java -cp my-extension-0.0.1.jar:wiremock-standalone-2.14.0.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --verbose --match-headers Set-Cookie --extensions my.extensions.ReplaceResponseTransformer --https-port 6443 --https-keystore wiremock.keystore --enable-browser-proxying

5) wireMock.startStubRecording("http://www.mocky.io/v2/5ab204022e000081004cbf2f");

6) call wiremock: curl 'https://localhost:6443/' -v -k

> GET / HTTP/1.1
> Host: localhost:6443
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Vary: Accept-Encoding, User-Agent
< Transfer-Encoding: chunked
< Server: Jetty(9.2.z-SNAPSHOT)
<
* Connection #0 to host localhost left intact
test for HTTP HEADERS issue

(response body is as expected but there is no Set-Cookie header)

7) if you remove updateContentLength from ReplaceResponseTransformer
the returned Content-Length is shorter then the response with applied transformation so the content is trimmed

**Comment by tomakehurst** [comment]
Closing this due to its age and the fact that the recorder has changed quite significantly in the meantime. Please reopen if still an issue.
