### ISSUE TITLE
Feature request, consider using more logger names

### ISSUE THREAD

**Issue by jonenst** [tomakehurst/wiremock#912]
Hi, I'm using wiremock 2.15.0 to write tests executed with maven. I would like to log the requests and responses handled by the wiremock stubs, without logging the stub configuration or the count query.
I would like to configure this using the standard facilities of the logging system I chose (log4j but could be something else). So it would be nice if different types of logs had different names so that users can selectively turn off some of them.

Here's what I would ideally like to see when I execute a test that does a single post to a stub:
```
INFO  WireMock - Request received:
127.0.0.1 - POST /foobarbaz
Host: [localhost:8089]
Content-Type: [application/json; charset=UTF-8]
{ "foobarbaz" : "foo" }

Response:
HTTP/1.1 200
Content-Type: [application/json]

{ "ok": true}
```

Here's what I see now
```
INFO  WireMock  - Received request to /mappings with body {
  "id" : "bd64702b-0927-46ca-bb37-71e1d906ab7a",
  "request" : {
    "url" : "/foobarbaz",
    "method" : "POST"
  },
  "response" : {
    "status" : 200,
    "body" : "{ \"ok\": true}",
    "headers" : {
      "Content-Type" : "application/json"
    }
  },
  "uuid" : "bd64702b-0927-46ca-bb37-71e1d906ab7a"
}
INFO  WireMock - Request received:
127.0.0.1 - POST /foobarbaz
Host: [localhost:8089]
Content-Type: [application/json; charset=UTF-8]
{ "foobarbaz" : "foo" }

Matched response definition:
{
  "status" : 200,
  "body" : "{ \"ok\": true}",
  "headers" : {
    "Content-Type" : "application/json"
  }
}

Response:
HTTP/1.1 200
Content-Type: [application/json]

{ "ok": true}

INFO  WireMock :34 - Received request to /requests/count with body {
  "urlPattern" : "/foobarbaz/",
  "method" : "POST",
  "headers" : {
    "Content-Type" : {
      "matches" : "application/json.*"
    }
  },
  "bodyPatterns" : [ {
    "matches" : ".*"
  } ]
}
```
Cheers,
Jon

**Comment by PeterPerhac** [comment]
I am also seeing "Received request to /mappings with body" in the logged output from wiremock. I'd rather see the actual mapping that handled the request. so, it should say "Received request to /foobarbaz with body"....

**Comment by tomakehurst** [comment]
Closing individual logging issues in favour of (referenced) logging redesign issue.
