### ISSUE TITLE
Scenarios - Complex Scenario Matching Method - Feature Request

### ISSUE THREAD

**Issue by bryantabaird** [tomakehurst/wiremock#913]
Hello,

I'd mark this as a Feature Request, but GitHub didn't mark my PR #893, so I can't do it myself :) 

I'm looking at a more complex scenario that I'd like to implement. Take your grocery list example (http://wiremock.org/docs/stateful-behaviour)

My grocery list is initially empty (S). I have 3 items: A, B, and C. I want to be able to add/remove all items in any order.

Currently, to achieve this, I will have to map all possible combinations:

S -> A
A -> AB
A -> AC
AB -> ABC
AC -> ABC
ABC -> AB
ABC -> AC
AB -> A
AC -> A
A -> S

S -> B
B -> AB
B -> BC
BC -> ABC
ABC -> BC
AB -> B
BC -> B
B -> S

S -> C
C -> BC
C -> AC
BC -> C
AC -> C
C -> S

(I hope I got them all, but I'm sure you get the idea)

I know there is a `whenScenarioStateIs()` method for checking the current state, but I'd like to suggest something like `whenScenarioStateMatches(regex)` method, or `whenScenarioStateIsIn(possibleStates)`, or something similar. This gives more flexibility on the current state logic. 

Is there anything like this currently available that I am missing?

Then, it could be something like:

(A, B, C) -> S

(S, AB, AC) -> A
(S, AB, BC) -> B
(S, AC, BC) -> C

(A, B, ABC) -> AB
(A, C, ABC) -> AC
(B, C, ABC) -> BC

(AB, BC, AC) -> ABC

In your opinion, would this even be possible?

Thanks,
Bryant

**Comment by tomakehurst** [comment]
Closing due to age and inactivity
