### ISSUE TITLE
Jetty Bug throwing javax.servlet.ServletException on Content-Type != multipart/form-data

### ISSUE THREAD

**Issue by mklose** [tomakehurst/wiremock#920]
multipart post with content type other than "multipart/form-data" for instance "multipart/mixed" fails
```
javax.servlet.ServletException: Content-Type != multipart/form-data
	at org.eclipse.jetty.server.Request.getParts(Request.java:2098) ~[jetty-server-9.2.24.v20180105.jar:9.2.24.v20180105]
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.safelyGetRequestParts(WireMockHttpServletRequestAdapter.java:280) ~[wiremock-2.17.0.jar:?]
```

**Comment by tomakehurst** [comment]
Yeah, unfortunately Jetty doesn't seem to support anything other than `multipart/form-data`, judging by the code I've looked at.

I agree it'd be nice to support other modes, but it'd mean writing our own parser, which probably isn't a trivial undertaking.

I'll mark this as a feature request.

**Comment by tekener** [comment]
@tomakehurst it is possible to fix it by skipping the processing in case of an other multipart sub type like "form-data" to avoid the exception.

**Comment by tekener** [comment]
Yes ;-)
