### ISSUE TITLE
use-gzip doesn't work

### ISSUE THREAD

**Issue by roland-kozma** [tomakehurst/wiremock#929]
Hi,

I configured WireMock to proxy requests, but when a request that uses gzip (with header:  use-gzip: [true]) reach to WireMock, it fails with:
    java.nio.charset.MalformedInputException: Input length = 1...

After I stopped using gzip, everything worked fine.
I attached the logs for both cases failure and success.

[failed_request_with_gzip.txt](https://github.com/tomakehurst/wiremock/files/1942051/failed_request_with_gzip.txt)
[successful_request_without_gzip.txt](https://github.com/tomakehurst/wiremock/files/1942052/successful_request_without_gzip.txt)

Regards,
Roland

**Comment by tomakehurst** [comment]
Have you tried it without traffic logging turned on?

**Comment by tomakehurst** [comment]
Can you share how you're making the request so I can try to replicate?

Also, are you certain it's not the API you're proxying to that's returning the 500? Since there's no stack trace in the 2nd example you've given, that seems like it might be the case.

**Comment by roland-kozma** [comment]
Hi Tom,

I created a Wireshark capture. 
You can see that the request is coming from my android phone (192.168.0.69).
My laptop (192.168.0.91), where WireMock is running receives the request and send back a 500 Server Error to the phone. 
I'm pretty sure that the failure is caused by the
    java.nio.charset.MalformedInputException: Input length = 1...
WireMock returns 500 because of this, and doesn't even get to try to call the proxyied api.

[gzip_failure.zip](https://github.com/tomakehurst/wiremock/files/1945965/gzip_failure.zip)

**Comment by roland-kozma** [comment]
You may be right, and the MalformedInputException may not be related to this. 
Then the MalformedInputException should be fixed as a separate issue.

I'll try to create an app for you this days, to reproduce the failure, because it seems that postman doesn't support to compress the request body: https://github.com/postmanlabs/postman-app-support/issues/4079

**Comment by roland-kozma** [comment]
Any update on this? Thanks!

**Comment by tomakehurst** [comment]
I've created a test case around this (to the best of my ability). I can at least confirm that the MalformedInputException is a red herring - the exception is being caught and logged, so doesn't bubble up and cause the 500 response.

Are you still experiencing this issue?
