### ISSUE TITLE
Helper 'now' has been replaced by 'now'

### ISSUE THREAD

**Issue by marcingrzejszczak** [tomakehurst/wiremock#935]
## Version:

WireMock 2.17.0

## How it's executed:

In Spring Cloud Contract from code.

## How to replicate:

just run `com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformerTest#queryParameters`

you'll see that 

`com.github.jknack.handlebars.helper.DefaultHelperRegistry#registerHelper` will call the `logger.warn` due to the fact that `com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer#ResponseTemplateTransformer(boolean, com.github.jknack.handlebars.Handlebars, java.util.Map<java.lang.String,com.github.jknack.handlebars.Helper>)` executes a helper under the same name from 2 classes `com.github.jknack.handlebars.helper.StringHelpers#now` and `com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WiremockHelpers#now`

in the logs you'll see

```
2018-05-08 18:11:49 WARN  HelperRegistry:106 - Helper 'now' has been replaced by 'now'
```

**Comment by tomakehurst** [comment]
Oops. I'll sort that out in the next release.

**Comment by ecolinet** [comment]
I think that this issue must be closed isn't it ?

**Comment by tomakehurst** [comment]
Yes, it should be. I'm not very good at GH issue housekeeping....
