### ISSUE TITLE
[FR] Provide method for stubbing GET and HEAD requests at the same time

### ISSUE THREAD

**Issue by gatesn** [tomakehurst/wiremock#937]
Most HTTP servers [1, 2] provide an implicit implementation of HEAD if the server handles the equivalent GET request. 

It would be nice to have WireMock provide a `getOrHead` MappingBuilder, or for an option to set it's default behaviour to translate HEAD into GET request. However I think being explicit is better when testing.

[1] Jersey: https://jersey.github.io/documentation/latest/jaxrs-resources.html#d0e2129
[2] Python's SimpleHttpServer: https://github.com/enthought/Python-2.7.3/blob/master/Lib/SimpleHTTPServer.py#L56

**Comment by tomakehurst** [comment]
I think a bit of Java DSL to do this would be OK. I'm less keen on the idea of adding it explicitly to the JSON API, as this might introduce more complexity than it would justify.

Are you thinking of raising a PR?

**Comment by tomakehurst** [comment]
Closing due to age and inactivity
