### ISSUE TITLE
maven tomcat7 Caused by: java.lang.ClassCastException: org.springframework.web.SpringServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer

### ISSUE THREAD

**Issue by Frantch** [tomakehurst/wiremock#939]
Hello,

I'm trying to use the latest WireMock standalone with maven + maven-tomcat7 but upon tomcat starts this is the error I get

> java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
> 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1123)
> 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:800)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
> 	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.base/java.lang.Thread.run(Thread.java:844)
> Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
> 	... 7 more
> Caused by: java.lang.ClassCastException: org.springframework.web.SpringServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
> 	at org.apache.catalina.startup.ContextConfig.getServletContainerInitializer(ContextConfig.java:1670)
> 	at org.apache.catalina.startup.ContextConfig.getServletContainerInitializers(ContextConfig.java:1652)
> 	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1562)
> 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1270)
> 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
> 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:376)
> 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
> 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	... 7 more

- Version 2.1.7 (standalone)
- maven tomcat plugin 2.2
- javax.servlet-api 4.0.1
- Spring-web 5.0.6.RELEASE

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README. Also suggest you include some more detail, in particular your setup code + config.
