### ISSUE TITLE
java.lang.NoSuchMethodError when verified failed when checking for queryParams

### ISSUE THREAD

**Issue by Frantch** [tomakehurst/wiremock#940]
Hello,

I get this error when verifying using query params;

> java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.from([Ljava/lang/Object;)Lcom/google/common/collect/FluentIterable

```
 verify(getRequestedFor(urlPathEqualTo("/v2/test/"))
          .withQueryParam("event", WireMock.containing("hello")));
```

WireMock 2.1.7

**Comment by liry** [comment]
FYI: use wiremock-jre8 if you are on Java8+. It contains newer guava version.
