### ISSUE TITLE
How to record Apache Chemistry opencmis ATOMpub url

### ISSUE THREAD

**Issue by WireMockBeginner** [tomakehurst/wiremock#947]
Hello,

I am trying to record a response from Apache Chemistry opencmis ATOMpub url.
e.g. http://<host>:port/fncmis/resource/service

The method does following:-
1) Creates a connection to the cmis
2) Builds a query - with dynamic query parameter
e.g. String statement = "Select" + this.param1 + "," + this.param2 from table1 where ....

3) Executes the query passing the repository ID 
4) Gets the result (documents) and some logic in for loop is applied

**The trouble is that - when I start recording as below:-**
public WireMockRule wireMockRule = new WireMockRule(9988);
WireMock.startRecording(http://<host>:port)  //This is  the cmis server url

**Then I make call to my method which does the four steps as mentioned above**

WireMock.stopRecording();

**Analyzing the Recordings:-**
In recordings it does not contain any document objects. It just has session object in the recording and no other data.

I observed that WireMock, does not record internal requests - it just records the first request i.e. for the first time when the session is created.
Since, once the session is created - the code has logic to add dymanic query params and fetch the objects (documents. So here there are multiple calls. Frist for session creation and second for the query.

Do I need to proxy on the proxy url due to multiple calls, and for doing it I need a guidance to resolve this functionality.

Any help on this would be much appreciated. Thanks in advance.

**Comment by tomakehurst** [comment]
Not a bug or feature request. Suggest re-posting to the mailing list if still a problem.
