### ISSUE TITLE
Feature request: Support handlebars templates in body file paths

### ISSUE THREAD

**Issue by martin-sladecek-o** [tomakehurst/wiremock#950]
Motivation: map requests to pre-defined responses, stored in files.
E.g.
stubFor(get(urlPathMatching("/resource/\\w*")).willReturn(
                ok().withTransformers(ResponseTemplateTransformer.NAME)
                        .withBodyFile("response/{{request.requestLine.path.[2]}}.json")));

**Comment by dcunited001** [comment]
Thanks! i need this. is this in a build of the standalone jar?

**Comment by tomakehurst** [comment]
Not yet, but will be soon. Couple of other things to add before I push a release.

**Comment by eric1988** [comment]
@tomakehurst, do you have an idea when this feature will be released?

**Comment by tomakehurst** [comment]
Fixed in 8a25659f2f854531b673db73937d60785609d5c6
