### ISSUE TITLE
com.github.tomakehurst.wiremock.common.JsonException:

### ISSUE THREAD

**Issue by OllyAndJo** [tomakehurst/wiremock#959]
com.github.tomakehurst.wiremock.common.JsonException: {
  "errors" : [ {
    "code" : 10,
    "source" : {
      "pointer" : "/"
    },
    "title" : "Error parsing JSON",
    "detail" : "No content to map due to end-of-input"
  } ]
}

**Comment by tomakehurst** [comment]
Questions on the mailing list please

**Comment by mongoDynamo** [comment]
@OllyAndJo I had a similar error : 
`com.github.tomakehurst.wiremock.common.JsonException: {
  "errors" : [ {
    "code" : 10,
    "source" : { },
    "title" : "Error parsing JSON",
    "detail" : "Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: (String)\"<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>nginx/1.17.4</center>\r\n</body>\r\n</html>\r\n\"; line: 1, column: 2]"
  } ]
}`

The issue for me is that I had a local docker image using the same port as what I was trying to use with wire mock. After I killed the docker image, the wiremock worked again for me locally.

**Comment by gempain** [comment]
Wasted about 30 minutes on this too, and was also caused by another app using this port. The error is not clear at all. Wiremock should handle this case properly.

**Comment by LeonorLunatech** [comment]
@OllyAndJo where you able to fix your issue? I'm having the exact same error

**Comment by justassub** [comment]
> Wasted about 30 minutes on this too, and was also caused by another app using this port. The error is not clear at all. Wiremock should handle this case properly.


Thanks! Port was taken already.
