### ISSUE TITLE
Swagger 'Try it out' doesn't work with HTTPS

### ISSUE THREAD

**Issue by vzhura** [tomakehurst/wiremock#965]
### Configuration
-  WireMock version 2.18.0
- Standalone process started with `java -jar wiremock-standalone-2.18.0.jar --port 9999 --https-port 9998`

### Steps to reproduce

1. Navigate to https://localhost:9998/__admin/swagger-ui
2. Click 'Try it now' for any API (f.e. DELETE mappings)
**Expected result:** API is executed with HTTPS and produces expected result
**Actual result:** API is executed with HTTP and error "no response from server" is produced.
See screen attached
<img width="969" alt="screen shot 2018-07-10 at 11 21 56" src="https://user-images.githubusercontent.com/41082285/42529558-a78f40a0-8433-11e8-9a60-9f0b3b8942a8.png">

**Comment by tomakehurst** [comment]
Looks like a bug in the Swagger UI. If the address at the top is HTTPS then the URLs it's calling should also be, but it's reverting to HTTP, but keeping the port number the same, meaning it's trying to connect to an HTTPS service using HTTP.

**Comment by Ranbato** [comment]
I have both HTTPS and HTTP working, I had to change wiremock-admin-api.json to include both schemes.
`
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "securityDefinitions": {},
  "swagger": "2.0"
`
It looks to me like this is generated during the build from the raml?

**Comment by tomakehurst** [comment]
Feel like raising a PR?

**Comment by Ranbato** [comment]
https://github.com/tomakehurst/wiremock/pull/981

**Comment by tomakehurst** [comment]
Thanks!

**Comment by luigicelano** [comment]
so what is the solution for this
