### ISSUE TITLE
API __admin/reset causes error 400 during proxying and recording

### ISSUE THREAD

**Issue by lucap84** [tomakehurst/wiremock#967]
## Bug reports
In order to replicate the issue:
- Use Wiremock 2.18.0
- Start Wiremock in standalone mode with --proxy-all and --record-mappings

After a call to /__admin/reset I noticed that:
- The API used is not documented in wiremock.org/docs/api/ (#954)
- A call to wiremock instances that doesn't match any configured stub return HTTP 400 error instead of proxy and record to the configured (--proxy-all) external service

**Comment by tomakehurst** [comment]
Thanks for the report. That approach to recording is deprecated now, so I'm unlikely to devote any time to fix it however.

Have you tried working with the new record feature?

**Comment by lucap84** [comment]
Thanks for reply.
No, I haven't tried yet the new recording feature.
I'll try it, anyway this is not a blocking issue for the moment.

**Comment by tomakehurst** [comment]
Won't fix, as this is for the legacy recorder.
