### ISSUE TITLE
On JDK11 WireMock does not force 'CONNECTION_RESET'

### ISSUE THREAD

**Issue by eolivelli** [tomakehurst/wiremock#970]
## Bug reports

I am using version 2.18.0

This stubbing code on JDK 8,9,10 produces a "Connection reset" error

@Rule
public WireMockRule wireMockRule = new WireMockRule(0, 0);

stubFor(post(urlEqualTo("/index_connection_reset.html"))
                .withHeader("Content-Type", new EqualToPattern("application/json"))
                .willReturn(aResponse()
                        .withFault(Fault.CONNECTION_RESET_BY_PEER)));

On OpenJDK11 build 23 the request ends with "Connection timed out"

java -version
```
openjdk 11-ea 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11-ea+23)
OpenJDK 64-Bit Server VM 18.9 (build 11-ea+23, mixed mode)

```

**Comment by tomakehurst** [comment]
Thanks for reporting this. Which platform are you running on?

**Comment by eolivelli** [comment]
Oh, I missed that part: Fedora 26

**Comment by eolivelli** [comment]
I see in JDK11 a lot of things changed in network stack implementations

**Comment by tomakehurst** [comment]
I also doesn't work on some Windows versions as far as I can tell. I probably need to put a health warning on there next time I edit the docs.

**Comment by eolivelli** [comment]
@tomakehurst this may be a JDK bug, JDK11 is going to be released soon, do you this it is a wiremock problem or should we report it back to OpenJDK community ?

**Comment by tomakehurst** [comment]
Hmmm...hard to say without a bit more work. I suspect the OpenJDK group would need quite a lot of detail e.g. tcpdump logs of working and non-working runs.

**Comment by vbauer** [comment]
Hello, I have the same problem with OpenJDK 11 and wiremock 2.19.0

```
➜ workspace git:(master) ✗ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)
```

**Comment by f9i1n1n1** [comment]
Same here since JDK 11. Got around it by applying a read timeout (>0) to the underlying URLConnection that targets the faulty Wiremock resource stub. For example by adding urlConnection.setReadTimeout(2500) to my user code, all my tests went green.

**Comment by eolivelli** [comment]
@f9i1n1n1 the problem with your approach is that you are no more seeing a "connection reset", isn't is ?

In my case I want to simulate a "connection reset" and now it is no more possible, it ends with "Read timeout" with is a very different case for some applications (in my case I have an HTTP Proxy)

**Comment by f9i1n1n1** [comment]
@eolivelli You're absolutely right but the solution works for my current interests saying there is kinda network issue preventing the business task to complete. If I wrote a technical library that feedback would be way too inaccurate.

**Comment by modax** [comment]
The following should help to understand what is going on in JDK 11:

https://bugs.openjdk.java.net/browse/JDK-8203059
http://mail.openjdk.java.net/pipermail/nio-dev/2018-May/005101.html
https://github.com/unofficial-openjdk/openjdk/commit/a0d2c635a64645d1709e4f69937cb2c36b64e420

While the first point in the mail thread appears to be fixed in recent JDK 11 releases, Wiremock does not do the 2nd point (i.e. flush "selectors") as close() is queued now. Apparently while Jetty selector is registered and waiting, RST never gets actually sent (in non-blocking mode) after Wiremock forces its socket close (confirmed this with wireshark on Linux). See the JDK test in openjdk commit above how the test triggers connection reset now in non-blocking mode. But this might need getting into Jetty internals a bit :/

**Comment by tomakehurst** [comment]
@modax - thanks for digging all that up, that's really helpful. I will try to find an adequate chunk of time soon to replicate this properly and see what can be done.

**Comment by olatheander** [comment]
FYI, while being able to repeat this problem with the test example from #1009 I've also noticed that the problem doesn't occur with the `wiremock-jre8`build, i.e. just switching to
```
<dependency>
    <groupId>com.github.tomakehurst</groupId>
    <artifactId>wiremock-jre8</artifactId>
    <version>2.21.0</version>
    <scope>test</scope>
</dependency>
```
and all other things alike the test now pass thus this might be a non-issue since the JRE8 build is recommended for later Java versions.

**Comment by eolivelli** [comment]
I will try.
Do you have an explanation?

**Comment by olatheander** [comment]
@eolivelli no explanation that is thoroughly researched but I do think it's related to more up-to-date dependencies in the JRE8 build.

**Comment by tomakehurst** [comment]
Strange, it was still failing when I tried this.

Which JDK11 build were you using?

**Comment by eolivelli** [comment]
Currently I am using 11.0.2 (adoptopenjdk) 
with wiremock-jre8 the problem is fixed.

I am closing this ticket.

**Comment by afayes** [comment]
I am using Java 11 and not able to get Wiremock working even with wiremock-jre8.

Java version:
```
java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

Tried the following dependencies:
```
  <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-jre8</artifactId>
            <version>2.10.0</version>
            <scope>test</scope>
        </dependency>
```
and
  ```
<dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-jre8</artifactId>
            <version>2.26.3</version>
            <scope>test</scope>
        </dependency>
```
and
 ```
 <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-</artifactId>
            <version>2.26.3</version>
            <scope>test</scope>
        </dependency>
```
