### ISSUE TITLE
Consider making Handlebars an optional dependency

### ISSUE THREAD

**Issue by sabi0** [tomakehurst/wiremock#971]
Hadlebars brings in a rather outdated ANTLR version - 4.5.1. It was conflicting with my environment which requires ANTLR 4.7.1. So I had to explicitly exclude it.

I don't use templating in my tests. So if Handlebars was an optional dependency I wouldn't have this problem in the first place.

Other options:
- Upgrade to Handlebars 4.0.7 which uses the latest ANTRL version
- Upgrade to Handlebars 4.1.0 which does not use ANTLR anymore (but requires Java 8)
https://github.com/jknack/handlebars.java/releases

**Comment by tomakehurst** [comment]
Have you tried using the standalone JAR?

**Comment by sabi0** [comment]
Why?
I am perfectly happy with JUnit Rule option. Except for the outdated ANTRL dependency.

**Comment by tomakehurst** [comment]
I mean as a dependency. It shades all of its dependencies so they don't clash with yours.

**Comment by sabi0** [comment]
That's a good alternative to excluding ANTLR transitive dependency. Thanks.

But I still think you should upgrade to Handlebars 4.0.7. I don't see any downside in doing that.
Also `<scope>optional</scope>` would be beneficial to those not using the templates feature.

**Comment by tomakehurst** [comment]
Handlebars upgrade would mean dropping Java 7 support. Numerous discussions on here about why we don't want to do that yet.

Not keen on the optional scope approach. It'd probably mean more than just changing dependencies around for one thing, but also people seems to have a hard enough time enabling templating even when it is built in. I'm not sure I'm ready for the deluge of support emails I'd get if there was an additional hurdle.

**Comment by sabi0** [comment]
4.0.7 is a minor update and it is still compatible with Java 7. They dropped Java 7 support starting from 4.1.0.

**Comment by tomakehurst** [comment]
Ah, that's OK then. I'll roll that into the next release.
