### ISSUE TITLE
Wiremock OpenAPI import (Swagger Import)

### ISSUE THREAD

**Issue by aosorio1** [tomakehurst/wiremock#976]
Wiremock should be able to set up the stub mappings based on a OpenAPI spec. 

I want to work on this feature request but I noticed that this is already implemented in Mocklab.
https://www.mocklab.io/docs/swagger/

POST http://my-swagger-api.mocklab.io/__admin/imports/open-api-spec
{
  "spec": "<your JSON or YAML Swagger definition>",
  "duplicatePolicy": "ALWAYS_OVERWRITE"
}

My questions are: Is this feature ever going to be pushed into Wiremock? If not, I would like to work on this feature but I am not sure if this should be implemented as an extension or as a part of the Wiremock core source code.

**Comment by tomakehurst** [comment]
I don't have any plans to open source MockLab's implementation at the moment.

I'd suggest if you want to work on this that you make it an extension. That's how I've done it inside ML as there's nothing about it that can't be done with the extension mechanism.

**Comment by codyaray** [comment]
@aosorio1 did you ever make progress on this extension?
