### ISSUE TITLE
POST cannot support form

### ISSUE THREAD

**Issue by hxiugangxh** [tomakehurst/wiremock#980]
Why can't POST support form
Be sure to get json (text)
Does anybody have a solution

**Comment by tomakehurst** [comment]
I don't really understand what's being asked here but it doesn't seem like a feature request or bug so I'm closing it.

If you still have a question, please post it on the mailing list with an explanation of what you are trying to achieve.

**Comment by hxiugangxh** [comment]
just like k-v(application/x-www-form-urlencoded)
