### ISSUE TITLE
how can i  reuse  the wiremock  method to match header,body,queryparams when   extend RequestMatcherExtension  

### ISSUE THREAD

**Issue by 278668433** [tomakehurst/wiremock#982]
[Hi , i will like to use wiremock to request with variables and request dynamic  .    i extend Wiremock functionality  RequestMatcherExtension  then rewrite match  ,.
example  request :
{
	"request":{
		"customMatcher":{
			"name":"extension-matcher",
			"parameters":{
				"bodyPatterns":[
					{
					      "equalTo":"domain=www.baidu.com@now('day','-2','%Y%m%d')"
					}
				]
			}
		},
		"method":"POST",
		"urlPath":"/dynamicParam"
	 },
	 "response":{
		"body":"7asddasda",
		"status":200
	 }
}
when i get the parameters and do the dynamic  function replaced .  how can i  reuse  the wiremock  method to match header,body,queryparams?
      
![how](https://user-images.githubusercontent.com/18320290/44502261-46b68380-a6c3-11e8-9a9a-d5858c147528.png)

**Comment by tomakehurst** [comment]
At present you can't mix ordinary matchers and a custom matcher.

Please post questions to the mailing list.
