### ISSUE TITLE
Incremental response parameter

### ISSUE THREAD

**Issue by kheifer** [tomakehurst/wiremock#988]
This is less of a issue as much as it's a feature request. Is there an easy way to have a parameter return incrementally while I'm running mappings. I basically would like to have the parameter return dynamically. So for every response I get that returns a response I'd like to be able to have a parameter decrease.

**Comment by tomakehurst** [comment]
You can approximate this with scenarios at the moment, but if you want true statefulness as you've described you'd need to write an extension class.

**Comment by kheifer** [comment]
Do you have any examples I could take a look at? Also is the usage limited to the java script or is it possible with just the json api

**Comment by tomakehurst** [comment]
You'd need to write the extension in Java or another JVM-compiled language like Groovy.

Extensions are documented here: http://wiremock.org/docs/extending-wiremock/
