### ISSUE TITLE
ClasspathFileSource.child() should use pathUri

### ISSUE THREAD

**Issue by fletchgqc** [tomakehurst/wiremock#993]
Shouldn't this function in ClasspathFileSource:

    @Override
    public FileSource child(String subDirectoryName) {
        return new ClasspathFileSource(path + "/" + subDirectoryName);
    }

rather look like this?

    @Override
    public FileSource child(String subDirectoryName) {
        return new ClasspathFileSource(**pathUri** + "/" + subDirectoryName);
    }

Background: I'm trying to use Wiremock embedded in my Java application to mock a backend which my application needs to access, even when the application is deployed. So I can't use a file path under src/test. I successfully set the path to wiremock files using usingFilesUnderClasspath("."), now I can access my mock responses in the target directory.

The next step is to configure the stubs completely via JSON. Contrary to the documentation, the mappings directory is not affected by the method usingFilesUnderClasspath("."), at least not in the way I wanted :-). It seems to be a result of this method.

Wiremock version 2.18.0
Using JAR, starting and configuring wiremock manually via Java.

**Comment by tomakehurst** [comment]
I don't have quite enough context to work on this, so given its age I'm going to close it. Anyone who still feels strongly, please shout - happy to look at it again with a test case in hand.
