### ISSUE TITLE
support standalone process with keystore/truststore type

### ISSUE THREAD

**Issue by aklemp** [tomakehurst/wiremock#994]
- [x] Which version of WireMock you're using
Wiremock 2.19.0
- [x] How you're starting and configuring WireMock, including configuration or CLI the command line
Started in Docker (https://hub.docker.com/r/rodolpheche/wiremock/) which is just bundling Wiremock in the standalone mode. The following arguments are used:
```--https-port 8443 --https-keystore /home/wiremock/keystore.p12 --global-response-templating --verbose```
- [x] A failing test case that demonstrates the problem
As shown in the configuration above, I'm using a keystore in PKCS12 format for various reasons (default in Java 9, Java keytool warnings when using JKS, consistency with other services I use). However, the HTTPS endpoint is only working when giving a keystore in JKS format. I also think to have found the cause.
When using the WiremockRule, the keystore and truststore types can be passed programmatically: https://github.com/tomakehurst/wiremock/blob/2.19.0/src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java#L349
This is simply missing in the configuration for the standalone mode: https://github.com/tomakehurst/wiremock/blob/2.19.0/src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java#L240
I don't have a clue why this could be on purpose so it seems to be a bug.
- [ ] Profiler data if the issue is performance related

**Comment by tomakehurst** [comment]
I'll mark this as a feature request.

The reason we never bothered putting it in the CLI is that for a while the only practical reason to change it from the default was embedded Android testing.

**Comment by tomakehurst** [comment]
Happy to accept a PR if you need this at all quickly.

**Comment by aklemp** [comment]
Unfortunately, while testing the pull request, I noticed that this alone is not supporting PKCS12 as keystore. In addition the keystore password is required as described in #807. Temporarily setting the password in JettyHttpServer allows using a PKCS12 keystore. As described in the issue, it would break backwards compatibility so I haven't included that change in this PR.

**Comment by tomakehurst** [comment]
Sorry for the long delay on this.

Is it not sufficient to use the existing `--keystore-password` and `--truststore-password` parameters with a type of PKCS12?

**Comment by aklemp** [comment]
When I last tested this, it was not sufficient because it is not propagated in the JettyHttpServer.

**Comment by aklemp** [comment]
Ok. I'm on it. Implementation seems to be done but I still have to test it in the next few days.

**Comment by aklemp** [comment]
Updated the pull request. But I have no idea where to document that it contains the breaking change.

**Comment by phillbarber** [comment]
Perhaps the breaking change could be documented in the release notes?  It would be great if this could be merged.  I was almost about to start working on a fix for https://github.com/tomakehurst/wiremock/issues/807 when I realised that this fixes it.  Thanks @aklemp for addressing this.
