### ISSUE TITLE
Wiremock request matching - Cannot match URL with dynamic path variable

### ISSUE THREAD

**Issue by javaw0rkspace** [tomakehurst/wiremock#995]
**Stub mapping** 

```
{
	"request": {
		"method": "GET",
		"urlPathPattern": "https://mywebsite/validation/session/([a-zA-Z0-9/-]*)"
	},
	"response": {
		"status": 200,
		"jsonBody": {
			"isIpBlocked": "Y",
			"serviceMessage": {
				"type": "OK",
				"code": "200",
				"description": "IP validated successfully. No result found"
			}
		},
		"headers": {
			"Content-Type": "application/json"
		}
	}
}
```

**cannot match the URL**

https://mywebsite/validation/session/687d69ae-42a8-4584-a395-8e0c876bacae

Also tried replacing urlPathPattern with urlPattern with no success

Tried all the below combination. Nothing worked

https://mywebsite/validation/session/([a-zA-Z0-9\\-]+)
https://mywebsite/validation/session/([a-zA-Z0-9\\-]*)
https://mywebsite/validation/session/([a-zA-Z0-9/-]+)
https://mywebsite/validation/session/([a-zA-Z0-9/-]*)

**Note:** Wiremock version 2.18.0, Spring Boot 2.0 

Actually, except url (in stub mapping with absolute URL) nothing is working for me.

**Comment by tomakehurst** [comment]
`urlPathPattern` needs to be relative, not absolute.

Please post future questions to the mailing list.

**Comment by javaw0rkspace** [comment]
Actually, it is not working even with a relative path.

```
    String fooResourceUrl  = "/validation/session/687d69ae-42a8-4584-a395-8e0c876bacae";
    ResponseEntity<String> response3   = restTemplate.getForEntity(fooResourceUrl, String.class);
```

{
	"request": {
		"method": "GET",
		"url": "/validation/session/([a-zA-Z0-9/-]*)"
	},
	"response": {
		"status": 200,
		"jsonBody": {
			"isIpBlocked": "Y",
			"serviceMessage": {
				"type": "OK",
				"code": "200",
				"description": "IP validated successfully. No result found"
			}
		},
		"headers": {
			"Content-Type": "application/json"
		}
	}
}

**Comment by tomakehurst** [comment]
Suggest you re-post on the mailing list

**Comment by javaw0rkspace** [comment]
Even reposted in the mailing list. I am struggling with this for the past 2 days. Your help is highly appreciated.

https://groups.google.com/forum/#!topic/wiremock-user/blOOiFaEa5Q
